const window_leads_data = [
  {
    "titulo": "El CIME de Mazarrón impulsa nuevas oportunidades laborales con numerosas ofertas de empleo activas - mazarron.es",
    "url": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxQN1RPV1hjZ3lISG8tQ2kxT2RvcXpvRF9lbElEeGFyd3owRnBxMExpSVVTeV93ZDBqZEVOVVJBXy1CSnNqdXlIYnR5NjlpWElUS1VMODJBZVlsREMwWFFRR1VjZUVxTW1Odm5TVGRXOGQzV1lLTjh2OXBBZHFOei13NGJIb2pKU1VMUGRXVmRkU24weUJlak5rLTdVQ2pUanI5NnNXZmYzZXR6MnZYWUoxbmNVcU9SSVVyY01NQWZCcGpCdUN4MUVMS3VlRDNVRlh5eDhKS1ROcWxRandjXzFWc1F4aTlnWVZFTVE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6gFBVV95cUxQN1RPV1hjZ3lISG8tQ2kxT2RvcXpvRF9lbElEeGFyd3owRnBxMExpSVVTeV93ZDBqZEVOVVJBXy1CSnNqdXlIYnR5NjlpWElUS1VMODJBZVlsREMwWFFRR1VjZUVxTW1Odm5TVGRXOGQzV1lLTjh2OXBBZHFOei13NGJIb2pKU1VMUGRXVmRkU24weUJlak5rLTdVQ2pUanI5NnNXZmYzZXR6MnZYWUoxbmNVcU9SSVVyY01NQWZCcGpCdUN4MUVMS3VlRDNVRlh5eDhKS1ROcWxRandjXzFWc1F4aTlnWVZFTVE?oc=5\" target=\"_blank\">El CIME de Mazarrón impulsa nuevas oportunidades laborales con numerosas ofertas de empleo activas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">mazarron.es</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T08:10:27Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La empresa auxiliar andaluza paraliza las contrataciones por la huelga de Airbus - El Conciso",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOYjhRTDNPR1ljQTBqTXVWa2JyaGkwYVF6VjdqSlRBY0NMb3FEUFZIMllfU0N5MDFwcVJlRm15Z0tuYXBTMkFGUDJmNHF5WmhoRS0wTkVfWndDMUdhTXNpV3paVUpha0c2Z28zR2ZIaG5JaTFjV09ELXo5YWplVzlqdThIRmQ5MTFtSGVIRllJVThVYjZLelUyODNKa2Zlc1RvZUkwYUUwZFlNekFKeEk2N0djSklDZ9IBuwFBVV95cUxOQ081M05TbzdBWlJrRWwzYlZWc051NG85ZG9TN1Q4ZkhDaHlXUG4yaTRaakVQZmhYVnFsb2ZBdDVaa0ZwN3A5dEVYVE84X0dzRG45cDRoYmI3RC1xNHBsdV95VVJfM0pSYWVEektJblV0eGVrUGxjTVd5a3pUZVkzeGtZSUtNeTZUWW1HUmREYjB2c0k2aDZreVl5SHloUWlmbkl4WGRfdVRiWU80TUU2SmpQOGQzTFZGWWVJ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitgFBVV95cUxOYjhRTDNPR1ljQTBqTXVWa2JyaGkwYVF6VjdqSlRBY0NMb3FEUFZIMllfU0N5MDFwcVJlRm15Z0tuYXBTMkFGUDJmNHF5WmhoRS0wTkVfWndDMUdhTXNpV3paVUpha0c2Z28zR2ZIaG5JaTFjV09ELXo5YWplVzlqdThIRmQ5MTFtSGVIRllJVThVYjZLelUyODNKa2Zlc1RvZUkwYUUwZFlNekFKeEk2N0djSklDZ9IBuwFBVV95cUxOQ081M05TbzdBWlJrRWwzYlZWc051NG85ZG9TN1Q4ZkhDaHlXUG4yaTRaakVQZmhYVnFsb2ZBdDVaa0ZwN3A5dEVYVE84X0dzRG45cDRoYmI3RC1xNHBsdV95VVJfM0pSYWVEektJblV0eGVrUGxjTVd5a3pUZVkzeGtZSUtNeTZUWW1HUmREYjB2c0k2aDZreVl5SHloUWlmbkl4WGRfdVRiWU80TUU2SmpQOGQzTFZGWWVJ?oc=5\" target=\"_blank\">La empresa auxiliar andaluza paraliza las contrataciones por la huelga de Airbus</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Conciso</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T12:48:02Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Airbus",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo de Madrid Trabaja 29.08.2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNMTZQY0VYU2RkS0NWUFJNU0pPRnVxVWF1dzVqRHQzLTVGLTlWQ0d0M1V2RmEzYkNrcTF6akJTek9USmF6aklBay0zSWhyOUI0eFdNSlg2dWJNb3puaVhSc3JVR1RoMkxzX1dMNFUwUXNnd1k2QkFNaUw3bGFkNzZVazBaY0JCNXEzUm5iTUE4UFVuLVN5M25EN0hwRzZjelhmNWJPNGZhbDNzNm81WWRrSkR6RXE2aElyMVpZbEQzZE9PMTFZei1OONIBzgFBVV95cUxQdlloNGZlU1VRc0RzdXJrVkxfUEJpOTJfeWVHZEdzNlFwanI1SGFlNUdaSjJ1UVRVOGJheTJBWnd3bnFTaUdSamFQakY3YkZpeWRGZ2F5MENhLXh1QWtxaE40WWFmSDlyRzV5cjVSNTItUy1SVVVTOTY2VnRxdk8zN2hqZGVOblUzckNJTjFsU1lDX0ZUNTVYNUZlRVVieFJnRW5lTzlNTWhMVEhnQlpQamRWU25KbUQtcTI4ajNlamNTLTZBblhGSEVLdjlLZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiyAFBVV95cUxNMTZQY0VYU2RkS0NWUFJNU0pPRnVxVWF1dzVqRHQzLTVGLTlWQ0d0M1V2RmEzYkNrcTF6akJTek9USmF6aklBay0zSWhyOUI0eFdNSlg2dWJNb3puaVhSc3JVR1RoMkxzX1dMNFUwUXNnd1k2QkFNaUw3bGFkNzZVazBaY0JCNXEzUm5iTUE4UFVuLVN5M25EN0hwRzZjelhmNWJPNGZhbDNzNm81WWRrSkR6RXE2aElyMVpZbEQzZE9PMTFZei1OONIBzgFBVV95cUxQdlloNGZlU1VRc0RzdXJrVkxfUEJpOTJfeWVHZEdzNlFwanI1SGFlNUdaSjJ1UVRVOGJheTJBWnd3bnFTaUdSamFQakY3YkZpeWRGZ2F5MENhLXh1QWtxaE40WWFmSDlyRzV5cjVSNTItUy1SVVVTOTY2VnRxdk8zN2hqZGVOblUzckNJTjFsU1lDX0ZUNTVYNUZlRVVieFJnRW5lTzlNTWhMVEhnQlpQamRWU25KbUQtcTI4ajNlamNTLTZBblhGSEVLdjlLZw?oc=5\" target=\"_blank\">Ofertas de empleo de Madrid Trabaja 29.08.2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-29T08:20:00Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Accede a ofertas de empleo y a un asesoramiento laboral a través de UGT Castilla-La Mancha - UGT Castilla-La Mancha",
    "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxNWGNOWThBUHdBVHN3SjNCWk5mNGtkY0RTWlpZZXc5MEFWQzhRQTVpRF80djdfaDdTYV92aXJCR3M0NmdSZzBLZXY0N1RSOHFPRGFjQ3hMUHEyQ0dDMjZVeDJQcVUxa3hPMUJydi1WRE5oY1pDYXBlR25JZHBscUxfYlpvNGMxSVVDTkkzOU1BVDB4OFczYW80ek82Y2twUWZZa1RrVW50RjZtS0VTRHlMbkd5VXJVX01YR0c4UmhfeXZvUExJUkE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMixgFBVV95cUxNWGNOWThBUHdBVHN3SjNCWk5mNGtkY0RTWlpZZXc5MEFWQzhRQTVpRF80djdfaDdTYV92aXJCR3M0NmdSZzBLZXY0N1RSOHFPRGFjQ3hMUHEyQ0dDMjZVeDJQcVUxa3hPMUJydi1WRE5oY1pDYXBlR25JZHBscUxfYlpvNGMxSVVDTkkzOU1BVDB4OFczYW80ek82Y2twUWZZa1RrVW50RjZtS0VTRHlMbkd5VXJVX01YR0c4UmhfeXZvUExJUkE?oc=5\" target=\"_blank\">Accede a ofertas de empleo y a un asesoramiento laboral a través de UGT Castilla-La Mancha</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">UGT Castilla-La Mancha</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-31T10:41:28Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "UGT Castilla-La Mancha"
  },
  {
    "titulo": "Ofertas de empleo para comenzar la semana - Radio Guijuelo",
    "url": "https://news.google.com/rss/articles/CBMihgFBVV95cUxOOUxzTHF6UDBJSjZjZnpHaHItVWc1OUt4a3BQd0QtRHhyYlFDTi1EalVKclFFNDNNdjlIbUQtZEVFZEt2X1VXbGJOcWZqY2F3eVJmcXNqazM1VzVTQU1Ba1NxS2JVUzdLTkt1U215b2dzVTRSdFc2cGU1eWdCSWVQNTZmSzk1dw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMihgFBVV95cUxOOUxzTHF6UDBJSjZjZnpHaHItVWc1OUt4a3BQd0QtRHhyYlFDTi1EalVKclFFNDNNdjlIbUQtZEVFZEt2X1VXbGJOcWZqY2F3eVJmcXNqazM1VzVTQU1Ba1NxS2JVUzdLTkt1U215b2dzVTRSdFc2cGU1eWdCSWVQNTZmSzk1dw?oc=5\" target=\"_blank\">Ofertas de empleo para comenzar la semana</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Radio Guijuelo</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-31T11:55:47Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en EEUU aumentan en julio tras fuerte revisión a la baja del mes anterior - TradingView",
    "url": "https://news.google.com/rss/articles/CBMid0FVX3lxTE1wYUhFMlRtNkxzUlJpcXMwSl94Z2NyTFh5Y1VUY3hiVGQyT0hiS2JZWXNHVmM3OTkzZXR0ck1QOXFFT1QyRFZhcXhid3NQaXpBUkhBblliamFjRzJVMEt3TUx2bkdjN29yMXpSVE9qeU0ycDF1dWpJ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMid0FVX3lxTE1wYUhFMlRtNkxzUlJpcXMwSl94Z2NyTFh5Y1VUY3hiVGQyT0hiS2JZWXNHVmM3OTkzZXR0ck1QOXFFT1QyRFZhcXhid3NQaXpBUkhBblliamFjRzJVMEt3TUx2bkdjN29yMXpSVE9qeU0ycDF1dWpJ?oc=5\" target=\"_blank\">Ofertas de empleo en EEUU aumentan en julio tras fuerte revisión a la baja del mes anterior</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">TradingView</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T15:16:24Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "TradingView",
    "ubicacion": "EEUU"
  },
  {
    "titulo": "Badalona contratará 63 parados durante un año - La Vanguardia",
    "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxOaFpqbzRPQmcwbTZxdFNILWhUYzdPRV9UZXZmdVlrTldJWFQxRkVoZEZEY3dGaGw2amxXNTVZWUYzNnZLRGljd0JfTzNoaVd3VlZMSHlOYUNtM3RhaG4wbHhkdzJJUjM0MU4wMWZlRzRIbjBjYU0xb3pSdEJ1OHV0UzJmdkFqSGNaTjZQY2dxc3ZxNHJfSmwxQ09NRXdId2Q3NTI1ZVY1Z1IwU0U5?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMirAFBVV95cUxOaFpqbzRPQmcwbTZxdFNILWhUYzdPRV9UZXZmdVlrTldJWFQxRkVoZEZEY3dGaGw2amxXNTVZWUYzNnZLRGljd0JfTzNoaVd3VlZMSHlOYUNtM3RhaG4wbHhkdzJJUjM0MU4wMWZlRzRIbjBjYU0xb3pSdEJ1OHV0UzJmdkFqSGNaTjZQY2dxc3ZxNHJfSmwxQ09NRXdId2Q3NTI1ZVY1Z1IwU0U5?oc=5\" target=\"_blank\">Badalona contratará 63 parados durante un año</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Vanguardia</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T15:24:16Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Badalona"
  },
  {
    "titulo": "Mercadona busca personal indefinido para trabajar sólo ocho días al mes con sueldo de 879 euros más complementos - ABC",
    "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxQbUdFdXpNNTk3S3VQMF9RSkVYam9MZks4TDlXR1BjOEtmLXBxNlpfT2Y2TFkxMEpLQndkdjgtYXNkektZVmducWZTcW55Wkw4UlpReWVSXzg2emdETmJSUGhlbklyMVJSaXUzeTRVRGtYY0xKTWpaLWNOX0R1UjFyWFJPRGQ5OEJITWt3SXk4ZC1Qc0QzaFlnWjVsMHl6S0ZHdUFpYVQxeExHZEFMeW43NWl4cHpqVS10eFpBVUQ5a055QdIBxwFBVV95cUxNUm9UVTBBVUV3YVZqQlAzUXZ6U2tUTmlJVVNVYXR2QnUzSU9fYWlwekYza2UxWkhwcHM2bTFyVng3eVl4Mnpac0FSaUszRWFBSXFwMEhrSk1EODAzS2ZVcUlmdFNOSVctQmFHYm9tUmxTWEI4N0VCdzI3eHp0Wjk2WjN3ZUtQUy13OTdZbmRuQkZhNE1neHRmOWxTTHRiT2tPZXViNDJXWkVBQm5rV3M5OS1ZTUZqM3Y0YW9nUDVtakRZcHNGMDVj?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiwgFBVV95cUxQbUdFdXpNNTk3S3VQMF9RSkVYam9MZks4TDlXR1BjOEtmLXBxNlpfT2Y2TFkxMEpLQndkdjgtYXNkektZVmducWZTcW55Wkw4UlpReWVSXzg2emdETmJSUGhlbklyMVJSaXUzeTRVRGtYY0xKTWpaLWNOX0R1UjFyWFJPRGQ5OEJITWt3SXk4ZC1Qc0QzaFlnWjVsMHl6S0ZHdUFpYVQxeExHZEFMeW43NWl4cHpqVS10eFpBVUQ5a055QdIBxwFBVV95cUxNUm9UVTBBVUV3YVZqQlAzUXZ6U2tUTmlJVVNVYXR2QnUzSU9fYWlwekYza2UxWkhwcHM2bTFyVng3eVl4Mnpac0FSaUszRWFBSXFwMEhrSk1EODAzS2ZVcUlmdFNOSVctQmFHYm9tUmxTWEI4N0VCdzI3eHp0Wjk2WjN3ZUtQUy13OTdZbmRuQkZhNE1neHRmOWxTTHRiT2tPZXViNDJXWkVBQm5rV3M5OS1ZTUZqM3Y0YW9nUDVtakRZcHNGMDVj?oc=5\" target=\"_blank\">Mercadona busca personal indefinido para trabajar sólo ocho días al mes con sueldo de 879 euros más complementos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ABC</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T05:40:43Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Cáceres contratará empresa especializada para el control de las palomas en el casco urbano - Región Digital",
    "url": "https://news.google.com/rss/articles/CBMi8wFBVV95cUxNckVyZERYODA2ZjlleFY3TlVrWlpnWDMzSTlEUHZRbU5GdEZ1clVyWEZvWXNZZ0xua0VDMXhrSEhQRDdOSmJCTGJUTXV6S0NBTTlPYnFJUk5EWVJmcVRZcGk4VGZ3X3g4RkNKSUhzZ1Z3Z2xVMWZSVWlRWkpSMDRHSnNRZ0l3bGVsUUhoRUI2cjhJSENvM1NTcFdxbjVQUnZnMlU2M0NrMU16MjFkZEkwR09ZYmFNNF95QXFPRzByMkRXMWJxaUVhVWcxTmtzQWd4cE4tWnJNQnNSWkFiV3hDMzQ5VHlsVjBlQUhNT0dpTG42QWPSAfgBQVVfeXFMTURZUG9ZcXJTNV9ZR3A1SHFkUzI2SU91MU1GdGdjUU9tVmpUSHZmUWRiQXJMQ05CRTBaVEFCcmwzN19sMjNodFhfMHJVelZVTWk2MXdYN0l5cHdYTEhqUTVETXFsdGlJaFJmamV5a3ZYQXFycWNJLTFoY0JIR045LVpXQmxPUVdGaGtHelZEV3FxZ3JZdEc5OUNIUGFPdUZCb0tzNzdkbUdMT0ktWVl4dV8ybWxJanFxcUh4OHVBQ3NkS19KSnBmTFVRM3FlTFhWSWU0cUJBczlyc1RpN081SFJTeW1jRWdXeUU0V1I5MW5zM2JRWXpaMjM?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi8wFBVV95cUxNckVyZERYODA2ZjlleFY3TlVrWlpnWDMzSTlEUHZRbU5GdEZ1clVyWEZvWXNZZ0xua0VDMXhrSEhQRDdOSmJCTGJUTXV6S0NBTTlPYnFJUk5EWVJmcVRZcGk4VGZ3X3g4RkNKSUhzZ1Z3Z2xVMWZSVWlRWkpSMDRHSnNRZ0l3bGVsUUhoRUI2cjhJSENvM1NTcFdxbjVQUnZnMlU2M0NrMU16MjFkZEkwR09ZYmFNNF95QXFPRzByMkRXMWJxaUVhVWcxTmtzQWd4cE4tWnJNQnNSWkFiV3hDMzQ5VHlsVjBlQUhNT0dpTG42QWPSAfgBQVVfeXFMTURZUG9ZcXJTNV9ZR3A1SHFkUzI2SU91MU1GdGdjUU9tVmpUSHZmUWRiQXJMQ05CRTBaVEFCcmwzN19sMjNodFhfMHJVelZVTWk2MXdYN0l5cHdYTEhqUTVETXFsdGlJaFJmamV5a3ZYQXFycWNJLTFoY0JIR045LVpXQmxPUVdGaGtHelZEV3FxZ3JZdEc5OUNIUGFPdUZCb0tzNzdkbUdMT0ktWVl4dV8ybWxJanFxcUh4OHVBQ3NkS19KSnBmTFVRM3FlTFhWSWU0cUJBczlyc1RpN081SFJTeW1jRWdXeUU0V1I5MW5zM2JRWXpaMjM?oc=5\" target=\"_blank\">Cáceres contratará empresa especializada para el control de las palomas en el casco urbano</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Región Digital</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T12:35:07Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en EE.UU. suben ligeramente a 7,27 millones mientras los despidos disminuyen - Bloomberg Línea",
    "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxPNndfWC1RWUpLUmhBMXpOVTlISTRoWEYyLXR2Ukp3c0hHVkhtRDViTXd0ZGU5Z2dQTHpRQ2t1LVJaQktMTk5UcWJ2LVV0RmJkQzFQRUs3T2E3TFh6bXRWN0M0b1Nzczk5OTROWnJCQUZKbllpUlpqNVNQblVrR21zQzJJY0gzYmRDZWhKdnRRZlNyVU13VlJCSGlGMkRqWUhiV2ptTHBHTEJBTlg3bllOTVpiQlNfblVWZndSM0Rpc0g0YmdIclg3Z3FDUVJFMUtJdHFZVDJZZlZDY2dy0gHwAUFVX3lxTE9kTTZOOUNLVVNtNy04eDFCOS1Bb2JWQUs5cllpa1A0UnU3LUtndC0tR0V6YUJ3WmZWVUZQbEhnNjdmWUc0WWpuS2VGQVlGYjBES0J2ZXN2UnNtdlVMQS1SbjU1TE42WUZjTzN3ZkNVYWx1eEZfYl9FWHBKcnE4cGZzX1FiVmhQUVQxV3dESmxYVXpkbVNNYUhCbDg4aVFkdWN4ZVpmOXpZQ2FpcnVkM3pGd2NBWWNad2FsX3FPaC02WHJnWlRHRXgzSTlRZFB6WDJxNUE0emNsQ3E0VjBRS3JCNUhTSVJQRWNRMGVaRm9nag?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi3AFBVV95cUxPNndfWC1RWUpLUmhBMXpOVTlISTRoWEYyLXR2Ukp3c0hHVkhtRDViTXd0ZGU5Z2dQTHpRQ2t1LVJaQktMTk5UcWJ2LVV0RmJkQzFQRUs3T2E3TFh6bXRWN0M0b1Nzczk5OTROWnJCQUZKbllpUlpqNVNQblVrR21zQzJJY0gzYmRDZWhKdnRRZlNyVU13VlJCSGlGMkRqWUhiV2ptTHBHTEJBTlg3bllOTVpiQlNfblVWZndSM0Rpc0g0YmdIclg3Z3FDUVJFMUtJdHFZVDJZZlZDY2dy0gHwAUFVX3lxTE9kTTZOOUNLVVNtNy04eDFCOS1Bb2JWQUs5cllpa1A0UnU3LUtndC0tR0V6YUJ3WmZWVUZQbEhnNjdmWUc0WWpuS2VGQVlGYjBES0J2ZXN2UnNtdlVMQS1SbjU1TE42WUZjTzN3ZkNVYWx1eEZfYl9FWHBKcnE4cGZzX1FiVmhQUVQxV3dESmxYVXpkbVNNYUhCbDg4aVFkdWN4ZVpmOXpZQ2FpcnVkM3pGd2NBWWNad2FsX3FPaC02WHJnWlRHRXgzSTlRZFB6WDJxNUE0emNsQ3E0VjBRS3JCNUhTSVJQRWNRMGVaRm9nag?oc=5\" target=\"_blank\">Ofertas de empleo en EE.UU. suben ligeramente a 7,27 millones mientras los despidos disminuyen</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Bloomberg Línea</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T16:18:35Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "EE.UU."
  },
  {
    "titulo": "El Ayuntamiento de Algeciras contratará a 70 trabajadores temporales para labores de reconstrucción por el tren de borrascas - Europa Sur",
    "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOVE1mLVVyeXZ3X3RpNU1FN2VVSWEwVmVSUWVpelprM1NOd1BEMnRhdVdYUU1TbkJNMFdpTmxMVTFzV1VsclZnYWVlaVBXeF96eDd3Q0d4WnhIc3lDLVctaTB5TTQwb29UYnpWQ1gxdXRFeTBiT0NXN0JDOXpnZjRKS0FxNjZxMktFM2g1d0NGaTJGWGo5Q2ZxRFRwQVZOSHYtNjVVNG9VLUlFempzVERLVWRzRFMwbHRpSDRN0gHAAUFVX3lxTE1JbkUyOUs3OGZEMUc4NDkxa1Y4Qk14eDZLcU1xMHNCR21EajRxSTNIb1pNQ1NVNlkxR3JsNlA4ZEhCMEFPWkk5YzU2RU9raVZjY3Q2bnVxQVptaTJhZ1R4N1Z2OWl3eEZvOFZlYzB0YXNrRGVHeHM2ZnlQZW4wT3VaMk1KNTFqN0FhcEw1dmlUNDl1Q19NTFJKd2t3bktNTzRoT2NPaU5yUzNlYzlCMmtYUG9KZjFUMmdCR0dpbTlYXw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiuwFBVV95cUxOVE1mLVVyeXZ3X3RpNU1FN2VVSWEwVmVSUWVpelprM1NOd1BEMnRhdVdYUU1TbkJNMFdpTmxMVTFzV1VsclZnYWVlaVBXeF96eDd3Q0d4WnhIc3lDLVctaTB5TTQwb29UYnpWQ1gxdXRFeTBiT0NXN0JDOXpnZjRKS0FxNjZxMktFM2g1d0NGaTJGWGo5Q2ZxRFRwQVZOSHYtNjVVNG9VLUlFempzVERLVWRzRFMwbHRpSDRN0gHAAUFVX3lxTE1JbkUyOUs3OGZEMUc4NDkxa1Y4Qk14eDZLcU1xMHNCR21EajRxSTNIb1pNQ1NVNlkxR3JsNlA4ZEhCMEFPWkk5YzU2RU9raVZjY3Q2bnVxQVptaTJhZ1R4N1Z2OWl3eEZvOFZlYzB0YXNrRGVHeHM2ZnlQZW4wT3VaMk1KNTFqN0FhcEw1dmlUNDl1Q19NTFJKd2t3bktNTzRoT2NPaU5yUzNlYzlCMmtYUG9KZjFUMmdCR0dpbTlYXw?oc=5\" target=\"_blank\">El Ayuntamiento de Algeciras contratará a 70 trabajadores temporales para labores de reconstrucción por el tren de borrascas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Europa Sur</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-31T12:15:38Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento de Algeciras"
  },
  {
    "titulo": "Volkswagen Navarra amplía plantilla con 1.200 nuevos empleos por la demanda de eléctricos - Vozpopuli",
    "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxQVlZsWFpHOXBJV2hkZnNoNzhZNGVoVTZiSkNoOEh1eVFnUDJ1V1FaaHJfYUJYNjVqM0JyVG1UMXJEQ2hjdzNHUlgxNU5ZWHlZbE1CbE4wYjBuTHgyWWphdGlGYWotLU52czZ1RlZyeFBkM215eGNvTkNjN1oybkJxZGEtWVVXUTIzRURKdGtBWXQxZjh6Vk9zTUhrNUNpcGItRXp0Sm9nNWstekhXSlFvSDZjNUVhQ1F4YzFvaTYxVVFxeDjSAcgBQVVfeXFMTUhwU1kxUURfWklta3otY096N0VaclhUZjNwTS1qRTlrQzVISzAwY2lKUEx1aS1pZXdUNVFQQkpLUDRhRWRDRlBEdjdVSlBBZ3RicTRQNUttcUJybnVZU2diSjR3TTNhbnRfQXBEZmV2V1FWd0JvUC0wS0oxdXNTUm01TWliMG8zVE80NTc4cjFhdkZYUl9RUUtoZEZuZjg2d3FHeUFtOW9uaFdRbG5ISVVCQTV1MTU0LXkwdTg0RUNtMlNoVUJkMGs?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiwwFBVV95cUxQVlZsWFpHOXBJV2hkZnNoNzhZNGVoVTZiSkNoOEh1eVFnUDJ1V1FaaHJfYUJYNjVqM0JyVG1UMXJEQ2hjdzNHUlgxNU5ZWHlZbE1CbE4wYjBuTHgyWWphdGlGYWotLU52czZ1RlZyeFBkM215eGNvTkNjN1oybkJxZGEtWVVXUTIzRURKdGtBWXQxZjh6Vk9zTUhrNUNpcGItRXp0Sm9nNWstekhXSlFvSDZjNUVhQ1F4YzFvaTYxVVFxeDjSAcgBQVVfeXFMTUhwU1kxUURfWklta3otY096N0VaclhUZjNwTS1qRTlrQzVISzAwY2lKUEx1aS1pZXdUNVFQQkpLUDRhRWRDRlBEdjdVSlBBZ3RicTRQNUttcUJybnVZU2diSjR3TTNhbnRfQXBEZmV2V1FWd0JvUC0wS0oxdXNTUm01TWliMG8zVE80NTc4cjFhdkZYUl9RUUtoZEZuZjg2d3FHeUFtOW9uaFdRbG5ISVVCQTV1MTU0LXkwdTg0RUNtMlNoVUJkMGs?oc=5\" target=\"_blank\">Volkswagen Navarra amplía plantilla con 1.200 nuevos empleos por la demanda de eléctricos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Vozpopuli</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T02:45:00Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Next Level Games, filial de Nintendo, busca personal para todos estos puestos de trabajo - Nintenderos",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxNREZlVFpwem1VUDRGc0JTY3EtZmFsRjFzWU43ZUFUUUttVjNlRDZIZkZZWDlERktORDh6WmNiLUlWTnBWa1Z6RkJNaC1STms4Nnk3T205UXJqVFcycmQ1OFNjM0dCYW5HZmJVajYwM0lOUHQzNUc4Z2Njb2RsTkpWRTR1NzdBMG9tLTRrYzlqRENjR05ha21NTVVsWEtLelNEbEljTzFvbXpMeHhFZV9MRTZZWFJjYkJUdXBaTlNveUg?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiwAFBVV95cUxNREZlVFpwem1VUDRGc0JTY3EtZmFsRjFzWU43ZUFUUUttVjNlRDZIZkZZWDlERktORDh6WmNiLUlWTnBWa1Z6RkJNaC1STms4Nnk3T205UXJqVFcycmQ1OFNjM0dCYW5HZmJVajYwM0lOUHQzNUc4Z2Njb2RsTkpWRTR1NzdBMG9tLTRrYzlqRENjR05ha21NTVVsWEtLelNEbEljTzFvbXpMeHhFZV9MRTZZWFJjYkJUdXBaTlNveUg?oc=5\" target=\"_blank\">Next Level Games, filial de Nintendo, busca personal para todos estos puestos de trabajo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Nintenderos</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-29T07:39:18Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Level Games",
    "ubicacion": "Nintenderos"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 3 de septiembre de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi7AFBVV95cUxPbTJPelgwMF9TTDJaemVFUDdRQzU0MENKYmtRZUYtVkNPNy1Kc2g1ek84d0xkRlhPSktna19CX1NuU3Q3clZzTkY1UlViYmZwQVIzY0VXamczNlczTHJ4TjhSSi04NlRWNV9PblI2QWY2eXhFTDNOUXU2M08wby1PUi1kaXFDOUhaX0Q1b25FX09BNXY0cTZSSFJIczhrdzlxcHJMRDFHeUNESXJMRGFuUGVhSk9rQzBKX3Nhal9QZlFXdzkzOGpzTVgyc1g4WGl0blFJd3dMTllaTVMyMWlmZHc0Ri1HU2Y4emh3bNIB8gFBVV95cUxNb0EyUC1rVUZDT1J5bG5vM0RPdUo4TGRmNzlGbm9ZVFJ3a29OUVFTekFYeE12SG9GUkJ1cnh1TzQ1dkFXdVlQYTRGSXR3M0x5TmNIekZnejJuWUN0eW1WOGhaQVppVTREbzdJMXNZZTB3MWEyZ1NpQ2M4dF9TV3NTRkRwaWNQajVreGZab3ExX3AwQmYwVGg4U0NoZ0ZQdVdtTWY0OFNTbW5yZTJuZzlhMTVvUzFBWGwyTVZPc0tjelplaGl2RldjOTh2S3VNNnpDejlZdzlTaWRaSzJXaUY3Y1MtaFFlU09IR2kzUHAxLTVhQQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi7AFBVV95cUxPbTJPelgwMF9TTDJaemVFUDdRQzU0MENKYmtRZUYtVkNPNy1Kc2g1ek84d0xkRlhPSktna19CX1NuU3Q3clZzTkY1UlViYmZwQVIzY0VXamczNlczTHJ4TjhSSi04NlRWNV9PblI2QWY2eXhFTDNOUXU2M08wby1PUi1kaXFDOUhaX0Q1b25FX09BNXY0cTZSSFJIczhrdzlxcHJMRDFHeUNESXJMRGFuUGVhSk9rQzBKX3Nhal9QZlFXdzkzOGpzTVgyc1g4WGl0blFJd3dMTllaTVMyMWlmZHc0Ri1HU2Y4emh3bNIB8gFBVV95cUxNb0EyUC1rVUZDT1J5bG5vM0RPdUo4TGRmNzlGbm9ZVFJ3a29OUVFTekFYeE12SG9GUkJ1cnh1TzQ1dkFXdVlQYTRGSXR3M0x5TmNIekZnejJuWUN0eW1WOGhaQVppVTREbzdJMXNZZTB3MWEyZ1NpQ2M4dF9TV3NTRkRwaWNQajVreGZab3ExX3AwQmYwVGg4U0NoZ0ZQdVdtTWY0OFNTbW5yZTJuZzlhMTVvUzFBWGwyTVZPc0tjelplaGl2RldjOTh2S3VNNnpDejlZdzlTaWRaSzJXaUY3Y1MtaFFlU09IR2kzUHAxLTVhQQ?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 3 de septiembre de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T10:41:46Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 27 de agosto de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi6AFBVV95cUxPYmhnQjhqelNMekcxWVA3d05mTDRmUlJHSTNQSlVpLXNsLWNyRDFtWUZaWHhsdXlMMUFZZVlsdERVSEoyMFkyaW16d1B6V0l2SnBvd2NIQTU3RUVJX28xdzdrUzJJSWFJbVBJNkE5ZkVSYW5SMUhfQXFvbnBjdlVCbUFZd1E5Vm43REU5X2dPRk1VQzUxc3JSbF9vQ0dmS2RESTBtYnVCT0RPZkR2eHItSWZaRk5wUmZrTkQtOV9MdFM3VFdpQVFERHZmRmNYZW5EZmdJdHZkbkNzeXlUNF8waG1LWVJPTzd00gHuAUFVX3lxTE1la0xhZkdYNF8tc1k5V3JYaDhhLUJtLVByQTNQYWpMc2xIQzQ1aU50SG9kTTVUeHFjeTl6SWxVOEdCQVNiV2xuNnRFX0NjWDdScHdxemJ4SC0yNF9Odmx1QkVYU0NqVUxYR2hiclR3MkRMT2d1QkxURWVqbF85UTJBVkFZdVZvWWVUdko0dHhMOFBFQUQzczJzblRJZVA0Y291eHBLazZFOHN2QXZRbWx1NW9oY2FPN1M4Tml0TnVMakZBTXdCTTF6dk91aWFBRW1TZ1diSWNlYU5TLTdJQjhidXZKRjVoeEtTX1U4R3c?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6AFBVV95cUxPYmhnQjhqelNMekcxWVA3d05mTDRmUlJHSTNQSlVpLXNsLWNyRDFtWUZaWHhsdXlMMUFZZVlsdERVSEoyMFkyaW16d1B6V0l2SnBvd2NIQTU3RUVJX28xdzdrUzJJSWFJbVBJNkE5ZkVSYW5SMUhfQXFvbnBjdlVCbUFZd1E5Vm43REU5X2dPRk1VQzUxc3JSbF9vQ0dmS2RESTBtYnVCT0RPZkR2eHItSWZaRk5wUmZrTkQtOV9MdFM3VFdpQVFERHZmRmNYZW5EZmdJdHZkbkNzeXlUNF8waG1LWVJPTzd00gHuAUFVX3lxTE1la0xhZkdYNF8tc1k5V3JYaDhhLUJtLVByQTNQYWpMc2xIQzQ1aU50SG9kTTVUeHFjeTl6SWxVOEdCQVNiV2xuNnRFX0NjWDdScHdxemJ4SC0yNF9Odmx1QkVYU0NqVUxYR2hiclR3MkRMT2d1QkxURWVqbF85UTJBVkFZdVZvWWVUdko0dHhMOFBFQUQzczJzblRJZVA0Y291eHBLazZFOHN2QXZRbWx1NW9oY2FPN1M4Tml0TnVMakZBTXdCTTF6dk91aWFBRW1TZ1diSWNlYU5TLTdJQjhidXZKRjVoeEtTX1U4R3c?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 27 de agosto de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-27T09:16:55Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Comentario Apertura: El empleo de EEUU marcará hoy el rumbo de las bolsas y de los tipos - Bolsamania",
    "url": "https://news.google.com/rss/articles/CBMi_AFBVV95cUxPZUJjSUVIMGdSQ1N2TF9CZFVmcnFMalBXWDBWbkVHMHVzU3d4Ri1zNzVHWVBWTkFsM1VQSExzZG0wOUstT0VqWGRUUVpsbGhHRmRTS2U4R0R3MUhyNnBpUmY2eTQyaDZjczVWUTNxR21mTnZWXzdMLXZXSTlMeHBCdmQ3LWEySldHazZXZmZ2aTlUQkw3RkNHTXlQMG9uZk1mSHVKQU5jekV2U1RZSDd2WDhXZkQ0bXlpdkhObkVhc1BYbnBxMkdzOUNWSHd4d2M0X1RHY0tIbzVfRUJ4ZWVSY08xeHR2MGpwS2xLdlhCWEthWWR3WE00TDRXelTSAYICQVVfeXFMTUhtR0hJejVtWXdoZkxCdDBHdVdsNkNVajZFWko0em1SUEdKQVd1OGRNcGNhSWhWbUdUS2ltZDY4WGl2OFhBRTJ5aWREa1ItUFV5cy02ZEk4bkdiSDIyalJPdEcyWDNHMmlRTXFuemNMaDVCTXowajF0YUsyU2pEaUhqcXB3U0pJZmVuVjF3akhlM0NxX1E2dldCWXhrZUNubmJQTER2MFY1aXpmdkw2V3ZHRUtGT182UXY4ck5EVEdHWWhtUmp2LTlxTUtjbl91YmJMZEVkT0s5OERjblF3c2RHUmVmQy1Xd1J1OWRGbTgzRnBrNl9Ec3FranNMUUlrclRB?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi_AFBVV95cUxPZUJjSUVIMGdSQ1N2TF9CZFVmcnFMalBXWDBWbkVHMHVzU3d4Ri1zNzVHWVBWTkFsM1VQSExzZG0wOUstT0VqWGRUUVpsbGhHRmRTS2U4R0R3MUhyNnBpUmY2eTQyaDZjczVWUTNxR21mTnZWXzdMLXZXSTlMeHBCdmQ3LWEySldHazZXZmZ2aTlUQkw3RkNHTXlQMG9uZk1mSHVKQU5jekV2U1RZSDd2WDhXZkQ0bXlpdkhObkVhc1BYbnBxMkdzOUNWSHd4d2M0X1RHY0tIbzVfRUJ4ZWVSY08xeHR2MGpwS2xLdlhCWEthWWR3WE00TDRXelTSAYICQVVfeXFMTUhtR0hJejVtWXdoZkxCdDBHdVdsNkNVajZFWko0em1SUEdKQVd1OGRNcGNhSWhWbUdUS2ltZDY4WGl2OFhBRTJ5aWREa1ItUFV5cy02ZEk4bkdiSDIyalJPdEcyWDNHMmlRTXFuemNMaDVCTXowajF0YUsyU2pEaUhqcXB3U0pJZmVuVjF3akhlM0NxX1E2dldCWXhrZUNubmJQTER2MFY1aXpmdkw2V3ZHRUtGT182UXY4ck5EVEdHWWhtUmp2LTlxTUtjbl91YmJMZEVkT0s5OERjblF3c2RHUmVmQy1Xd1J1OWRGbTgzRnBrNl9Ec3FranNMUUlrclRB?oc=5\" target=\"_blank\">Comentario Apertura: El empleo de EEUU marcará hoy el rumbo de las bolsas y de los tipos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Bolsamania</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-04T07:10:13Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Comentario Apertura",
    "ubicacion": "EEUU"
  },
  {
    "titulo": "Lupa busca 40 empleados para la inminente apertura de Tifer en Soria - Heraldo-Diario de Soria",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQWUR5Tzl0SzlJLWIya25Hb2d5WUFRdkItYmtYbzZmWWREZjRheDM2eG9RSFlBMllWMWU0bkVYdm83cjktZ2xfOG51UExfdzR2UE44enM5V2dYWklUSDFhVG5wXzNIYXVrdDlQU2lzY2pBLU1zR1U2VDZIQkZNTVpOaXh5UUZ0VWdqZXlwb0w2bkhjNHI2M0YtRmxYQU1Qc2hLX0lNYUItVjdDQ2NHTjNfbTlUR084QdIBuwFBVV95cUxPWTVUUXJCam5FQXB0aHB5eVdzaGVIUWVHLTJFdUYyOGpfdnFOTm1GLUJ2YzVFMWYyOHJiOEZPSEJSc09VUUtzVEhnd3d1SWlZR05UUS1sa1FheUtITlJjWjM2Ukp2RlY4b2ZKMU44REJ5QldLdzhTY194WEZ4d3oyNHRsOERUb0dieUludXo1bUFrREV0QlNaNU9UaUlYYlFRdFByQzg1dl9RR09CQm1WM0hDY0kzMHFieWdn?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitgFBVV95cUxQWUR5Tzl0SzlJLWIya25Hb2d5WUFRdkItYmtYbzZmWWREZjRheDM2eG9RSFlBMllWMWU0bkVYdm83cjktZ2xfOG51UExfdzR2UE44enM5V2dYWklUSDFhVG5wXzNIYXVrdDlQU2lzY2pBLU1zR1U2VDZIQkZNTVpOaXh5UUZ0VWdqZXlwb0w2bkhjNHI2M0YtRmxYQU1Qc2hLX0lNYUItVjdDQ2NHTjNfbTlUR084QdIBuwFBVV95cUxPWTVUUXJCam5FQXB0aHB5eVdzaGVIUWVHLTJFdUYyOGpfdnFOTm1GLUJ2YzVFMWYyOHJiOEZPSEJSc09VUUtzVEhnd3d1SWlZR05UUS1sa1FheUtITlJjWjM2Ukp2RlY4b2ZKMU44REJ5QldLdzhTY194WEZ4d3oyNHRsOERUb0dieUludXo1bUFrREV0QlNaNU9UaUlYYlFRdFByQzg1dl9RR09CQm1WM0hDY0kzMHFieWdn?oc=5\" target=\"_blank\">Lupa busca 40 empleados para la inminente apertura de Tifer en Soria</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Heraldo-Diario de Soria</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-29T06:15:06Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Tifer"
  },
  {
    "titulo": "Video de la apertura de plicas - Ayuntamiento de Madrid",
    "url": "https://news.google.com/rss/articles/CBMiowRBVV95cUxPNUJnMTVzcDJ3ck40bjY2cTZ5Y3FKOVktTmtYZjMydUFHY0Y2M0hSUE1ZbUZBM05YekJNRGRPcHdfUURaTW0wdUJLN0VYeWdBRWJzbnN3OHNhczNJVklPaTlFdnpFdmhzekJOWXJpSkNtR2F3TTBuM1BFTU0tQzFnYjQ1ZFMxSURyamY5OW5LVEJ6bnFOSW1WSWwxV1FtV1NWOVY1c3pFaGJTZElNakhKM1o2Mm5HbXVFWE01ZVZNdGhCTTBrd3NkdVoxTFI1WGNmS1p3SnBzdXF0Ym1SNW1CSlpVeGd0blJyWHc4ejE2ZkY5UGtyMVB4R1U4eGNnTXEtNXpYYkxvbS1uQ1JKdzhIWXdjT3VjRWZKWXZ2aE1McUVmRU1qSzREcFg2TDV0RVBQVVpQVkZNdm1OYnVhS2Q1eERFR1h0a3VmYVlaX3R0dTFLNmdBOTdUWFZyMUVxWlJET2NXMkkwcUJYNlA4MVdkSFJEVXVzS1BTNUFjRDRRaG1RbGJ2anFSZDJuSW1Qc3V5RGoxb3hnQTFJZUVRVFBWX3FUR1dqeFhkU1JHOXgzTEFRZ0RLMVAzN2JMd0NTSWxEMS04MXRxNzlmc2d1YUN4c1pNY2k3VUJtOXBMRGoxUmpWMGJOWFpJeVhBbmhERDhQQmtxd2ZBRHpuUmRidF8yVFg2YVNkQzQ1MVVSWW41elc2Vy1nYU9aNUxVck1xUFJuT1dj?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiowRBVV95cUxPNUJnMTVzcDJ3ck40bjY2cTZ5Y3FKOVktTmtYZjMydUFHY0Y2M0hSUE1ZbUZBM05YekJNRGRPcHdfUURaTW0wdUJLN0VYeWdBRWJzbnN3OHNhczNJVklPaTlFdnpFdmhzekJOWXJpSkNtR2F3TTBuM1BFTU0tQzFnYjQ1ZFMxSURyamY5OW5LVEJ6bnFOSW1WSWwxV1FtV1NWOVY1c3pFaGJTZElNakhKM1o2Mm5HbXVFWE01ZVZNdGhCTTBrd3NkdVoxTFI1WGNmS1p3SnBzdXF0Ym1SNW1CSlpVeGd0blJyWHc4ejE2ZkY5UGtyMVB4R1U4eGNnTXEtNXpYYkxvbS1uQ1JKdzhIWXdjT3VjRWZKWXZ2aE1McUVmRU1qSzREcFg2TDV0RVBQVVpQVkZNdm1OYnVhS2Q1eERFR1h0a3VmYVlaX3R0dTFLNmdBOTdUWFZyMUVxWlJET2NXMkkwcUJYNlA4MVdkSFJEVXVzS1BTNUFjRDRRaG1RbGJ2anFSZDJuSW1Qc3V5RGoxb3hnQTFJZUVRVFBWX3FUR1dqeFhkU1JHOXgzTEFRZ0RLMVAzN2JMd0NTSWxEMS04MXRxNzlmc2d1YUN4c1pNY2k3VUJtOXBMRGoxUmpWMGJOWFpJeVhBbmhERDhQQmtxd2ZBRHpuUmRidF8yVFg2YVNkQzQ1MVVSWW41elc2Vy1nYU9aNUxVck1xUFJuT1dj?oc=5\" target=\"_blank\">Video de la apertura de plicas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Ayuntamiento de Madrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-29T11:19:39Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento de Madrid"
  },
  {
    "titulo": "Primark empieza a fichar para su nueva tienda en Salamanca: estos son los puestos que busca - Tribuna de Salamanca.",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxQZzFzVkoyY01YWXR1V0lfbWVvRXhxZC16MHAwaFk4TE1KZGZYOG9lV01Db2otOVl0Vmplb0NzbjNmOGp1M1hoVGxuXy1rS0ZtMExtR056WDRmRWYwOHcyQjQtTE1VdUhDQm5qdEYzUDVSYkVxRjhUOHFQd0RUdGJoQnlFNW41V2ZOYVQtbHl4OVlWcEFPT3Z1MFZBZU5zenF3UzhuSW9jTUJnNVh5dEk5U1lyT1RpdlpRN1NSR1l5dHZ1VFZTdnJfcEVfazJmSFJIMDZjNk93?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi1gFBVV95cUxQZzFzVkoyY01YWXR1V0lfbWVvRXhxZC16MHAwaFk4TE1KZGZYOG9lV01Db2otOVl0Vmplb0NzbjNmOGp1M1hoVGxuXy1rS0ZtMExtR056WDRmRWYwOHcyQjQtTE1VdUhDQm5qdEYzUDVSYkVxRjhUOHFQd0RUdGJoQnlFNW41V2ZOYVQtbHl4OVlWcEFPT3Z1MFZBZU5zenF3UzhuSW9jTUJnNVh5dEk5U1lyT1RpdlpRN1NSR1l5dHZ1VFZTdnJfcEVfazJmSFJIMDZjNk93?oc=5\" target=\"_blank\">Primark empieza a fichar para su nueva tienda en Salamanca: estos son los puestos que busca</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Tribuna de Salamanca.</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-02T20:09:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Salamanca"
  },
  {
    "titulo": "Empleo, no gustaría dato demasiado bueno. Apertura en video por Cárpatos 4-9-2026 - Serenity Markets",
    "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxNTXpSaTlDcnU5elZYVmszcFg5XzJYREJUd2Nob3pHLUhINnpXWDYzTFozZGFKXzE2Y3FpT0czUWNaMVlCZXJERUdpcXBvTTFGU0tYRDlTZ3ByZmVOalZpZnJQUUN2WUI5WDBPZ292Vi0zeHVHeUQ2QTA5TFJvY0djeGdCaW9uRVlPMG1vN0hFaVRaM0w4UUhOMWNaU25QWmRBMUJKMU9MUXJmSjJzeFpiZ1EwMXBTSC00MWVZb1BBdw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMivwFBVV95cUxNTXpSaTlDcnU5elZYVmszcFg5XzJYREJUd2Nob3pHLUhINnpXWDYzTFozZGFKXzE2Y3FpT0czUWNaMVlCZXJERUdpcXBvTTFGU0tYRDlTZ3ByZmVOalZpZnJQUUN2WUI5WDBPZ292Vi0zeHVHeUQ2QTA5TFJvY0djeGdCaW9uRVlPMG1vN0hFaVRaM0w4UUhOMWNaU25QWmRBMUJKMU9MUXJmSjJzeFpiZ1EwMXBTSC00MWVZb1BBdw?oc=5\" target=\"_blank\">Empleo, no gustaría dato demasiado bueno. Apertura en video por Cárpatos 4-9-2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Serenity Markets</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-04T07:14:40Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Apertura"
  },
  {
    "titulo": "VIDEONOTICIA. Mequinenza inaugura residencia de ancianos con 78 plazas y que planea crear hasta 40 empleos - Aragón Play",
    "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxPVWtYOVZ4WGdCMmpOckQtZlBIaFk3WUc0a1hLTEVITHB3QUU3VVB4amFmLW54YS02STUzZ0tPUnhUTXlFUVVIdlJQaU5VUkpVOG5pUVNHMzV2SVd4M2x6UTZ2cWpXNEFSaWJSV01KUUljdEZQYXB2X0FRSFZ2NWV0RmNISnBzZXhiWjJCS082QUR5MW5ZMmlUU1lkUG9jSXFqcTVGLTlWengtMVVYbzF6X1lIT1lONmQycEVPSk5sN0RlWVJfaERibno3TkV3eXhSMkxzVlNLSzlhdmVYZFE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi3gFBVV95cUxPVWtYOVZ4WGdCMmpOckQtZlBIaFk3WUc0a1hLTEVITHB3QUU3VVB4amFmLW54YS02STUzZ0tPUnhUTXlFUVVIdlJQaU5VUkpVOG5pUVNHMzV2SVd4M2x6UTZ2cWpXNEFSaWJSV01KUUljdEZQYXB2X0FRSFZ2NWV0RmNISnBzZXhiWjJCS082QUR5MW5ZMmlUU1lkUG9jSXFqcTVGLTlWengtMVVYbzF6X1lIT1lONmQycEVPSk5sN0RlWVJfaERibno3TkV3eXhSMkxzVlNLSzlhdmVYZFE?oc=5\" target=\"_blank\">VIDEONOTICIA. Mequinenza inaugura residencia de ancianos con 78 plazas y que planea crear hasta 40 empleos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Aragón Play</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-02T12:34:42Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Mequinenza"
  },
  {
    "titulo": "Dia refuerza su apuesta por Castilla y León y Castilla-La Mancha con la apertura de dos nuevas tiendas - Revista ARAL",
    "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxORWZCWi1abDEwdFlZQmJ5Y0tCaEh4RUhoSGRQSzVOVWNNanJhRzB1MVRCbkhyM3NLanhOdm4tSEpCX1hmZ3JUcDBsbE5Gd0VVbnAwbjdVYUF6d2w4aWVzb3prOXQzYUZrc1VyYm5nRWxpMWdLZ2VOMTl5dm8zY25uVEVyZjBGS2pDYkNKckJPQ0w0WGhDMGtQempfSTJIOUhjZmExQS1MT2dNTlR6aFJrTUNUcW5aN08yamNWUmtPNTBnMEZGcmJDcmZBRQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxORWZCWi1abDEwdFlZQmJ5Y0tCaEh4RUhoSGRQSzVOVWNNanJhRzB1MVRCbkhyM3NLanhOdm4tSEpCX1hmZ3JUcDBsbE5Gd0VVbnAwbjdVYUF6d2w4aWVzb3prOXQzYUZrc1VyYm5nRWxpMWdLZ2VOMTl5dm8zY25uVEVyZjBGS2pDYkNKckJPQ0w0WGhDMGtQempfSTJIOUhjZmExQS1MT2dNTlR6aFJrTUNUcW5aN08yamNWUmtPNTBnMEZGcmJDcmZBRQ?oc=5\" target=\"_blank\">Dia refuerza su apuesta por Castilla y León y Castilla-La Mancha con la apertura de dos nuevas tiendas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Revista ARAL</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T08:47:29Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Castilla y León"
  },
  {
    "titulo": "Fotos de la apertura de curso en las Escuelas Taller del Ayuntamiento de Pamplona - Noticias de Navarra",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxOdWd2SVNOdG1qbzczVXVKRHdYVkRZMjJzU0I4LW9yTzRWanlGM2hqS1JocTJoYXVjdVZ6Y1NpdGg5QnZYclVnMVRwSXlvaTFvZFI0R2stOHo2VnNpUFktUXA3akRQY1hpYUozY21hZ0VMWXhPVElCbUl2Yzc2bEhOVXNwVWtkNU5WeDFzOW8xbVRucG5Xd2ZvN3JDVjVRbU5zYlRWbnhKUF9yM1ZoWDVv?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMirwFBVV95cUxOdWd2SVNOdG1qbzczVXVKRHdYVkRZMjJzU0I4LW9yTzRWanlGM2hqS1JocTJoYXVjdVZ6Y1NpdGg5QnZYclVnMVRwSXlvaTFvZFI0R2stOHo2VnNpUFktUXA3akRQY1hpYUozY21hZ0VMWXhPVElCbUl2Yzc2bEhOVXNwVWtkNU5WeDFzOW8xbVRucG5Xd2ZvN3JDVjVRbU5zYlRWbnhKUF9yM1ZoWDVv?oc=5\" target=\"_blank\">Fotos de la apertura de curso en las Escuelas Taller del Ayuntamiento de Pamplona</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Noticias de Navarra</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-02T11:58:20Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Escuelas Taller del Ayuntamiento de Pamplona"
  },
  {
    "titulo": "CCOO Canarias responde a Bermúdez: pide “no improvisar” con la apertura dominical y reclama proteger el empleo y el pequeño comercio - Atlántico Hoy",
    "url": "https://news.google.com/rss/articles/CBMigAJBVV95cUxON2t3WWJHUm1GelAyeF82OGNpSmJoOW1ieVhoVFc2UHJpMG4yWHBHYkZYWFJLNEVxb2loeC0tSlZMbXA4bzlxa1pjSi1Fd1RNc0RhaEdubXBsTU5pWFVieVJjZ05BeGxtX2Q1VS00bTRyb24xN1l6N1dJSzNtTFVwYUJTcGQzTXdNMHl4WVE5NFVETVJ4QWl0NWpkcm0tNV9SLTdQdy1jWjBRUTR3N3haTXdjajczTURoXzAzRGVQX19PZ0tFQXdtamYxR2dUZDUyZnhhd3VLNkFpQ2NfaVdnYlBoQWZ1LVVRY05Yand2Z2dyTlpTTWxhWFMwVjVhckho?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMigAJBVV95cUxON2t3WWJHUm1GelAyeF82OGNpSmJoOW1ieVhoVFc2UHJpMG4yWHBHYkZYWFJLNEVxb2loeC0tSlZMbXA4bzlxa1pjSi1Fd1RNc0RhaEdubXBsTU5pWFVieVJjZ05BeGxtX2Q1VS00bTRyb24xN1l6N1dJSzNtTFVwYUJTcGQzTXdNMHl4WVE5NFVETVJ4QWl0NWpkcm0tNV9SLTdQdy1jWjBRUTR3N3haTXdjajczTURoXzAzRGVQX19PZ0tFQXdtamYxR2dUZDUyZnhhd3VLNkFpQ2NfaVdnYlBoQWZ1LVVRY05Yand2Z2dyTlpTTWxhWFMwVjVhckho?oc=5\" target=\"_blank\">CCOO Canarias responde a Bermúdez: pide “no improvisar” con la apertura dominical y reclama proteger el empleo y el pequeño comercio</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Atlántico Hoy</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-02T09:49:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "CCOO Canarias",
    "ubicacion": "“"
  },
  {
    "titulo": "Mercadona invierte 6,5 millones en la apertura de un nuevo supermercado en Canals - Levante-EMV",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxONTh5UXl0aGUtWVZzX3lrdEZvWUJlbHozbDBXdkRQbjFRVk12ZlFmdUo4N3p1LVN2ODhOTl9nRWdmaWdrVUI5NHhjMGlpS1QycFliSTh4cUdNNVkwZzYtR2piSGNjTl81RDlNZ1hyQ29iWGxLdEdwNGlTSjNpWXdIMUtFNmNTTXAzYUV0TmxTc29fTHhnQXFJZNIBngFBVV95cUxQcGU2cFVfM0N3cTMyYnlSZVo0ZkhUV1BRN1BLV3d0Sl9MM1B6a0VyTEZTNTdrek5aZUNYVF9QaWlWQmVPRzdGZ1BLajQ5ekRpb0dIUFU0T1NnZF9HdnZ4VFRqaUVCdmI5TXZWLTZFWFp6RTJ4bGVIV3IyRkJDcWx6eV9NTHZhZnVyTmhJUGh6dVRGMjlvZTF3ZTFWTk5aZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMimAFBVV95cUxONTh5UXl0aGUtWVZzX3lrdEZvWUJlbHozbDBXdkRQbjFRVk12ZlFmdUo4N3p1LVN2ODhOTl9nRWdmaWdrVUI5NHhjMGlpS1QycFliSTh4cUdNNVkwZzYtR2piSGNjTl81RDlNZ1hyQ29iWGxLdEdwNGlTSjNpWXdIMUtFNmNTTXAzYUV0TmxTc29fTHhnQXFJZNIBngFBVV95cUxQcGU2cFVfM0N3cTMyYnlSZVo0ZkhUV1BRN1BLV3d0Sl9MM1B6a0VyTEZTNTdrek5aZUNYVF9QaWlWQmVPRzdGZ1BLajQ5ekRpb0dIUFU0T1NnZF9HdnZ4VFRqaUVCdmI5TXZWLTZFWFp6RTJ4bGVIV3IyRkJDcWx6eV9NTHZhZnVyTmhJUGh6dVRGMjlvZTF3ZTFWTk5aZw?oc=5\" target=\"_blank\">Mercadona invierte 6,5 millones en la apertura de un nuevo supermercado en Canals</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Levante-EMV</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T04:01:01Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Mercadona"
  },
  {
    "titulo": "MediaMarkt ya tiene fecha para su apertura en Ponferrada - Info Bierzo",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOQ0tDdkpaaVVnT0M4MVJpQlhTWlFaQzNZaG9UZTJhVUExcC1IZktTZnFJeGlQSEw0ZHB4ZURUcFBobmthT2VvajhjLTNMWkpBR0FJUzVKOHNZWmdKTkNVdTBwTmdFS1FRX1ZWQW53T3Nic3RpVm11cVFsb0dkTDBWMFBQUUs2T0dHbTd3ZDdVbHVJTXkzQW16YXBJZGpxT3ZrbzgzWWlUeExxTkVYOUdLTDJhaXVITG5P0gG-AUFVX3lxTE84Q29GQUo5NWNxRmRJQmJUUGV5ZWhSUzJ3RmJ5aHdtZVNLNnZ5MEpUWGNXdDA5aUtIQXE1bnFjeGs2MG5kUHU4YmhCd1B1TUQ5QlFETDR2cHRveG5Xb2RxdnpxelpZTC1JVGVQY3BmTDVJOFdoaUIwTmlIQXpydTZCZU1ia0FweGdnMDRIS1JpdEx4QXgzcWUtbU13Nmlqc3lJQ1ItOV9QenRmZUxqVGVuRDZ1RWtZcFR2bFV0Wmc?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiuAFBVV95cUxOQ0tDdkpaaVVnT0M4MVJpQlhTWlFaQzNZaG9UZTJhVUExcC1IZktTZnFJeGlQSEw0ZHB4ZURUcFBobmthT2VvajhjLTNMWkpBR0FJUzVKOHNZWmdKTkNVdTBwTmdFS1FRX1ZWQW53T3Nic3RpVm11cVFsb0dkTDBWMFBQUUs2T0dHbTd3ZDdVbHVJTXkzQW16YXBJZGpxT3ZrbzgzWWlUeExxTkVYOUdLTDJhaXVITG5P0gG-AUFVX3lxTE84Q29GQUo5NWNxRmRJQmJUUGV5ZWhSUzJ3RmJ5aHdtZVNLNnZ5MEpUWGNXdDA5aUtIQXE1bnFjeGs2MG5kUHU4YmhCd1B1TUQ5QlFETDR2cHRveG5Xb2RxdnpxelpZTC1JVGVQY3BmTDVJOFdoaUIwTmlIQXpydTZCZU1ia0FweGdnMDRIS1JpdEx4QXgzcWUtbU13Nmlqc3lJQ1ItOV9QenRmZUxqVGVuRDZ1RWtZcFR2bFV0Wmc?oc=5\" target=\"_blank\">MediaMarkt ya tiene fecha para su apertura en Ponferrada</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Info Bierzo</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-31T08:58:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Ponferrada"
  },
  {
    "titulo": "El IBEX sube un 0,19 % en la apertura atento al empleo en EE.UU., la inflación y a los PMI - Infobae",
    "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxPV0FxUFJOY0pQdWpzVld6WEhVZUY0VXZGeUR3SnYyNE5tdVgtRXNZa01SN3A5RVoxQ0pyVjkydXpoMXNjSm5MSHdWNEd4Rk5DNDlsVkpRemRSOFFvaE4wWFp4ZmpxSFMtcGZHcHVHVm8tYVNpbmJfdHhCS3JWN2l0TEdjNGpxZXVITG5RS2JkWEkzYkZqUjhqaTBLWkY5a0ZpV0JJTURORkl0VFRxalJ0eTkyTTdVeUVHbFJOa0dXX0RIMTNJWV9ELXUzLVNTZXhVRHfSAewBQVVfeXFMUFhHUmJXUUE1aXFJcVFKS25zUk9FWU5ydUs4UzF4VDFPeXJzZV9EVkppMF9SaVBfY25ub2NiSmtTdTRwUjlkZWNWQ2xOb3N0dlB4eFJuRlhMeDdJbENCRGlsS0VMMmdyVlJjSmhSU0tIdGZ6eWtCdDY1dURKNk1TR1RuWk9ZYkc0UncyM0ttQ0g1WHJBbUg4MllrSlFBU0VVcXBubTlYYl83MWotc0l5V1d4M0NRTEthWWRoTW1pNV8yWVNqQkp1ZFd1amc3TmNCTFJ5cFJQX3R6SnpYM1ZWS2t2eXBRRUZQZVN5c3Q?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi0gFBVV95cUxPV0FxUFJOY0pQdWpzVld6WEhVZUY0VXZGeUR3SnYyNE5tdVgtRXNZa01SN3A5RVoxQ0pyVjkydXpoMXNjSm5MSHdWNEd4Rk5DNDlsVkpRemRSOFFvaE4wWFp4ZmpxSFMtcGZHcHVHVm8tYVNpbmJfdHhCS3JWN2l0TEdjNGpxZXVITG5RS2JkWEkzYkZqUjhqaTBLWkY5a0ZpV0JJTURORkl0VFRxalJ0eTkyTTdVeUVHbFJOa0dXX0RIMTNJWV9ELXUzLVNTZXhVRHfSAewBQVVfeXFMUFhHUmJXUUE1aXFJcVFKS25zUk9FWU5ydUs4UzF4VDFPeXJzZV9EVkppMF9SaVBfY25ub2NiSmtTdTRwUjlkZWNWQ2xOb3N0dlB4eFJuRlhMeDdJbENCRGlsS0VMMmdyVlJjSmhSU0tIdGZ6eWtCdDY1dURKNk1TR1RuWk9ZYkc0UncyM0ttQ0g1WHJBbUg4MllrSlFBU0VVcXBubTlYYl83MWotc0l5V1d4M0NRTEthWWRoTW1pNV8yWVNqQkp1ZFd1amc3TmNCTFJ5cFJQX3R6SnpYM1ZWS2t2eXBRRUZQZVN5c3Q?oc=5\" target=\"_blank\">El IBEX sube un 0,19 % en la apertura atento al empleo en EE.UU., la inflación y a los PMI</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Infobae</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T08:17:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "PMI",
    "ubicacion": "EE.UU."
  },
  {
    "titulo": "Tazacorte inaugura el observatorio marino BECOMAR «Rogelio Herrera»: ciencia, empleo y economía azul en el puerto - El Faro de La Palma",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxPQUE3MFlPR2NvRHc0SnJuX1I1OFNqT0NyN2tVTnNVYVVZUy1sZ2pEQzJlWWxvNU5YM0k0ZW9UU2p1ekxXUTI0RVlCcmVsbXRUZkhib1pRZjI3Mk04XzgxSTAzZlZ1bk1sQnRzMldCR1pOTnZESUhWUFZkNl9tTTJTaDl2eTNVRzZJQkNNRF9teU15MUNoOXJHVUJBdw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMimwFBVV95cUxPQUE3MFlPR2NvRHc0SnJuX1I1OFNqT0NyN2tVTnNVYVVZUy1sZ2pEQzJlWWxvNU5YM0k0ZW9UU2p1ekxXUTI0RVlCcmVsbXRUZkhib1pRZjI3Mk04XzgxSTAzZlZ1bk1sQnRzMldCR1pOTnZESUhWUFZkNl9tTTJTaDl2eTNVRzZJQkNNRF9teU15MUNoOXJHVUJBdw?oc=5\" target=\"_blank\">Tazacorte inaugura el observatorio marino BECOMAR «Rogelio Herrera»: ciencia, empleo y economía azul en el puerto</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Faro de La Palma</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T13:14:53Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Tazacorte"
  },
  {
    "titulo": "Primark prepara su llegada al Centro Comercial El Tormes y busca facilitar la contratación de trabajadores en Santa Marta - Salamanca Diario",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxOcm42TTdrVTN1Y0g5QmZOQ3dEN05lWDRYckxjVUwtaERMSmJ4VHBkcnVtdVZFVXRmaDRNaS0xajBNQVNUdUhld0Y1YkdIUV8wWjg2TWZoVFY5c19JMEtMdFlIcExjZWVnV0JMelFpX1ZCc3lPV1p1Nk1SRWZrd1ROLWM3UmVWWG5WYU84WHpDNl9wd3BSTDFoYXVXbGY3TW91TU5BWm5jZDRtUENrRFh0ZU1fenozMk5YWGpONFRtUlIyT1M4a1NVY3FIdGdxOENaS21yb1NMQkXSAbwDQVVfeXFMTlFJem5NNlpRNVYxc2tLUjkwV1lnSzdXcEtNLThWMENDaWVDbF9kXzBfVlYwVzRyY2tMd01qSUt1RlYxbHZvN1dEWEl4cDZyZ2RCYm9FZ2EtQ1JJY1RJM2dJQ194UVZCemRob2NwZ1lnTTh3dEZGQ1FHUUZlRHBtejVoM296a0tpMkphY1lub05MR1hnMjE5dEpMRVRDTVYtM21uT25odktvTzU0b3pqNmljNlR6R1BBMXkwY1VtUUQtckFHWnNvNEdYcVNzM2hRVW9ac1F5aU01NDBzUnNVcG9KVWpSQzMyRmQ3WGVGQ3o3Y1duVkRXY1V3T0dnenh6ckN6TlVnalZBZi1LZm9nZnR6ZTJuVWxNV2JJWWhNNmViZTc5VFdFT1VPeERhdElrRkNVVmtWVVNqdUIweDJhWENyUmJkRVk4cXlnZ3VuOUUzeFlTZTJMZmhWUmtuVnh2bFpyZ0xRVnZzUVo3eTFnUFVGb1dYMEJzNm1MNlpnQTEya19UNTRQSFlIV2xpcGgzeThEX0J2MjN0Sk9zMzVzSnpkU0JkRG5VZ1IyLXI4OVRCWVlSSEdrU2JiZ0E5?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi2AFBVV95cUxOcm42TTdrVTN1Y0g5QmZOQ3dEN05lWDRYckxjVUwtaERMSmJ4VHBkcnVtdVZFVXRmaDRNaS0xajBNQVNUdUhld0Y1YkdIUV8wWjg2TWZoVFY5c19JMEtMdFlIcExjZWVnV0JMelFpX1ZCc3lPV1p1Nk1SRWZrd1ROLWM3UmVWWG5WYU84WHpDNl9wd3BSTDFoYXVXbGY3TW91TU5BWm5jZDRtUENrRFh0ZU1fenozMk5YWGpONFRtUlIyT1M4a1NVY3FIdGdxOENaS21yb1NMQkXSAbwDQVVfeXFMTlFJem5NNlpRNVYxc2tLUjkwV1lnSzdXcEtNLThWMENDaWVDbF9kXzBfVlYwVzRyY2tMd01qSUt1RlYxbHZvN1dEWEl4cDZyZ2RCYm9FZ2EtQ1JJY1RJM2dJQ194UVZCemRob2NwZ1lnTTh3dEZGQ1FHUUZlRHBtejVoM296a0tpMkphY1lub05MR1hnMjE5dEpMRVRDTVYtM21uT25odktvTzU0b3pqNmljNlR6R1BBMXkwY1VtUUQtckFHWnNvNEdYcVNzM2hRVW9ac1F5aU01NDBzUnNVcG9KVWpSQzMyRmQ3WGVGQ3o3Y1duVkRXY1V3T0dnenh6ckN6TlVnalZBZi1LZm9nZnR6ZTJuVWxNV2JJWWhNNmViZTc5VFdFT1VPeERhdElrRkNVVmtWVVNqdUIweDJhWENyUmJkRVk4cXlnZ3VuOUUzeFlTZTJMZmhWUmtuVnh2bFpyZ0xRVnZzUVo3eTFnUFVGb1dYMEJzNm1MNlpnQTEya19UNTRQSFlIV2xpcGgzeThEX0J2MjN0Sk9zMzVzSnpkU0JkRG5VZ1IyLXI4OVRCWVlSSEdrU2JiZ0E5?oc=5\" target=\"_blank\">Primark prepara su llegada al Centro Comercial El Tormes y busca facilitar la contratación de trabajadores en Santa Marta</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Salamanca Diario</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T15:46:28Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Centro Comercial El Tormes"
  },
  {
    "titulo": "Dia refuerza su presencia con la apertura de dos nuevos supermercados - Revista ARAL",
    "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxPOTZ4eGRrQkwzLXpob2hrQjlrQ0w2ZmpzQjdXSWFIODhHS1JuVUNZWWlHU2d3aVI5VkJNOXYtWlc0bG1UeGJjb1RHM3hXWVBDSGhxYVhMTXhXY0xveWhoQW5uZ3loZk9iaDdzRWdOeTRrN2F4QXhxNXJoczQweTZhVGRrbmFVT0ZGSXUzcW9vTWQtc3RNMlE1TzlYSVg2SWtYc2hjRjE0LVE3NlBjS3c?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMirgFBVV95cUxPOTZ4eGRrQkwzLXpob2hrQjlrQ0w2ZmpzQjdXSWFIODhHS1JuVUNZWWlHU2d3aVI5VkJNOXYtWlc0bG1UeGJjb1RHM3hXWVBDSGhxYVhMTXhXY0xveWhoQW5uZ3loZk9iaDdzRWdOeTRrN2F4QXhxNXJoczQweTZhVGRrbmFVT0ZGSXUzcW9vTWQtc3RNMlE1TzlYSVg2SWtYc2hjRjE0LVE3NlBjS3c?oc=5\" target=\"_blank\">Dia refuerza su presencia con la apertura de dos nuevos supermercados</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Revista ARAL</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-02T08:44:18Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La británica Vodafone Group prepara un ERE para el 20% de su filial española - Cinco Días",
    "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPWXBJOS12ZE15UXdwNUNFbFZNNmRnZHVIQUVNQ2J4WEROanZma05aYXB0ZG4tWDJqdjgtR2RIbGRLQ0dXdHhaV19VSjRtNFZpak5EcUdpYTNoMTg3R1lrMUdRTHBUR2JFeUVQMVZtYXpwVWx5ZTJqNlFNenVDRm9rZS15U0J0T2VWQVRfUDc1T3Z3VVpBS3ZMUmYyclk2a2RBV0xZXzVhRFlBdjJKeG5QR3JacFNPaGNHXzJQWFBtaHJ4Z1BGVk5tNmxR0gHeAUFVX3lxTFBVNTE0VThlb0pmZEpEc2d5czh2a01STjhKSTZQaDVkRzhrdDZiQnZ3cG1vREdZNjVzT3l1UzNTNEQ1YU53TDUyZHNPTEVyWFo4MC0xdUhUUURuSWU2Nk1mRWNFalpDdWhVRl9hcWxBY2hNZF85QWlTMF9ka0prcWw1anZFNERpeWw4bVdseEV6UlpreENnTUU3QjVuQUtzWFRhSm55cWx2eS1tbVZhZVcxbTR4M0FJbG96M2N2Z3JwaWVQS1FUbFFGdHBZeFQ3YXVwTHBFQVdRV2toWm1pUQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiygFBVV95cUxPWXBJOS12ZE15UXdwNUNFbFZNNmRnZHVIQUVNQ2J4WEROanZma05aYXB0ZG4tWDJqdjgtR2RIbGRLQ0dXdHhaV19VSjRtNFZpak5EcUdpYTNoMTg3R1lrMUdRTHBUR2JFeUVQMVZtYXpwVWx5ZTJqNlFNenVDRm9rZS15U0J0T2VWQVRfUDc1T3Z3VVpBS3ZMUmYyclk2a2RBV0xZXzVhRFlBdjJKeG5QR3JacFNPaGNHXzJQWFBtaHJ4Z1BGVk5tNmxR0gHeAUFVX3lxTFBVNTE0VThlb0pmZEpEc2d5czh2a01STjhKSTZQaDVkRzhrdDZiQnZ3cG1vREdZNjVzT3l1UzNTNEQ1YU53TDUyZHNPTEVyWFo4MC0xdUhUUURuSWU2Nk1mRWNFalpDdWhVRl9hcWxBY2hNZF85QWlTMF9ka0prcWw1anZFNERpeWw4bVdseEV6UlpreENnTUU3QjVuQUtzWFRhSm55cWx2eS1tbVZhZVcxbTR4M0FJbG96M2N2Z3JwaWVQS1FUbFFGdHBZeFQ3YXVwTHBFQVdRV2toWm1pUQ?oc=5\" target=\"_blank\">La británica Vodafone Group prepara un ERE para el 20% de su filial española</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Cinco Días</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T15:09:34Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Vodafone Group",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Vodafone presenta un ERE de hasta 180 empleados en su filial VOIS en España - El Confidencial",
    "url": "https://news.google.com/rss/articles/CBMigwFBVV95cUxNQ3ZxeER6d1JQLVRySDBuNWsxckpYQVRfVm1COFVnWHBhV0hiVEhNa0JfQzJSZUF5MEVPOXFIblNKWkpOSnZpUTFwUktPY2UyVGZiR2RyeXZENTI4anhOU1BWNU5rbmZkOW9BMWpxalluUGs3UG5zaUdRQzA0X001aWxYZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMigwFBVV95cUxNQ3ZxeER6d1JQLVRySDBuNWsxckpYQVRfVm1COFVnWHBhV0hiVEhNa0JfQzJSZUF5MEVPOXFIblNKWkpOSnZpUTFwUktPY2UyVGZiR2RyeXZENTI4anhOU1BWNU5rbmZkOW9BMWpxalluUGs3UG5zaUdRQzA0X001aWxYZw?oc=5\" target=\"_blank\">Vodafone presenta un ERE de hasta 180 empleados en su filial VOIS en España</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Confidencial</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T16:33:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Vodafone"
  },
  {
    "titulo": "La británica Vodafone Group plantea un ERE para el 20% de la plantilla de VOIS en España - Expansión",
    "url": "https://news.google.com/rss/articles/CBMijwFBVV95cUxObTh6eV9jS2tDRWltNGVmQWVKVzR2am9JN3hYcFFJVWdtMEhVTm92UUhicG9mVEY5LVR4WEdMTG5zWDEyS3QtSWp2UURCUmo5dUFPTGRKZGFYWDVZOTdsaVI5WVdkVjdETHpwRjNaa1IxWW42STRVQnNwRU1Fdl9oSUZ4MWtMVF96TUVjUXRXUdIBjwFBVV95cUxQQnZDeDl3VV9sRE9XMlJ1WG5iY25NRmNkeG5saTM4ajM2dFprb2dUbDVzQkdPak00UVJXWnNldVdMNm94SmVyeDc5TGtoQkJ2cWMydTZvOFEzampCeDFPZkhSclZ1OV9leHlDcDNJVmIxZjlObU8yaVU1OGlCLWctYlhyMFhvYWRicl92Mkk2dw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMijwFBVV95cUxObTh6eV9jS2tDRWltNGVmQWVKVzR2am9JN3hYcFFJVWdtMEhVTm92UUhicG9mVEY5LVR4WEdMTG5zWDEyS3QtSWp2UURCUmo5dUFPTGRKZGFYWDVZOTdsaVI5WVdkVjdETHpwRjNaa1IxWW42STRVQnNwRU1Fdl9oSUZ4MWtMVF96TUVjUXRXUdIBjwFBVV95cUxQQnZDeDl3VV9sRE9XMlJ1WG5iY25NRmNkeG5saTM4ajM2dFprb2dUbDVzQkdPak00UVJXWnNldVdMNm94SmVyeDc5TGtoQkJ2cWMydTZvOFEzampCeDFPZkhSclZ1OV9leHlDcDNJVmIxZjlObU8yaVU1OGlCLWctYlhyMFhvYWRicl92Mkk2dw?oc=5\" target=\"_blank\">La británica Vodafone Group plantea un ERE para el 20% de la plantilla de VOIS en España</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Expansión</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T14:43:20Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Vodafone Group",
    "ubicacion": "VOIS"
  },
  {
    "titulo": "La última empresa de Vodafone Grupo en España anuncia un ERE para el 20% de su planilla - elespanol.com",
    "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxOSXVfcEZHUjZsOU90ZWtySkV3Z3E5bkJJOHBPNXJFTXJrRnNkT0g4VHJhenBvaGlhRkpSNEFpWF9jaTZlQ3dIVzRDYjJ1LXM0R29vU0owTDdGN1JVU2Rja2FJQzMzWmZodllfUU5QOTVFcTVLSzdfWDh5UW8yQWZRVjJrRTBTODAyUURwNWoteWFfQ1kyWHRqTHp4U1cwNU1kZ0ViQVNXeVlDMDNKTWNsOXJvVkgxai00N3BNa0JUNlRpTHVsNjRydTluWmFWZVJLUVBNN3ZLQmZMZ9IB3wFBVV95cUxQSWxWcWVDYldsaWNnZWpHUy1IQ3hBQm1KME9ldk41dVo3Y25udFpCRDhxckFCUjlmcERNLWdsSEM4czN6Vk94VFZQU3VtYXBvTFFNSGIzYjNkbFBhVWdtN2g1WmhyeHdmYmFVZkZ3czR4Mk00VmdOVmxDZFZiLVQ1VVE5c0FYODNzNVRYQ1RtWjJTMXRTX2xiTzlFSW82V2xnaVVKVUphMGRIUVhlV29PVmJTNjFGTENIM0I4UXd1UXkydXJ2V3E1aFItRlNyLUo4ZDgyMEFVYzFPYVdaUVQw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi2gFBVV95cUxOSXVfcEZHUjZsOU90ZWtySkV3Z3E5bkJJOHBPNXJFTXJrRnNkT0g4VHJhenBvaGlhRkpSNEFpWF9jaTZlQ3dIVzRDYjJ1LXM0R29vU0owTDdGN1JVU2Rja2FJQzMzWmZodllfUU5QOTVFcTVLSzdfWDh5UW8yQWZRVjJrRTBTODAyUURwNWoteWFfQ1kyWHRqTHp4U1cwNU1kZ0ViQVNXeVlDMDNKTWNsOXJvVkgxai00N3BNa0JUNlRpTHVsNjRydTluWmFWZVJLUVBNN3ZLQmZMZ9IB3wFBVV95cUxQSWxWcWVDYldsaWNnZWpHUy1IQ3hBQm1KME9ldk41dVo3Y25udFpCRDhxckFCUjlmcERNLWdsSEM4czN6Vk94VFZQU3VtYXBvTFFNSGIzYjNkbFBhVWdtN2g1WmhyeHdmYmFVZkZ3czR4Mk00VmdOVmxDZFZiLVQ1VVE5c0FYODNzNVRYQ1RtWjJTMXRTX2xiTzlFSW82V2xnaVVKVUphMGRIUVhlV29PVmJTNjFGTENIM0I4UXd1UXkydXJ2V3E1aFItRlNyLUo4ZDgyMEFVYzFPYVdaUVQw?oc=5\" target=\"_blank\">La última empresa de Vodafone Grupo en España anuncia un ERE para el 20% de su planilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">elespanol.com</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T15:02:42Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "Vodafone Grupo"
  },
  {
    "titulo": "Iveco prepara un nuevo ERTE para asumir otra caída de pedidos - El Día de Valladolid",
    "url": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxORHpDLUk1eTBNcW12aEJCOFdvdDNfZ1lkNjMyYnBhaFBZOEdFMENwS1pmVFVNZzl0bGFnbHhOX2VwVTV3UGRvUVU2U29Bd1hUZVA0QlJPSy15U3BvSHItTDNQbmRXeDlrdDl1dlFUcmtodWczN1l4U1c3QXBuTjdtSjZkOTlrQ05ueVkwT0ZDazEyUDhVWmQtLTFJUkJCOVp4aWZOVnpmVmZmVFRjQXgwQUJGV2JLYjFjcGVjclQ2dnpfWGlvSjJGY0I1dW1ySEFxaUxIaFVMSXdCSGFEWENNRw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi4AFBVV95cUxORHpDLUk1eTBNcW12aEJCOFdvdDNfZ1lkNjMyYnBhaFBZOEdFMENwS1pmVFVNZzl0bGFnbHhOX2VwVTV3UGRvUVU2U29Bd1hUZVA0QlJPSy15U3BvSHItTDNQbmRXeDlrdDl1dlFUcmtodWczN1l4U1c3QXBuTjdtSjZkOTlrQ05ueVkwT0ZDazEyUDhVWmQtLTFJUkJCOVp4aWZOVnpmVmZmVFRjQXgwQUJGV2JLYjFjcGVjclQ2dnpfWGlvSjJGY0I1dW1ySEFxaUxIaFVMSXdCSGFEWENNRw?oc=5\" target=\"_blank\">Iveco prepara un nuevo ERTE para asumir otra caída de pedidos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Día de Valladolid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-28T12:41:28Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Iveco",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "VOIS, la filial de Vodafone, plantea un ERE en España que afectaría a un máximo de 180 trabajadores lo que supone el 20% de la plantilla - 20minutos.es",
    "url": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxNT3FIMFRrdEg3NTFPdEVsUTh1MXpQZUJPelVoX1JfZFpsU2tIemdad3EtcjJ4ck40S3ExUjdWYUl1M2NaYUtnVWg0TTVMeV9mVF9zdnpXakkwa1ZQMng2MGJ4ZlFUdG5SQ3VoMWh1WEJjbk1RcVdUaUxjREFub2ozVTQ5SmF4cTZiaVNQYTBvVF8xQjZWLUZIZURjbkg4YXBFVEd3Nlplcko4djA0S2E1SG03WHdJRFRDbFFIMTdVcEc4aFY2d2M2ZUtmYnRVWFlLNmFPVlpOSFdVOXhKa1g3LWQ3QkxsTzZWTVZ0VHZJcjREVTZHVk9MUGp2bHFNZGs?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi_wFBVV95cUxNT3FIMFRrdEg3NTFPdEVsUTh1MXpQZUJPelVoX1JfZFpsU2tIemdad3EtcjJ4ck40S3ExUjdWYUl1M2NaYUtnVWg0TTVMeV9mVF9zdnpXakkwa1ZQMng2MGJ4ZlFUdG5SQ3VoMWh1WEJjbk1RcVdUaUxjREFub2ozVTQ5SmF4cTZiaVNQYTBvVF8xQjZWLUZIZURjbkg4YXBFVEd3Nlplcko4djA0S2E1SG03WHdJRFRDbFFIMTdVcEc4aFY2d2M2ZUtmYnRVWFlLNmFPVlpOSFdVOXhKa1g3LWQ3QkxsTzZWTVZ0VHZJcjREVTZHVk9MUGp2bHFNZGs?oc=5\" target=\"_blank\">VOIS, la filial de Vodafone, plantea un ERE en España que afectaría a un máximo de 180 trabajadores lo que supone el 20% de la plantilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">20minutos.es</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T18:37:35Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "VOIS"
  },
  {
    "titulo": "Concentrix fulmina en A Coruña más de 150 empleos tras cerrar sin acuerdo su segundo ERE en un mes - La Opinión A Coruña",
    "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxOTDUwSlljQnl3c0owcTJUSDBsSm1BWDRmck5ueTk4Y0RQeDRMYl93TlhtdWtlbjEyMVctNWp0ZFM3VHkzSHhta1R6YzBQSTFJTUhLVDlJWWJ1Rk9EcTJiM25hU2U4Z1hZNVBDMU9LaGhrOU5SN0lqSFdUTzEzYWtFN2tqUU0zUFkwRWw1a3lvTXZmbGRJaXlfNHRzNGdqcmlyeXfSAacBQVVfeXFMT2tRd3FramZBTnJJTm9lb1hVZjM0OXc4WG9MZ000RXFvNGlzdlQ0aUVJd1NoclpYOFZpaGpnN3BFQ1ZVNi1yUThoaF8xTmRCeUFwbl82UHJBM3pvYnpQVHRFdjRMZmxKT2RseHFsYUJUUXVEUmppdTZFMGk5cGVnb3pmWFNEaDFaN3VMWU1MbWdhdmJ5OXNCeHNPUzN5TXBFNG9aQTZlbEU?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiogFBVV95cUxOTDUwSlljQnl3c0owcTJUSDBsSm1BWDRmck5ueTk4Y0RQeDRMYl93TlhtdWtlbjEyMVctNWp0ZFM3VHkzSHhta1R6YzBQSTFJTUhLVDlJWWJ1Rk9EcTJiM25hU2U4Z1hZNVBDMU9LaGhrOU5SN0lqSFdUTzEzYWtFN2tqUU0zUFkwRWw1a3lvTXZmbGRJaXlfNHRzNGdqcmlyeXfSAacBQVVfeXFMT2tRd3FramZBTnJJTm9lb1hVZjM0OXc4WG9MZ000RXFvNGlzdlQ0aUVJd1NoclpYOFZpaGpnN3BFQ1ZVNi1yUThoaF8xTmRCeUFwbl82UHJBM3pvYnpQVHRFdjRMZmxKT2RseHFsYUJUUXVEUmppdTZFMGk5cGVnb3pmWFNEaDFaN3VMWU1MbWdhdmJ5OXNCeHNPUzN5TXBFNG9aQTZlbEU?oc=5\" target=\"_blank\">Concentrix fulmina en A Coruña más de 150 empleos tras cerrar sin acuerdo su segundo ERE en un mes</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Opinión A Coruña</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-27T15:45:11Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "VOIS comunica un ERE que afectará al 20% de una plantilla compuesta por 900 personas trabajadoras - FeSMC - UGT",
    "url": "https://news.google.com/rss/articles/CBMiiAJBVV95cUxOU1lfamNDSXVsZG02LV9VbVZmd2s1Z0hoOE1DTGpoZlJjRlhKYjJHS2RtRTVzQ3lEdTliX1ljZXcycGZxSzRTVHhncEZ0QlhQLTlybmFVc25hcmlUNEVvNVZVYm04RER3QnQtamZ4M3EtWmZ5STl0bHlTM19XLUpHeUxMc1FtSTFHajJ5eDZvZEhlamdmLXBsb20yRjlIQXNkeTFPa0Yxd25wSno1S0h1TUl5OG56QjdXRDkxTFlTZm9EOC1iSkc4S2dYamt5WDJIWW9TcGJRalh2R3FTOE8xNXd1OFNrOFF1Z1R4T3hkcTBQTHNqLWJVWlVveWhwTG5uUUs5UDgzbHQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiiAJBVV95cUxOU1lfamNDSXVsZG02LV9VbVZmd2s1Z0hoOE1DTGpoZlJjRlhKYjJHS2RtRTVzQ3lEdTliX1ljZXcycGZxSzRTVHhncEZ0QlhQLTlybmFVc25hcmlUNEVvNVZVYm04RER3QnQtamZ4M3EtWmZ5STl0bHlTM19XLUpHeUxMc1FtSTFHajJ5eDZvZEhlamdmLXBsb20yRjlIQXNkeTFPa0Yxd25wSno1S0h1TUl5OG56QjdXRDkxTFlTZm9EOC1iSkc4S2dYamt5WDJIWW9TcGJRalh2R3FTOE8xNXd1OFNrOFF1Z1R4T3hkcTBQTHNqLWJVWlVveWhwTG5uUUs5UDgzbHQ?oc=5\" target=\"_blank\">VOIS comunica un ERE que afectará al 20% de una plantilla compuesta por 900 personas trabajadoras</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">FeSMC - UGT</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-02T06:35:50Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "UGT",
    "ubicacion": "VOIS"
  },
  {
    "titulo": "Gabinete de Comunicación - Ministerio de Trabajo y Economía Social",
    "url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE9BbDVnYV9mdUpTcC1kZHN6alFPcU8xdVM3aHVkaHE3TWxub2VSZzRYeUt1Nm9GZzNxb1NaUTVkd3ZGMGRlOE9VYWtnNUtLb2pTb29WelV5dm04Y1ozQWo3cUZuWVNvZmNBTlVWc3lZcnNfY1NX?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMidEFVX3lxTE9BbDVnYV9mdUpTcC1kZHN6alFPcU8xdVM3aHVkaHE3TWxub2VSZzRYeUt1Nm9GZzNxb1NaUTVkd3ZGMGRlOE9VYWtnNUtLb2pTb29WelV5dm04Y1ozQWo3cUZuWVNvZmNBTlVWc3lZcnNfY1NX?oc=5\" target=\"_blank\">Gabinete de Comunicación</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Ministerio de Trabajo y Economía Social</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T11:24:45Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "Aemsa Santana plantea el cierre de la planta de Linares y ERE colectivo - extrajaen.com",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxQemhQNEk3elNqbktSa3FrQlRTcTRjdzZvbm9qQ3RsT1pXR1lCYkRRdGlrSVBSSVRibTBxNm1qeFRGSnF3Vm9aUjVza2JwS2ZlX2V6SjhSM3BocEFKTEhQQng2bkxPUnJ4N1N3RVZULTI2UHRnUTlIS3J6c3VMQ19PM2xMSk8yaW5ET2VibkU4ZWg0YlB6cVdJdnVKLURRd0U?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMinwFBVV95cUxQemhQNEk3elNqbktSa3FrQlRTcTRjdzZvbm9qQ3RsT1pXR1lCYkRRdGlrSVBSSVRibTBxNm1qeFRGSnF3Vm9aUjVza2JwS2ZlX2V6SjhSM3BocEFKTEhQQng2bkxPUnJ4N1N3RVZULTI2UHRnUTlIS3J6c3VMQ19PM2xMSk8yaW5ET2VibkU4ZWg0YlB6cVdJdnVKLURRd0U?oc=5\" target=\"_blank\">Aemsa Santana plantea el cierre de la planta de Linares y ERE colectivo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">extrajaen.com</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T05:06:18Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Linares"
  },
  {
    "titulo": "VOIS (Vodafone) plantea un ERE que podría afectar a 180 trabajadores en España - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxPeU8xd243b3p5T1lKWFFzM29tbXBOZWEwaV94VjY4S0R2cWhidjNoVDF4YzNsdTJnRnJvV2RpdWIzWXFESUtIUlE3aWJ5T0YweE1Ta2VoTXhBSEZWRko3dUwtY0RFQ2ZSVFY5c3dveFBlY2N0YnhlX1lNZVZORkpLdl9DbmVIRVFGUFZMNXBWd3RnRVJwZXRHcDRQZGRYZHVkd3N6NHFRMDJSQm43d3pCQ2U4NVpiNkQyREFaaEI1OWtHNEI1d29KS3h5d1FWdw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMizgFBVV95cUxPeU8xd243b3p5T1lKWFFzM29tbXBOZWEwaV94VjY4S0R2cWhidjNoVDF4YzNsdTJnRnJvV2RpdWIzWXFESUtIUlE3aWJ5T0YweE1Ta2VoTXhBSEZWRko3dUwtY0RFQ2ZSVFY5c3dveFBlY2N0YnhlX1lNZVZORkpLdl9DbmVIRVFGUFZMNXBWd3RnRVJwZXRHcDRQZGRYZHVkd3N6NHFRMDJSQm43d3pCQ2U4NVpiNkQyREFaaEI1OWtHNEI1d29KS3h5d1FWdw?oc=5\" target=\"_blank\">VOIS (Vodafone) plantea un ERE que podría afectar a 180 trabajadores en España</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">RRHH Digital</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T13:48:08Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "VOIS"
  },
  {
    "titulo": "La filial de I+D de la británica Vodafone Group anuncia un ERE para 180 empleados en España - Economía Digital",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPZEZEc2VWWmkxUEZiVGlIMV9vdFpacDhPRl9razFHdlI5XzlIbG9fLWR6Y3VJY2x0SkRGMWRrNGMyeDhpXzc5RjBDZzV4QjJEU3YwT293RWlTYTBPQjRxcXhqLTNEem1lMEhsczlyU0h5dzZxWUgxMjBMUDdmTWZUZGx1ZzAyZHdUbFVFMHB5SERKNWtfRGtkY3hqc183czFtWi0wSmJGSDVSVENBZXJuZWJn0gG3AUFVX3lxTE9fNm5IU24zdV96STcxSDlCaWN5LVdrZDZMbkthaU1NWDZoNlctb0xOdVY4eFltWFMxOTAzeXotaktyckRFbjZ1MXdMU3VibktQbXItamllUFdTR1R1SWhhai1haVpfaVRDWXVZcWNYeGxudWRubmkzWFpXdXpMLTN0aVUwb2JNZk5tNU45Rlhmbk16U0ZOWndxMUFGcGlScmJwV2NzMnFHcEFqYlZtNVhqYTNpVUxpZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMisgFBVV95cUxPZEZEc2VWWmkxUEZiVGlIMV9vdFpacDhPRl9razFHdlI5XzlIbG9fLWR6Y3VJY2x0SkRGMWRrNGMyeDhpXzc5RjBDZzV4QjJEU3YwT293RWlTYTBPQjRxcXhqLTNEem1lMEhsczlyU0h5dzZxWUgxMjBMUDdmTWZUZGx1ZzAyZHdUbFVFMHB5SERKNWtfRGtkY3hqc183czFtWi0wSmJGSDVSVENBZXJuZWJn0gG3AUFVX3lxTE9fNm5IU24zdV96STcxSDlCaWN5LVdrZDZMbkthaU1NWDZoNlctb0xOdVY4eFltWFMxOTAzeXotaktyckRFbjZ1MXdMU3VibktQbXItamllUFdTR1R1SWhhai1haVpfaVRDWXVZcWNYeGxudWRubmkzWFpXdXpMLTN0aVUwb2JNZk5tNU45Rlhmbk16U0ZOWndxMUFGcGlScmJwV2NzMnFHcEFqYlZtNVhqYTNpVUxpZw?oc=5\" target=\"_blank\">La filial de I+D de la británica Vodafone Group anuncia un ERE para 180 empleados en España</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Economía Digital</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-01T15:11:11Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "I+D",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ojo con los criterios de indemnización en un ERE voluntario: el trabajador puede reclamar si la suma es discriminatoria - Law&Trends",
    "url": "https://news.google.com/rss/articles/CBMigAJBVV95cUxQQlJMTTVhVjRod2pRYmdHN1FQZmQwaUhkM1dJcVB1SXlnNWtsdW9CTElQWUQzcmxJdVR5VjlBQU93MmJRVmlGbUVtbVEtNXNNeWtPa2ctd3pNR3BWbUZSY185eV8zNHVlRV85Q0V6M3plVi1xSGlLb01kMm4zUHN6RWNUcGpEN2VMLTAzTjk1ZjlLYWs1Z1ZZcGM4VEh0N1Y4V1pkQVpmVVg2YWZsdHIyZ3lnRm9wSFVsYnpjbkhVeXpLTXZmRmZ6aWY3cHVrNnh3eHF3MHlaMFhvODlCd3hRdDdaWjBVMnQ4QkZJYkxIbTJYc1BzWXdiRHRHa3VXMDRv?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMigAJBVV95cUxQQlJMTTVhVjRod2pRYmdHN1FQZmQwaUhkM1dJcVB1SXlnNWtsdW9CTElQWUQzcmxJdVR5VjlBQU93MmJRVmlGbUVtbVEtNXNNeWtPa2ctd3pNR3BWbUZSY185eV8zNHVlRV85Q0V6M3plVi1xSGlLb01kMm4zUHN6RWNUcGpEN2VMLTAzTjk1ZjlLYWs1Z1ZZcGM4VEh0N1Y4V1pkQVpmVVg2YWZsdHIyZ3lnRm9wSFVsYnpjbkhVeXpLTXZmRmZ6aWY3cHVrNnh3eHF3MHlaMFhvODlCd3hRdDdaWjBVMnQ4QkZJYkxIbTJYc1BzWXdiRHRHa3VXMDRv?oc=5\" target=\"_blank\">Ojo con los criterios de indemnización en un ERE voluntario: el trabajador puede reclamar si la suma es discriminatoria</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Law&amp;Trends</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-28T16:41:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "indemnización"
  },
  {
    "titulo": "El Gobierno reforzará los ERTE para Ceuta: derecho a paro sin cotización previa y 100% bonificados a las empresas - elDiario.es",
    "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxNVlRoZ2h6bGF0WWEtZVMwTTcxTk1zY3FaRmdYZkpKU2RPQmxZQkIwSmNtZ0dBT3Jxb2tGTVVTdXh4TEtFZUVNemhHWU5mX3BtSGU3TllpT21lZzFVdWhOUDJzMGs1MFBIMjFHY3pRaEdLbmRnMExZTmNDdlZWMjluR3NEVDJBRzYxaU9QelM1bURzZ1F6bGFvby1vQlJQS3gwdTk3Y2ozUWxoV0hkS0xZcW5TRDdKQ0QyRl9PaDFxNW1uZjlCTmEya0s1MFByY3fSAdQBQVVfeXFMUFpVeUNqakNTSndyMDQ0aTBxd2ZWMk4zS3oxY0tYekFlMmVIX1hIZVRCYXhvY0pHaUFJTm41Zk94VzdLT1RGVFNrdHVyeV9YSjRXb0FNTzFtZm1tM3lHSDExSHFXZWFvLTBPMFh6ckdHM3AxOW82c2xNWjdCWjZkdExMLWJtcmIwNFJhOF9VOVBySHAwMzZWeU5MM1VoWS1ZVnB1b1BOUk9nSS1aRDNZZDFYVWFGRnJiTnlLcnFsaUIwSzdGbk1hUmxJNlNnYURZODRDZmk?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMizwFBVV95cUxNVlRoZ2h6bGF0WWEtZVMwTTcxTk1zY3FaRmdYZkpKU2RPQmxZQkIwSmNtZ0dBT3Jxb2tGTVVTdXh4TEtFZUVNemhHWU5mX3BtSGU3TllpT21lZzFVdWhOUDJzMGs1MFBIMjFHY3pRaEdLbmRnMExZTmNDdlZWMjluR3NEVDJBRzYxaU9QelM1bURzZ1F6bGFvby1vQlJQS3gwdTk3Y2ozUWxoV0hkS0xZcW5TRDdKQ0QyRl9PaDFxNW1uZjlCTmEya0s1MFByY3fSAdQBQVVfeXFMUFpVeUNqakNTSndyMDQ0aTBxd2ZWMk4zS3oxY0tYekFlMmVIX1hIZVRCYXhvY0pHaUFJTm41Zk94VzdLT1RGVFNrdHVyeV9YSjRXb0FNTzFtZm1tM3lHSDExSHFXZWFvLTBPMFh6ckdHM3AxOW82c2xNWjdCWjZkdExMLWJtcmIwNFJhOF9VOVBySHAwMzZWeU5MM1VoWS1ZVnB1b1BOUk9nSS1aRDNZZDFYVWFGRnJiTnlLcnFsaUIwSzdGbk1hUmxJNlNnYURZODRDZmk?oc=5\" target=\"_blank\">El Gobierno reforzará los ERTE para Ceuta: derecho a paro sin cotización previa y 100% bonificados a las empresas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">elDiario.es</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-08-31T07:53:57Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Gobierno"
  },
  {
    "titulo": "Aemsa Linares plantea un ERE para toda su plantilla - El Nuevo Observador",
    "url": "https://news.google.com/rss/articles/CBMiigFBVV95cUxOb2VWZnpQYk1oTk9DYkkyM3dTd1lnaW1zX2NvNzRrV1RHQnJCbVpSbkJRYy1OMFVzN3pHdjI4OFdvSTNGSGtnX3lfUmFXS1VGSUliblRYclVPckFZdTFYdUJ1enVYc2xqT2Iyd0hQdnJJT3NSdWlSOWVEM1N4aXd3Tm1xaVdFQ2VreXc?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiigFBVV95cUxOb2VWZnpQYk1oTk9DYkkyM3dTd1lnaW1zX2NvNzRrV1RHQnJCbVpSbkJRYy1OMFVzN3pHdjI4OFdvSTNGSGtnX3lfUmFXS1VGSUliblRYclVPckFZdTFYdUJ1enVYc2xqT2Iyd0hQdnJJT3NSdWlSOWVEM1N4aXd3Tm1xaVdFQ2VreXc?oc=5\" target=\"_blank\">Aemsa Linares plantea un ERE para toda su plantilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Nuevo Observador</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-09-03T10:25:55Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Aemsa Linares",
    "ubicacion": "Nacional"
  }
];