const window_leads_data = [
  {
    "titulo": "BBVA replantea las contrataciones en su área tecnológica ante la incertidumbre de la IA - El Economista",
    "url": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxQb3ZrRDVHaTRSS080aHlXV25reS1hbk9SZktWUlF2WkhCbFZTTWxhWkluY091ck1DRnpJaFFNSGQwb3QtZjAtRFJwNnNYNkRQd1ZLX3RwQzhYcFRLcHV4RVdUOERpNkNibWw1R1BZNlE3SThXc1RuYU1ZcGdTeGZxVVhCbTZEV1lsTE5GcVU3TnUxa2ZOTW9hVVZLTTlyMjlWUkVIdVN3U0VzT2ZHaGxZNlJnT01vUmxTcUxkUm9TYndBcVRjVGJVZktCVjVyRzlZZElpd1lld1UtZE1feTJCVmFSUS00ZDFGUC1aOEdXZkXSAdsBQVVfeXFMTUx1VnJBSXlJanlZWTBMUHFYazBIYzdHV3ZzVE5ETklJamE2MUo4eFAzeFpGenF3c28xWWY5aFV6WjZUdDBJTGhIZkZieVR4Y1dWYnFlaGdOd1ZJTUlFQllQUm05YlF6YlppWHBIV1lwcjVFZ0xfd3FZNmRBQVFvbXNJRERzSTRjd0tiOXE5UElPVlhSZC16MmNiR1Y5VGRYZE5tRGZjMHdZWDhybjFCdkZVSzNpcnhMbEJ5OUFXSkVWZGtrQVpXeGRSWFZTVC0tc2g5TTdHdWp0Q05B?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi8AFBVV95cUxQb3ZrRDVHaTRSS080aHlXV25reS1hbk9SZktWUlF2WkhCbFZTTWxhWkluY091ck1DRnpJaFFNSGQwb3QtZjAtRFJwNnNYNkRQd1ZLX3RwQzhYcFRLcHV4RVdUOERpNkNibWw1R1BZNlE3SThXc1RuYU1ZcGdTeGZxVVhCbTZEV1lsTE5GcVU3TnUxa2ZOTW9hVVZLTTlyMjlWUkVIdVN3U0VzT2ZHaGxZNlJnT01vUmxTcUxkUm9TYndBcVRjVGJVZktCVjVyRzlZZElpd1lld1UtZE1feTJCVmFSUS00ZDFGUC1aOEdXZkXSAdsBQVVfeXFMTUx1VnJBSXlJanlZWTBMUHFYazBIYzdHV3ZzVE5ETklJamE2MUo4eFAzeFpGenF3c28xWWY5aFV6WjZUdDBJTGhIZkZieVR4Y1dWYnFlaGdOd1ZJTUlFQllQUm05YlF6YlppWHBIV1lwcjVFZ0xfd3FZNmRBQVFvbXNJRERzSTRjd0tiOXE5UElPVlhSZC16MmNiR1Y5VGRYZE5tRGZjMHdZWDhybjFCdkZVSzNpcnhMbEJ5OUFXSkVWZGtrQVpXeGRSWFZTVC0tc2g5TTdHdWp0Q05B?oc=5\" target=\"_blank\">BBVA replantea las contrataciones en su área tecnológica ante la incertidumbre de la IA</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Economista</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T04:00:50Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "BBVA",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 23 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPamlXTVFpaVFsX2VCMXM4by1PM0xHOExvUi1MdFNRSDVPNmVTQjlqSFdaa0lEMzhPejM5bzBRUi1BRXVINGY1cWlqZjg2cWFVVG5JRjlIdHRMTmJQQmxiX3l2UUNhTzNnaEF2cGJqWnNHZWx3TjZRSWVxcmZXQkR4TzVMUEJ4a0JXa1JjVFMxN1Y3MjVBWjMtOHZWdUk3TXdNSVJ5NVF6WG9vdFZxRGtBOWVRUzF4Vm9sOEdIOFgyUDh3cUVKM3h3QktfNTBHSVhWUFhJV0hzX2dYei1iTEp6cGEwTFVlZlXSAewBQVVfeXFMUDh0VFhrbi0wVm81dVFyOExnRnAwS1hfWVVsRFNVNTZYMlVnX0xkNXdJaTV0TENOTVJoUkNmeW1qLUpkekpETWhJVUNZWU5TbTkxSVY2S2NJUkJlX0ZMVWQ0LUxoYmN1UW53bWdxNDFjM2YyU3JNdElzckVYZkNqZDE0a0Z4SlJteVNpYlY2Zm5Sc0x1NU1HcDRHTy11Mjgta0tvZGoyY0RuUWZlRmV5ZGVQV1lTdF9UZ3hvX0hWS01oZmFnZU9JdkZqZWlMQ1hpTEczUUlHRE9FaDNCenRtdS12M3djX0lJN3U1c3Y?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPamlXTVFpaVFsX2VCMXM4by1PM0xHOExvUi1MdFNRSDVPNmVTQjlqSFdaa0lEMzhPejM5bzBRUi1BRXVINGY1cWlqZjg2cWFVVG5JRjlIdHRMTmJQQmxiX3l2UUNhTzNnaEF2cGJqWnNHZWx3TjZRSWVxcmZXQkR4TzVMUEJ4a0JXa1JjVFMxN1Y3MjVBWjMtOHZWdUk3TXdNSVJ5NVF6WG9vdFZxRGtBOWVRUzF4Vm9sOEdIOFgyUDh3cUVKM3h3QktfNTBHSVhWUFhJV0hzX2dYei1iTEp6cGEwTFVlZlXSAewBQVVfeXFMUDh0VFhrbi0wVm81dVFyOExnRnAwS1hfWVVsRFNVNTZYMlVnX0xkNXdJaTV0TENOTVJoUkNmeW1qLUpkekpETWhJVUNZWU5TbTkxSVY2S2NJUkJlX0ZMVWQ0LUxoYmN1UW53bWdxNDFjM2YyU3JNdElzckVYZkNqZDE0a0Z4SlJteVNpYlY2Zm5Sc0x1NU1HcDRHTy11Mjgta0tvZGoyY0RuUWZlRmV5ZGVQV1lTdF9UZ3hvX0hWS01oZmFnZU9JdkZqZWlMQ1hpTEczUUlHRE9FaDNCenRtdS12M3djX0lJN3U1c3Y?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 23 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T10:50:19Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "La implementación del nuevo modelo de certificación en el Perú, según la ley 32069 Ley General de Contrataciones Públicas - Observatorio de Contratación Pública",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOWnI3SkdrVGVFTl9GT0E0OEdTd3RNOUZMdm0wMTJfZVluSlFqVDViMFByaER6QVl3TUFZdlpjX2prSjA2SDlFdnQtczRuaHpNVy1wWDIweG1rbUJobWprTXJlcFlablJtZjcyRG1VOFI3QWJPYTc0TWhHQmE1Y0J2OVRUN0pzelVkT2VrdldBT1E2QkZ3bjYtR1JTZUlfMF9HUmZYbWhCWG5LU0F1dldKSw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMisAFBVV95cUxOWnI3SkdrVGVFTl9GT0E0OEdTd3RNOUZMdm0wMTJfZVluSlFqVDViMFByaER6QVl3TUFZdlpjX2prSjA2SDlFdnQtczRuaHpNVy1wWDIweG1rbUJobWprTXJlcFlablJtZjcyRG1VOFI3QWJPYTc0TWhHQmE1Y0J2OVRUN0pzelVkT2VrdldBT1E2QkZ3bjYtR1JTZUlfMF9HUmZYbWhCWG5LU0F1dldKSw?oc=5\" target=\"_blank\">La implementación del nuevo modelo de certificación en el Perú, según la ley 32069 Ley General de Contrataciones Públicas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Observatorio de Contratación Pública</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T07:59:40Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Perú"
  },
  {
    "titulo": "Accede a ofertas de empleo y a un asesoramiento laboral a través de UGT Castilla-La Mancha - UGT Castilla-La Mancha",
    "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxNOFdWa2RNZ1dVaXl4eGk3Szc2ajEteWhyUkQ5OHZuUEZBVThlYlJGam9UYVBXdWItRm9WTUh5aFp0WkRjMWI0YTlxYm5CYVJSRjVZSDd0LU5EWURwLUcyQS1fakZHd05DTFdOSnBkTkdIdUxUUEV0SDc0ajhoNkFPRkdIVUFaY2MxZk1QdExXR09NLTVkVFhVU1BSMnlsUkp3QzA1NXp1Sm53N3JVUDNQQzA0Z3FnRl81NE0wWXdhMWNlTWN2Z3c?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMixgFBVV95cUxNOFdWa2RNZ1dVaXl4eGk3Szc2ajEteWhyUkQ5OHZuUEZBVThlYlJGam9UYVBXdWItRm9WTUh5aFp0WkRjMWI0YTlxYm5CYVJSRjVZSDd0LU5EWURwLUcyQS1fakZHd05DTFdOSnBkTkdIdUxUUEV0SDc0ajhoNkFPRkdIVUFaY2MxZk1QdExXR09NLTVkVFhVU1BSMnlsUkp3QzA1NXp1Sm53N3JVUDNQQzA0Z3FnRl81NE0wWXdhMWNlTWN2Z3c?oc=5\" target=\"_blank\">Accede a ofertas de empleo y a un asesoramiento laboral a través de UGT Castilla-La Mancha</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">UGT Castilla-La Mancha</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T10:53:20Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "UGT Castilla-La Mancha"
  },
  {
    "titulo": "El Centro Dramático Galego contratará a 35 intérpretes para producir ‘Isto tamén é Sargadelos’ y ‘Eurídice’ y reponer ‘A serie clopen’ y ‘Hamlet’ - Xunta de Galicia",
    "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxNRUd6SGx0NWZvVE9ISDBmN0l1Mkhmc3k3ZS1PYzN3QTBFYVJKbVNiNFRhMVZMSXJNQWZELWZtV3plZ2NwaXBnQUgwYjMzMG1rdHJLYmdlUVh2cDNLWlBxVlk1ZkM3RUVFWVJndF80YjdRclZSRmJSRW9Ub25MYU9KN01jQkFRMjhrRHNreC13MGtQOXRUbUo0dDdQa2pTNjFreGpPM3htS3dkZVBDVjk4azZVWWNfVS0wUXFnak9JeHNXVGYtOXBZYlFDVENCc0ZMcjBtM0J4RQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi1wFBVV95cUxNRUd6SGx0NWZvVE9ISDBmN0l1Mkhmc3k3ZS1PYzN3QTBFYVJKbVNiNFRhMVZMSXJNQWZELWZtV3plZ2NwaXBnQUgwYjMzMG1rdHJLYmdlUVh2cDNLWlBxVlk1ZkM3RUVFWVJndF80YjdRclZSRmJSRW9Ub25MYU9KN01jQkFRMjhrRHNreC13MGtQOXRUbUo0dDdQa2pTNjFreGpPM3htS3dkZVBDVjk4azZVWWNfVS0wUXFnak9JeHNXVGYtOXBZYlFDVENCc0ZMcjBtM0J4RQ?oc=5\" target=\"_blank\">El Centro Dramático Galego contratará a 35 intérpretes para producir ‘Isto tamén é Sargadelos’ y ‘Eurídice’ y reponer ‘A serie clopen’ y ‘Hamlet’</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Xunta de Galicia</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T11:39:07Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Centro Dramático Galego",
    "ubicacion": "‘Eurídice’"
  },
  {
    "titulo": "Las ofertas de empleo en EEUU alcanzan su nivel más alto en dos años, pero la contratación sigue siendo difícil - TradingView",
    "url": "https://news.google.com/rss/articles/CBMid0FVX3lxTE5kQUVEVVl4bTVhQm41V0hnREtxZ1dSdnlsRDNIa1o1QkhvVkZUWGlyb21lSGlDcTBBeVF6cTh3Wk1aSm5lWFY2TmxGUEVNcDlXYS11NGFLSUJUbGZ4N0h6ZjlpWmQxR2kyaXNLemFSeGFaYnJ0clJ3?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMid0FVX3lxTE5kQUVEVVl4bTVhQm41V0hnREtxZ1dSdnlsRDNIa1o1QkhvVkZUWGlyb21lSGlDcTBBeVF6cTh3Wk1aSm5lWFY2TmxGUEVNcDlXYS11NGFLSUJUbGZ4N0h6ZjlpWmQxR2kyaXNLemFSeGFaYnJ0clJ3?oc=5\" target=\"_blank\">Las ofertas de empleo en EEUU alcanzan su nivel más alto en dos años, pero la contratación sigue siendo difícil</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">TradingView</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T18:16:53Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "TradingView",
    "ubicacion": "EEUU"
  },
  {
    "titulo": "Málaga contratará un estudio para analizar un nuevo acceso rodado soterrado al puerto - EL MERCANTIL",
    "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxPakd5RnFaQ3dKd1h5VGdUMkZKUm0yN1lhWHVOaHRqVUhrd2FXcnNYYjB0aGlFWlJkazc1Rjlfem5oMy1lemxyQWg5SDZ5bGlSeVdwaXZfMGZQU2VHY3BsZHdsNVZIRGMzU1Rpa3JVaHNINlNIRlRsWkd1Wk9xeU5qWVFKTURDOThKY3pBZ0YxS1EybDRSWVlCTlNHNnlOdVdzaDI1TXdjTnQtZkhjcTB6djRYYVVYSkVIaXlDOFhn?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMivgFBVV95cUxPakd5RnFaQ3dKd1h5VGdUMkZKUm0yN1lhWHVOaHRqVUhrd2FXcnNYYjB0aGlFWlJkazc1Rjlfem5oMy1lemxyQWg5SDZ5bGlSeVdwaXZfMGZQU2VHY3BsZHdsNVZIRGMzU1Rpa3JVaHNINlNIRlRsWkd1Wk9xeU5qWVFKTURDOThKY3pBZ0YxS1EybDRSWVlCTlNHNnlOdVdzaDI1TXdjTnQtZkhjcTB6djRYYVVYSkVIaXlDOFhn?oc=5\" target=\"_blank\">Málaga contratará un estudio para analizar un nuevo acceso rodado soterrado al puerto</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL MERCANTIL</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-24T16:04:03Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Málaga"
  },
  {
    "titulo": "El nuevo Plan de Empleo Especial de Mérida permitirá 178 contrataciones - Cadena SER",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxQdjBNU1p0cnBDRzg3bVZjM1E0aERHSExWRzBtaTg4LUgycGtKMlJlU2htNXNNN2ZKTnVtWFdvMC1vOERiRmtoTEVIOEFSVDcta09kMXYzaHZxVGd5bGFKXzg2djNhUDVXX3hPSUlQOUJnVW5zalVWVm5SLXVWU2pwVDVmVU5OXzVqRzJYNFJidkREaWZNQ0VHdlVqWEtYVUt0djZ1bU8ySTYyNXNIOEtaTmNxdkR6QVljbzZQdkZzSFU2R2FJVjJn0gHbAUFVX3lxTFBwOFdPZ0lyOHFTdEFsQ3poUDc2UWhkV1VTVnhjN2FmTUFmZ2xlOW1DVlVSMlBHZnFaaDBPZ0FWZms2UnVvbXdWT0xfOTQteHFON2RlbERPdGw0SWdaejVncEdFSXlkY1BHRTdrMzlKdVhYVWo5ajBEQ0ZQMDZzdlRxSUN3RkFFRlFPLWRaUFQyeE1YWWRTOFJPczRmbVRmcDItOE04amtuSld5aFJndWk4WjJWQnd4VlFmYlZyeU9xVk5GaFNOc2lWYUhXSFQyOTZWNVpYb2xOZkZyOA?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMixwFBVV95cUxQdjBNU1p0cnBDRzg3bVZjM1E0aERHSExWRzBtaTg4LUgycGtKMlJlU2htNXNNN2ZKTnVtWFdvMC1vOERiRmtoTEVIOEFSVDcta09kMXYzaHZxVGd5bGFKXzg2djNhUDVXX3hPSUlQOUJnVW5zalVWVm5SLXVWU2pwVDVmVU5OXzVqRzJYNFJidkREaWZNQ0VHdlVqWEtYVUt0djZ1bU8ySTYyNXNIOEtaTmNxdkR6QVljbzZQdkZzSFU2R2FJVjJn0gHbAUFVX3lxTFBwOFdPZ0lyOHFTdEFsQ3poUDc2UWhkV1VTVnhjN2FmTUFmZ2xlOW1DVlVSMlBHZnFaaDBPZ0FWZms2UnVvbXdWT0xfOTQteHFON2RlbERPdGw0SWdaejVncEdFSXlkY1BHRTdrMzlKdVhYVWo5ajBEQ0ZQMDZzdlRxSUN3RkFFRlFPLWRaUFQyeE1YWWRTOFJPczRmbVRmcDItOE04amtuSld5aFJndWk4WjJWQnd4VlFmYlZyeU9xVk5GaFNOc2lWYUhXSFQyOTZWNVpYb2xOZkZyOA?oc=5\" target=\"_blank\">El nuevo Plan de Empleo Especial de Mérida permitirá 178 contrataciones</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Cadena SER</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-24T13:19:58Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Cadena SER",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Este viernes nuevas ofertas de empleo - Radio Guijuelo",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPWVk5N2YzU3dKb3F1UHNkTWU1Yk4yNEVBWllJamFtMmgyMnM1Wk9zWnUtMFo3QTZMX2JxZWdNeWFuZXpZelIzc3NxYW81YzF2S3M1STM4QW5oYlRLX3J3cWZXNUZtMXU2OXlpTjRwY0tDcmZlcUpBdl9aZUgxdkNmOA?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMigAFBVV95cUxPWVk5N2YzU3dKb3F1UHNkTWU1Yk4yNEVBWllJamFtMmgyMnM1Wk9zWnUtMFo3QTZMX2JxZWdNeWFuZXpZelIzc3NxYW81YzF2S3M1STM4QW5oYlRLX3J3cWZXNUZtMXU2OXlpTjRwY0tDcmZlcUpBdl9aZUgxdkNmOA?oc=5\" target=\"_blank\">Este viernes nuevas ofertas de empleo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Radio Guijuelo</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T10:49:45Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo de Madrid Trabaja 27.06.2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxPRDl1Q0h1RmxsWHhCcXFpV0RLazB0amF4Mk9PYnB1UW4tX2NPaDhOQlFFclRwMFNKUTdWdVV1UGhhZ0t0czJGV0l4S09CcjF6M1JzQWl6R0FQd0NTMDdOU1hTdk9WMl8wLXhFNzRXZk5wS2xmTmlpczZha0pjeFNoNDNUUEZIem1qM1dHdWVEQWktUlJha1VjbFQyYURPdFZBZnZ4aXhsdG40dnFjeS1YMVJNX2xtRmRLNWgzZHM0eVcyUGFlNjZBaNIBzgFBVV95cUxPV3NIMUQ2dm96dXJDMV9yczBxSEtvbG1qMWJ1WHFuNHBXOERyc3pBeS01ZXVyaFgyWkpXUzhsZkRrRk5nelBja2oxdFEwUjgwMFE4MkgybEVLWEdrTVlLQktUcnpyekdQbGhtdUpyS2JLZm40Rlh3TC1oUFYzb0c5S1NwWU5aUTVJazA1S0UySTVsTkZvcUczU1NHdWxtakhJQW5pX3dkX2dIcTlDUV91SEk4UmlYV0RqVGt6N2hmSnJPNExoZGYtMWxreUE3QQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiyAFBVV95cUxPRDl1Q0h1RmxsWHhCcXFpV0RLazB0amF4Mk9PYnB1UW4tX2NPaDhOQlFFclRwMFNKUTdWdVV1UGhhZ0t0czJGV0l4S09CcjF6M1JzQWl6R0FQd0NTMDdOU1hTdk9WMl8wLXhFNzRXZk5wS2xmTmlpczZha0pjeFNoNDNUUEZIem1qM1dHdWVEQWktUlJha1VjbFQyYURPdFZBZnZ4aXhsdG40dnFjeS1YMVJNX2xtRmRLNWgzZHM0eVcyUGFlNjZBaNIBzgFBVV95cUxPV3NIMUQ2dm96dXJDMV9yczBxSEtvbG1qMWJ1WHFuNHBXOERyc3pBeS01ZXVyaFgyWkpXUzhsZkRrRk5nelBja2oxdFEwUjgwMFE4MkgybEVLWEdrTVlLQktUcnpyekdQbGhtdUpyS2JLZm40Rlh3TC1oUFYzb0c5S1NwWU5aUTVJazA1S0UySTVsTkZvcUczU1NHdWxtakhJQW5pX3dkX2dIcTlDUV91SEk4UmlYV0RqVGt6N2hmSnJPNExoZGYtMWxreUE3QQ?oc=5\" target=\"_blank\">Ofertas de empleo de Madrid Trabaja 27.06.2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-27T07:15:00Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 30 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxOM21vdEtBVnZtY3Y2U0FtczhYdXh0NXl2QXMxSDE1dXJ1X3dyR1NTZGlYTE9lV2cyNFlMc3BYWHMtTnptN2ZaS0hHYWphcjlfLUttT3lqTlZQUENkSm9RdmZQYWQ5MUdCUUlQU1dlNHFvQ0dqOE5vcXktajlpU3JXTl9HaV81R0VINEtpYXVvdm5TODFKWHp4TFVheXpJRC1vMlFGWDZ1RnJFcml6Y0RfVjNxQ2ZXektkRl9QRXFpUzRtTnVQQWtvWDRJU0JuMTA2dk9rZldrb091X3hHZUt4TElxZHNQTE3SAewBQVVfeXFMTnNoLVFCbEJOSHVFSDlCblFSNm9GVjJFU3ZrY3NXZmtaanpsMHhRVHNWYnhIdUpESnk0TVNrLXduZDhlS2wzQmd2bS1OY3dlODJxanc2a1hoS0dNRmQ4UHZYaElza2hwYVJNUW9xaW1XdWRMOF9XNk5IZnp5TVpyVlljc1dhWDlfQ2xDdDhiMDlwakF0YmRhSDFMb192MURvdEVBMHRVOWhYOFVuVXhmWkpLTDBSSDJRZ3VnWk5kVDNqc2x5YmNKaEZNcUtxRWs0VjlES1VEU1RzQUZNOXc0LVh4VmVONGE2YzNUYS0?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxOM21vdEtBVnZtY3Y2U0FtczhYdXh0NXl2QXMxSDE1dXJ1X3dyR1NTZGlYTE9lV2cyNFlMc3BYWHMtTnptN2ZaS0hHYWphcjlfLUttT3lqTlZQUENkSm9RdmZQYWQ5MUdCUUlQU1dlNHFvQ0dqOE5vcXktajlpU3JXTl9HaV81R0VINEtpYXVvdm5TODFKWHp4TFVheXpJRC1vMlFGWDZ1RnJFcml6Y0RfVjNxQ2ZXektkRl9QRXFpUzRtTnVQQWtvWDRJU0JuMTA2dk9rZldrb091X3hHZUt4TElxZHNQTE3SAewBQVVfeXFMTnNoLVFCbEJOSHVFSDlCblFSNm9GVjJFU3ZrY3NXZmtaanpsMHhRVHNWYnhIdUpESnk0TVNrLXduZDhlS2wzQmd2bS1OY3dlODJxanc2a1hoS0dNRmQ4UHZYaElza2hwYVJNUW9xaW1XdWRMOF9XNk5IZnp5TVpyVlljc1dhWDlfQ2xDdDhiMDlwakF0YmRhSDFMb192MURvdEVBMHRVOWhYOFVuVXhmWkpLTDBSSDJRZ3VnWk5kVDNqc2x5YmNKaEZNcUtxRWs0VjlES1VEU1RzQUZNOXc0LVh4VmVONGE2YzNUYS0?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 30 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T11:30:43Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 25 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPaldoV2lpZFFFQ0pZaS1yaTBsYU5XQjR5TWRmUjJoblNaRFFjZ2xOLWVHV3NmTzBhRl9hbTJRd3FFSVZrN0ptM0t5TTRvblhlS0ptODJwdENuUGVhamItVmpVeXRieEZ5d21ta19vN1ZYWk42bnpXMlF0VGZPdmhTVVQ2X0Z4R0J2UTd4Qm9ic2FMN3VYbnVkallvRVVicHJIWGJXZkFLX1RVbWN5VzNyUG5xa3RIektMQ3lIZFNVc3hCRTJFLUNpd2NGSkpCOFI4TVBDV0xzMFpRMXc5YUZiYlU5czlzT1HSAewBQVVfeXFMUDhVQnRCYmMxNGNFaFZyS09PZXluVTg2T0RUTXBQNFphd2lmcmRsaEtETl9icWdSMWJBLU9Ib0V3a1JhUXNaRmtRWG1vcURleEYyVURLZi1GZ0JRbG0xVVMxMkRWMEl6VjRLSWZXRFBYVHBOZ2VLZDd3QVA1WXh0YnZvd3hPZFFRRzN2UFJsVUZLNTkxenFHOFRDMV82XzRpbEJhZmQtSlN3SnkzRUFuNE1LRlZIZjRLRVdXTGhIMzlFMl9YVmdvdGtBUGtVaDc4aDY3ZnAwZjFzaG1iZ2VKRUJUemNDSWZGd0ZQSjU?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPaldoV2lpZFFFQ0pZaS1yaTBsYU5XQjR5TWRmUjJoblNaRFFjZ2xOLWVHV3NmTzBhRl9hbTJRd3FFSVZrN0ptM0t5TTRvblhlS0ptODJwdENuUGVhamItVmpVeXRieEZ5d21ta19vN1ZYWk42bnpXMlF0VGZPdmhTVVQ2X0Z4R0J2UTd4Qm9ic2FMN3VYbnVkallvRVVicHJIWGJXZkFLX1RVbWN5VzNyUG5xa3RIektMQ3lIZFNVc3hCRTJFLUNpd2NGSkpCOFI4TVBDV0xzMFpRMXc5YUZiYlU5czlzT1HSAewBQVVfeXFMUDhVQnRCYmMxNGNFaFZyS09PZXluVTg2T0RUTXBQNFphd2lmcmRsaEtETl9icWdSMWJBLU9Ib0V3a1JhUXNaRmtRWG1vcURleEYyVURLZi1GZ0JRbG0xVVMxMkRWMEl6VjRLSWZXRFBYVHBOZ2VLZDd3QVA1WXh0YnZvd3hPZFFRRzN2UFJsVUZLNTkxenFHOFRDMV82XzRpbEJhZmQtSlN3SnkzRUFuNE1LRlZIZjRLRVdXTGhIMzlFMl9YVmdvdGtBUGtVaDc4aDY3ZnAwZjFzaG1iZ2VKRUJUemNDSWZGd0ZQSjU?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 25 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T11:32:26Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 29 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPOHR5RHhFbmNoeHpkZ2JOOGF5V1ZNa0dwTFlmTnltaGlldU5oRzkzM1dEaFowclNxM2lzT04yV1Y3S3RSdlMydXpoaE13UGhkZ1dxallwcWxuVnBHRnBSOW5IUUFKNk9zUFc5T1JhSXQ5TTdUYWJ2YTAzZEZvbW1pdmpqbTBvZmJCX1lxUzlRQlZpRFhYZk1yMmhNaGc0YUtmQ011ejhIZl8xSW1GWlEyZWtib09aNFNpT0FseU9ETHhVUjNwZERHcjI1QTFabmlTRGRHbXM3MFpTQUJvbWdlVWlfZDFiXzTSAewBQVVfeXFMTUQzSEQxRjRTYjYwMF9mSUp2S1NHcS1sX0RYaXVZQ0txbXBlYkE5bDN4b1VvQlZ0aEFaQ0dpSFpCSVdzaDJwV2MyUkNpbkZvU21XTVhIdVZCc2xldE9nZ3ZIOGE3ZWlLellPYmxxLXdPMTBPLUNvYzYxUUMxV1pqSHBFcXE5OVZWYmtYY251QUJCWlY4Sm9rQ3NfeW5tWXRVdkx6YV9xX1N4Qi1SZkhuellnV281WnJlMWJTcWRwNUJzbVhYRFpDS25zMmFZMTBVc0F3Mjd6TGk2SlNRaFBRak0zbWRzQTQzLW90Z3A?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPOHR5RHhFbmNoeHpkZ2JOOGF5V1ZNa0dwTFlmTnltaGlldU5oRzkzM1dEaFowclNxM2lzT04yV1Y3S3RSdlMydXpoaE13UGhkZ1dxallwcWxuVnBHRnBSOW5IUUFKNk9zUFc5T1JhSXQ5TTdUYWJ2YTAzZEZvbW1pdmpqbTBvZmJCX1lxUzlRQlZpRFhYZk1yMmhNaGc0YUtmQ011ejhIZl8xSW1GWlEyZWtib09aNFNpT0FseU9ETHhVUjNwZERHcjI1QTFabmlTRGRHbXM3MFpTQUJvbWdlVWlfZDFiXzTSAewBQVVfeXFMTUQzSEQxRjRTYjYwMF9mSUp2S1NHcS1sX0RYaXVZQ0txbXBlYkE5bDN4b1VvQlZ0aEFaQ0dpSFpCSVdzaDJwV2MyUkNpbkZvU21XTVhIdVZCc2xldE9nZ3ZIOGE3ZWlLellPYmxxLXdPMTBPLUNvYzYxUUMxV1pqSHBFcXE5OVZWYmtYY251QUJCWlY4Sm9rQ3NfeW5tWXRVdkx6YV9xX1N4Qi1SZkhuellnV281WnJlMWJTcWRwNUJzbVhYRFpDS25zMmFZMTBVc0F3Mjd6TGk2SlNRaFBRak0zbWRzQTQzLW90Z3A?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 29 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T12:37:14Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 26 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxQTHpid1M5S3R6bFJreWhLek40NlBZM0VlSVFlUzd5NnFhTnp6VmU1ejZPakNWdUlrV2FjQk9Qbkh1Vk5vZFFkRHEtRFQtcDZUcXVoLTJJbk1sbzRsb3FEVklOdkctWTV1NGJPMzBTTFpWQ3BQRUJvZlhNbkhZZ2IzUF84eTBpSi1yM1BoTGFJSjZMd1h0eFNwV09TSUQ3US1HSk84bmwyVWNrRHhQdkxkMjdlVXAzVjJUTzY5Z1F0bE42RElZa3pxSmEtRVZIQ1k0LW9sTnpfSGpCQ2hzZFROX3BmYTVNYmfSAewBQVVfeXFMTkxTTl9CZ3FCY0JvY1U4WmdkQ010SFh1WTA1cXhkWGxwdndTUmhFSDBWVkMtNlp2c04tYmJrN2duYmlxRWp5cGhSTGdCb0RmRlNNaXhRd3cxUFpHUGp4d3NBQnhMUnpybFBaNUxwWHRHcmlnUzdVMlFYb0VjSlY0VUxsb2lFSDN1TXRYeklnVEhyTWNQdHdnZlkwbWpLd3I5cElnUVdhb3pNM1BMQ2tJU09rNzgtX2EzcklQd0FXcWR0bDQ3Yml6aENvLWtiWmVfTjFRZWZ4eW04eU94NVNyc2lhcVlFMldiMGd3UmI?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxQTHpid1M5S3R6bFJreWhLek40NlBZM0VlSVFlUzd5NnFhTnp6VmU1ejZPakNWdUlrV2FjQk9Qbkh1Vk5vZFFkRHEtRFQtcDZUcXVoLTJJbk1sbzRsb3FEVklOdkctWTV1NGJPMzBTTFpWQ3BQRUJvZlhNbkhZZ2IzUF84eTBpSi1yM1BoTGFJSjZMd1h0eFNwV09TSUQ3US1HSk84bmwyVWNrRHhQdkxkMjdlVXAzVjJUTzY5Z1F0bE42RElZa3pxSmEtRVZIQ1k0LW9sTnpfSGpCQ2hzZFROX3BmYTVNYmfSAewBQVVfeXFMTkxTTl9CZ3FCY0JvY1U4WmdkQ010SFh1WTA1cXhkWGxwdndTUmhFSDBWVkMtNlp2c04tYmJrN2duYmlxRWp5cGhSTGdCb0RmRlNNaXhRd3cxUFpHUGp4d3NBQnhMUnpybFBaNUxwWHRHcmlnUzdVMlFYb0VjSlY0VUxsb2lFSDN1TXRYeklnVEhyTWNQdHdnZlkwbWpLd3I5cElnUVdhb3pNM1BMQ2tJU09rNzgtX2EzcklQd0FXcWR0bDQ3Yml6aENvLWtiWmVfTjFRZWZ4eW04eU94NVNyc2lhcVlFMldiMGd3UmI?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 26 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T10:24:32Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 24 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxNRmd0SHhzNDhMMkhqNk9RYzlzendsNWtfd2U3ZHRfZC1fS20zMjAxZEVta3N4UWdpYjhQcDhhMnVHRlFUOTNhOUROaDQxMzliVXBnTE9ULXRLUzRMRjF1RkFtTk5BX3pSdUNUd3F4YWlxYUwyTm9TZVBfUWdZYmxsTFIxdUVsYVIxWnpKZVA2QVZHaXFidTVxOUpuX2lrMFROZENKelNRMlgtX1dzem5ycE9HblFySnU4cFEyWFN5MTFjWHg2TG9SNFNZUXJGOHVZekJyT2hwa2ozTFA2ZzhTR0lhUUZKZkXSAewBQVVfeXFMT29HeVhVX2dsSVN5cHFzZmVUb1VEVHpCc2MwNGFGNnRTbGlNS3ZxWjU4RkNIVnJEaXR4am1ub1U0eF9uSU9tUnpxZHM4aG1JaHU3RmZDUG12MFVpQ2E4c2loOHlyZTU1bHJCRlBkQ01rVlhGZTdvUzZxWHRud0FMTVN2Um1tcFhNVWJiT1Fablhmd2xwWkFtWFJvcjVqa0dyR21sdEp2NmphZDg0NHVoWWRsblNYem9ROVJIbm8tTDNqNWdmZFpYdlltaVN6eXc2bm5CaERkSWgwdlJsODg2WkJPRGVNSG1la0tyX1Y?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxNRmd0SHhzNDhMMkhqNk9RYzlzendsNWtfd2U3ZHRfZC1fS20zMjAxZEVta3N4UWdpYjhQcDhhMnVHRlFUOTNhOUROaDQxMzliVXBnTE9ULXRLUzRMRjF1RkFtTk5BX3pSdUNUd3F4YWlxYUwyTm9TZVBfUWdZYmxsTFIxdUVsYVIxWnpKZVA2QVZHaXFidTVxOUpuX2lrMFROZENKelNRMlgtX1dzem5ycE9HblFySnU4cFEyWFN5MTFjWHg2TG9SNFNZUXJGOHVZekJyT2hwa2ozTFA2ZzhTR0lhUUZKZkXSAewBQVVfeXFMT29HeVhVX2dsSVN5cHFzZmVUb1VEVHpCc2MwNGFGNnRTbGlNS3ZxWjU4RkNIVnJEaXR4am1ub1U0eF9uSU9tUnpxZHM4aG1JaHU3RmZDUG12MFVpQ2E4c2loOHlyZTU1bHJCRlBkQ01rVlhGZTdvUzZxWHRud0FMTVN2Um1tcFhNVWJiT1Fablhmd2xwWkFtWFJvcjVqa0dyR21sdEp2NmphZDg0NHVoWWRsblNYem9ROVJIbm8tTDNqNWdmZFpYdlltaVN6eXc2bm5CaERkSWgwdlJsODg2WkJPRGVNSG1la0tyX1Y?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 24 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-24T10:18:47Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Video de apertura de plicas - Ayuntamiento de Madrid",
    "url": "https://news.google.com/rss/articles/CBMi6gJBVV95cUxPdXhkT1FIbUNOUnZXTGowM3FRNWxVR2tHZUNKaWVlaFBaR0o5bnRhcTlGSlJycUNZdTh6QnpxWmNXdTJkRUZvenN2X3RWMEwwR1ppNWtZUHI0ZlJrU2JIU2NRY0xKdEgyMXQwbWFUcHBkaTJyVmI4ajJ6NVdQOUx3R3JkM25zZXRGems4YUxzbUx5WUEtaW9CMnYxS3RadnptemQwQjdoNzc1bUlSUlZJUWNid2VGeXRsYnZMOThnZmtjRFM3WVRoZjlwT1hxNmNwQlpkQXZrRHRpaExrZllDaXRjcnVENjRBekxrRkJ4Sy1rX2UzN3B3bHNYYk84eUNsbjJtYTlySnhOc2NNR0tHQnljWmdxbHZwVU5hbEpUMGc3Q1pmZGlHclh4T0ZDME5xa3M2emxjV0E5Zm1Gc3hubFAyUDZvM0NXVGppUWVRTzZZMUlwMEdOZHZBTEd0eTF0aW5zZ2NlUHFVZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6gJBVV95cUxPdXhkT1FIbUNOUnZXTGowM3FRNWxVR2tHZUNKaWVlaFBaR0o5bnRhcTlGSlJycUNZdTh6QnpxWmNXdTJkRUZvenN2X3RWMEwwR1ppNWtZUHI0ZlJrU2JIU2NRY0xKdEgyMXQwbWFUcHBkaTJyVmI4ajJ6NVdQOUx3R3JkM25zZXRGems4YUxzbUx5WUEtaW9CMnYxS3RadnptemQwQjdoNzc1bUlSUlZJUWNid2VGeXRsYnZMOThnZmtjRFM3WVRoZjlwT1hxNmNwQlpkQXZrRHRpaExrZllDaXRjcnVENjRBekxrRkJ4Sy1rX2UzN3B3bHNYYk84eUNsbjJtYTlySnhOc2NNR0tHQnljWmdxbHZwVU5hbEpUMGc3Q1pmZGlHclh4T0ZDME5xa3M2emxjV0E5Zm1Gc3hubFAyUDZvM0NXVGppUWVRTzZZMUlwMEdOZHZBTEd0eTF0aW5zZ2NlUHFVZw?oc=5\" target=\"_blank\">Video de apertura de plicas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Ayuntamiento de Madrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-21T16:07:43Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento de Madrid"
  },
  {
    "titulo": "Osalan inaugura su Curso de Verano sobre trabajo digno y prevención de riesgos laborales - Euskadi.eus",
    "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxQYWw1MV9wWVh3MF9XbkN3NUtqM1I4bkpSRWFveEZVVzhqN25ONURTVGwwdjNKVi02a2ZIczhVYVpNbWhfUFRKNGZYVjgxUlRaUFM2VkVlTzF2M0swU1A0VWxDaWNZWEtvbjVodHZFYWcwQTBYWWNSQTdTbVpFZ3F3Z2R0VmhINGRPbkhRd25aMFFHWkNPZnNkU0hveVBwYWZCNGlVeXhaVlZQT0xuTE90Xy1mYmFCV0d2MWpKNDFZMTdDaGtMWkVuTC1ERQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxQYWw1MV9wWVh3MF9XbkN3NUtqM1I4bkpSRWFveEZVVzhqN25ONURTVGwwdjNKVi02a2ZIczhVYVpNbWhfUFRKNGZYVjgxUlRaUFM2VkVlTzF2M0swU1A0VWxDaWNZWEtvbjVodHZFYWcwQTBYWWNSQTdTbVpFZ3F3Z2R0VmhINGRPbkhRd25aMFFHWkNPZnNkU0hveVBwYWZCNGlVeXhaVlZQT0xuTE90Xy1mYmFCV0d2MWpKNDFZMTdDaGtMWkVuTC1ERQ?oc=5\" target=\"_blank\">Osalan inaugura su Curso de Verano sobre trabajo digno y prevención de riesgos laborales</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Euskadi.eus</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T07:00:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Osalan"
  },
  {
    "titulo": "BOLSA INGESA | CEUTA/MELILLA | Cronograma orientativo de apertura de bolsa de empleo temporal en la categoría de Celador/a. - Sindicato Cean",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxQcnV2Z3pvSXp4cnpmczhfTThzQnQ3SlRRdU5PWlo1V2czSTlQRDRFUzlGYUNtU2F4V3hqbkZjYk5oVlRDbS1yTW1SUExSU2NDOHBMOTVYU3k3bXNzWmNSSXBiUlg4bml5cmNQajYxaThUUmJleWRrQTFTTXFPbjZMSmZGNFd3Z3Rpcm9GSVVYUU9scV9jVWJ4WDNXTDM5OXJBQ081cXpFdWRQVXdUbWYwQ0NsRURrMzc1d29EazNjYklBNGswQVJ6cFRVYXVFdFNyVnFjWnlJcVNOS0E4SmJCQnNrRUJCb05ETnk4?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6wFBVV95cUxQcnV2Z3pvSXp4cnpmczhfTThzQnQ3SlRRdU5PWlo1V2czSTlQRDRFUzlGYUNtU2F4V3hqbkZjYk5oVlRDbS1yTW1SUExSU2NDOHBMOTVYU3k3bXNzWmNSSXBiUlg4bml5cmNQajYxaThUUmJleWRrQTFTTXFPbjZMSmZGNFd3Z3Rpcm9GSVVYUU9scV9jVWJ4WDNXTDM5OXJBQ081cXpFdWRQVXdUbWYwQ0NsRURrMzc1d29EazNjYklBNGswQVJ6cFRVYXVFdFNyVnFjWnlJcVNOS0E4SmJCQnNrRUJCb05ETnk4?oc=5\" target=\"_blank\">BOLSA INGESA | CEUTA/MELILLA | Cronograma orientativo de apertura de bolsa de empleo temporal en la categoría de Celador/a.</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Sindicato Cean</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T12:45:45Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "BOLSA INGESA",
    "ubicacion": "categoría de Celador"
  },
  {
    "titulo": "ACEESCA inaugura en O Porriño su escuela profesional de empleo inclusivo - La Voz de Galicia",
    "url": "https://news.google.com/rss/articles/CBMi6AFBVV95cUxPdS1xcXExUzc2TllVeFFLRFRTX0NMODdNQ01lUFZPdjBVOG9QaEFkTEs0OGI1YzFHM3BsVjFOMmxUYW5kUTQ4VGxJMzI2QkVvdlFQSWpvbDROdExEakdyaWJPdjh0dDFPTXFvbWFWd2xrcjdabDJWNWFTX1JCWHRjVXdHaTI5ZVE2aG9JdjMyRTVzc25PWjhxZ2p1U0pXMWJLVzcxbWlGWi00NmNOaS1KcTBGb1ZVMVR6RVVNaFFEcC1mVkJEVS1ONmFjRndDSWhnblZuSEE5cWlTVE1EMm5jWUYxaTg4MUc20gGEAkFVX3lxTE13WV9pQ2dyT0xTSEw3QzdVM2RJOGxhSmhNMURmRFpUSDVveWk1Vk9fV0lRVVZoX09nQThwOVhHVjVFbjVmS2NvalVxUjRKSHRRNnBMOFJjMkZGQV9YcUo2Y1NUMlRpckVRcGtXZ3FpWWlXa180aHBZcnViUHV2YUJINUphbXN2MUZaSFVtTTRWTGlnbHFCLTgyMGd5M0dtWmRVYTdXbUk3YWdnX0JXTFpGY2pDSWU5d0dhcy0tc0swcnYwdnBJLWRENml1WkI5ZGFNRFJvZXdDRjllRWxSYWZ5ZWwtYzdaVjlzX3FjR09QNWRYUFcyaUZXTmlTWndrMDkxVDlr?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6AFBVV95cUxPdS1xcXExUzc2TllVeFFLRFRTX0NMODdNQ01lUFZPdjBVOG9QaEFkTEs0OGI1YzFHM3BsVjFOMmxUYW5kUTQ4VGxJMzI2QkVvdlFQSWpvbDROdExEakdyaWJPdjh0dDFPTXFvbWFWd2xrcjdabDJWNWFTX1JCWHRjVXdHaTI5ZVE2aG9JdjMyRTVzc25PWjhxZ2p1U0pXMWJLVzcxbWlGWi00NmNOaS1KcTBGb1ZVMVR6RVVNaFFEcC1mVkJEVS1ONmFjRndDSWhnblZuSEE5cWlTVE1EMm5jWUYxaTg4MUc20gGEAkFVX3lxTE13WV9pQ2dyT0xTSEw3QzdVM2RJOGxhSmhNMURmRFpUSDVveWk1Vk9fV0lRVVZoX09nQThwOVhHVjVFbjVmS2NvalVxUjRKSHRRNnBMOFJjMkZGQV9YcUo2Y1NUMlRpckVRcGtXZ3FpWWlXa180aHBZcnViUHV2YUJINUphbXN2MUZaSFVtTTRWTGlnbHFCLTgyMGd5M0dtWmRVYTdXbUk3YWdnX0JXTFpGY2pDSWU5d0dhcy0tc0swcnYwdnBJLWRENml1WkI5ZGFNRFJvZXdDRjllRWxSYWZ5ZWwtYzdaVjlzX3FjR09QNWRYUFcyaUZXTmlTWndrMDkxVDlr?oc=5\" target=\"_blank\">ACEESCA inaugura en O Porriño su escuela profesional de empleo inclusivo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Voz de Galicia</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-18T07:00:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Voz de Galicia",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La nueva fábrica de Leapmotor en Mallén (Zaragoza) producirá unas 60.000 baterías al año y dará empleo a 90 personas - Europa Press",
    "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxPalRfTVJsQXUzZFE3U1prdUR0am1xaUs4RWlzeDBfYi1WWGVfMHV6WGNBRXV5VmotN2d4M2RuZzFoZm8wZU12V3pGaW5xVlpvQmtiMUZpd3BmT2RzeFgxQWZoNUJ2bEg3MThCaVdOLUVXMktSRUV2TXVhZUd3X0dGTnlybzgtWnZ0NzBCUlJEVGVEV1ZsYUcyNU13RTlLNDl0bzZQaVFMazNzUWtFRDVzYWNIWm1mX2dDV2swekk5cVgxWnpzaEZmV2wwelZobm8xekFyRTJSLTlHZU41TzRzaEtBelBnMl9nXy1DUkt5VkF3VGRKUEhuUmFn?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi-gFBVV95cUxPalRfTVJsQXUzZFE3U1prdUR0am1xaUs4RWlzeDBfYi1WWGVfMHV6WGNBRXV5VmotN2d4M2RuZzFoZm8wZU12V3pGaW5xVlpvQmtiMUZpd3BmT2RzeFgxQWZoNUJ2bEg3MThCaVdOLUVXMktSRUV2TXVhZUd3X0dGTnlybzgtWnZ0NzBCUlJEVGVEV1ZsYUcyNU13RTlLNDl0bzZQaVFMazNzUWtFRDVzYWNIWm1mX2dDV2swekk5cVgxWnpzaEZmV2wwelZobm8xekFyRTJSLTlHZU41TzRzaEtBelBnMl9nXy1DUkt5VkF3VGRKUEhuUmFn?oc=5\" target=\"_blank\">La nueva fábrica de Leapmotor en Mallén (Zaragoza) producirá unas 60.000 baterías al año y dará empleo a 90 personas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Europa Press</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T12:02:40Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Mallén"
  },
  {
    "titulo": "Lidl impulsa su presencia en Gipuzkoa con la convocatoria de 13 vacantes de liderazgo y gestión para sus tiendas - Lidl Empresa",
    "url": "https://news.google.com/rss/articles/CBMiggJBVV95cUxPYzBUVi1DeU1VODl3U2ZHdHp6Rm81WHRfaVlxR3Vpb0lhMXhxTnpUNk5wc1d1cElWNEZGOHJXeW5IV1RaaWx5OEI1bW1GWTdZSFVFYzlyUW5tQmtLX3JVSHpjODdMSFhrbEZEZ082UU9fSHNXc0lyVXpiRFRLeUtBN2dmWEY4aUdzV0JfZUhkVW44SlZSVGhpX3I0Uzhfc1FyZlBlT0huSW5pSzd0TnltR3FEcG5Db2o0Vy1KM05uYXl1cXdYU2dPbl8xQ0t3RjRjaDBPUlYyc1h4c1lHNmw1NTR3TFpCSE5kcUxSM3AyRDdrdFZvcXJRZU9rUnFBWmJHeWc?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiggJBVV95cUxPYzBUVi1DeU1VODl3U2ZHdHp6Rm81WHRfaVlxR3Vpb0lhMXhxTnpUNk5wc1d1cElWNEZGOHJXeW5IV1RaaWx5OEI1bW1GWTdZSFVFYzlyUW5tQmtLX3JVSHpjODdMSFhrbEZEZ082UU9fSHNXc0lyVXpiRFRLeUtBN2dmWEY4aUdzV0JfZUhkVW44SlZSVGhpX3I0Uzhfc1FyZlBlT0huSW5pSzd0TnltR3FEcG5Db2o0Vy1KM05uYXl1cXdYU2dPbl8xQ0t3RjRjaDBPUlYyc1h4c1lHNmw1NTR3TFpCSE5kcUxSM3AyRDdrdFZvcXJRZU9rUnFBWmJHeWc?oc=5\" target=\"_blank\">Lidl impulsa su presencia en Gipuzkoa con la convocatoria de 13 vacantes de liderazgo y gestión para sus tiendas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Lidl Empresa</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-18T22:57:54Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Gipuzkoa"
  },
  {
    "titulo": "Consum abre una nueva tienda en Almería y avanza en su plan de dieciocho aperturas en 2026 - El Conciso",
    "url": "https://news.google.com/rss/articles/CBMiigFBVV95cUxQdlh5Z1o2eWhVc0VhYUZreEJPb2NoUUtrMHQyM29oeTNyX252WHA2T29Nd0VQY1ZxQzVIS2psTmtsQnZNSFliOFNtdlF1bHQzNXd3OFp2dmZuRTlZZDI3dTFHUWdueHVqM3lKaEt0NkJzS2xfR0x4ODdoWTVvMzFlWTlKa3NHTUEzM3fSAY8BQVVfeXFMUFFRcTJ4clNrOS13LWw1aTJGNVJRMFpGd3g1SG00d2xLOVRWREpnRDJYOGtnbWo2c1JvSXl6S18zcjk2MEJYVmpEejUwemE3N2JZS0Fnc2xGT2J6TFVSMERQZzdWbXZ4N3ZKV0E1bUtXZXhudXl4UEdlbFYtZ3FZTU5xaUxQLXVwWEl3LVROVms?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiigFBVV95cUxQdlh5Z1o2eWhVc0VhYUZreEJPb2NoUUtrMHQyM29oeTNyX252WHA2T29Nd0VQY1ZxQzVIS2psTmtsQnZNSFliOFNtdlF1bHQzNXd3OFp2dmZuRTlZZDI3dTFHUWdueHVqM3lKaEt0NkJzS2xfR0x4ODdoWTVvMzFlWTlKa3NHTUEzM3fSAY8BQVVfeXFMUFFRcTJ4clNrOS13LWw1aTJGNVJRMFpGd3g1SG00d2xLOVRWREpnRDJYOGtnbWo2c1JvSXl6S18zcjk2MEJYVmpEejUwemE3N2JZS0Fnc2xGT2J6TFVSMERQZzdWbXZ4N3ZKV0E1bUtXZXhudXl4UEdlbFYtZ3FZTU5xaUxQLXVwWEl3LVROVms?oc=5\" target=\"_blank\">Consum abre una nueva tienda en Almería y avanza en su plan de dieciocho aperturas en 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Conciso</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T10:04:15Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Obramat inaugura en Churra su segundo almacén en la Región de Murcia - Interempresas.net",
    "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxQNnJHaWdYTnRJUktzakdFQWJwUC00ZXhVSGR4VTE0YkFqS3dqVVA5dmd3WGlwYmNXWEI1QlpsVmRETWRuRkJXc1N1NnRzWl9QRE9QbFFxcXB5VW9QYU5hMzZTQTY5NDcxd2Y4OFpyWG5za1E0TzJjNFprNUxsU1JzLUVKYWdQRHcyM3JKTV9USzA4MXlvazVZMGsyaVZZU0xsT0xYaWc2aDhMU1I1eEFQS2xpSUhlQkFRd2tzdjVoWWJCLUxSUXVrcGxsd0hoYzJ0MS1faXhrQzJMR1lE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi3AFBVV95cUxQNnJHaWdYTnRJUktzakdFQWJwUC00ZXhVSGR4VTE0YkFqS3dqVVA5dmd3WGlwYmNXWEI1QlpsVmRETWRuRkJXc1N1NnRzWl9QRE9QbFFxcXB5VW9QYU5hMzZTQTY5NDcxd2Y4OFpyWG5za1E0TzJjNFprNUxsU1JzLUVKYWdQRHcyM3JKTV9USzA4MXlvazVZMGsyaVZZU0xsT0xYaWc2aDhMU1I1eEFQS2xpSUhlQkFRd2tzdjVoWWJCLUxSUXVrcGxsd0hoYzJ0MS1faXhrQzJMR1lE?oc=5\" target=\"_blank\">Obramat inaugura en Churra su segundo almacén en la Región de Murcia</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Interempresas.net</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T12:23:36Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Obramat"
  },
  {
    "titulo": "Así será la nueva fábrica de MG en Galicia, que dará empleo a 1.000 trabajadores - forococheselectricos.com",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxNb056RFZncmZudHNEZW1WekQ5c2JOQXIzUnc5VDNKMEJPdGdYNThtbjdyMWhoWldrdVB3TlMzZWZ5TTg3dzRmSTN1bDhjb1pmZGFzUjVrWnRMSWtyTE9pMnlPSkY1RWE3a3oxUVVoc1FyLUFmbzU2VFkyTlZZVVdNZ2hnSTJXQmtVREgzd3JTeDk4OHBfUlAwSVlnRXpTTFE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMinwFBVV95cUxNb056RFZncmZudHNEZW1WekQ5c2JOQXIzUnc5VDNKMEJPdGdYNThtbjdyMWhoWldrdVB3TlMzZWZ5TTg3dzRmSTN1bDhjb1pmZGFzUjVrWnRMSWtyTE9pMnlPSkY1RWE3a3oxUVVoc1FyLUFmbzU2VFkyTlZZVVdNZ2hnSTJXQmtVREgzd3JTeDk4OHBfUlAwSVlnRXpTTFE?oc=5\" target=\"_blank\">Así será la nueva fábrica de MG en Galicia, que dará empleo a 1.000 trabajadores</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">forococheselectricos.com</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T07:48:19Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "MG"
  },
  {
    "titulo": "El nuevo kiosco del centro de León busca empleados para su apertura - Digital de León",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPS3FySGJLSHBLbzRRR2tIUmFuUnpwVjVaLVhTQmdyZVplR0N5Q3JsbFZkMzNhWXQ4bWRuQTVrZWIzdzVRbnhua25NUmtGQm5nSTU4UFl5ZkxfY2tIdnNEUHRFR0k0SjZUc1ZHR0JfdDNEVWZyTk9sZXNCLWJIbGthMndEa1Q1b3pUbzl6UzB2ZG9GRV85a29ubG94akdNWGtOR2xUMWI1NFFaUkF2U2NMSFkzRmNXT3E0ZnEzVXpaemthSDhLdkxr0gHMAUFVX3lxTE9LaXlhRFc0b1l1ak9Jckx4NThuSkZORGY4X0JWNVhpdHg0NUVqTDdqVzdKbFVTandrYmFULVB4c2xJamIxMlFSbEhpZm85MFg4emxMWldoQ3BNZEk5WDBVTHZ3d2UtZ003c180d081bTBtQUZBeEw2eXdXRDdkOHQ4YlVOTmo5ZXBXMEZEc1RLeExpYVJSTklNSUpTTzdTVXhRNDRaWm1nVWtfZG51R3U1U3dIc0FpZjN4ZVdYaGNWNGFlR3Y1dVVOd3BqOQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMixwFBVV95cUxPS3FySGJLSHBLbzRRR2tIUmFuUnpwVjVaLVhTQmdyZVplR0N5Q3JsbFZkMzNhWXQ4bWRuQTVrZWIzdzVRbnhua25NUmtGQm5nSTU4UFl5ZkxfY2tIdnNEUHRFR0k0SjZUc1ZHR0JfdDNEVWZyTk9sZXNCLWJIbGthMndEa1Q1b3pUbzl6UzB2ZG9GRV85a29ubG94akdNWGtOR2xUMWI1NFFaUkF2U2NMSFkzRmNXT3E0ZnEzVXpaemthSDhLdkxr0gHMAUFVX3lxTE9LaXlhRFc0b1l1ak9Jckx4NThuSkZORGY4X0JWNVhpdHg0NUVqTDdqVzdKbFVTandrYmFULVB4c2xJamIxMlFSbEhpZm85MFg4emxMWldoQ3BNZEk5WDBVTHZ3d2UtZ003c180d081bTBtQUZBeEw2eXdXRDdkOHQ4YlVOTmo5ZXBXMEZEc1RLeExpYVJSTklNSUpTTzdTVXhRNDRaWm1nVWtfZG51R3U1U3dIc0FpZjN4ZVdYaGNWNGFlR3Y1dVVOd3BqOQ?oc=5\" target=\"_blank\">El nuevo kiosco del centro de León busca empleados para su apertura</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Digital de León</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T12:30:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "León"
  },
  {
    "titulo": "Leche Pascual presenta un ERE para los 80 trabajadores de su planta de Gurb (Barcelona) - EL PAÍS",
    "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQa2F6bnZSNmxhZ2JnRW5ZdE1OMlF2VmtacDR6VXRMSGpFTE02cG9ONmxaQno4WndBdm5mYmlKeWRxUGxneE9pR21mQVdDVm5YUmJpRDNyMXl2QlhYTkwwTDhpakxnNVBEai1TUHVlNTljeElyM01DdUFnWkYyZklid3E3RHVNTUtpX1FXeHkwbHN3TjJ3RzlCZ1duNEFQQU5sUlNCdWVJWUdoa0k4cllaRDh0bDdmcFZpZmpaUG0xZ19ETVJ0ZDM0REZmaHp4aTdJM1RJ0gHnAUFVX3lxTFBEUGVVU3ViNll1WFlkVVIwQVEwX1BtTG1pbjYxaGJSRzZJUFltTGJPc3B5TVByeTBnYmJMQjVac0JIM3VocDBPSThOTWctanFmVV9oVFBGaWZxSnowRXBXaUlBUEVCbEpBN2VFWlZHSlZwNU9oc243NFY5QV8tQ2tyTnFTZkwxdlFiZE1Vak40clZBQ0lMZWU0cTF1d1lBWWlQcVgyMlBTV0hpNDhKdUJzeHVkOWt3RXpqb3hfTEpSWE1zTWVsOWNNSVhuUlFnU1hKN09hbnBoUi1vTWgtaUlQOUE5UnJjaw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi0wFBVV95cUxQa2F6bnZSNmxhZ2JnRW5ZdE1OMlF2VmtacDR6VXRMSGpFTE02cG9ONmxaQno4WndBdm5mYmlKeWRxUGxneE9pR21mQVdDVm5YUmJpRDNyMXl2QlhYTkwwTDhpakxnNVBEai1TUHVlNTljeElyM01DdUFnWkYyZklid3E3RHVNTUtpX1FXeHkwbHN3TjJ3RzlCZ1duNEFQQU5sUlNCdWVJWUdoa0k4cllaRDh0bDdmcFZpZmpaUG0xZ19ETVJ0ZDM0REZmaHp4aTdJM1RJ0gHnAUFVX3lxTFBEUGVVU3ViNll1WFlkVVIwQVEwX1BtTG1pbjYxaGJSRzZJUFltTGJPc3B5TVByeTBnYmJMQjVac0JIM3VocDBPSThOTWctanFmVV9oVFBGaWZxSnowRXBXaUlBUEVCbEpBN2VFWlZHSlZwNU9oc243NFY5QV8tQ2tyTnFTZkwxdlFiZE1Vak40clZBQ0lMZWU0cTF1d1lBWWlQcVgyMlBTV0hpNDhKdUJzeHVkOWt3RXpqb3hfTEpSWE1zTWVsOWNNSVhuUlFnU1hKN09hbnBoUi1vTWgtaUlQOUE5UnJjaw?oc=5\" target=\"_blank\">Leche Pascual presenta un ERE para los 80 trabajadores de su planta de Gurb (Barcelona)</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL PAÍS</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T11:43:59Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "ERE",
    "ubicacion": "Gurb"
  },
  {
    "titulo": "Eroski inaugura un nuevo supermercado franquiciado en Mallorca - Revista ARAL",
    "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPT0d2aWRJMW9RU0Radkl4b3ZpQ2xvbnRoSFBxa09LWDRPSDBreVhIVVl0c2lRbTVhWFM5VS1pVlZQN1dlMmR2RTlEUk0yMHI3TkFNTFVfbzNTRkIwYkpHOTZEZmJWLUdaWGJKR2VNVldleTBQRThHeEw1U1BfdkZIV1lGd09fV2d6eVphTzF2Nm9uX2VmaUY5QVpvOWE1bEROYUw0UUxXVm5lcVFmTDRPXzFuTQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiswFBVV95cUxPT0d2aWRJMW9RU0Radkl4b3ZpQ2xvbnRoSFBxa09LWDRPSDBreVhIVVl0c2lRbTVhWFM5VS1pVlZQN1dlMmR2RTlEUk0yMHI3TkFNTFVfbzNTRkIwYkpHOTZEZmJWLUdaWGJKR2VNVldleTBQRThHeEw1U1BfdkZIV1lGd09fV2d6eVphTzF2Nm9uX2VmaUY5QVpvOWE1bEROYUw0UUxXVm5lcVFmTDRPXzFuTQ?oc=5\" target=\"_blank\">Eroski inaugura un nuevo supermercado franquiciado en Mallorca</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Revista ARAL</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T14:18:50Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Mallorca"
  },
  {
    "titulo": "La cooperativa valenciana Consum abre una nueva tienda en Almería y alcanza los 30 supermercados en la provincia - El Debate",
    "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxQcGlDS1FYMFlxczVqZUZVVUltTFo4bHBUMDVNaHhYeDBBXy16LXZ2TGN1VVNBeVRUVTZtdDF6YU5MOHhyaUF3SnloR3BUN0UzcXh4c0YwVFltMXJsRVREVmJsSkN1ZF85M19ESHRWMkl4MVJ4dTFOMGpyQzdELWJ5Z2R3Tkh6ZEVLel9lcC16eHNnaGpoMHZ3UGctVGpBd1NKaUV0bmpzMVZ5SllZNlhWLXhJQmk5cUc4ZUZRQVI2ZFlWTU9TeUdVMTRWbWNfN093azFKVERSSGNRa2d1WDIzbGMtYzFlN3NYejliendyTm1jZURRM0HSAfsBQVVfeXFMTm5wSnNnblhjeklTckJFV2U2UlZMYW93VGRsbkRjM2NPNHFfRFFVV21DQzRIWEQ3dU1iNzVzSHQ1TXpSQndJT3NHU201N2pVRS1tREZIS2preGpPZEl1UWJUbUJyWWxtVTh3M2pYSDJiajVxMnloOFdPSlNNOXRXSWZ4Vi10M2ZIQ1dNQ0Z3VFl0Q2hFSnFVUUlGSFdzcWxObFBaZzkxX0M1WG1rTnVHalFQbUlhT2VzUjc2R3dWbVRqSUN2Mm9qNW5pLTNyeHI3RUtwSDF0ODN1b3dPdUNPVVJ1SURNQm1KYVZBNXphcGtrR21zN0pOYnpFRG8?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi9gFBVV95cUxQcGlDS1FYMFlxczVqZUZVVUltTFo4bHBUMDVNaHhYeDBBXy16LXZ2TGN1VVNBeVRUVTZtdDF6YU5MOHhyaUF3SnloR3BUN0UzcXh4c0YwVFltMXJsRVREVmJsSkN1ZF85M19ESHRWMkl4MVJ4dTFOMGpyQzdELWJ5Z2R3Tkh6ZEVLel9lcC16eHNnaGpoMHZ3UGctVGpBd1NKaUV0bmpzMVZ5SllZNlhWLXhJQmk5cUc4ZUZRQVI2ZFlWTU9TeUdVMTRWbWNfN093azFKVERSSGNRa2d1WDIzbGMtYzFlN3NYejliendyTm1jZURRM0HSAfsBQVVfeXFMTm5wSnNnblhjeklTckJFV2U2UlZMYW93VGRsbkRjM2NPNHFfRFFVV21DQzRIWEQ3dU1iNzVzSHQ1TXpSQndJT3NHU201N2pVRS1tREZIS2preGpPZEl1UWJUbUJyWWxtVTh3M2pYSDJiajVxMnloOFdPSlNNOXRXSWZ4Vi10M2ZIQ1dNQ0Z3VFl0Q2hFSnFVUUlGSFdzcWxObFBaZzkxX0M1WG1rTnVHalFQbUlhT2VzUjc2R3dWbVRqSUN2Mm9qNW5pLTNyeHI3RUtwSDF0ODN1b3dPdUNPVVJ1SURNQm1KYVZBNXphcGtrR21zN0pOYnpFRG8?oc=5\" target=\"_blank\">La cooperativa valenciana Consum abre una nueva tienda en Almería y alcanza los 30 supermercados en la provincia</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Debate</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T09:26:47Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Alcampo refuerza su red de franquicias con una nueva apertura en Hondarribia - Just Retail",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQZ3hyMi1yak9BY3JfazBMYk9WMXp3RDJiTlpfVEZnXzN6VGRlejF1ZHVhZ3lvdU9tZnFWeUpxc29jRER5NDd0Uk5SRXVGX2RES1VzWkZqU0pWYXNBb2M5NTYyWjVtZDNsVXRLQmNOSk5oNElQc01TTm5hYURsQnQ3bDdIODh6NlhQMjBqS0EtMHFJQThLWDFwYkJkYzlXbE1uZF92MmNGUXNTWEE2MzFjVHJ1VVk?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitAFBVV95cUxQZ3hyMi1yak9BY3JfazBMYk9WMXp3RDJiTlpfVEZnXzN6VGRlejF1ZHVhZ3lvdU9tZnFWeUpxc29jRER5NDd0Uk5SRXVGX2RES1VzWkZqU0pWYXNBb2M5NTYyWjVtZDNsVXRLQmNOSk5oNElQc01TTm5hYURsQnQ3bDdIODh6NlhQMjBqS0EtMHFJQThLWDFwYkJkYzlXbE1uZF92MmNGUXNTWEE2MzFjVHJ1VVk?oc=5\" target=\"_blank\">Alcampo refuerza su red de franquicias con una nueva apertura en Hondarribia</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Just Retail</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T08:55:01Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Hondarribia"
  },
  {
    "titulo": "EROSKI inaugura en Mallorca un nuevo supermercado franquiciado con la enseña RAPID - Diario de Mallorca",
    "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxNX2hXbGs5SHEzeENtdVliaU1fSnZPX19vb2NnbE5YU2NHQWhuRnlXU1Via3RiQmRMa2FOcjNqZHlEeXZpMzFzSGhxekRrbXFleEttM3FORnR5TVlRTHJqdEZwZDg2SzJFbzE5dnFhSHlRbzNBNEFLV0h5b3RuRXZUVlp6ZWI4UkFRZmwwWnV5TXZicnNuYTNQS1U2UG5SaHl4WlI0azRGN29DMmF0YlB6REtyb0ZaTG1Ca1M0RGN3ONIBxAFBVV95cUxPMWNzMzBWb0o3ekJDSkRLSDBVU1RkcVJQdjdoWHlWSDItR3V6YmR0ekFfTTk2ZW05OXUyNnV3cjFhVEpqNy16NDBYUDQ4cWc4THNPeUpETHZMMHhPT3g4V0NCS3FvcU5pSUlkY2NuSlpwQUJaRVRlYy1TeVFmUDI1XzlqV2FjaXc5R2hDTEhJODNJdlBwX3IydWZvNjM0eE80WmdnMWZzbmxnR0gxeW5Jb1BPY0xQYmxvODVIMHZGejhJNjkx?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMivwFBVV95cUxNX2hXbGs5SHEzeENtdVliaU1fSnZPX19vb2NnbE5YU2NHQWhuRnlXU1Via3RiQmRMa2FOcjNqZHlEeXZpMzFzSGhxekRrbXFleEttM3FORnR5TVlRTHJqdEZwZDg2SzJFbzE5dnFhSHlRbzNBNEFLV0h5b3RuRXZUVlp6ZWI4UkFRZmwwWnV5TXZicnNuYTNQS1U2UG5SaHl4WlI0azRGN29DMmF0YlB6REtyb0ZaTG1Ca1M0RGN3ONIBxAFBVV95cUxPMWNzMzBWb0o3ekJDSkRLSDBVU1RkcVJQdjdoWHlWSDItR3V6YmR0ekFfTTk2ZW05OXUyNnV3cjFhVEpqNy16NDBYUDQ4cWc4THNPeUpETHZMMHhPT3g4V0NCS3FvcU5pSUlkY2NuSlpwQUJaRVRlYy1TeVFmUDI1XzlqV2FjaXc5R2hDTEhJODNJdlBwX3IydWZvNjM0eE80WmdnMWZzbmxnR0gxeW5Jb1BPY0xQYmxvODVIMHZGejhJNjkx?oc=5\" target=\"_blank\">EROSKI inaugura en Mallorca un nuevo supermercado franquiciado con la enseña RAPID</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Diario de Mallorca</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-19T07:00:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "EROSKI",
    "ubicacion": "Mallorca"
  },
  {
    "titulo": "Iberia pone en rampa de salida su ERE voluntario para 844 trabajadores - EL PAÍS",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQcGNJeW5HSTVtV1BZbU9mOFVrOExPYktDY2Exc2trWGhFSE5yT05NR2pxekNQUU1iRWtIMFh3c1lnVEd2dDMtZmJQbWRSMFc1cS1WLXpYN2VvOGEyVVUzREhkVDMzRXA0RVNrSXU3NXZiY3dKaTVGMTRRckwtVDdjZTRzVDBtY2N3YTJqX2ZTMUgxOWF6SmVjR2xQZGM0RFN5TjVLZ3lKdktva0tSNVlnWFBBOHXSAcgBQVVfeXFMUHh2SUFwNThLRXVaM0twV1pWbmVLM1JVLUJGWHNfd3JGdU1iaUZGem02VlhKQk50RU1kbm8xMmxIZ09RdWF4YUI1REdGR0R2TkJZOHZlRW5ReFc5NGhsMW9IYXVVWHNyTHVjWC1YYjRTWDk5Rkl0eFhYN1htTUE5WnNkbUU4WFNrRlNERXIwRy1ZOE1razJFU0JOaGg4LUU5WlFIczdNSm9LbDZPZ3VGQ3FrbUxwemF2VUMta1c3WVFmcVlCbjNlNUo?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitAFBVV95cUxQcGNJeW5HSTVtV1BZbU9mOFVrOExPYktDY2Exc2trWGhFSE5yT05NR2pxekNQUU1iRWtIMFh3c1lnVEd2dDMtZmJQbWRSMFc1cS1WLXpYN2VvOGEyVVUzREhkVDMzRXA0RVNrSXU3NXZiY3dKaTVGMTRRckwtVDdjZTRzVDBtY2N3YTJqX2ZTMUgxOWF6SmVjR2xQZGM0RFN5TjVLZ3lKdktva0tSNVlnWFBBOHXSAcgBQVVfeXFMUHh2SUFwNThLRXVaM0twV1pWbmVLM1JVLUJGWHNfd3JGdU1iaUZGem02VlhKQk50RU1kbm8xMmxIZ09RdWF4YUI1REdGR0R2TkJZOHZlRW5ReFc5NGhsMW9IYXVVWHNyTHVjWC1YYjRTWDk5Rkl0eFhYN1htTUE5WnNkbUU4WFNrRlNERXIwRy1ZOE1razJFU0JOaGg4LUU5WlFIczdNSm9LbDZPZ3VGQ3FrbUxwemF2VUMta1c3WVFmcVlCbjNlNUo?oc=5\" target=\"_blank\">Iberia pone en rampa de salida su ERE voluntario para 844 trabajadores</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL PAÍS</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-22T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Iberia",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Magnific (Freepik) plantea un ERE para el 30% de su plantilla - Expansión",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxPaFM2WmJQSmx0ZnJtd2JueEVBeVFlZmtMUFhlUl9MeXRpRnotbXdsdXNqU3hHRmUtNHdIeGQ3UE9Iem1kZmg1aFF0SmVqakpYNkdrM2dFcUFNM3FneV9rMGRBUjRvRDgwNXc5NjZ3NXRKdzJta29EZEFvX2gycXJRaU5lMGxlb2NZT21iQXFCVEFEeV9ZQTM5atIBmAFBVV95cUxOcnRWZklpRHNUOUlBNk0yRkM3OHdaZzlnNy1jamFJYTdDNUo3LXpKUW5hMHRkODFxQVQ2eVNhUENuUFpTTGc1RmlKVUxocWc3Vmp4RnRlTkNTNXF3RUtSc1llMDdkUjh6TVdzbDF0RWp5cHFRdmJUQURENGgzaW9RWVBnVmNBNk1ZVVhVUmdWREdWcEM0cDRPTQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMimAFBVV95cUxPaFM2WmJQSmx0ZnJtd2JueEVBeVFlZmtMUFhlUl9MeXRpRnotbXdsdXNqU3hHRmUtNHdIeGQ3UE9Iem1kZmg1aFF0SmVqakpYNkdrM2dFcUFNM3FneV9rMGRBUjRvRDgwNXc5NjZ3NXRKdzJta29EZEFvX2gycXJRaU5lMGxlb2NZT21iQXFCVEFEeV9ZQTM5atIBmAFBVV95cUxOcnRWZklpRHNUOUlBNk0yRkM3OHdaZzlnNy1jamFJYTdDNUo3LXpKUW5hMHRkODFxQVQ2eVNhUENuUFpTTGc1RmlKVUxocWc3Vmp4RnRlTkNTNXF3RUtSc1llMDdkUjh6TVdzbDF0RWp5cHFRdmJUQURENGgzaW9RWVBnVmNBNk1ZVVhVUmdWREdWcEM0cDRPTQ?oc=5\" target=\"_blank\">Magnific (Freepik) plantea un ERE para el 30% de su plantilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Expansión</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-18T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Magnific"
  },
  {
    "titulo": "Stellantis plantea un ERE y un ERTE en Villaverde tras recortar en 7.800 coches su previsión de producción - El Economista",
    "url": "https://news.google.com/rss/articles/CBMi_AFBVV95cUxNQkE2YmU5Vl9Wd0E2ellyYzk3M180Uk5oYVJjdjFoclV6UXA1SlE3dTVWRUdCbEJVUm1wT0hfZ29BVzZjdFFvMXlLN0hIY09aRU9sckVTaWlOV0x3NEJBQkU0RVZCQWtZQjhGWjRIQUQ1WnpPanE5WldBRHFCZnNObm5KVlo5X1RCdHk4YnBvVlBkUFJiYnZLeDBMWXRBbjZKNWFrUXhzdDg2OFdVamM1dGIwR3RLTVBLQ1JkZzBYbnlCc25oS1JNcHV2bE9SNTNyOF83OHk0WjRtTHd3MWhyVHJ0aDZjVjJxZlJ0V2RqSk9jQ1lhNGxOS1dBV3PSAecBQVVfeXFMUHFOb2EzUVJIT3pRQWJnOTJIOUUyUlRDZDdOU3BUemtLSUFpdWMxQnNsbEsxdlZuclBOQUZiV09WVXpkWjI5SldTTXp6R1ZuS25iYXJZMzY0dUFsM2YtNGlpb0I4LWVGUmo1bEtMZGdIbVkwX2wwT0hZNlhIWHlJbEt3SUdXTmRYYmg0d0dnek01c3N6aE81VVlaZE9SdWY1dHNoZEpuNmp6RWU0QzZCQ1NnclJIQVRSSjFGM0Y5UGFaYnAyb3ZpTnp0X2doSUs2TzlwLWRsTGE5RHA4c3RWcFRpZmQ3amFB?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi_AFBVV95cUxNQkE2YmU5Vl9Wd0E2ellyYzk3M180Uk5oYVJjdjFoclV6UXA1SlE3dTVWRUdCbEJVUm1wT0hfZ29BVzZjdFFvMXlLN0hIY09aRU9sckVTaWlOV0x3NEJBQkU0RVZCQWtZQjhGWjRIQUQ1WnpPanE5WldBRHFCZnNObm5KVlo5X1RCdHk4YnBvVlBkUFJiYnZLeDBMWXRBbjZKNWFrUXhzdDg2OFdVamM1dGIwR3RLTVBLQ1JkZzBYbnlCc25oS1JNcHV2bE9SNTNyOF83OHk0WjRtTHd3MWhyVHJ0aDZjVjJxZlJ0V2RqSk9jQ1lhNGxOS1dBV3PSAecBQVVfeXFMUHFOb2EzUVJIT3pRQWJnOTJIOUUyUlRDZDdOU3BUemtLSUFpdWMxQnNsbEsxdlZuclBOQUZiV09WVXpkWjI5SldTTXp6R1ZuS25iYXJZMzY0dUFsM2YtNGlpb0I4LWVGUmo1bEtMZGdIbVkwX2wwT0hZNlhIWHlJbEt3SUdXTmRYYmg0d0dnek01c3N6aE81VVlaZE9SdWY1dHNoZEpuNmp6RWU0QzZCQ1NnclJIQVRSSjFGM0Y5UGFaYnAyb3ZpTnp0X2doSUs2TzlwLWRsTGE5RHA4c3RWcFRpZmQ3amFB?oc=5\" target=\"_blank\">Stellantis plantea un ERE y un ERTE en Villaverde tras recortar en 7.800 coches su previsión de producción</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Economista</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T15:46:41Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Villaverde"
  },
  {
    "titulo": "Magnific (Freepik) plantea un ERE para 111 empleados, casi una cuarta parte de su plantilla - Diario Sur",
    "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxOZk1xM19hMy14VHBhbWRNQ1BtaE9jeEo2azlhTTBvQjBocWJNajZOVHNDbnI4X1lZSURCT3BQcFV3RnlwRV9vcXoyRkc1UTRQaUd2UTBSZlJyTk1MbHVCYjVlQzhTUzZNOTh2VXJMWUg5ejNIeVFLbGdGMGFUdmpWRVJsMmR5RS1lN1JZUk0xcWNfTWpQa1FFZXFnbi1FT0pOOElNX3B5SmMwS2pq0gGyAUFVX3lxTFBnUWNoanUzcEJKY0l0ajM5NDQ4VFVQOEh4b01kUnVNSzNyUjQwcDZZdXRIWVl1Q0ExR21VZDhDUnJTSTNWWVhQY1BDMnlGSVRHcjVQRVpKOTVhYkNPaEpuRUZ6YXZSdjdmak02MHpIdG5zWjZ0VGFQV1JsMFF1cWQxWTlBMWl3eXZyY1hVQTlsSjF3Tm82RlJQQVB0ZUZTVk0tNmhyQWd2WEtGNE40X01WZ2c?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMirAFBVV95cUxOZk1xM19hMy14VHBhbWRNQ1BtaE9jeEo2azlhTTBvQjBocWJNajZOVHNDbnI4X1lZSURCT3BQcFV3RnlwRV9vcXoyRkc1UTRQaUd2UTBSZlJyTk1MbHVCYjVlQzhTUzZNOTh2VXJMWUg5ejNIeVFLbGdGMGFUdmpWRVJsMmR5RS1lN1JZUk0xcWNfTWpQa1FFZXFnbi1FT0pOOElNX3B5SmMwS2pq0gGyAUFVX3lxTFBnUWNoanUzcEJKY0l0ajM5NDQ4VFVQOEh4b01kUnVNSzNyUjQwcDZZdXRIWVl1Q0ExR21VZDhDUnJTSTNWWVhQY1BDMnlGSVRHcjVQRVpKOTVhYkNPaEpuRUZ6YXZSdjdmak02MHpIdG5zWjZ0VGFQV1JsMFF1cWQxWTlBMWl3eXZyY1hVQTlsSjF3Tm82RlJQQVB0ZUZTVk0tNmhyQWd2WEtGNE40X01WZ2c?oc=5\" target=\"_blank\">Magnific (Freepik) plantea un ERE para 111 empleados, casi una cuarta parte de su plantilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Diario Sur</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-17T14:39:10Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Magnific"
  },
  {
    "titulo": "Iberia reabrirá su ERE voluntario tras quedarse a 152 bajas del objetivo - Preferente.com",
    "url": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxNMWZ3ZEdtMGp5QXM0MHRsRUdHQnJyTTNOVnFBQ0hHekc1dTl0b3ZWMVhvQ1VDZXpRc2FXRmJLRVU0X1FsTzNBWTRid0RER2dKb2lkZm8yTmtoTGhBQzlNcGh5TUhxSUt1Zi0wYVZlbHRtTGJXa0xxcy1aN2Z6eEw4MGh5ME5VSU1sMFJIRFdTaUhCUHNZazZfR0VMdXB1aTdlSlB5bXJ5SjNYaU4ycFZ1MlN5ZlZ2UV9wQ0otX2Zsb0xlWW5YV1RGQkRYWFUxVjg4am10MUtqb3VUZUN4TTZTNWJrdGRleGxBUkhRRWVRVQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi7wFBVV95cUxNMWZ3ZEdtMGp5QXM0MHRsRUdHQnJyTTNOVnFBQ0hHekc1dTl0b3ZWMVhvQ1VDZXpRc2FXRmJLRVU0X1FsTzNBWTRid0RER2dKb2lkZm8yTmtoTGhBQzlNcGh5TUhxSUt1Zi0wYVZlbHRtTGJXa0xxcy1aN2Z6eEw4MGh5ME5VSU1sMFJIRFdTaUhCUHNZazZfR0VMdXB1aTdlSlB5bXJ5SjNYaU4ycFZ1MlN5ZlZ2UV9wQ0otX2Zsb0xlWW5YV1RGQkRYWFUxVjg4am10MUtqb3VUZUN4TTZTNWJrdGRleGxBUkhRRWVRVQ?oc=5\" target=\"_blank\">Iberia reabrirá su ERE voluntario tras quedarse a 152 bajas del objetivo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Preferente.com</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T09:36:07Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Iberia",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "ElPulpo activa un ERTE en su sede central de A Coruña tras replegarse de Nanos - La Opinión A Coruña",
    "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNWjhsVEdRMU01UUF5SVNFYndGa0x3dEhlamtXSl96M2dkQldCMkNnZDk1WWJiNm8zMEV1VHZHQ0hJX2JtUW9oWHBnOFhhWFBYdGNEOGVHQXZqdGpVaGhvc2lzelQxSU1PbXh2OTM4X3NXNlJEajZPbU9GS1ZBLVRvcTBURVQta2NJRTNxd1JMR1ZLdS0yeFhaWXl2SERBbTQ0ZVRCRXlsc9IBrAFBVV95cUxPRDdvLXJBOEM5UF9VekgtRTEtY0V5Z2k2NkNtWUtGWEJtLXFxd0dTSWJ1RlkyQmY1bWx2LUVKQjNLV3BVMWNqcDItWEpqUF9GQ1RrdGtGRWkwN1BSNi01ZnJabmdzdENFU1prU01qdHdsRHdJbWFDMkxvaWpLVkxpMEZoVlJmblZhMWQtUU90T1ZsT09QZUZRb290WThyTnNGMkZPOGlmbHFBNzFC?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMipwFBVV95cUxNWjhsVEdRMU01UUF5SVNFYndGa0x3dEhlamtXSl96M2dkQldCMkNnZDk1WWJiNm8zMEV1VHZHQ0hJX2JtUW9oWHBnOFhhWFBYdGNEOGVHQXZqdGpVaGhvc2lzelQxSU1PbXh2OTM4X3NXNlJEajZPbU9GS1ZBLVRvcTBURVQta2NJRTNxd1JMR1ZLdS0yeFhaWXl2SERBbTQ0ZVRCRXlsc9IBrAFBVV95cUxPRDdvLXJBOEM5UF9VekgtRTEtY0V5Z2k2NkNtWUtGWEJtLXFxd0dTSWJ1RlkyQmY1bWx2LUVKQjNLV3BVMWNqcDItWEpqUF9GQ1RrdGtGRWkwN1BSNi01ZnJabmdzdENFU1prU01qdHdsRHdJbWFDMkxvaWpLVkxpMEZoVlJmblZhMWQtUU90T1ZsT09QZUZRb290WThyTnNGMkZPOGlmbHFBNzFC?oc=5\" target=\"_blank\">ElPulpo activa un ERTE en su sede central de A Coruña tras replegarse de Nanos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Opinión A Coruña</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-20T16:54:43Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "A Coruña"
  },
  {
    "titulo": "La malagueña Magnific (antes Freepik) presenta un ERE para el 30% de sus 350 trabajadores en España por su cambio de modelo a la IA - La Opinión de Málaga",
    "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxOdFRRVDdXeDZmR25sQjhRNEU2alVhZWFhTHN5dGFLUllvQm45bDhSY216SnlTa3d2TWJnX3RCV3VjN3RiNDdHeG9aZk5fVHZBRGFlVmJnanJyMEl5THhZMG42Uzh0ejhiekdwdXB6NjR3RUsyRnE1X2FLeFB0VWk2WVRHTHdORktWSHlRUDFPaEFwVDMtVWc5MzhrN21yM21KQkVQelE3dmY2QnFnYnQ0dmQ0eVU5akpDM25pVzNYSDQ3eUdkTmdBcHFWRG5LTGvSAdQBQVVfeXFMUG9mX2tDUkM0OTdrSkZDeU0ycmtqZXpXcHNLS0xhOUdXOFlNZTZ3azFPNTdrci1XeGN0VHlXZ0ZWLWxmcG0wWVZlekxXc0VGWWxydExsMk9qMHNhVzNWbHh3dmZiVnY0NDA4TzczWlUtRmRTV2d4bVprYS1MQktVVGMxajBSX0kwNUh4TWlfSzQzdk9reG9sblpaa2NSVWcyVFFpWXZpUDJSN2U5STJkRzZidWFnS1lMOHh0cGw1RURNQ01IWVpJTC1SUmtKODgzaVhEZ2g?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMizwFBVV95cUxOdFRRVDdXeDZmR25sQjhRNEU2alVhZWFhTHN5dGFLUllvQm45bDhSY216SnlTa3d2TWJnX3RCV3VjN3RiNDdHeG9aZk5fVHZBRGFlVmJnanJyMEl5THhZMG42Uzh0ejhiekdwdXB6NjR3RUsyRnE1X2FLeFB0VWk2WVRHTHdORktWSHlRUDFPaEFwVDMtVWc5MzhrN21yM21KQkVQelE3dmY2QnFnYnQ0dmQ0eVU5akpDM25pVzNYSDQ3eUdkTmdBcHFWRG5LTGvSAdQBQVVfeXFMUG9mX2tDUkM0OTdrSkZDeU0ycmtqZXpXcHNLS0xhOUdXOFlNZTZ3azFPNTdrci1XeGN0VHlXZ0ZWLWxmcG0wWVZlekxXc0VGWWxydExsMk9qMHNhVzNWbHh3dmZiVnY0NDA4TzczWlUtRmRTV2d4bVprYS1MQktVVGMxajBSX0kwNUh4TWlfSzQzdk9reG9sblpaa2NSVWcyVFFpWXZpUDJSN2U5STJkRzZidWFnS1lMOHh0cGw1RURNQ01IWVpJTC1SUmtKODgzaVhEZ2g?oc=5\" target=\"_blank\">La malagueña Magnific (antes Freepik) presenta un ERE para el 30% de sus 350 trabajadores en España por su cambio de modelo a la IA</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Opinión de Málaga</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-18T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Freepik"
  },
  {
    "titulo": "Mercazaragoza impulsa un ere para al menos 20 trabajadores por la crisis del matadero municipal - El Periódico de Aragón",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxNVHBMOXRwNHdRRElMS1FZMFA4Y1NhSTJOdVkxMkdySFJFN19OMVVMaHFMR0lySVNQYWJIclJxWG1yYXh0TF9wWE85Q0xYTjFkVTNqYWxVQXJRWGNhZkkyRVNrb1VwTWpnbW9fQU8tb2RqbGlRYW5nMFBFTWhQMDRVSlF3T1k0eU9Oa1FkR0dzaWJvOWZQRlF4WDFVWTZ3ajk2MmNSd01LRG9GYUpsMkVjTlJB0gG3AUFVX3lxTE5ubncyMXIxS2h4SWs2ZHNLWkw1T09EbVBlcDRibmJESDhySmVjbHR0TFN1MUE4V0djR0V4WUVCdEZlT1lvSzBwRkZkaEE4WWhtSGZOdmpZNXBNVXpCd29odUpyS09iRGV3bUg5akdheXlDZFc1TzZzVWgzdVRwZ1JLcTJxRU54Y3Y2ODZuV2ZZZWlySzBuakR0X3ViVmdvc3MzZWwzZUVNQzNOLVd5MExHWTdKbzdfZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMisgFBVV95cUxNVHBMOXRwNHdRRElMS1FZMFA4Y1NhSTJOdVkxMkdySFJFN19OMVVMaHFMR0lySVNQYWJIclJxWG1yYXh0TF9wWE85Q0xYTjFkVTNqYWxVQXJRWGNhZkkyRVNrb1VwTWpnbW9fQU8tb2RqbGlRYW5nMFBFTWhQMDRVSlF3T1k0eU9Oa1FkR0dzaWJvOWZQRlF4WDFVWTZ3ajk2MmNSd01LRG9GYUpsMkVjTlJB0gG3AUFVX3lxTE5ubncyMXIxS2h4SWs2ZHNLWkw1T09EbVBlcDRibmJESDhySmVjbHR0TFN1MUE4V0djR0V4WUVCdEZlT1lvSzBwRkZkaEE4WWhtSGZOdmpZNXBNVXpCd29odUpyS09iRGV3bUg5akdheXlDZFc1TzZzVWgzdVRwZ1JLcTJxRU54Y3Y2ODZuV2ZZZWlySzBuakR0X3ViVmdvc3MzZWwzZUVNQzNOLVd5MExHWTdKbzdfZw?oc=5\" target=\"_blank\">Mercazaragoza impulsa un ere para al menos 20 trabajadores por la crisis del matadero municipal</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Periódico de Aragón</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-22T05:00:32Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "El Periódico"
  },
  {
    "titulo": "La empresa leonesa de telemarketing Plus Contacto anuncia un ERE a su plantilla - ILEON",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQUXYxWHVNMmhpY3BITl9peXpmV2thUS1kYVJTNnZ1VVhzb1ZzUkY3T29MT1Z3OWxrTlctekNDOFJMVDJ1RFBQaEdXZGNvVzVkM1o5bUxVTS1fcWhEdHdvUDJpZ2V5czFHTlFMOGowTHk2V0wtek04UHB4WWY4N2U4UmpNMmRRYTB2TFFzQTF6THkzUVVlTVJxSndHTXQteHV0TGF0aUxWSlMyWXN1Ujl2ZkM5V1Z4TXPSAbwBQVVfeXFMTUZXd1Znd1JjVEtRZG1Wald2bktmeWwtMzRJejZXMXg1ZEdNZXR4bEdITm9mZU12T21WZVJNeXI4Y1pHOGdKOUZQTFVYbkdJUGFleTVBWjNXNVA0X1g0eUFSaXFzSHdHTFRMRTViUE1IYzF2TzBhV2p1dnhHQWh4S2hjdThrUWVFUFZ0ZFVSbVdpeFc5UkxWa1FEWkIweEFOT29UN19WWWJkajlmcUlxQ3RKTUFzWDdWajFvdWk?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitwFBVV95cUxQUXYxWHVNMmhpY3BITl9peXpmV2thUS1kYVJTNnZ1VVhzb1ZzUkY3T29MT1Z3OWxrTlctekNDOFJMVDJ1RFBQaEdXZGNvVzVkM1o5bUxVTS1fcWhEdHdvUDJpZ2V5czFHTlFMOGowTHk2V0wtek04UHB4WWY4N2U4UmpNMmRRYTB2TFFzQTF6THkzUVVlTVJxSndHTXQteHV0TGF0aUxWSlMyWXN1Ujl2ZkM5V1Z4TXPSAbwBQVVfeXFMTUZXd1Znd1JjVEtRZG1Wald2bktmeWwtMzRJejZXMXg1ZEdNZXR4bEdITm9mZU12T21WZVJNeXI4Y1pHOGdKOUZQTFVYbkdJUGFleTVBWjNXNVA0X1g0eUFSaXFzSHdHTFRMRTViUE1IYzF2TzBhV2p1dnhHQWh4S2hjdThrUWVFUFZ0ZFVSbVdpeFc5UkxWa1FEWkIweEFOT29UN19WWWJkajlmcUlxQ3RKTUFzWDdWajFvdWk?oc=5\" target=\"_blank\">La empresa leonesa de telemarketing Plus Contacto anuncia un ERE a su plantilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ILEON</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T15:59:53Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ILEON",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La fábrica de Nestlé en La Penilla recibe 69 solicitudes de salida voluntaria con el ERE - El Diario Montañés",
    "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxNVDM2bG9aczVPNnhZYy1FU1djTUVwSXVhRFFvaVpZeXZmVldObHZ6aVdkbnNsM0tjQ3NNWFRQZlc2TTBhOFA0ejRUdS14Y1llNzRvVHNmQnlxbGJGWUlPeFFFZUVOekJ4elM3dVcyVkdDSlE0Yi1xVWVKN1RwUHYzWUJtbjd4QzdMX28yVU1tSDFKZHdWSzBIUEwybXd2cGtWVS1zbFQwajZCcEZrVVNWN1A0M2N4dEdEUXdQMUxzMjR3RENGcnhuM1dzOA?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxNVDM2bG9aczVPNnhZYy1FU1djTUVwSXVhRFFvaVpZeXZmVldObHZ6aVdkbnNsM0tjQ3NNWFRQZlc2TTBhOFA0ejRUdS14Y1llNzRvVHNmQnlxbGJGWUlPeFFFZUVOekJ4elM3dVcyVkdDSlE0Yi1xVWVKN1RwUHYzWUJtbjd4QzdMX28yVU1tSDFKZHdWSzBIUEwybXd2cGtWVS1zbFQwajZCcEZrVVNWN1A0M2N4dEdEUXdQMUxzMjR3RENGcnhuM1dzOA?oc=5\" target=\"_blank\">La fábrica de Nestlé en La Penilla recibe 69 solicitudes de salida voluntaria con el ERE</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Diario Montañés</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T05:17:19Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Nestlé",
    "ubicacion": "La Penilla"
  },
  {
    "titulo": "ElPulpo presenta un ERTE para 15 trabajadores en su sede de A Coruña durante ocho meses - La Voz de Galicia",
    "url": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxPd0NnbWp0WjZSUkw1SGhneHc3MkRaTTJxWExTY2hsaTIzcG9LOTRiSFE1X2EwN3lLSkFybExia3VaZDAxODNUVFZPWkRKekt1RGV0RzI4RHVVczRpLWtTTExoTzJkOHpuQ3pOTXM3aTFueTVvZW5adW9MUVoxVnNHdDh3NUZja2pBUkpGdVhqZ3loR0RzV01EWk03c1N5dTBPV19VWWR0MWlETFg2Q1BnbDdYNnY2T2ZvQXhVc2t5SF9EZzZ5SGZoQmYtc2RkbXFwWl9XYkNRNTlHTUNrbVYyZ25OSGZ4RldNS3fSAYYCQVVfeXFMT0hqN1BPU3lBOEZsbUlsdTBVVXdvRzhKcW4zY0VRYVFMT0d3YlMyV2lXRjBNWWo5OEwyWVBMRVNNYWxzeUhBR0p1Zkk5eW9tQmxZWFdxSl9MUUxIVm5WaHd4dDVvMU5OWUpVQ3BfS2ljcHdsZEp0LXQxdWFGbVBWZUxlaVRibTI3blBiaGFITFFrM2xXNDZ3SUx2bHNnc1F2bG52MjU1cEZ5ak1OX1EwUUNjZVJvLVd1YWlGajZEMTkyVTFoVVJrUm9qMTNPa1BHRktUT3FmM0hmSVQ1NG1QVXhCWlBjdGJOVFZ6NW5JNGFYWWxBNGExUGRkNzBVdWctZ0MyYjBOUQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6gFBVV95cUxPd0NnbWp0WjZSUkw1SGhneHc3MkRaTTJxWExTY2hsaTIzcG9LOTRiSFE1X2EwN3lLSkFybExia3VaZDAxODNUVFZPWkRKekt1RGV0RzI4RHVVczRpLWtTTExoTzJkOHpuQ3pOTXM3aTFueTVvZW5adW9MUVoxVnNHdDh3NUZja2pBUkpGdVhqZ3loR0RzV01EWk03c1N5dTBPV19VWWR0MWlETFg2Q1BnbDdYNnY2T2ZvQXhVc2t5SF9EZzZ5SGZoQmYtc2RkbXFwWl9XYkNRNTlHTUNrbVYyZ25OSGZ4RldNS3fSAYYCQVVfeXFMT0hqN1BPU3lBOEZsbUlsdTBVVXdvRzhKcW4zY0VRYVFMT0d3YlMyV2lXRjBNWWo5OEwyWVBMRVNNYWxzeUhBR0p1Zkk5eW9tQmxZWFdxSl9MUUxIVm5WaHd4dDVvMU5OWUpVQ3BfS2ljcHdsZEp0LXQxdWFGbVBWZUxlaVRibTI3blBiaGFITFFrM2xXNDZ3SUx2bHNnc1F2bG52MjU1cEZ5ak1OX1EwUUNjZVJvLVd1YWlGajZEMTkyVTFoVVJrUm9qMTNPa1BHRktUT3FmM0hmSVQ1NG1QVXhCWlBjdGJOVFZ6NW5JNGFYWWxBNGExUGRkNzBVdWctZ0MyYjBOUQ?oc=5\" target=\"_blank\">ElPulpo presenta un ERTE para 15 trabajadores en su sede de A Coruña durante ocho meses</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Voz de Galicia</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-20T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Tubacex no está siendo capaz de acreditar las causas del ERTE - ELA Sindikatua",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxQMm5lMEs2S1NDRlVOQnl3NmgteFN1Q2R3a3A4Mk52emw1bEFkUmpWaVZTRklkVUNfTVA1SVkzNjRYY1NSM1kyRmdUdHE3YWN0bTd3dHcwNE12OXFkUEI0VU96M3UyVy1ZMHVLOWpYQW0zLXBCVTVVY3ZaVzZpNkRQaEVydk9pWG9JLUU5ZXQ1ZEJUQ3hEaGJ0d1ZFS095VlNGQTRIWUgxanRCZWZkSHB0U1daRHpBWWNGOUE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiugFBVV95cUxQMm5lMEs2S1NDRlVOQnl3NmgteFN1Q2R3a3A4Mk52emw1bEFkUmpWaVZTRklkVUNfTVA1SVkzNjRYY1NSM1kyRmdUdHE3YWN0bTd3dHcwNE12OXFkUEI0VU96M3UyVy1ZMHVLOWpYQW0zLXBCVTVVY3ZaVzZpNkRQaEVydk9pWG9JLUU5ZXQ1ZEJUQ3hEaGJ0d1ZFS095VlNGQTRIWUgxanRCZWZkSHB0U1daRHpBWWNGOUE?oc=5\" target=\"_blank\">Tubacex no está siendo capaz de acreditar las causas del ERTE</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ELA Sindikatua</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T11:55:08Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "ERE ZEEMAN TEXTIL SUPERS, NUEVA REUNIÓN DE LA MESA NEGOCIADORA - CCOO CAT",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxNVkd3OEhfcGdoZHozRlhnLWU4Mm85QkFyd1pmOUhtclhUSGVmb1BrQUU2SHJaRjNQeGVWRmJ1RFdqZ01XUVljTzQydndic3IwbDdlRzYwOUJiaG93TnRsYzZ5LWVmekZDSkNUWXZtYjIweTlBd3pGeGFLYWUyb3l2NzdmNDdNaG5OMnlrV0xTc0d6ZkxPY1dCcVFkeWplY0k?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMinwFBVV95cUxNVkd3OEhfcGdoZHozRlhnLWU4Mm85QkFyd1pmOUhtclhUSGVmb1BrQUU2SHJaRjNQeGVWRmJ1RFdqZ01XUVljTzQydndic3IwbDdlRzYwOUJiaG93TnRsYzZ5LWVmekZDSkNUWXZtYjIweTlBd3pGeGFLYWUyb3l2NzdmNDdNaG5OMnlrV0xTc0d6ZkxPY1dCcVFkeWplY0k?oc=5\" target=\"_blank\">ERE ZEEMAN TEXTIL SUPERS, NUEVA REUNIÓN DE LA MESA NEGOCIADORA</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">CCOO CAT</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-17T09:47:30Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Magnific (antes Freepik) despide a un centenar de empleados en Málaga: \"Liderar la IA es mantener talento humano\" - Cadena SER",
    "url": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxQLWlFeFRqQkFGQWRIejE3ZnZabXhwT2NLTl9RczllQ0g4ZWtqVnZTbjgxOFBvWnFsa0N2TVA4TEx2Z2RyRnhGeGVEeFY0LXFrQTFXZEw0ZjhDUEc0aWpScjlSTEswdEI4UnZxd3lRRXNYdzRHakpfT0NQNEdUUEtDeHF6UkU0TlRMeGdyWmR5djdPTmZtdlR5RDEzUHlQX2FvRmdOWjJUamRTaGhDc2hVa2RmTFFGSHVyOWlmMjk3RkJ5VS1ULWdKZ0ZBY2N3TjFub2h6V1RwaFZ2TzNHUmN0NUVSR2pzUTM3TktsNk1Sc1fSAYQCQVVfeXFMTTFpckpQRVFhTnBBMkNIYUtLajZLUE92RzZEMkNzSXh6U0VQemZ1X2cwc0JTOW11ZDAwZElwTHhZalU5WERTYjV4anpMNjZDUVBWTjNVLTBCVllNWVYtdEMwZS1rZF91ZDlQQklnaXgwbDRaenFYM05SUHFRckR6czh0YVk4WTU3V0hMRWlKWHIyRm9teFJjempZa0FvWm5semVxSTVxUkpGRlQ4V2ZWQW1DM3o3UmR4SWU0N2R2aHlHcTZzTGFyd1RqdHNFdEI0RHRkVHVWV1Z1V1I5MzdPblRvZUIxWXV6bldTcU9JM2U5emZELUw5V21lM1FaUGgxZTNIUGE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi8AFBVV95cUxQLWlFeFRqQkFGQWRIejE3ZnZabXhwT2NLTl9RczllQ0g4ZWtqVnZTbjgxOFBvWnFsa0N2TVA4TEx2Z2RyRnhGeGVEeFY0LXFrQTFXZEw0ZjhDUEc0aWpScjlSTEswdEI4UnZxd3lRRXNYdzRHakpfT0NQNEdUUEtDeHF6UkU0TlRMeGdyWmR5djdPTmZtdlR5RDEzUHlQX2FvRmdOWjJUamRTaGhDc2hVa2RmTFFGSHVyOWlmMjk3RkJ5VS1ULWdKZ0ZBY2N3TjFub2h6V1RwaFZ2TzNHUmN0NUVSR2pzUTM3TktsNk1Sc1fSAYQCQVVfeXFMTTFpckpQRVFhTnBBMkNIYUtLajZLUE92RzZEMkNzSXh6U0VQemZ1X2cwc0JTOW11ZDAwZElwTHhZalU5WERTYjV4anpMNjZDUVBWTjNVLTBCVllNWVYtdEMwZS1rZF91ZDlQQklnaXgwbDRaenFYM05SUHFRckR6czh0YVk4WTU3V0hMRWlKWHIyRm9teFJjempZa0FvWm5semVxSTVxUkpGRlQ4V2ZWQW1DM3o3UmR4SWU0N2R2aHlHcTZzTGFyd1RqdHNFdEI0RHRkVHVWV1Z1V1I5MzdPblRvZUIxWXV6bldTcU9JM2U5emZELUw5V21lM1FaUGgxZTNIUGE?oc=5\" target=\"_blank\">Magnific (antes Freepik) despide a un centenar de empleados en Málaga: \"Liderar la IA es mantener talento humano\"</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Cadena SER</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-18T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Cadena SER",
    "ubicacion": "Freepik"
  },
  {
    "titulo": "Pascual presenta un ERE para los 80 trabajadores de su fábrica de Gurb (Barcelona) - ABC",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPRkhLS2VUS1Fia1oxSXpnZzZqMDd0M1JGT1JlbHRmN093NG80b2RKU3pDSjdJeVZ1YWFuSUtER0x0SlBmWXRxWkJ0c1VrYVQ5Uk13LVhlT0Y0TnRtQXNYSlNoQUdWejMwMTM0cTA0dHRxc0RoakFwbURXaklMSkpiYnhMOEJxRGJfOFdhX0xqV21DaXF5X2oyVElvVXZrRFBRc0FTRFFGNDRVQ1nSAbABQVVfeXFMUGN2c0hhbkJBZGVoYzV0eGJRZW16YV9uUWgyaDZadzAtSTZlVjIyTVJBTl9OcVpqanNBU29zUEhsWkd6WWNNdHZoejdUWkNYd3U5anVPcmdIZDRCOVdHYkRwbWNLdUI5eFN0YkVOTGwxamJiS2JubERBUk4ybzlJNEppaTdGNXBVc1RGbHR6YVJja0dud1l3WHk2NlYzTm80Tm90UXdJOFdsQTU5QkpYQ0I?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiqwFBVV95cUxPRkhLS2VUS1Fia1oxSXpnZzZqMDd0M1JGT1JlbHRmN093NG80b2RKU3pDSjdJeVZ1YWFuSUtER0x0SlBmWXRxWkJ0c1VrYVQ5Uk13LVhlT0Y0TnRtQXNYSlNoQUdWejMwMTM0cTA0dHRxc0RoakFwbURXaklMSkpiYnhMOEJxRGJfOFdhX0xqV21DaXF5X2oyVElvVXZrRFBRc0FTRFFGNDRVQ1nSAbABQVVfeXFMUGN2c0hhbkJBZGVoYzV0eGJRZW16YV9uUWgyaDZadzAtSTZlVjIyTVJBTl9OcVpqanNBU29zUEhsWkd6WWNNdHZoejdUWkNYd3U5anVPcmdIZDRCOVdHYkRwbWNLdUI5eFN0YkVOTGwxamJiS2JubERBUk4ybzlJNEppaTdGNXBVc1RGbHR6YVJja0dud1l3WHk2NlYzTm80Tm90UXdJOFdsQTU5QkpYQ0I?oc=5\" target=\"_blank\">Pascual presenta un ERE para los 80 trabajadores de su fábrica de Gurb (Barcelona)</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ABC</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T18:16:04Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Gurb"
  }
];