const window_leads_data = [
  {
    "titulo": "BBVA replantea las contrataciones en su área tecnológica ante la incertidumbre de la IA - El Economista",
    "url": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxQb3ZrRDVHaTRSS080aHlXV25reS1hbk9SZktWUlF2WkhCbFZTTWxhWkluY091ck1DRnpJaFFNSGQwb3QtZjAtRFJwNnNYNkRQd1ZLX3RwQzhYcFRLcHV4RVdUOERpNkNibWw1R1BZNlE3SThXc1RuYU1ZcGdTeGZxVVhCbTZEV1lsTE5GcVU3TnUxa2ZOTW9hVVZLTTlyMjlWUkVIdVN3U0VzT2ZHaGxZNlJnT01vUmxTcUxkUm9TYndBcVRjVGJVZktCVjVyRzlZZElpd1lld1UtZE1feTJCVmFSUS00ZDFGUC1aOEdXZkXSAdsBQVVfeXFMTUx1VnJBSXlJanlZWTBMUHFYazBIYzdHV3ZzVE5ETklJamE2MUo4eFAzeFpGenF3c28xWWY5aFV6WjZUdDBJTGhIZkZieVR4Y1dWYnFlaGdOd1ZJTUlFQllQUm05YlF6YlppWHBIV1lwcjVFZ0xfd3FZNmRBQVFvbXNJRERzSTRjd0tiOXE5UElPVlhSZC16MmNiR1Y5VGRYZE5tRGZjMHdZWDhybjFCdkZVSzNpcnhMbEJ5OUFXSkVWZGtrQVpXeGRSWFZTVC0tc2g5TTdHdWp0Q05B?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi8AFBVV95cUxQb3ZrRDVHaTRSS080aHlXV25reS1hbk9SZktWUlF2WkhCbFZTTWxhWkluY091ck1DRnpJaFFNSGQwb3QtZjAtRFJwNnNYNkRQd1ZLX3RwQzhYcFRLcHV4RVdUOERpNkNibWw1R1BZNlE3SThXc1RuYU1ZcGdTeGZxVVhCbTZEV1lsTE5GcVU3TnUxa2ZOTW9hVVZLTTlyMjlWUkVIdVN3U0VzT2ZHaGxZNlJnT01vUmxTcUxkUm9TYndBcVRjVGJVZktCVjVyRzlZZElpd1lld1UtZE1feTJCVmFSUS00ZDFGUC1aOEdXZkXSAdsBQVVfeXFMTUx1VnJBSXlJanlZWTBMUHFYazBIYzdHV3ZzVE5ETklJamE2MUo4eFAzeFpGenF3c28xWWY5aFV6WjZUdDBJTGhIZkZieVR4Y1dWYnFlaGdOd1ZJTUlFQllQUm05YlF6YlppWHBIV1lwcjVFZ0xfd3FZNmRBQVFvbXNJRERzSTRjd0tiOXE5UElPVlhSZC16MmNiR1Y5VGRYZE5tRGZjMHdZWDhybjFCdkZVSzNpcnhMbEJ5OUFXSkVWZGtrQVpXeGRSWFZTVC0tc2g5TTdHdWp0Q05B?oc=5\" target=\"_blank\">BBVA replantea las contrataciones en su área tecnológica ante la incertidumbre de la IA</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Economista</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T04:00:50Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "BBVA",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 23 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPamlXTVFpaVFsX2VCMXM4by1PM0xHOExvUi1MdFNRSDVPNmVTQjlqSFdaa0lEMzhPejM5bzBRUi1BRXVINGY1cWlqZjg2cWFVVG5JRjlIdHRMTmJQQmxiX3l2UUNhTzNnaEF2cGJqWnNHZWx3TjZRSWVxcmZXQkR4TzVMUEJ4a0JXa1JjVFMxN1Y3MjVBWjMtOHZWdUk3TXdNSVJ5NVF6WG9vdFZxRGtBOWVRUzF4Vm9sOEdIOFgyUDh3cUVKM3h3QktfNTBHSVhWUFhJV0hzX2dYei1iTEp6cGEwTFVlZlXSAewBQVVfeXFMUDh0VFhrbi0wVm81dVFyOExnRnAwS1hfWVVsRFNVNTZYMlVnX0xkNXdJaTV0TENOTVJoUkNmeW1qLUpkekpETWhJVUNZWU5TbTkxSVY2S2NJUkJlX0ZMVWQ0LUxoYmN1UW53bWdxNDFjM2YyU3JNdElzckVYZkNqZDE0a0Z4SlJteVNpYlY2Zm5Sc0x1NU1HcDRHTy11Mjgta0tvZGoyY0RuUWZlRmV5ZGVQV1lTdF9UZ3hvX0hWS01oZmFnZU9JdkZqZWlMQ1hpTEczUUlHRE9FaDNCenRtdS12M3djX0lJN3U1c3Y?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPamlXTVFpaVFsX2VCMXM4by1PM0xHOExvUi1MdFNRSDVPNmVTQjlqSFdaa0lEMzhPejM5bzBRUi1BRXVINGY1cWlqZjg2cWFVVG5JRjlIdHRMTmJQQmxiX3l2UUNhTzNnaEF2cGJqWnNHZWx3TjZRSWVxcmZXQkR4TzVMUEJ4a0JXa1JjVFMxN1Y3MjVBWjMtOHZWdUk3TXdNSVJ5NVF6WG9vdFZxRGtBOWVRUzF4Vm9sOEdIOFgyUDh3cUVKM3h3QktfNTBHSVhWUFhJV0hzX2dYei1iTEp6cGEwTFVlZlXSAewBQVVfeXFMUDh0VFhrbi0wVm81dVFyOExnRnAwS1hfWVVsRFNVNTZYMlVnX0xkNXdJaTV0TENOTVJoUkNmeW1qLUpkekpETWhJVUNZWU5TbTkxSVY2S2NJUkJlX0ZMVWQ0LUxoYmN1UW53bWdxNDFjM2YyU3JNdElzckVYZkNqZDE0a0Z4SlJteVNpYlY2Zm5Sc0x1NU1HcDRHTy11Mjgta0tvZGoyY0RuUWZlRmV5ZGVQV1lTdF9UZ3hvX0hWS01oZmFnZU9JdkZqZWlMQ1hpTEczUUlHRE9FaDNCenRtdS12M3djX0lJN3U1c3Y?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 23 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T10:50:19Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "La implementación del nuevo modelo de certificación en el Perú, según la ley 32069 Ley General de Contrataciones Públicas - Observatorio de Contratación Pública",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOWnI3SkdrVGVFTl9GT0E0OEdTd3RNOUZMdm0wMTJfZVluSlFqVDViMFByaER6QVl3TUFZdlpjX2prSjA2SDlFdnQtczRuaHpNVy1wWDIweG1rbUJobWprTXJlcFlablJtZjcyRG1VOFI3QWJPYTc0TWhHQmE1Y0J2OVRUN0pzelVkT2VrdldBT1E2QkZ3bjYtR1JTZUlfMF9HUmZYbWhCWG5LU0F1dldKSw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMisAFBVV95cUxOWnI3SkdrVGVFTl9GT0E0OEdTd3RNOUZMdm0wMTJfZVluSlFqVDViMFByaER6QVl3TUFZdlpjX2prSjA2SDlFdnQtczRuaHpNVy1wWDIweG1rbUJobWprTXJlcFlablJtZjcyRG1VOFI3QWJPYTc0TWhHQmE1Y0J2OVRUN0pzelVkT2VrdldBT1E2QkZ3bjYtR1JTZUlfMF9HUmZYbWhCWG5LU0F1dldKSw?oc=5\" target=\"_blank\">La implementación del nuevo modelo de certificación en el Perú, según la ley 32069 Ley General de Contrataciones Públicas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Observatorio de Contratación Pública</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T07:59:40Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Perú"
  },
  {
    "titulo": "Todas las ofertas de empleo público, en el boletín semanal del Ministerio para la Transformación Digital y de la Función Pública (del 1 al 7 de julio de 2026) - La Administración al Día",
    "url": "https://news.google.com/rss/articles/CBMibEFVX3lxTE1zQ2VXNDB0UkMtTU5FUzhmLTlsUWR3WnpjWEJOQVAtR0tZYnRyaFJGTUwwUUVzanpJaml1RzBicmh1dDJnLWNwb21oR1hrLTZJSHJpWVhGbDNNa24wdXR4elhFcnh3NzJFajVLMg?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMibEFVX3lxTE1zQ2VXNDB0UkMtTU5FUzhmLTlsUWR3WnpjWEJOQVAtR0tZYnRyaFJGTUwwUUVzanpJaml1RzBicmh1dDJnLWNwb21oR1hrLTZJSHJpWVhGbDNNa24wdXR4elhFcnh3NzJFajVLMg?oc=5\" target=\"_blank\">Todas las ofertas de empleo público, en el boletín semanal del Ministerio para la Transformación Digital y de la Función Pública (del 1 al 7 de julio de 2026)</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Administración al Día</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-01T08:54:26Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Función Pública",
    "ubicacion": "Ministerio para la Transformación Digital"
  },
  {
    "titulo": "Accede a ofertas de empleo y a un asesoramiento laboral a través de UGT Castilla-La Mancha - UGT Castilla-La Mancha",
    "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxNOFdWa2RNZ1dVaXl4eGk3Szc2ajEteWhyUkQ5OHZuUEZBVThlYlJGam9UYVBXdWItRm9WTUh5aFp0WkRjMWI0YTlxYm5CYVJSRjVZSDd0LU5EWURwLUcyQS1fakZHd05DTFdOSnBkTkdIdUxUUEV0SDc0ajhoNkFPRkdIVUFaY2MxZk1QdExXR09NLTVkVFhVU1BSMnlsUkp3QzA1NXp1Sm53N3JVUDNQQzA0Z3FnRl81NE0wWXdhMWNlTWN2Z3c?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMixgFBVV95cUxNOFdWa2RNZ1dVaXl4eGk3Szc2ajEteWhyUkQ5OHZuUEZBVThlYlJGam9UYVBXdWItRm9WTUh5aFp0WkRjMWI0YTlxYm5CYVJSRjVZSDd0LU5EWURwLUcyQS1fakZHd05DTFdOSnBkTkdIdUxUUEV0SDc0ajhoNkFPRkdIVUFaY2MxZk1QdExXR09NLTVkVFhVU1BSMnlsUkp3QzA1NXp1Sm53N3JVUDNQQzA0Z3FnRl81NE0wWXdhMWNlTWN2Z3c?oc=5\" target=\"_blank\">Accede a ofertas de empleo y a un asesoramiento laboral a través de UGT Castilla-La Mancha</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">UGT Castilla-La Mancha</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T10:53:20Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "UGT Castilla-La Mancha"
  },
  {
    "titulo": "Las ofertas de empleo en EEUU alcanzan su nivel más alto en dos años, pero la contratación sigue siendo difícil - TradingView",
    "url": "https://news.google.com/rss/articles/CBMid0FVX3lxTE5kQUVEVVl4bTVhQm41V0hnREtxZ1dSdnlsRDNIa1o1QkhvVkZUWGlyb21lSGlDcTBBeVF6cTh3Wk1aSm5lWFY2TmxGUEVNcDlXYS11NGFLSUJUbGZ4N0h6ZjlpWmQxR2kyaXNLemFSeGFaYnJ0clJ3?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMid0FVX3lxTE5kQUVEVVl4bTVhQm41V0hnREtxZ1dSdnlsRDNIa1o1QkhvVkZUWGlyb21lSGlDcTBBeVF6cTh3Wk1aSm5lWFY2TmxGUEVNcDlXYS11NGFLSUJUbGZ4N0h6ZjlpWmQxR2kyaXNLemFSeGFaYnJ0clJ3?oc=5\" target=\"_blank\">Las ofertas de empleo en EEUU alcanzan su nivel más alto en dos años, pero la contratación sigue siendo difícil</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">TradingView</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T18:16:53Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "TradingView",
    "ubicacion": "EEUU"
  },
  {
    "titulo": "Laseme gestiona unas cien ofertas de empleo al año en Tierra Estella - Navarra Capital",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxOS1JHUXE5eFJyMEJfdXlBTEMzdlc0X0RMVDdCdHl2VVh5M19tVXJuZ1N4S2ZzS2o2ZFJMMVdpMndUdHNnMmFSS2pmX1lvT2thcDVhd2Y5WTFlR2ZuWGhTLWxXRUswV2I5RWFXY1FfWURRWnNnS1ZpZjVtNkVwTTJMLXRTRVNEcVhyNUxnX191ZGJ6TlJ6MlM1MWtscw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMimwFBVV95cUxOS1JHUXE5eFJyMEJfdXlBTEMzdlc0X0RMVDdCdHl2VVh5M19tVXJuZ1N4S2ZzS2o2ZFJMMVdpMndUdHNnMmFSS2pmX1lvT2thcDVhd2Y5WTFlR2ZuWGhTLWxXRUswV2I5RWFXY1FfWURRWnNnS1ZpZjVtNkVwTTJMLXRTRVNEcVhyNUxnX191ZGJ6TlJ6MlM1MWtscw?oc=5\" target=\"_blank\">Laseme gestiona unas cien ofertas de empleo al año en Tierra Estella</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Navarra Capital</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-01T11:01:00Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Tierra Estella"
  },
  {
    "titulo": "Málaga contratará un estudio para analizar un nuevo acceso rodado soterrado al puerto - EL MERCANTIL",
    "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxPakd5RnFaQ3dKd1h5VGdUMkZKUm0yN1lhWHVOaHRqVUhrd2FXcnNYYjB0aGlFWlJkazc1Rjlfem5oMy1lemxyQWg5SDZ5bGlSeVdwaXZfMGZQU2VHY3BsZHdsNVZIRGMzU1Rpa3JVaHNINlNIRlRsWkd1Wk9xeU5qWVFKTURDOThKY3pBZ0YxS1EybDRSWVlCTlNHNnlOdVdzaDI1TXdjTnQtZkhjcTB6djRYYVVYSkVIaXlDOFhn?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMivgFBVV95cUxPakd5RnFaQ3dKd1h5VGdUMkZKUm0yN1lhWHVOaHRqVUhrd2FXcnNYYjB0aGlFWlJkazc1Rjlfem5oMy1lemxyQWg5SDZ5bGlSeVdwaXZfMGZQU2VHY3BsZHdsNVZIRGMzU1Rpa3JVaHNINlNIRlRsWkd1Wk9xeU5qWVFKTURDOThKY3pBZ0YxS1EybDRSWVlCTlNHNnlOdVdzaDI1TXdjTnQtZkhjcTB6djRYYVVYSkVIaXlDOFhn?oc=5\" target=\"_blank\">Málaga contratará un estudio para analizar un nuevo acceso rodado soterrado al puerto</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL MERCANTIL</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-24T16:04:03Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Desconocida",
    "ubicacion": "Málaga"
  },
  {
    "titulo": "El nuevo Plan de Empleo Especial de Mérida permitirá 178 contrataciones - Cadena SER",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxQdjBNU1p0cnBDRzg3bVZjM1E0aERHSExWRzBtaTg4LUgycGtKMlJlU2htNXNNN2ZKTnVtWFdvMC1vOERiRmtoTEVIOEFSVDcta09kMXYzaHZxVGd5bGFKXzg2djNhUDVXX3hPSUlQOUJnVW5zalVWVm5SLXVWU2pwVDVmVU5OXzVqRzJYNFJidkREaWZNQ0VHdlVqWEtYVUt0djZ1bU8ySTYyNXNIOEtaTmNxdkR6QVljbzZQdkZzSFU2R2FJVjJn0gHbAUFVX3lxTFBwOFdPZ0lyOHFTdEFsQ3poUDc2UWhkV1VTVnhjN2FmTUFmZ2xlOW1DVlVSMlBHZnFaaDBPZ0FWZms2UnVvbXdWT0xfOTQteHFON2RlbERPdGw0SWdaejVncEdFSXlkY1BHRTdrMzlKdVhYVWo5ajBEQ0ZQMDZzdlRxSUN3RkFFRlFPLWRaUFQyeE1YWWRTOFJPczRmbVRmcDItOE04amtuSld5aFJndWk4WjJWQnd4VlFmYlZyeU9xVk5GaFNOc2lWYUhXSFQyOTZWNVpYb2xOZkZyOA?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMixwFBVV95cUxQdjBNU1p0cnBDRzg3bVZjM1E0aERHSExWRzBtaTg4LUgycGtKMlJlU2htNXNNN2ZKTnVtWFdvMC1vOERiRmtoTEVIOEFSVDcta09kMXYzaHZxVGd5bGFKXzg2djNhUDVXX3hPSUlQOUJnVW5zalVWVm5SLXVWU2pwVDVmVU5OXzVqRzJYNFJidkREaWZNQ0VHdlVqWEtYVUt0djZ1bU8ySTYyNXNIOEtaTmNxdkR6QVljbzZQdkZzSFU2R2FJVjJn0gHbAUFVX3lxTFBwOFdPZ0lyOHFTdEFsQ3poUDc2UWhkV1VTVnhjN2FmTUFmZ2xlOW1DVlVSMlBHZnFaaDBPZ0FWZms2UnVvbXdWT0xfOTQteHFON2RlbERPdGw0SWdaejVncEdFSXlkY1BHRTdrMzlKdVhYVWo5ajBEQ0ZQMDZzdlRxSUN3RkFFRlFPLWRaUFQyeE1YWWRTOFJPczRmbVRmcDItOE04amtuSld5aFJndWk4WjJWQnd4VlFmYlZyeU9xVk5GaFNOc2lWYUhXSFQyOTZWNVpYb2xOZkZyOA?oc=5\" target=\"_blank\">El nuevo Plan de Empleo Especial de Mérida permitirá 178 contrataciones</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Cadena SER</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-24T13:19:58Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Cadena SER",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 25 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPaldoV2lpZFFFQ0pZaS1yaTBsYU5XQjR5TWRmUjJoblNaRFFjZ2xOLWVHV3NmTzBhRl9hbTJRd3FFSVZrN0ptM0t5TTRvblhlS0ptODJwdENuUGVhamItVmpVeXRieEZ5d21ta19vN1ZYWk42bnpXMlF0VGZPdmhTVVQ2X0Z4R0J2UTd4Qm9ic2FMN3VYbnVkallvRVVicHJIWGJXZkFLX1RVbWN5VzNyUG5xa3RIektMQ3lIZFNVc3hCRTJFLUNpd2NGSkpCOFI4TVBDV0xzMFpRMXc5YUZiYlU5czlzT1HSAewBQVVfeXFMUDhVQnRCYmMxNGNFaFZyS09PZXluVTg2T0RUTXBQNFphd2lmcmRsaEtETl9icWdSMWJBLU9Ib0V3a1JhUXNaRmtRWG1vcURleEYyVURLZi1GZ0JRbG0xVVMxMkRWMEl6VjRLSWZXRFBYVHBOZ2VLZDd3QVA1WXh0YnZvd3hPZFFRRzN2UFJsVUZLNTkxenFHOFRDMV82XzRpbEJhZmQtSlN3SnkzRUFuNE1LRlZIZjRLRVdXTGhIMzlFMl9YVmdvdGtBUGtVaDc4aDY3ZnAwZjFzaG1iZ2VKRUJUemNDSWZGd0ZQSjU?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPaldoV2lpZFFFQ0pZaS1yaTBsYU5XQjR5TWRmUjJoblNaRFFjZ2xOLWVHV3NmTzBhRl9hbTJRd3FFSVZrN0ptM0t5TTRvblhlS0ptODJwdENuUGVhamItVmpVeXRieEZ5d21ta19vN1ZYWk42bnpXMlF0VGZPdmhTVVQ2X0Z4R0J2UTd4Qm9ic2FMN3VYbnVkallvRVVicHJIWGJXZkFLX1RVbWN5VzNyUG5xa3RIektMQ3lIZFNVc3hCRTJFLUNpd2NGSkpCOFI4TVBDV0xzMFpRMXc5YUZiYlU5czlzT1HSAewBQVVfeXFMUDhVQnRCYmMxNGNFaFZyS09PZXluVTg2T0RUTXBQNFphd2lmcmRsaEtETl9icWdSMWJBLU9Ib0V3a1JhUXNaRmtRWG1vcURleEYyVURLZi1GZ0JRbG0xVVMxMkRWMEl6VjRLSWZXRFBYVHBOZ2VLZDd3QVA1WXh0YnZvd3hPZFFRRzN2UFJsVUZLNTkxenFHOFRDMV82XzRpbEJhZmQtSlN3SnkzRUFuNE1LRlZIZjRLRVdXTGhIMzlFMl9YVmdvdGtBUGtVaDc4aDY3ZnAwZjFzaG1iZ2VKRUJUemNDSWZGd0ZQSjU?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 25 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T11:32:26Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 30 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxOM21vdEtBVnZtY3Y2U0FtczhYdXh0NXl2QXMxSDE1dXJ1X3dyR1NTZGlYTE9lV2cyNFlMc3BYWHMtTnptN2ZaS0hHYWphcjlfLUttT3lqTlZQUENkSm9RdmZQYWQ5MUdCUUlQU1dlNHFvQ0dqOE5vcXktajlpU3JXTl9HaV81R0VINEtpYXVvdm5TODFKWHp4TFVheXpJRC1vMlFGWDZ1RnJFcml6Y0RfVjNxQ2ZXektkRl9QRXFpUzRtTnVQQWtvWDRJU0JuMTA2dk9rZldrb091X3hHZUt4TElxZHNQTE3SAewBQVVfeXFMTnNoLVFCbEJOSHVFSDlCblFSNm9GVjJFU3ZrY3NXZmtaanpsMHhRVHNWYnhIdUpESnk0TVNrLXduZDhlS2wzQmd2bS1OY3dlODJxanc2a1hoS0dNRmQ4UHZYaElza2hwYVJNUW9xaW1XdWRMOF9XNk5IZnp5TVpyVlljc1dhWDlfQ2xDdDhiMDlwakF0YmRhSDFMb192MURvdEVBMHRVOWhYOFVuVXhmWkpLTDBSSDJRZ3VnWk5kVDNqc2x5YmNKaEZNcUtxRWs0VjlES1VEU1RzQUZNOXc0LVh4VmVONGE2YzNUYS0?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxOM21vdEtBVnZtY3Y2U0FtczhYdXh0NXl2QXMxSDE1dXJ1X3dyR1NTZGlYTE9lV2cyNFlMc3BYWHMtTnptN2ZaS0hHYWphcjlfLUttT3lqTlZQUENkSm9RdmZQYWQ5MUdCUUlQU1dlNHFvQ0dqOE5vcXktajlpU3JXTl9HaV81R0VINEtpYXVvdm5TODFKWHp4TFVheXpJRC1vMlFGWDZ1RnJFcml6Y0RfVjNxQ2ZXektkRl9QRXFpUzRtTnVQQWtvWDRJU0JuMTA2dk9rZldrb091X3hHZUt4TElxZHNQTE3SAewBQVVfeXFMTnNoLVFCbEJOSHVFSDlCblFSNm9GVjJFU3ZrY3NXZmtaanpsMHhRVHNWYnhIdUpESnk0TVNrLXduZDhlS2wzQmd2bS1OY3dlODJxanc2a1hoS0dNRmQ4UHZYaElza2hwYVJNUW9xaW1XdWRMOF9XNk5IZnp5TVpyVlljc1dhWDlfQ2xDdDhiMDlwakF0YmRhSDFMb192MURvdEVBMHRVOWhYOFVuVXhmWkpLTDBSSDJRZ3VnWk5kVDNqc2x5YmNKaEZNcUtxRWs0VjlES1VEU1RzQUZNOXc0LVh4VmVONGE2YzNUYS0?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 30 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T11:30:43Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo de Madrid Trabaja 27.06.2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxPRDl1Q0h1RmxsWHhCcXFpV0RLazB0amF4Mk9PYnB1UW4tX2NPaDhOQlFFclRwMFNKUTdWdVV1UGhhZ0t0czJGV0l4S09CcjF6M1JzQWl6R0FQd0NTMDdOU1hTdk9WMl8wLXhFNzRXZk5wS2xmTmlpczZha0pjeFNoNDNUUEZIem1qM1dHdWVEQWktUlJha1VjbFQyYURPdFZBZnZ4aXhsdG40dnFjeS1YMVJNX2xtRmRLNWgzZHM0eVcyUGFlNjZBaNIBzgFBVV95cUxPV3NIMUQ2dm96dXJDMV9yczBxSEtvbG1qMWJ1WHFuNHBXOERyc3pBeS01ZXVyaFgyWkpXUzhsZkRrRk5nelBja2oxdFEwUjgwMFE4MkgybEVLWEdrTVlLQktUcnpyekdQbGhtdUpyS2JLZm40Rlh3TC1oUFYzb0c5S1NwWU5aUTVJazA1S0UySTVsTkZvcUczU1NHdWxtakhJQW5pX3dkX2dIcTlDUV91SEk4UmlYV0RqVGt6N2hmSnJPNExoZGYtMWxreUE3QQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiyAFBVV95cUxPRDl1Q0h1RmxsWHhCcXFpV0RLazB0amF4Mk9PYnB1UW4tX2NPaDhOQlFFclRwMFNKUTdWdVV1UGhhZ0t0czJGV0l4S09CcjF6M1JzQWl6R0FQd0NTMDdOU1hTdk9WMl8wLXhFNzRXZk5wS2xmTmlpczZha0pjeFNoNDNUUEZIem1qM1dHdWVEQWktUlJha1VjbFQyYURPdFZBZnZ4aXhsdG40dnFjeS1YMVJNX2xtRmRLNWgzZHM0eVcyUGFlNjZBaNIBzgFBVV95cUxPV3NIMUQ2dm96dXJDMV9yczBxSEtvbG1qMWJ1WHFuNHBXOERyc3pBeS01ZXVyaFgyWkpXUzhsZkRrRk5nelBja2oxdFEwUjgwMFE4MkgybEVLWEdrTVlLQktUcnpyekdQbGhtdUpyS2JLZm40Rlh3TC1oUFYzb0c5S1NwWU5aUTVJazA1S0UySTVsTkZvcUczU1NHdWxtakhJQW5pX3dkX2dIcTlDUV91SEk4UmlYV0RqVGt6N2hmSnJPNExoZGYtMWxreUE3QQ?oc=5\" target=\"_blank\">Ofertas de empleo de Madrid Trabaja 27.06.2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-27T07:15:00Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 01 de julio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPb0xVYXlLWjdhbGJVV1M4LWlVT1pTelpXa3lYR0p6N3hTY3hiQ1R1YklidTJ6eGNyMVN2M0paZjVucUlaLUNwbWlaNkJ4b2d0MWlPMjJVd0FKaklfQTNyajV1Y2Q1M1p1YnhGekszdU5UZ3BKNjJzRFJMUUZLQXBXRElnWW1BYTRJdG93RUdRaVZ2eHhwYzczamVLQ3lha3BqTjRaV2xjVXZKb0RBbkd4cGNjb1VycHA1dzRScy1iV1VtRWdzMEVuMWVXQnhFQzhONUl4eU1WU2NaQmtkRXB3eVlTTXB5Q1nSAewBQVVfeXFMTzVBRUZlZjVDbzZqcWtTNGw5cG82YWMyQlhrZGstMGZ6MFJ4d0FwWm5JYWtPMUE4QVdWY1NGQzJfWFNtNEJBUWFFOURKVTlzcXpQVGF1R1FhUFJfRXdERmRwTkFzT29WR0R3Z1dQbHBLWGQ5MmpvMExuYXVhTF9JWlV6MHRFUkNqNXMyY0NxWnBkLXRRYWVHWnJnbW5tVFFzQUs5RS1sOVM5TDlHcU1XbHgwR0pQTUxQV3dCTDVlYUhfRUtYNFFsSk1IMjNGTFBWVTdtUkN2WFN6S2JhQ29vejdFVkRfS2ZlQzZDZFo?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPb0xVYXlLWjdhbGJVV1M4LWlVT1pTelpXa3lYR0p6N3hTY3hiQ1R1YklidTJ6eGNyMVN2M0paZjVucUlaLUNwbWlaNkJ4b2d0MWlPMjJVd0FKaklfQTNyajV1Y2Q1M1p1YnhGekszdU5UZ3BKNjJzRFJMUUZLQXBXRElnWW1BYTRJdG93RUdRaVZ2eHhwYzczamVLQ3lha3BqTjRaV2xjVXZKb0RBbkd4cGNjb1VycHA1dzRScy1iV1VtRWdzMEVuMWVXQnhFQzhONUl4eU1WU2NaQmtkRXB3eVlTTXB5Q1nSAewBQVVfeXFMTzVBRUZlZjVDbzZqcWtTNGw5cG82YWMyQlhrZGstMGZ6MFJ4d0FwWm5JYWtPMUE4QVdWY1NGQzJfWFNtNEJBUWFFOURKVTlzcXpQVGF1R1FhUFJfRXdERmRwTkFzT29WR0R3Z1dQbHBLWGQ5MmpvMExuYXVhTF9JWlV6MHRFUkNqNXMyY0NxWnBkLXRRYWVHWnJnbW5tVFFzQUs5RS1sOVM5TDlHcU1XbHgwR0pQTUxQV3dCTDVlYUhfRUtYNFFsSk1IMjNGTFBWVTdtUkN2WFN6S2JhQ29vejdFVkRfS2ZlQzZDZFo?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 01 de julio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-01T11:45:58Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 29 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPOHR5RHhFbmNoeHpkZ2JOOGF5V1ZNa0dwTFlmTnltaGlldU5oRzkzM1dEaFowclNxM2lzT04yV1Y3S3RSdlMydXpoaE13UGhkZ1dxallwcWxuVnBHRnBSOW5IUUFKNk9zUFc5T1JhSXQ5TTdUYWJ2YTAzZEZvbW1pdmpqbTBvZmJCX1lxUzlRQlZpRFhYZk1yMmhNaGc0YUtmQ011ejhIZl8xSW1GWlEyZWtib09aNFNpT0FseU9ETHhVUjNwZERHcjI1QTFabmlTRGRHbXM3MFpTQUJvbWdlVWlfZDFiXzTSAewBQVVfeXFMTUQzSEQxRjRTYjYwMF9mSUp2S1NHcS1sX0RYaXVZQ0txbXBlYkE5bDN4b1VvQlZ0aEFaQ0dpSFpCSVdzaDJwV2MyUkNpbkZvU21XTVhIdVZCc2xldE9nZ3ZIOGE3ZWlLellPYmxxLXdPMTBPLUNvYzYxUUMxV1pqSHBFcXE5OVZWYmtYY251QUJCWlY4Sm9rQ3NfeW5tWXRVdkx6YV9xX1N4Qi1SZkhuellnV281WnJlMWJTcWRwNUJzbVhYRFpDS25zMmFZMTBVc0F3Mjd6TGk2SlNRaFBRak0zbWRzQTQzLW90Z3A?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxPOHR5RHhFbmNoeHpkZ2JOOGF5V1ZNa0dwTFlmTnltaGlldU5oRzkzM1dEaFowclNxM2lzT04yV1Y3S3RSdlMydXpoaE13UGhkZ1dxallwcWxuVnBHRnBSOW5IUUFKNk9zUFc5T1JhSXQ5TTdUYWJ2YTAzZEZvbW1pdmpqbTBvZmJCX1lxUzlRQlZpRFhYZk1yMmhNaGc0YUtmQ011ejhIZl8xSW1GWlEyZWtib09aNFNpT0FseU9ETHhVUjNwZERHcjI1QTFabmlTRGRHbXM3MFpTQUJvbWdlVWlfZDFiXzTSAewBQVVfeXFMTUQzSEQxRjRTYjYwMF9mSUp2S1NHcS1sX0RYaXVZQ0txbXBlYkE5bDN4b1VvQlZ0aEFaQ0dpSFpCSVdzaDJwV2MyUkNpbkZvU21XTVhIdVZCc2xldE9nZ3ZIOGE3ZWlLellPYmxxLXdPMTBPLUNvYzYxUUMxV1pqSHBFcXE5OVZWYmtYY251QUJCWlY4Sm9rQ3NfeW5tWXRVdkx6YV9xX1N4Qi1SZkhuellnV281WnJlMWJTcWRwNUJzbVhYRFpDS25zMmFZMTBVc0F3Mjd6TGk2SlNRaFBRak0zbWRzQTQzLW90Z3A?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 29 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T12:37:14Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Ofertas de empleo en la Comunidad de Madrid del 24 de junio de 2026 - Telemadrid",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxNRmd0SHhzNDhMMkhqNk9RYzlzendsNWtfd2U3ZHRfZC1fS20zMjAxZEVta3N4UWdpYjhQcDhhMnVHRlFUOTNhOUROaDQxMzliVXBnTE9ULXRLUzRMRjF1RkFtTk5BX3pSdUNUd3F4YWlxYUwyTm9TZVBfUWdZYmxsTFIxdUVsYVIxWnpKZVA2QVZHaXFidTVxOUpuX2lrMFROZENKelNRMlgtX1dzem5ycE9HblFySnU4cFEyWFN5MTFjWHg2TG9SNFNZUXJGOHVZekJyT2hwa2ozTFA2ZzhTR0lhUUZKZkXSAewBQVVfeXFMT29HeVhVX2dsSVN5cHFzZmVUb1VEVHpCc2MwNGFGNnRTbGlNS3ZxWjU4RkNIVnJEaXR4am1ub1U0eF9uSU9tUnpxZHM4aG1JaHU3RmZDUG12MFVpQ2E4c2loOHlyZTU1bHJCRlBkQ01rVlhGZTdvUzZxWHRud0FMTVN2Um1tcFhNVWJiT1Fablhmd2xwWkFtWFJvcjVqa0dyR21sdEp2NmphZDg0NHVoWWRsblNYem9ROVJIbm8tTDNqNWdmZFpYdlltaVN6eXc2bm5CaERkSWgwdlJsODg2WkJPRGVNSG1la0tyX1Y?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi5wFBVV95cUxNRmd0SHhzNDhMMkhqNk9RYzlzendsNWtfd2U3ZHRfZC1fS20zMjAxZEVta3N4UWdpYjhQcDhhMnVHRlFUOTNhOUROaDQxMzliVXBnTE9ULXRLUzRMRjF1RkFtTk5BX3pSdUNUd3F4YWlxYUwyTm9TZVBfUWdZYmxsTFIxdUVsYVIxWnpKZVA2QVZHaXFidTVxOUpuX2lrMFROZENKelNRMlgtX1dzem5ycE9HblFySnU4cFEyWFN5MTFjWHg2TG9SNFNZUXJGOHVZekJyT2hwa2ozTFA2ZzhTR0lhUUZKZkXSAewBQVVfeXFMT29HeVhVX2dsSVN5cHFzZmVUb1VEVHpCc2MwNGFGNnRTbGlNS3ZxWjU4RkNIVnJEaXR4am1ub1U0eF9uSU9tUnpxZHM4aG1JaHU3RmZDUG12MFVpQ2E4c2loOHlyZTU1bHJCRlBkQ01rVlhGZTdvUzZxWHRud0FMTVN2Um1tcFhNVWJiT1Fablhmd2xwWkFtWFJvcjVqa0dyR21sdEp2NmphZDg0NHVoWWRsblNYem9ROVJIbm8tTDNqNWdmZFpYdlltaVN6eXc2bm5CaERkSWgwdlJsODg2WkJPRGVNSG1la0tyX1Y?oc=5\" target=\"_blank\">Ofertas de empleo en la Comunidad de Madrid del 24 de junio de 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Telemadrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-24T10:18:47Z",
    "fuente": "Contratación Directa",
    "categoria": "Contratacion",
    "empresa": "Telemadrid",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "Video de apertura de plicas - Ayuntamiento de Madrid",
    "url": "https://news.google.com/rss/articles/CBMi6gJBVV95cUxPdXhkT1FIbUNOUnZXTGowM3FRNWxVR2tHZUNKaWVlaFBaR0o5bnRhcTlGSlJycUNZdTh6QnpxWmNXdTJkRUZvenN2X3RWMEwwR1ppNWtZUHI0ZlJrU2JIU2NRY0xKdEgyMXQwbWFUcHBkaTJyVmI4ajJ6NVdQOUx3R3JkM25zZXRGems4YUxzbUx5WUEtaW9CMnYxS3RadnptemQwQjdoNzc1bUlSUlZJUWNid2VGeXRsYnZMOThnZmtjRFM3WVRoZjlwT1hxNmNwQlpkQXZrRHRpaExrZllDaXRjcnVENjRBekxrRkJ4Sy1rX2UzN3B3bHNYYk84eUNsbjJtYTlySnhOc2NNR0tHQnljWmdxbHZwVU5hbEpUMGc3Q1pmZGlHclh4T0ZDME5xa3M2emxjV0E5Zm1Gc3hubFAyUDZvM0NXVGppUWVRTzZZMUlwMEdOZHZBTEd0eTF0aW5zZ2NlUHFVZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6gJBVV95cUxPdXhkT1FIbUNOUnZXTGowM3FRNWxVR2tHZUNKaWVlaFBaR0o5bnRhcTlGSlJycUNZdTh6QnpxWmNXdTJkRUZvenN2X3RWMEwwR1ppNWtZUHI0ZlJrU2JIU2NRY0xKdEgyMXQwbWFUcHBkaTJyVmI4ajJ6NVdQOUx3R3JkM25zZXRGems4YUxzbUx5WUEtaW9CMnYxS3RadnptemQwQjdoNzc1bUlSUlZJUWNid2VGeXRsYnZMOThnZmtjRFM3WVRoZjlwT1hxNmNwQlpkQXZrRHRpaExrZllDaXRjcnVENjRBekxrRkJ4Sy1rX2UzN3B3bHNYYk84eUNsbjJtYTlySnhOc2NNR0tHQnljWmdxbHZwVU5hbEpUMGc3Q1pmZGlHclh4T0ZDME5xa3M2emxjV0E5Zm1Gc3hubFAyUDZvM0NXVGppUWVRTzZZMUlwMEdOZHZBTEd0eTF0aW5zZ2NlUHFVZw?oc=5\" target=\"_blank\">Video de apertura de plicas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Ayuntamiento de Madrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-21T16:07:43Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento de Madrid"
  },
  {
    "titulo": "Osalan inaugura su Curso de Verano sobre trabajo digno y prevención de riesgos laborales - Euskadi.eus",
    "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxQYWw1MV9wWVh3MF9XbkN3NUtqM1I4bkpSRWFveEZVVzhqN25ONURTVGwwdjNKVi02a2ZIczhVYVpNbWhfUFRKNGZYVjgxUlRaUFM2VkVlTzF2M0swU1A0VWxDaWNZWEtvbjVodHZFYWcwQTBYWWNSQTdTbVpFZ3F3Z2R0VmhINGRPbkhRd25aMFFHWkNPZnNkU0hveVBwYWZCNGlVeXhaVlZQT0xuTE90Xy1mYmFCV0d2MWpKNDFZMTdDaGtMWkVuTC1ERQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxQYWw1MV9wWVh3MF9XbkN3NUtqM1I4bkpSRWFveEZVVzhqN25ONURTVGwwdjNKVi02a2ZIczhVYVpNbWhfUFRKNGZYVjgxUlRaUFM2VkVlTzF2M0swU1A0VWxDaWNZWEtvbjVodHZFYWcwQTBYWWNSQTdTbVpFZ3F3Z2R0VmhINGRPbkhRd25aMFFHWkNPZnNkU0hveVBwYWZCNGlVeXhaVlZQT0xuTE90Xy1mYmFCV0d2MWpKNDFZMTdDaGtMWkVuTC1ERQ?oc=5\" target=\"_blank\">Osalan inaugura su Curso de Verano sobre trabajo digno y prevención de riesgos laborales</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Euskadi.eus</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T07:00:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Osalan"
  },
  {
    "titulo": "Así será la nueva fábrica de MG en Galicia, que dará empleo a 1.000 trabajadores - forococheselectricos.com",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxNb056RFZncmZudHNEZW1WekQ5c2JOQXIzUnc5VDNKMEJPdGdYNThtbjdyMWhoWldrdVB3TlMzZWZ5TTg3dzRmSTN1bDhjb1pmZGFzUjVrWnRMSWtyTE9pMnlPSkY1RWE3a3oxUVVoc1FyLUFmbzU2VFkyTlZZVVdNZ2hnSTJXQmtVREgzd3JTeDk4OHBfUlAwSVlnRXpTTFE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMinwFBVV95cUxNb056RFZncmZudHNEZW1WekQ5c2JOQXIzUnc5VDNKMEJPdGdYNThtbjdyMWhoWldrdVB3TlMzZWZ5TTg3dzRmSTN1bDhjb1pmZGFzUjVrWnRMSWtyTE9pMnlPSkY1RWE3a3oxUVVoc1FyLUFmbzU2VFkyTlZZVVdNZ2hnSTJXQmtVREgzd3JTeDk4OHBfUlAwSVlnRXpTTFE?oc=5\" target=\"_blank\">Así será la nueva fábrica de MG en Galicia, que dará empleo a 1.000 trabajadores</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">forococheselectricos.com</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T07:48:19Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "MG"
  },
  {
    "titulo": "El Ibex 35 se aferra a los 19.400 puntos antes del dato de empleo de EEUU - Estrategias de Inversión",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxPWjRzVURNRWttanVneW1FYXBZSFYtRzVfUHM3Q3hQVVZ4RHJuM0tCeHVpNzAxREIwWjJ0MkdDZWI0XzZ4VVZBSm5USEI2NW9nU2s2RGZyUTJkdjljQzFBNk5GM2ZtTzZMc05wOFc1Ykh5b3k0TUtPbVVReGlCSlpBczZzWGtFX09GTnlaaTc0a3pDVWRJallpc0ZILTJTZ9IBngFBVV95cUxPWjRzVURNRWttanVneW1FYXBZSFYtRzVfUHM3Q3hQVVZ4RHJuM0tCeHVpNzAxREIwWjJ0MkdDZWI0XzZ4VVZBSm5USEI2NW9nU2s2RGZyUTJkdjljQzFBNk5GM2ZtTzZMc05wOFc1Ykh5b3k0TUtPbVVReGlCSlpBczZzWGtFX09GTnlaaTc0a3pDVWRJallpc0ZILTJTZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMingFBVV95cUxPWjRzVURNRWttanVneW1FYXBZSFYtRzVfUHM3Q3hQVVZ4RHJuM0tCeHVpNzAxREIwWjJ0MkdDZWI0XzZ4VVZBSm5USEI2NW9nU2s2RGZyUTJkdjljQzFBNk5GM2ZtTzZMc05wOFc1Ykh5b3k0TUtPbVVReGlCSlpBczZzWGtFX09GTnlaaTc0a3pDVWRJallpc0ZILTJTZ9IBngFBVV95cUxPWjRzVURNRWttanVneW1FYXBZSFYtRzVfUHM3Q3hQVVZ4RHJuM0tCeHVpNzAxREIwWjJ0MkdDZWI0XzZ4VVZBSm5USEI2NW9nU2s2RGZyUTJkdjljQzFBNk5GM2ZtTzZMc05wOFc1Ykh5b3k0TUtPbVVReGlCSlpBczZzWGtFX09GTnlaaTc0a3pDVWRJallpc0ZILTJTZw?oc=5\" target=\"_blank\">El Ibex 35 se aferra a los 19.400 puntos antes del dato de empleo de EEUU</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Estrategias de Inversión</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-02T07:00:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "EEUU"
  },
  {
    "titulo": "La nueva fábrica de Leapmotor en Mallén (Zaragoza) producirá unas 60.000 baterías al año y dará empleo a 90 personas - Europa Press",
    "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxPalRfTVJsQXUzZFE3U1prdUR0am1xaUs4RWlzeDBfYi1WWGVfMHV6WGNBRXV5VmotN2d4M2RuZzFoZm8wZU12V3pGaW5xVlpvQmtiMUZpd3BmT2RzeFgxQWZoNUJ2bEg3MThCaVdOLUVXMktSRUV2TXVhZUd3X0dGTnlybzgtWnZ0NzBCUlJEVGVEV1ZsYUcyNU13RTlLNDl0bzZQaVFMazNzUWtFRDVzYWNIWm1mX2dDV2swekk5cVgxWnpzaEZmV2wwelZobm8xekFyRTJSLTlHZU41TzRzaEtBelBnMl9nXy1DUkt5VkF3VGRKUEhuUmFn?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi-gFBVV95cUxPalRfTVJsQXUzZFE3U1prdUR0am1xaUs4RWlzeDBfYi1WWGVfMHV6WGNBRXV5VmotN2d4M2RuZzFoZm8wZU12V3pGaW5xVlpvQmtiMUZpd3BmT2RzeFgxQWZoNUJ2bEg3MThCaVdOLUVXMktSRUV2TXVhZUd3X0dGTnlybzgtWnZ0NzBCUlJEVGVEV1ZsYUcyNU13RTlLNDl0bzZQaVFMazNzUWtFRDVzYWNIWm1mX2dDV2swekk5cVgxWnpzaEZmV2wwelZobm8xekFyRTJSLTlHZU41TzRzaEtBelBnMl9nXy1DUkt5VkF3VGRKUEhuUmFn?oc=5\" target=\"_blank\">La nueva fábrica de Leapmotor en Mallén (Zaragoza) producirá unas 60.000 baterías al año y dará empleo a 90 personas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Europa Press</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T12:02:40Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Mallén"
  },
  {
    "titulo": "Lidl impulsa su presencia en Gipuzkoa con la convocatoria de 13 vacantes de liderazgo y gestión para sus tiendas - Lidl España",
    "url": "https://news.google.com/rss/articles/CBMiggJBVV95cUxPYzBUVi1DeU1VODl3U2ZHdHp6Rm81WHRfaVlxR3Vpb0lhMXhxTnpUNk5wc1d1cElWNEZGOHJXeW5IV1RaaWx5OEI1bW1GWTdZSFVFYzlyUW5tQmtLX3JVSHpjODdMSFhrbEZEZ082UU9fSHNXc0lyVXpiRFRLeUtBN2dmWEY4aUdzV0JfZUhkVW44SlZSVGhpX3I0Uzhfc1FyZlBlT0huSW5pSzd0TnltR3FEcG5Db2o0Vy1KM05uYXl1cXdYU2dPbl8xQ0t3RjRjaDBPUlYyc1h4c1lHNmw1NTR3TFpCSE5kcUxSM3AyRDdrdFZvcXJRZU9rUnFBWmJHeWc?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiggJBVV95cUxPYzBUVi1DeU1VODl3U2ZHdHp6Rm81WHRfaVlxR3Vpb0lhMXhxTnpUNk5wc1d1cElWNEZGOHJXeW5IV1RaaWx5OEI1bW1GWTdZSFVFYzlyUW5tQmtLX3JVSHpjODdMSFhrbEZEZ082UU9fSHNXc0lyVXpiRFRLeUtBN2dmWEY4aUdzV0JfZUhkVW44SlZSVGhpX3I0Uzhfc1FyZlBlT0huSW5pSzd0TnltR3FEcG5Db2o0Vy1KM05uYXl1cXdYU2dPbl8xQ0t3RjRjaDBPUlYyc1h4c1lHNmw1NTR3TFpCSE5kcUxSM3AyRDdrdFZvcXJRZU9rUnFBWmJHeWc?oc=5\" target=\"_blank\">Lidl impulsa su presencia en Gipuzkoa con la convocatoria de 13 vacantes de liderazgo y gestión para sus tiendas</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Lidl España</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-18T22:57:54Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Gipuzkoa"
  },
  {
    "titulo": "Consum abre una nueva tienda en Almería y avanza en su plan de dieciocho aperturas en 2026 - El Conciso",
    "url": "https://news.google.com/rss/articles/CBMiigFBVV95cUxQdlh5Z1o2eWhVc0VhYUZreEJPb2NoUUtrMHQyM29oeTNyX252WHA2T29Nd0VQY1ZxQzVIS2psTmtsQnZNSFliOFNtdlF1bHQzNXd3OFp2dmZuRTlZZDI3dTFHUWdueHVqM3lKaEt0NkJzS2xfR0x4ODdoWTVvMzFlWTlKa3NHTUEzM3fSAY8BQVVfeXFMUFFRcTJ4clNrOS13LWw1aTJGNVJRMFpGd3g1SG00d2xLOVRWREpnRDJYOGtnbWo2c1JvSXl6S18zcjk2MEJYVmpEejUwemE3N2JZS0Fnc2xGT2J6TFVSMERQZzdWbXZ4N3ZKV0E1bUtXZXhudXl4UEdlbFYtZ3FZTU5xaUxQLXVwWEl3LVROVms?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiigFBVV95cUxQdlh5Z1o2eWhVc0VhYUZreEJPb2NoUUtrMHQyM29oeTNyX252WHA2T29Nd0VQY1ZxQzVIS2psTmtsQnZNSFliOFNtdlF1bHQzNXd3OFp2dmZuRTlZZDI3dTFHUWdueHVqM3lKaEt0NkJzS2xfR0x4ODdoWTVvMzFlWTlKa3NHTUEzM3fSAY8BQVVfeXFMUFFRcTJ4clNrOS13LWw1aTJGNVJRMFpGd3g1SG00d2xLOVRWREpnRDJYOGtnbWo2c1JvSXl6S18zcjk2MEJYVmpEejUwemE3N2JZS0Fnc2xGT2J6TFVSMERQZzdWbXZ4N3ZKV0E1bUtXZXhudXl4UEdlbFYtZ3FZTU5xaUxQLXVwWEl3LVROVms?oc=5\" target=\"_blank\">Consum abre una nueva tienda en Almería y avanza en su plan de dieciocho aperturas en 2026</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Conciso</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T10:04:15Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Obramat inaugura en Churra su segundo almacén en la Región de Murcia - Interempresas.net",
    "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxQNnJHaWdYTnRJUktzakdFQWJwUC00ZXhVSGR4VTE0YkFqS3dqVVA5dmd3WGlwYmNXWEI1QlpsVmRETWRuRkJXc1N1NnRzWl9QRE9QbFFxcXB5VW9QYU5hMzZTQTY5NDcxd2Y4OFpyWG5za1E0TzJjNFprNUxsU1JzLUVKYWdQRHcyM3JKTV9USzA4MXlvazVZMGsyaVZZU0xsT0xYaWc2aDhMU1I1eEFQS2xpSUhlQkFRd2tzdjVoWWJCLUxSUXVrcGxsd0hoYzJ0MS1faXhrQzJMR1lE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi3AFBVV95cUxQNnJHaWdYTnRJUktzakdFQWJwUC00ZXhVSGR4VTE0YkFqS3dqVVA5dmd3WGlwYmNXWEI1QlpsVmRETWRuRkJXc1N1NnRzWl9QRE9QbFFxcXB5VW9QYU5hMzZTQTY5NDcxd2Y4OFpyWG5za1E0TzJjNFprNUxsU1JzLUVKYWdQRHcyM3JKTV9USzA4MXlvazVZMGsyaVZZU0xsT0xYaWc2aDhMU1I1eEFQS2xpSUhlQkFRd2tzdjVoWWJCLUxSUXVrcGxsd0hoYzJ0MS1faXhrQzJMR1lE?oc=5\" target=\"_blank\">Obramat inaugura en Churra su segundo almacén en la Región de Murcia</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Interempresas.net</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T12:23:36Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Obramat"
  },
  {
    "titulo": "Leche Pascual presenta un ERE para los 80 trabajadores de su planta de Gurb (Barcelona) - EL PAÍS",
    "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQa2F6bnZSNmxhZ2JnRW5ZdE1OMlF2VmtacDR6VXRMSGpFTE02cG9ONmxaQno4WndBdm5mYmlKeWRxUGxneE9pR21mQVdDVm5YUmJpRDNyMXl2QlhYTkwwTDhpakxnNVBEai1TUHVlNTljeElyM01DdUFnWkYyZklid3E3RHVNTUtpX1FXeHkwbHN3TjJ3RzlCZ1duNEFQQU5sUlNCdWVJWUdoa0k4cllaRDh0bDdmcFZpZmpaUG0xZ19ETVJ0ZDM0REZmaHp4aTdJM1RJ0gHnAUFVX3lxTFBEUGVVU3ViNll1WFlkVVIwQVEwX1BtTG1pbjYxaGJSRzZJUFltTGJPc3B5TVByeTBnYmJMQjVac0JIM3VocDBPSThOTWctanFmVV9oVFBGaWZxSnowRXBXaUlBUEVCbEpBN2VFWlZHSlZwNU9oc243NFY5QV8tQ2tyTnFTZkwxdlFiZE1Vak40clZBQ0lMZWU0cTF1d1lBWWlQcVgyMlBTV0hpNDhKdUJzeHVkOWt3RXpqb3hfTEpSWE1zTWVsOWNNSVhuUlFnU1hKN09hbnBoUi1vTWgtaUlQOUE5UnJjaw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi0wFBVV95cUxQa2F6bnZSNmxhZ2JnRW5ZdE1OMlF2VmtacDR6VXRMSGpFTE02cG9ONmxaQno4WndBdm5mYmlKeWRxUGxneE9pR21mQVdDVm5YUmJpRDNyMXl2QlhYTkwwTDhpakxnNVBEai1TUHVlNTljeElyM01DdUFnWkYyZklid3E3RHVNTUtpX1FXeHkwbHN3TjJ3RzlCZ1duNEFQQU5sUlNCdWVJWUdoa0k4cllaRDh0bDdmcFZpZmpaUG0xZ19ETVJ0ZDM0REZmaHp4aTdJM1RJ0gHnAUFVX3lxTFBEUGVVU3ViNll1WFlkVVIwQVEwX1BtTG1pbjYxaGJSRzZJUFltTGJPc3B5TVByeTBnYmJMQjVac0JIM3VocDBPSThOTWctanFmVV9oVFBGaWZxSnowRXBXaUlBUEVCbEpBN2VFWlZHSlZwNU9oc243NFY5QV8tQ2tyTnFTZkwxdlFiZE1Vak40clZBQ0lMZWU0cTF1d1lBWWlQcVgyMlBTV0hpNDhKdUJzeHVkOWt3RXpqb3hfTEpSWE1zTWVsOWNNSVhuUlFnU1hKN09hbnBoUi1vTWgtaUlQOUE5UnJjaw?oc=5\" target=\"_blank\">Leche Pascual presenta un ERE para los 80 trabajadores de su planta de Gurb (Barcelona)</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL PAÍS</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T11:43:59Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "ERE",
    "ubicacion": "Gurb"
  },
  {
    "titulo": "Wall Street retrocede antes de la apertura a la espera de datos clave de empleo y de la intervención de Kevin Warsh - MarketScreener España",
    "url": "https://news.google.com/rss/articles/CBMi7AFBVV95cUxNZjR2SFRTTU5ycnotblZYVHByN2Rza04yZ09rQ2JXZGREcUZ6dm9pMWpXMmVVeEVvU2ZfRWNDR1VfaHZmcFBDUEV5eDZkeWdMMTVCRmJ6aG4yMzRaNmVmMUJfWTVXcGwtYUJxWFh3a19rMDI0b2pyS2hMR2djelRVNjJxVHNYb19NdWRKZHl5Q3ZiZVhtTUR2UURvT1pNZGxtMnpiVmZPcFR1OTJKM3cwT2JpczhDZmFRTjdLbzh0T1RrdnJ2aTdtNUZTTmJmamN5VzhLX2s4bkU4NDBORC10VEM1QnhNbUU5QzVxMQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi7AFBVV95cUxNZjR2SFRTTU5ycnotblZYVHByN2Rza04yZ09rQ2JXZGREcUZ6dm9pMWpXMmVVeEVvU2ZfRWNDR1VfaHZmcFBDUEV5eDZkeWdMMTVCRmJ6aG4yMzRaNmVmMUJfWTVXcGwtYUJxWFh3a19rMDI0b2pyS2hMR2djelRVNjJxVHNYb19NdWRKZHl5Q3ZiZVhtTUR2UURvT1pNZGxtMnpiVmZPcFR1OTJKM3cwT2JpczhDZmFRTjdLbzh0T1RrdnJ2aTdtNUZTTmJmamN5VzhLX2s4bkU4NDBORC10VEM1QnhNbUU5QzVxMQ?oc=5\" target=\"_blank\">Wall Street retrocede antes de la apertura a la espera de datos clave de empleo y de la intervención de Kevin Warsh</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">MarketScreener España</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-01T12:14:29Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Wall Street"
  },
  {
    "titulo": "La bolsa hoy: Claves y agenda económica del día - Bankinter",
    "url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE01ckxPMVJvMVR5VWFYZXNkdU8ySXBEdE9fc0NXd3ZUMFZVT3VyazhkRzFZdXpGSmdIcXllLUN2cERBN2xIcE14NGlpVTFpeE1SZjA4RGU4ckZhOXBEMWxuWkxGZ2IxMVJIVmpWN1A0dU4?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMicEFVX3lxTE01ckxPMVJvMVR5VWFYZXNkdU8ySXBEdE9fc0NXd3ZUMFZVT3VyazhkRzFZdXpGSmdIcXllLUN2cERBN2xIcE14NGlpVTFpeE1SZjA4RGU4ckZhOXBEMWxuWkxGZ2IxMVJIVmpWN1A0dU4?oc=5\" target=\"_blank\">La bolsa hoy: Claves y agenda económica del día</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Bankinter</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-29T16:35:06Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Claves"
  },
  {
    "titulo": "DIGI abre en Torrent su tienda 100 en España y refuerza su red - El Diario de Madrid",
    "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxNTi02WW9HYVNaWjVyM0hGZ195eVQyRllUZ1dGT09tLXg0ejlERmM5c0NRVGR0eDJJNmhVMUhqU010dXpCNzFEV2NQbmZpeEJIbkVIQ21lRHpwTDN5OV9RbF95LWtWVGExZlZKUWlhNHQ3ZzZsUWhBd0h5bzIyLURaUTVMT1FpOWpKdmFpWUxSS25nM3V0emdwS2ZzQmdaNXRpYWRDNVRUME1CWHlyb1lPWDBOTW14Uy1ORU1YWm1UVDFoeGZrcmhlSXYxRFRPYXBteTNlc21Kd1Yyd9IB2gFBVV95cUxNTi02WW9HYVNaWjVyM0hGZ195eVQyRllUZ1dGT09tLXg0ejlERmM5c0NRVGR0eDJJNmhVMUhqU010dXpCNzFEV2NQbmZpeEJIbkVIQ21lRHpwTDN5OV9RbF95LWtWVGExZlZKUWlhNHQ3ZzZsUWhBd0h5bzIyLURaUTVMT1FpOWpKdmFpWUxSS25nM3V0emdwS2ZzQmdaNXRpYWRDNVRUME1CWHlyb1lPWDBOTW14Uy1ORU1YWm1UVDFoeGZrcmhlSXYxRFRPYXBteTNlc21Kd1Yydw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi2gFBVV95cUxNTi02WW9HYVNaWjVyM0hGZ195eVQyRllUZ1dGT09tLXg0ejlERmM5c0NRVGR0eDJJNmhVMUhqU010dXpCNzFEV2NQbmZpeEJIbkVIQ21lRHpwTDN5OV9RbF95LWtWVGExZlZKUWlhNHQ3ZzZsUWhBd0h5bzIyLURaUTVMT1FpOWpKdmFpWUxSS25nM3V0emdwS2ZzQmdaNXRpYWRDNVRUME1CWHlyb1lPWDBOTW14Uy1ORU1YWm1UVDFoeGZrcmhlSXYxRFRPYXBteTNlc21Kd1Yyd9IB2gFBVV95cUxNTi02WW9HYVNaWjVyM0hGZ195eVQyRllUZ1dGT09tLXg0ejlERmM5c0NRVGR0eDJJNmhVMUhqU010dXpCNzFEV2NQbmZpeEJIbkVIQ21lRHpwTDN5OV9RbF95LWtWVGExZlZKUWlhNHQ3ZzZsUWhBd0h5bzIyLURaUTVMT1FpOWpKdmFpWUxSS25nM3V0emdwS2ZzQmdaNXRpYWRDNVRUME1CWHlyb1lPWDBOTW14Uy1ORU1YWm1UVDFoeGZrcmhlSXYxRFRPYXBteTNlc21Kd1Yydw?oc=5\" target=\"_blank\">DIGI abre en Torrent su tienda 100 en España y refuerza su red</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Diario de Madrid</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-01T11:37:30Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "DIGI",
    "ubicacion": "Torrent"
  },
  {
    "titulo": "Eroski inaugura un nuevo supermercado franquiciado en Mallorca - Revista ARAL",
    "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPT0d2aWRJMW9RU0Radkl4b3ZpQ2xvbnRoSFBxa09LWDRPSDBreVhIVVl0c2lRbTVhWFM5VS1pVlZQN1dlMmR2RTlEUk0yMHI3TkFNTFVfbzNTRkIwYkpHOTZEZmJWLUdaWGJKR2VNVldleTBQRThHeEw1U1BfdkZIV1lGd09fV2d6eVphTzF2Nm9uX2VmaUY5QVpvOWE1bEROYUw0UUxXVm5lcVFmTDRPXzFuTQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiswFBVV95cUxPT0d2aWRJMW9RU0Radkl4b3ZpQ2xvbnRoSFBxa09LWDRPSDBreVhIVVl0c2lRbTVhWFM5VS1pVlZQN1dlMmR2RTlEUk0yMHI3TkFNTFVfbzNTRkIwYkpHOTZEZmJWLUdaWGJKR2VNVldleTBQRThHeEw1U1BfdkZIV1lGd09fV2d6eVphTzF2Nm9uX2VmaUY5QVpvOWE1bEROYUw0UUxXVm5lcVFmTDRPXzFuTQ?oc=5\" target=\"_blank\">Eroski inaugura un nuevo supermercado franquiciado en Mallorca</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Revista ARAL</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T14:18:50Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Mallorca"
  },
  {
    "titulo": "Alcampo refuerza su red de franquicias con una nueva apertura en Hondarribia - Just Retail",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQZ3hyMi1yak9BY3JfazBMYk9WMXp3RDJiTlpfVEZnXzN6VGRlejF1ZHVhZ3lvdU9tZnFWeUpxc29jRER5NDd0Uk5SRXVGX2RES1VzWkZqU0pWYXNBb2M5NTYyWjVtZDNsVXRLQmNOSk5oNElQc01TTm5hYURsQnQ3bDdIODh6NlhQMjBqS0EtMHFJQThLWDFwYkJkYzlXbE1uZF92MmNGUXNTWEE2MzFjVHJ1VVk?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitAFBVV95cUxQZ3hyMi1yak9BY3JfazBMYk9WMXp3RDJiTlpfVEZnXzN6VGRlejF1ZHVhZ3lvdU9tZnFWeUpxc29jRER5NDd0Uk5SRXVGX2RES1VzWkZqU0pWYXNBb2M5NTYyWjVtZDNsVXRLQmNOSk5oNElQc01TTm5hYURsQnQ3bDdIODh6NlhQMjBqS0EtMHFJQThLWDFwYkJkYzlXbE1uZF92MmNGUXNTWEE2MzFjVHJ1VVk?oc=5\" target=\"_blank\">Alcampo refuerza su red de franquicias con una nueva apertura en Hondarribia</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Just Retail</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T08:55:01Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "Desconocida",
    "ubicacion": "Hondarribia"
  },
  {
    "titulo": "EROSKI inaugura en Mallorca un nuevo supermercado franquiciado con la enseña RAPID - Diario de Mallorca",
    "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxNX2hXbGs5SHEzeENtdVliaU1fSnZPX19vb2NnbE5YU2NHQWhuRnlXU1Via3RiQmRMa2FOcjNqZHlEeXZpMzFzSGhxekRrbXFleEttM3FORnR5TVlRTHJqdEZwZDg2SzJFbzE5dnFhSHlRbzNBNEFLV0h5b3RuRXZUVlp6ZWI4UkFRZmwwWnV5TXZicnNuYTNQS1U2UG5SaHl4WlI0azRGN29DMmF0YlB6REtyb0ZaTG1Ca1M0RGN3ONIBxAFBVV95cUxPMWNzMzBWb0o3ekJDSkRLSDBVU1RkcVJQdjdoWHlWSDItR3V6YmR0ekFfTTk2ZW05OXUyNnV3cjFhVEpqNy16NDBYUDQ4cWc4THNPeUpETHZMMHhPT3g4V0NCS3FvcU5pSUlkY2NuSlpwQUJaRVRlYy1TeVFmUDI1XzlqV2FjaXc5R2hDTEhJODNJdlBwX3IydWZvNjM0eE80WmdnMWZzbmxnR0gxeW5Jb1BPY0xQYmxvODVIMHZGejhJNjkx?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMivwFBVV95cUxNX2hXbGs5SHEzeENtdVliaU1fSnZPX19vb2NnbE5YU2NHQWhuRnlXU1Via3RiQmRMa2FOcjNqZHlEeXZpMzFzSGhxekRrbXFleEttM3FORnR5TVlRTHJqdEZwZDg2SzJFbzE5dnFhSHlRbzNBNEFLV0h5b3RuRXZUVlp6ZWI4UkFRZmwwWnV5TXZicnNuYTNQS1U2UG5SaHl4WlI0azRGN29DMmF0YlB6REtyb0ZaTG1Ca1M0RGN3ONIBxAFBVV95cUxPMWNzMzBWb0o3ekJDSkRLSDBVU1RkcVJQdjdoWHlWSDItR3V6YmR0ekFfTTk2ZW05OXUyNnV3cjFhVEpqNy16NDBYUDQ4cWc4THNPeUpETHZMMHhPT3g4V0NCS3FvcU5pSUlkY2NuSlpwQUJaRVRlYy1TeVFmUDI1XzlqV2FjaXc5R2hDTEhJODNJdlBwX3IydWZvNjM0eE80WmdnMWZzbmxnR0gxeW5Jb1BPY0xQYmxvODVIMHZGejhJNjkx?oc=5\" target=\"_blank\">EROSKI inaugura en Mallorca un nuevo supermercado franquiciado con la enseña RAPID</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Diario de Mallorca</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-19T07:00:00Z",
    "fuente": "Nuevas Aperturas",
    "categoria": "Aperturas",
    "empresa": "EROSKI",
    "ubicacion": "Mallorca"
  },
  {
    "titulo": "Iberia pone en rampa de salida su ERE voluntario para 844 trabajadores - EL PAÍS",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQcGNJeW5HSTVtV1BZbU9mOFVrOExPYktDY2Exc2trWGhFSE5yT05NR2pxekNQUU1iRWtIMFh3c1lnVEd2dDMtZmJQbWRSMFc1cS1WLXpYN2VvOGEyVVUzREhkVDMzRXA0RVNrSXU3NXZiY3dKaTVGMTRRckwtVDdjZTRzVDBtY2N3YTJqX2ZTMUgxOWF6SmVjR2xQZGM0RFN5TjVLZ3lKdktva0tSNVlnWFBBOHXSAcgBQVVfeXFMUHh2SUFwNThLRXVaM0twV1pWbmVLM1JVLUJGWHNfd3JGdU1iaUZGem02VlhKQk50RU1kbm8xMmxIZ09RdWF4YUI1REdGR0R2TkJZOHZlRW5ReFc5NGhsMW9IYXVVWHNyTHVjWC1YYjRTWDk5Rkl0eFhYN1htTUE5WnNkbUU4WFNrRlNERXIwRy1ZOE1razJFU0JOaGg4LUU5WlFIczdNSm9LbDZPZ3VGQ3FrbUxwemF2VUMta1c3WVFmcVlCbjNlNUo?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitAFBVV95cUxQcGNJeW5HSTVtV1BZbU9mOFVrOExPYktDY2Exc2trWGhFSE5yT05NR2pxekNQUU1iRWtIMFh3c1lnVEd2dDMtZmJQbWRSMFc1cS1WLXpYN2VvOGEyVVUzREhkVDMzRXA0RVNrSXU3NXZiY3dKaTVGMTRRckwtVDdjZTRzVDBtY2N3YTJqX2ZTMUgxOWF6SmVjR2xQZGM0RFN5TjVLZ3lKdktva0tSNVlnWFBBOHXSAcgBQVVfeXFMUHh2SUFwNThLRXVaM0twV1pWbmVLM1JVLUJGWHNfd3JGdU1iaUZGem02VlhKQk50RU1kbm8xMmxIZ09RdWF4YUI1REdGR0R2TkJZOHZlRW5ReFc5NGhsMW9IYXVVWHNyTHVjWC1YYjRTWDk5Rkl0eFhYN1htTUE5WnNkbUU4WFNrRlNERXIwRy1ZOE1razJFU0JOaGg4LUU5WlFIczdNSm9LbDZPZ3VGQ3FrbUxwemF2VUMta1c3WVFmcVlCbjNlNUo?oc=5\" target=\"_blank\">Iberia pone en rampa de salida su ERE voluntario para 844 trabajadores</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL PAÍS</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-22T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Iberia",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Tubacex no está siendo capaz de acreditar las causas del ERTE - ELA Sindikatua",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxQMm5lMEs2S1NDRlVOQnl3NmgteFN1Q2R3a3A4Mk52emw1bEFkUmpWaVZTRklkVUNfTVA1SVkzNjRYY1NSM1kyRmdUdHE3YWN0bTd3dHcwNE12OXFkUEI0VU96M3UyVy1ZMHVLOWpYQW0zLXBCVTVVY3ZaVzZpNkRQaEVydk9pWG9JLUU5ZXQ1ZEJUQ3hEaGJ0d1ZFS095VlNGQTRIWUgxanRCZWZkSHB0U1daRHpBWWNGOUE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiugFBVV95cUxQMm5lMEs2S1NDRlVOQnl3NmgteFN1Q2R3a3A4Mk52emw1bEFkUmpWaVZTRklkVUNfTVA1SVkzNjRYY1NSM1kyRmdUdHE3YWN0bTd3dHcwNE12OXFkUEI0VU96M3UyVy1ZMHVLOWpYQW0zLXBCVTVVY3ZaVzZpNkRQaEVydk9pWG9JLUU5ZXQ1ZEJUQ3hEaGJ0d1ZFS095VlNGQTRIWUgxanRCZWZkSHB0U1daRHpBWWNGOUE?oc=5\" target=\"_blank\">Tubacex no está siendo capaz de acreditar las causas del ERTE</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ELA Sindikatua</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T11:55:08Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Stellantis plantea un ERE y un ERTE en Villaverde tras recortar en 7.800 coches su previsión de producción - El Economista",
    "url": "https://news.google.com/rss/articles/CBMi_AFBVV95cUxNQkE2YmU5Vl9Wd0E2ellyYzk3M180Uk5oYVJjdjFoclV6UXA1SlE3dTVWRUdCbEJVUm1wT0hfZ29BVzZjdFFvMXlLN0hIY09aRU9sckVTaWlOV0x3NEJBQkU0RVZCQWtZQjhGWjRIQUQ1WnpPanE5WldBRHFCZnNObm5KVlo5X1RCdHk4YnBvVlBkUFJiYnZLeDBMWXRBbjZKNWFrUXhzdDg2OFdVamM1dGIwR3RLTVBLQ1JkZzBYbnlCc25oS1JNcHV2bE9SNTNyOF83OHk0WjRtTHd3MWhyVHJ0aDZjVjJxZlJ0V2RqSk9jQ1lhNGxOS1dBV3PSAecBQVVfeXFMUHFOb2EzUVJIT3pRQWJnOTJIOUUyUlRDZDdOU3BUemtLSUFpdWMxQnNsbEsxdlZuclBOQUZiV09WVXpkWjI5SldTTXp6R1ZuS25iYXJZMzY0dUFsM2YtNGlpb0I4LWVGUmo1bEtMZGdIbVkwX2wwT0hZNlhIWHlJbEt3SUdXTmRYYmg0d0dnek01c3N6aE81VVlaZE9SdWY1dHNoZEpuNmp6RWU0QzZCQ1NnclJIQVRSSjFGM0Y5UGFaYnAyb3ZpTnp0X2doSUs2TzlwLWRsTGE5RHA4c3RWcFRpZmQ3amFB?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi_AFBVV95cUxNQkE2YmU5Vl9Wd0E2ellyYzk3M180Uk5oYVJjdjFoclV6UXA1SlE3dTVWRUdCbEJVUm1wT0hfZ29BVzZjdFFvMXlLN0hIY09aRU9sckVTaWlOV0x3NEJBQkU0RVZCQWtZQjhGWjRIQUQ1WnpPanE5WldBRHFCZnNObm5KVlo5X1RCdHk4YnBvVlBkUFJiYnZLeDBMWXRBbjZKNWFrUXhzdDg2OFdVamM1dGIwR3RLTVBLQ1JkZzBYbnlCc25oS1JNcHV2bE9SNTNyOF83OHk0WjRtTHd3MWhyVHJ0aDZjVjJxZlJ0V2RqSk9jQ1lhNGxOS1dBV3PSAecBQVVfeXFMUHFOb2EzUVJIT3pRQWJnOTJIOUUyUlRDZDdOU3BUemtLSUFpdWMxQnNsbEsxdlZuclBOQUZiV09WVXpkWjI5SldTTXp6R1ZuS25iYXJZMzY0dUFsM2YtNGlpb0I4LWVGUmo1bEtMZGdIbVkwX2wwT0hZNlhIWHlJbEt3SUdXTmRYYmg0d0dnek01c3N6aE81VVlaZE9SdWY1dHNoZEpuNmp6RWU0QzZCQ1NnclJIQVRSSjFGM0Y5UGFaYnAyb3ZpTnp0X2doSUs2TzlwLWRsTGE5RHA4c3RWcFRpZmQ3amFB?oc=5\" target=\"_blank\">Stellantis plantea un ERE y un ERTE en Villaverde tras recortar en 7.800 coches su previsión de producción</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Economista</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-25T15:46:41Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Villaverde"
  },
  {
    "titulo": "Iberia reabrirá su ERE voluntario tras quedarse a 152 bajas del objetivo - Preferente.com",
    "url": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxNMWZ3ZEdtMGp5QXM0MHRsRUdHQnJyTTNOVnFBQ0hHekc1dTl0b3ZWMVhvQ1VDZXpRc2FXRmJLRVU0X1FsTzNBWTRid0RER2dKb2lkZm8yTmtoTGhBQzlNcGh5TUhxSUt1Zi0wYVZlbHRtTGJXa0xxcy1aN2Z6eEw4MGh5ME5VSU1sMFJIRFdTaUhCUHNZazZfR0VMdXB1aTdlSlB5bXJ5SjNYaU4ycFZ1MlN5ZlZ2UV9wQ0otX2Zsb0xlWW5YV1RGQkRYWFUxVjg4am10MUtqb3VUZUN4TTZTNWJrdGRleGxBUkhRRWVRVQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi7wFBVV95cUxNMWZ3ZEdtMGp5QXM0MHRsRUdHQnJyTTNOVnFBQ0hHekc1dTl0b3ZWMVhvQ1VDZXpRc2FXRmJLRVU0X1FsTzNBWTRid0RER2dKb2lkZm8yTmtoTGhBQzlNcGh5TUhxSUt1Zi0wYVZlbHRtTGJXa0xxcy1aN2Z6eEw4MGh5ME5VSU1sMFJIRFdTaUhCUHNZazZfR0VMdXB1aTdlSlB5bXJ5SjNYaU4ycFZ1MlN5ZlZ2UV9wQ0otX2Zsb0xlWW5YV1RGQkRYWFUxVjg4am10MUtqb3VUZUN4TTZTNWJrdGRleGxBUkhRRWVRVQ?oc=5\" target=\"_blank\">Iberia reabrirá su ERE voluntario tras quedarse a 152 bajas del objetivo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">Preferente.com</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T09:36:07Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Iberia",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "ElPulpo activa un ERTE en su sede central de A Coruña tras replegarse de Nanos - La Opinión A Coruña",
    "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNWjhsVEdRMU01UUF5SVNFYndGa0x3dEhlamtXSl96M2dkQldCMkNnZDk1WWJiNm8zMEV1VHZHQ0hJX2JtUW9oWHBnOFhhWFBYdGNEOGVHQXZqdGpVaGhvc2lzelQxSU1PbXh2OTM4X3NXNlJEajZPbU9GS1ZBLVRvcTBURVQta2NJRTNxd1JMR1ZLdS0yeFhaWXl2SERBbTQ0ZVRCRXlsc9IBrAFBVV95cUxPRDdvLXJBOEM5UF9VekgtRTEtY0V5Z2k2NkNtWUtGWEJtLXFxd0dTSWJ1RlkyQmY1bWx2LUVKQjNLV3BVMWNqcDItWEpqUF9GQ1RrdGtGRWkwN1BSNi01ZnJabmdzdENFU1prU01qdHdsRHdJbWFDMkxvaWpLVkxpMEZoVlJmblZhMWQtUU90T1ZsT09QZUZRb290WThyTnNGMkZPOGlmbHFBNzFC?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMipwFBVV95cUxNWjhsVEdRMU01UUF5SVNFYndGa0x3dEhlamtXSl96M2dkQldCMkNnZDk1WWJiNm8zMEV1VHZHQ0hJX2JtUW9oWHBnOFhhWFBYdGNEOGVHQXZqdGpVaGhvc2lzelQxSU1PbXh2OTM4X3NXNlJEajZPbU9GS1ZBLVRvcTBURVQta2NJRTNxd1JMR1ZLdS0yeFhaWXl2SERBbTQ0ZVRCRXlsc9IBrAFBVV95cUxPRDdvLXJBOEM5UF9VekgtRTEtY0V5Z2k2NkNtWUtGWEJtLXFxd0dTSWJ1RlkyQmY1bWx2LUVKQjNLV3BVMWNqcDItWEpqUF9GQ1RrdGtGRWkwN1BSNi01ZnJabmdzdENFU1prU01qdHdsRHdJbWFDMkxvaWpLVkxpMEZoVlJmblZhMWQtUU90T1ZsT09QZUZRb290WThyTnNGMkZPOGlmbHFBNzFC?oc=5\" target=\"_blank\">ElPulpo activa un ERTE en su sede central de A Coruña tras replegarse de Nanos</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Opinión A Coruña</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-20T16:54:43Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "A Coruña"
  },
  {
    "titulo": "Mercazaragoza impulsa un ere para al menos 20 trabajadores por la crisis del matadero municipal - El Periódico de Aragón",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxNVHBMOXRwNHdRRElMS1FZMFA4Y1NhSTJOdVkxMkdySFJFN19OMVVMaHFMR0lySVNQYWJIclJxWG1yYXh0TF9wWE85Q0xYTjFkVTNqYWxVQXJRWGNhZkkyRVNrb1VwTWpnbW9fQU8tb2RqbGlRYW5nMFBFTWhQMDRVSlF3T1k0eU9Oa1FkR0dzaWJvOWZQRlF4WDFVWTZ3ajk2MmNSd01LRG9GYUpsMkVjTlJB0gG3AUFVX3lxTE5ubncyMXIxS2h4SWs2ZHNLWkw1T09EbVBlcDRibmJESDhySmVjbHR0TFN1MUE4V0djR0V4WUVCdEZlT1lvSzBwRkZkaEE4WWhtSGZOdmpZNXBNVXpCd29odUpyS09iRGV3bUg5akdheXlDZFc1TzZzVWgzdVRwZ1JLcTJxRU54Y3Y2ODZuV2ZZZWlySzBuakR0X3ViVmdvc3MzZWwzZUVNQzNOLVd5MExHWTdKbzdfZw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMisgFBVV95cUxNVHBMOXRwNHdRRElMS1FZMFA4Y1NhSTJOdVkxMkdySFJFN19OMVVMaHFMR0lySVNQYWJIclJxWG1yYXh0TF9wWE85Q0xYTjFkVTNqYWxVQXJRWGNhZkkyRVNrb1VwTWpnbW9fQU8tb2RqbGlRYW5nMFBFTWhQMDRVSlF3T1k0eU9Oa1FkR0dzaWJvOWZQRlF4WDFVWTZ3ajk2MmNSd01LRG9GYUpsMkVjTlJB0gG3AUFVX3lxTE5ubncyMXIxS2h4SWs2ZHNLWkw1T09EbVBlcDRibmJESDhySmVjbHR0TFN1MUE4V0djR0V4WUVCdEZlT1lvSzBwRkZkaEE4WWhtSGZOdmpZNXBNVXpCd29odUpyS09iRGV3bUg5akdheXlDZFc1TzZzVWgzdVRwZ1JLcTJxRU54Y3Y2ODZuV2ZZZWlySzBuakR0X3ViVmdvc3MzZWwzZUVNQzNOLVd5MExHWTdKbzdfZw?oc=5\" target=\"_blank\">Mercazaragoza impulsa un ere para al menos 20 trabajadores por la crisis del matadero municipal</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Periódico de Aragón</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-22T05:00:32Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "El Periódico"
  },
  {
    "titulo": "La empresa leonesa de telemarketing Plus Contacto anuncia un ERE a su plantilla - ILEON",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxQUXYxWHVNMmhpY3BITl9peXpmV2thUS1kYVJTNnZ1VVhzb1ZzUkY3T29MT1Z3OWxrTlctekNDOFJMVDJ1RFBQaEdXZGNvVzVkM1o5bUxVTS1fcWhEdHdvUDJpZ2V5czFHTlFMOGowTHk2V0wtek04UHB4WWY4N2U4UmpNMmRRYTB2TFFzQTF6THkzUVVlTVJxSndHTXQteHV0TGF0aUxWSlMyWXN1Ujl2ZkM5V1Z4TXPSAbwBQVVfeXFMTUZXd1Znd1JjVEtRZG1Wald2bktmeWwtMzRJejZXMXg1ZEdNZXR4bEdITm9mZU12T21WZVJNeXI4Y1pHOGdKOUZQTFVYbkdJUGFleTVBWjNXNVA0X1g0eUFSaXFzSHdHTFRMRTViUE1IYzF2TzBhV2p1dnhHQWh4S2hjdThrUWVFUFZ0ZFVSbVdpeFc5UkxWa1FEWkIweEFOT29UN19WWWJkajlmcUlxQ3RKTUFzWDdWajFvdWk?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMitwFBVV95cUxQUXYxWHVNMmhpY3BITl9peXpmV2thUS1kYVJTNnZ1VVhzb1ZzUkY3T29MT1Z3OWxrTlctekNDOFJMVDJ1RFBQaEdXZGNvVzVkM1o5bUxVTS1fcWhEdHdvUDJpZ2V5czFHTlFMOGowTHk2V0wtek04UHB4WWY4N2U4UmpNMmRRYTB2TFFzQTF6THkzUVVlTVJxSndHTXQteHV0TGF0aUxWSlMyWXN1Ujl2ZkM5V1Z4TXPSAbwBQVVfeXFMTUZXd1Znd1JjVEtRZG1Wald2bktmeWwtMzRJejZXMXg1ZEdNZXR4bEdITm9mZU12T21WZVJNeXI4Y1pHOGdKOUZQTFVYbkdJUGFleTVBWjNXNVA0X1g0eUFSaXFzSHdHTFRMRTViUE1IYzF2TzBhV2p1dnhHQWh4S2hjdThrUWVFUFZ0ZFVSbVdpeFc5UkxWa1FEWkIweEFOT29UN19WWWJkajlmcUlxQ3RKTUFzWDdWajFvdWk?oc=5\" target=\"_blank\">La empresa leonesa de telemarketing Plus Contacto anuncia un ERE a su plantilla</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ILEON</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T15:59:53Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ILEON",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "ElPulpo presenta un ERTE para 15 trabajadores en su sede de A Coruña durante ocho meses - La Voz de Galicia",
    "url": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxPd0NnbWp0WjZSUkw1SGhneHc3MkRaTTJxWExTY2hsaTIzcG9LOTRiSFE1X2EwN3lLSkFybExia3VaZDAxODNUVFZPWkRKekt1RGV0RzI4RHVVczRpLWtTTExoTzJkOHpuQ3pOTXM3aTFueTVvZW5adW9MUVoxVnNHdDh3NUZja2pBUkpGdVhqZ3loR0RzV01EWk03c1N5dTBPV19VWWR0MWlETFg2Q1BnbDdYNnY2T2ZvQXhVc2t5SF9EZzZ5SGZoQmYtc2RkbXFwWl9XYkNRNTlHTUNrbVYyZ25OSGZ4RldNS3fSAYYCQVVfeXFMT0hqN1BPU3lBOEZsbUlsdTBVVXdvRzhKcW4zY0VRYVFMT0d3YlMyV2lXRjBNWWo5OEwyWVBMRVNNYWxzeUhBR0p1Zkk5eW9tQmxZWFdxSl9MUUxIVm5WaHd4dDVvMU5OWUpVQ3BfS2ljcHdsZEp0LXQxdWFGbVBWZUxlaVRibTI3blBiaGFITFFrM2xXNDZ3SUx2bHNnc1F2bG52MjU1cEZ5ak1OX1EwUUNjZVJvLVd1YWlGajZEMTkyVTFoVVJrUm9qMTNPa1BHRktUT3FmM0hmSVQ1NG1QVXhCWlBjdGJOVFZ6NW5JNGFYWWxBNGExUGRkNzBVdWctZ0MyYjBOUQ?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi6gFBVV95cUxPd0NnbWp0WjZSUkw1SGhneHc3MkRaTTJxWExTY2hsaTIzcG9LOTRiSFE1X2EwN3lLSkFybExia3VaZDAxODNUVFZPWkRKekt1RGV0RzI4RHVVczRpLWtTTExoTzJkOHpuQ3pOTXM3aTFueTVvZW5adW9MUVoxVnNHdDh3NUZja2pBUkpGdVhqZ3loR0RzV01EWk03c1N5dTBPV19VWWR0MWlETFg2Q1BnbDdYNnY2T2ZvQXhVc2t5SF9EZzZ5SGZoQmYtc2RkbXFwWl9XYkNRNTlHTUNrbVYyZ25OSGZ4RldNS3fSAYYCQVVfeXFMT0hqN1BPU3lBOEZsbUlsdTBVVXdvRzhKcW4zY0VRYVFMT0d3YlMyV2lXRjBNWWo5OEwyWVBMRVNNYWxzeUhBR0p1Zkk5eW9tQmxZWFdxSl9MUUxIVm5WaHd4dDVvMU5OWUpVQ3BfS2ljcHdsZEp0LXQxdWFGbVBWZUxlaVRibTI3blBiaGFITFFrM2xXNDZ3SUx2bHNnc1F2bG52MjU1cEZ5ak1OX1EwUUNjZVJvLVd1YWlGajZEMTkyVTFoVVJrUm9qMTNPa1BHRktUT3FmM0hmSVQ1NG1QVXhCWlBjdGJOVFZ6NW5JNGFYWWxBNGExUGRkNzBVdWctZ0MyYjBOUQ?oc=5\" target=\"_blank\">ElPulpo presenta un ERTE para 15 trabajadores en su sede de A Coruña durante ocho meses</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Voz de Galicia</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-20T07:00:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Tubacex aplicará un ERTE en Araba a partir del 7 de julio tras no haber acuerdo con el comité - naiz:",
    "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNYlZUS29OcWwtMlE2anBpNUptS0tneERsTXVjdDFPUjVMZENRbUVDT1RyWVhMdEd2cVlyWmNsdXhaWjVfSEx4bzN3d1I0QlFrN0g2bTgtbGRUT2JEc3dRRm9ZV09RUE41TURONm5OcGE4NWR3aTRIajNZcHo2b1JkVW5GdUV1RU9SNDIxTVMtQU5NdU9FUFloS0dhTWQwUHBYNTNITnBfal90RVJ3eko0bTVodjRNSXJCM2JMZFNCTGs3Z1hpNzFVSjRudTLSAdIBQVVfeXFMT0pqZDZwMDB6d2VmTFZxY0x3X3A3c09BNzBTTkxCT0ExWXA2Z2IxSTBac3pSNmxBNlFNSjN2ZllFYTlYaTRNSkx6R0NqbF9BUktpOUVtSWM1Q2U2MVItakhuSnYxcDliUUR0NEFpQ3FLelh2Yy1lVDZBRkctWnNGWkxTSnZxUUd2Zm9PdVJhUUZlV1k0Um5YbUZ6VzhQbGxVMWIzSmhrNWZqX1lmbU5jSXR4MWlGWll1NGFWZTdneVBOU0EtckxUWi1OOHBjNlpmTE13?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMizAFBVV95cUxNYlZUS29OcWwtMlE2anBpNUptS0tneERsTXVjdDFPUjVMZENRbUVDT1RyWVhMdEd2cVlyWmNsdXhaWjVfSEx4bzN3d1I0QlFrN0g2bTgtbGRUT2JEc3dRRm9ZV09RUE41TURONm5OcGE4NWR3aTRIajNZcHo2b1JkVW5GdUV1RU9SNDIxTVMtQU5NdU9FUFloS0dhTWQwUHBYNTNITnBfal90RVJ3eko0bTVodjRNSXJCM2JMZFNCTGs3Z1hpNzFVSjRudTLSAdIBQVVfeXFMT0pqZDZwMDB6d2VmTFZxY0x3X3A3c09BNzBTTkxCT0ExWXA2Z2IxSTBac3pSNmxBNlFNSjN2ZllFYTlYaTRNSkx6R0NqbF9BUktpOUVtSWM1Q2U2MVItakhuSnYxcDliUUR0NEFpQ3FLelh2Yy1lVDZBRkctWnNGWkxTSnZxUUd2Zm9PdVJhUUZlV1k0Um5YbUZ6VzhQbGxVMWIzSmhrNWZqX1lmbU5jSXR4MWlGWll1NGFWZTdneVBOU0EtckxUWi1OOHBjNlpmTE13?oc=5\" target=\"_blank\">Tubacex aplicará un ERTE en Araba a partir del 7 de julio tras no haber acuerdo con el comité</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">naiz:</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-07-01T14:46:00Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERTE",
    "ubicacion": "Tubacex"
  },
  {
    "titulo": "La fábrica de Nestlé en La Penilla recibe 69 solicitudes de salida voluntaria con el ERE - El Diario Montañés",
    "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxNVDM2bG9aczVPNnhZYy1FU1djTUVwSXVhRFFvaVpZeXZmVldObHZ6aVdkbnNsM0tjQ3NNWFRQZlc2TTBhOFA0ejRUdS14Y1llNzRvVHNmQnlxbGJGWUlPeFFFZUVOekJ4elM3dVcyVkdDSlE0Yi1xVWVKN1RwUHYzWUJtbjd4QzdMX28yVU1tSDFKZHdWSzBIUEwybXd2cGtWVS1zbFQwajZCcEZrVVNWN1A0M2N4dEdEUXdQMUxzMjR3RENGcnhuM1dzOA?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxNVDM2bG9aczVPNnhZYy1FU1djTUVwSXVhRFFvaVpZeXZmVldObHZ6aVdkbnNsM0tjQ3NNWFRQZlc2TTBhOFA0ejRUdS14Y1llNzRvVHNmQnlxbGJGWUlPeFFFZUVOekJ4elM3dVcyVkdDSlE0Yi1xVWVKN1RwUHYzWUJtbjd4QzdMX28yVU1tSDFKZHdWSzBIUEwybXd2cGtWVS1zbFQwajZCcEZrVVNWN1A0M2N4dEdEUXdQMUxzMjR3RENGcnhuM1dzOA?oc=5\" target=\"_blank\">La fábrica de Nestlé en La Penilla recibe 69 solicitudes de salida voluntaria con el ERE</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">El Diario Montañés</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T05:17:19Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Nestlé",
    "ubicacion": "La Penilla"
  },
  {
    "titulo": "Quinta jornada de negociación del despido colectivo en Capgemini - ccoo-servicios.es",
    "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTFBsVXVzUkVvdVpzWDhqSGtYSmJuX1V3NllhQU8wQTVza3hDaGI2VzRDaW9EcEUyZThGRGI3X2pHVkoyVFU0NmNwRFhWcV9YOHo3QnV4WHJaT210dkdGVmRNUlNmeFd0ZXBv?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiaEFVX3lxTFBsVXVzUkVvdVpzWDhqSGtYSmJuX1V3NllhQU8wQTVza3hDaGI2VzRDaW9EcEUyZThGRGI3X2pHVkoyVFU0NmNwRFhWcV9YOHo3QnV4WHJaT210dkdGVmRNUlNmeFd0ZXBv?oc=5\" target=\"_blank\">Quinta jornada de negociación del despido colectivo en Capgemini</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ccoo-servicios.es</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T14:01:42Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "Desconocida",
    "ubicacion": "Capgemini"
  },
  {
    "titulo": "UGT ALCANZA UN ACUERDO EN EL ERE DE ZEEMAN QUE GARANTIZA CONDICIONES DIGNAS Y REDUCE LOS DESPIDOS - FeSMC - UGT",
    "url": "https://news.google.com/rss/articles/CBMiogJBVV95cUxOY2Z5bEd3QkEwVW1yMEtYeWMzaEVCdHZOUFJWTkVNQThTNHZGUlFQOGhwZ1V3MS1VVk9zRzd3TVJ3Q3g0MF9IVnJycTVDYUwtSHpUOWhSZUNaaEp0aVBwdVUxZ3lnUWlrS01sNGRuQXZGbUNCcWxDTGdTMmRMeHFrSHE4bmdfLUY1ellPMHljNE5DNndCRllJUnNrdnpMaEdjeGNZRV8xcnlaTzVUbktNU2JNYkQ1X0VWYWlaQk9aSHMyM2pVaUVZWmtnS0VkZVp5WnpFLVpnNUw4aE9GemdYT3BCWTQya0YzYWJMX0xZbUg1cFNOcU9xQl9HZVFCcmYwSmhGYTRldnFWVEU5RVZzZTRrcDhFaU41dTRHbFRsWjU4dw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiogJBVV95cUxOY2Z5bEd3QkEwVW1yMEtYeWMzaEVCdHZOUFJWTkVNQThTNHZGUlFQOGhwZ1V3MS1VVk9zRzd3TVJ3Q3g0MF9IVnJycTVDYUwtSHpUOWhSZUNaaEp0aVBwdVUxZ3lnUWlrS01sNGRuQXZGbUNCcWxDTGdTMmRMeHFrSHE4bmdfLUY1ellPMHljNE5DNndCRllJUnNrdnpMaEdjeGNZRV8xcnlaTzVUbktNU2JNYkQ1X0VWYWlaQk9aSHMyM2pVaUVZWmtnS0VkZVp5WnpFLVpnNUw4aE9GemdYT3BCWTQya0YzYWJMX0xZbUg1cFNOcU9xQl9HZVFCcmYwSmhGYTRldnFWVEU5RVZzZTRrcDhFaU41dTRHbFRsWjU4dw?oc=5\" target=\"_blank\">UGT ALCANZA UN ACUERDO EN EL ERE DE ZEEMAN QUE GARANTIZA CONDICIONES DIGNAS Y REDUCE LOS DESPIDOS</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">FeSMC - UGT</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-30T14:10:44Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "UGT",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Pascual presenta un ERE para los 80 trabajadores de su fábrica de Gurb (Barcelona) - ABC",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPRkhLS2VUS1Fia1oxSXpnZzZqMDd0M1JGT1JlbHRmN093NG80b2RKU3pDSjdJeVZ1YWFuSUtER0x0SlBmWXRxWkJ0c1VrYVQ5Uk13LVhlT0Y0TnRtQXNYSlNoQUdWejMwMTM0cTA0dHRxc0RoakFwbURXaklMSkpiYnhMOEJxRGJfOFdhX0xqV21DaXF5X2oyVElvVXZrRFBRc0FTRFFGNDRVQ1nSAbABQVVfeXFMUGN2c0hhbkJBZGVoYzV0eGJRZW16YV9uUWgyaDZadzAtSTZlVjIyTVJBTl9OcVpqanNBU29zUEhsWkd6WWNNdHZoejdUWkNYd3U5anVPcmdIZDRCOVdHYkRwbWNLdUI5eFN0YkVOTGwxamJiS2JubERBUk4ybzlJNEppaTdGNXBVc1RGbHR6YVJja0dud1l3WHk2NlYzTm80Tm90UXdJOFdsQTU5QkpYQ0I?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiqwFBVV95cUxPRkhLS2VUS1Fia1oxSXpnZzZqMDd0M1JGT1JlbHRmN093NG80b2RKU3pDSjdJeVZ1YWFuSUtER0x0SlBmWXRxWkJ0c1VrYVQ5Uk13LVhlT0Y0TnRtQXNYSlNoQUdWejMwMTM0cTA0dHRxc0RoakFwbURXaklMSkpiYnhMOEJxRGJfOFdhX0xqV21DaXF5X2oyVElvVXZrRFBRc0FTRFFGNDRVQ1nSAbABQVVfeXFMUGN2c0hhbkJBZGVoYzV0eGJRZW16YV9uUWgyaDZadzAtSTZlVjIyTVJBTl9OcVpqanNBU29zUEhsWkd6WWNNdHZoejdUWkNYd3U5anVPcmdIZDRCOVdHYkRwbWNLdUI5eFN0YkVOTGwxamJiS2JubERBUk4ybzlJNEppaTdGNXBVc1RGbHR6YVJja0dud1l3WHk2NlYzTm80Tm90UXdJOFdsQTU5QkpYQ0I?oc=5\" target=\"_blank\">Pascual presenta un ERE para los 80 trabajadores de su fábrica de Gurb (Barcelona)</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">ABC</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T18:16:04Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Gurb"
  },
  {
    "titulo": "Los despidos por ERE se moderan en Catalunya pese al repunte de expedientes hasta mayo - La Vanguardia",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxOV2tiRDZUR2NuTXRwemNRclNyVlB0WWdmdUU5OVZfVXR2LVhLcEhuRjdQSnFINU52ZGxDOWtQVjlqYWVGOXBScTgxRVpKNTFPc1FhbnBiWVkyam4zaUdBSUt0bEVZam9jZEdYSmZqblQtUzEtRGctaFJVT0RyODFjeXYtUGRNel9XYWhKUzlIbHl1dF8tLThhMXo2Q3NOOGNwVWxhNF9OMEp1ZXfSAbABQVVfeXFMT2dvWmxLQjZndW5HdUlhYlVtRGtDOEJjQzNMdEI4Um9zeG1ucmdYNHhTUzUySDdGSm1Wcl9tOGVLb3FuVXdhN1lEaGcxdHZwNGZKRHdxTm5HM0M2LXNsVUJSQkZhd0Y1UGJOcXR3OE9WazhLeDE5WS1JQjVQOWo1cnZsemJWcHZVT2RGc2p6Sm5GbmMzM2JmVDFXMGRNRXF4VnpBMkdYLWstU2EyOVZLWUE?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMiqwFBVV95cUxOV2tiRDZUR2NuTXRwemNRclNyVlB0WWdmdUU5OVZfVXR2LVhLcEhuRjdQSnFINU52ZGxDOWtQVjlqYWVGOXBScTgxRVpKNTFPc1FhbnBiWVkyam4zaUdBSUt0bEVZam9jZEdYSmZqblQtUzEtRGctaFJVT0RyODFjeXYtUGRNel9XYWhKUzlIbHl1dF8tLThhMXo2Q3NOOGNwVWxhNF9OMEp1ZXfSAbABQVVfeXFMT2dvWmxLQjZndW5HdUlhYlVtRGtDOEJjQzNMdEI4Um9zeG1ucmdYNHhTUzUySDdGSm1Wcl9tOGVLb3FuVXdhN1lEaGcxdHZwNGZKRHdxTm5HM0M2LXNsVUJSQkZhd0Y1UGJOcXR3OE9WazhLeDE5WS1JQjVQOWo1cnZsemJWcHZVT2RGc2p6Sm5GbmMzM2JmVDFXMGRNRXF4VnpBMkdYLWstU2EyOVZLWUE?oc=5\" target=\"_blank\">Los despidos por ERE se moderan en Catalunya pese al repunte de expedientes hasta mayo</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">La Vanguardia</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-23T15:53:30Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Leche Pascual presenta un ERE para los 80 trabajadores de su planta de Gurb (Barcelona) - EL PAÍS",
    "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQa2F6bnZSNmxhZ2JnRW5ZdE1OMlF2VmtacDR6VXRMSGpFTE02cG9ONmxaQno4WndBdm5mYmlKeWRxUGxneE9pR21mQVdDVm5YUmJpRDNyMXl2QlhYTkwwTDhpakxnNVBEai1TUHVlNTljeElyM01DdUFnWkYyZklid3E3RHVNTUtpX1FXeHkwbHN3TjJ3RzlCZ1duNEFQQU5sUlNCdWVJWUdoa0k4cllaRDh0bDdmcFZpZmpaUG0xZ19ETVJ0ZDM0REZmaHp4aTdJM1RJ0gHnAUFVX3lxTFBEUGVVU3ViNll1WFlkVVIwQVEwX1BtTG1pbjYxaGJSRzZJUFltTGJPc3B5TVByeTBnYmJMQjVac0JIM3VocDBPSThOTWctanFmVV9oVFBGaWZxSnowRXBXaUlBUEVCbEpBN2VFWlZHSlZwNU9oc243NFY5QV8tQ2tyTnFTZkwxdlFiZE1Vak40clZBQ0lMZWU0cTF1d1lBWWlQcVgyMlBTV0hpNDhKdUJzeHVkOWt3RXpqb3hfTEpSWE1zTWVsOWNNSVhuUlFnU1hKN09hbnBoUi1vTWgtaUlQOUE5UnJjaw?oc=5",
    "resumen": "<a href=\"https://news.google.com/rss/articles/CBMi0wFBVV95cUxQa2F6bnZSNmxhZ2JnRW5ZdE1OMlF2VmtacDR6VXRMSGpFTE02cG9ONmxaQno4WndBdm5mYmlKeWRxUGxneE9pR21mQVdDVm5YUmJpRDNyMXl2QlhYTkwwTDhpakxnNVBEai1TUHVlNTljeElyM01DdUFnWkYyZklid3E3RHVNTUtpX1FXeHkwbHN3TjJ3RzlCZ1duNEFQQU5sUlNCdWVJWUdoa0k4cllaRDh0bDdmcFZpZmpaUG0xZ19ETVJ0ZDM0REZmaHp4aTdJM1RJ0gHnAUFVX3lxTFBEUGVVU3ViNll1WFlkVVIwQVEwX1BtTG1pbjYxaGJSRzZJUFltTGJPc3B5TVByeTBnYmJMQjVac0JIM3VocDBPSThOTWctanFmVV9oVFBGaWZxSnowRXBXaUlBUEVCbEpBN2VFWlZHSlZwNU9oc243NFY5QV8tQ2tyTnFTZkwxdlFiZE1Vak40clZBQ0lMZWU0cTF1d1lBWWlQcVgyMlBTV0hpNDhKdUJzeHVkOWt3RXpqb3hfTEpSWE1zTWVsOWNNSVhuUlFnU1hKN09hbnBoUi1vTWgtaUlQOUE5UnJjaw?oc=5\" target=\"_blank\">Leche Pascual presenta un ERE para los 80 trabajadores de su planta de Gurb (Barcelona)</a>&nbsp;&nbsp;<font color=\"#6f6f6f\">EL PAÍS</font>",
    "impacto": "N/A",
    "riesgos": "N/A",
    "fecha": "2026-06-26T11:43:59Z",
    "fuente": "Alertas de Reestructuración",
    "categoria": "Reestructuracion",
    "empresa": "ERE",
    "ubicacion": "Gurb"
  }
];