const window_news_data = [
  {
    "titulo": "La promesa rota de la reforma laboral: el 68% de los fijos discontinuos se van a 'casa' en verano y ya son los nuevos temporales - El Economista",
    "url": "https://news.google.com/rss/articles/CBMimgJBVV95cUxNaUFWbjgtcGhXNll4RTUxQWdCQzZYOVFXU1pPSDVlM3NacXE5b0c3SkhHcHpHb2UwdXVRenN3Rm9NTDZlLXNfa19PMXVqdFVIanhUQmlBTU9FbXFJRmZlMHJuV25VejBZMDhZTVZDR1dXb1dPUEtUN1R3RkhwbVhkR01IdFB4WEdla1J4NHdTX0VFT0pTb1dIUE1FeGQ1X0FxbkVmZDFvNEpHRnNmNVQ2amMwVExKTU1GdElEZ2VibEpSMnM2c3RjZ2prZFQyU255NkdFOXZhV3plSE9fdk1ZWDBfUHUtVmk3MGlNaTRzSElzVEotdlltakNsMlMtSWxmcEpnM2x2NFpCSS1ZNy1JSDItTW9WOVpuTkE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T04:30:08Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: tienes derecho a tener tu registro horario y así blindar tus horas extra - larazon.es",
    "url": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxONmdVbzJVY1pQQjNWRWpCWTlQQTVzbFl0bUdnUHFSN2dOWlozQXYyUVh5OEpqMl9kZVVMSFlIU3NkbmlqSGdHMmRYR1MxMzdNc0thcm1YWHlNS2ExbloyWGtsYTVNSWpzLTNOZnp3RHFwQnhlME9YU1dQcXBQTFF4WWx6V3NwRkx4NG83RkI4ajhJZGNDS2JNZjBWbjJOR1pPdzJUcG9hU3VoTm51djVFVERxbnVYVUhEQkR6MkVSLXVtcElzdGJDS3pvNkV4Y3QwOWZRaHNucFc0VlJUSFBodFBwRHN4d1ItdWtWRmFFeWE4UFdFNVRKTzBFRTNyUWvSAZMCQVVfeXFMTWxva1ZybkZjckFSajBYZE0xZl9vZjNpekZmYzVSLVlZOHRZckVFVVEtOVZ3MG1QaUF0SGxjajBPSHdvNGJZRGJNdGVFeVJrQ1FROTVUYmpEQlo4TkxMQTUwR082cjRHamdmeDV2U2hMZVVGVFN4WlhZMGw1Nkk0VjAyUnhmVTRDX042bHBsdWczRHlRMzE0SHVmMkktWHY2VkR3bVptSlBUaUxSX0ItTFJWYjhhVGNYNjRkeXZiNjl4VDgxR3ZEVEN2Rlk5S2hKNHZnbzRNQ3F3RlZMck91ZHIxRmtlVHlNUDd6Y3MweDEwMXkwWm4tUW5oMGRiTEQ1dmpqVHZWNWV1MXlxZjZHbFpOeDA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T08:43:35Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores cambia las reglas a miles de empresas: los trabajadores pasarán a ser fijos si encadenan 18 meses de contratos temporales - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxONWtINFNDdHkxeDJCVUdra29zU0dmNk5qT1otdEhiNm1qMGtvbHhLTGJoMTR2OWhxRm1WQlhxQmhaMWNoYWU2M3pQZ0syUlJlS3E4QWs2b2w4YWUxcExDRDdmNVVhVEFQM0N0bHZLWEZLcG4zSmxJWWVxTHhoa19tUmJ6YlFjdUU3RmhURHBDeU9rV19VWXN4am1lMGY2Q1VjYm5yVzhidFpHRDlyX3fSAbMBQVVfeXFMUHlZVmxiTEFTdUc1dVZNaE1sSElnZWJJUUctYUpYdVIzT1l2d0xLd05UYmN4eG9jWWpfQVR4UDc0Q1BJeEhCR1BndUFHOGxuSzNZaVNueXVrQk8zQ29FYk85bW9vdmNzY0g4NUFkLUZ3cHFhVVJBbWZNT0tzVXVWRW5WcTlvYjJjZFVON1ZTdmg5dHlWc1p3b3pBdk5MT2FmN0tRTzN5S2JHX3h4MTladzZhVDQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T09:31:17Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Provincia"
  },
  {
    "titulo": "La Ley Laboral lo confirma y el Estatuto de los Trabajadores lo avala: se permite la «retribución específic... - OkDiario",
    "url": "https://news.google.com/rss/articles/CBMi8gFBVV95cUxQa2FnbDgtMVJ1Vm9XYnkzTEgwb0xxYnFLa3R0MUdSdVRXUEFHQUFjcmkyRXRGYjhzODg5d2hPYk82ZzJHR0dMZl9ldjRsQjg3eWVSWEE2TjFtOHY0QVFZMmtmUGlrMUJWZU02TU96LU5sVjJkYUlFcl9sSk9iZDhCUnZpa0FmM0dic0JoUkRsZ0ZXa0ZydmhjejduOUtQcDJpc3JGNkdaU2FiNnFwREZ4V190YWh5ZTVYeUNZN0VZeDVmSTZCcC1xaTdza3Z4ZzVqVHhWRjJJMTg3NXpBLXp5TmdrMDR6ekJFRFh3SlQ1ZTZBQdIB9wFBVV95cUxOalVSb0c4Z3pUeGNtZUFSNEV3OGdWczlqaEE5WUlvbGdXZ2tMNExmZm9mQWFzOTlmTlRsMXNzS08yZ1pWYjl0M3U2Z05HWW1ETmdHY3ZZM0RMT1pXM25YTm1kckxnMW5FNHRVeXBRdG9TajQyendDNVI0UFFHaGxHbE83WUxLQUlwNTFrTXJ4VFN1R1dBUE15MERrdDVjNHB3aktfT1hmZmxtMlIyZ0pYdEh5RHJpMTA5cTBHd1Q2WmxDN2djZlpxeDdVbndRTVQxWXkxVmFISXV5ZzZCOXdRWm4zaUEwZ1J3T09nLUhZcDE3cjN1QXRj?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T11:18:05Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ya está en vigor: el Estatuto de los Trabajadores recuerda que los empleados tienen derecho a 4 días de permiso retribuido en estos casos - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMigAJBVV95cUxQbjZ2T3RveHNaY3g5XzZKOWZEc2tLYllrdjZHLXc4Y2lJQWM2NUdUN0ZLN0tUVXJHYzNVemQzQVhyenhndzN1WG1NYXFpZXhJR0tURE1HeFg1LXE3ejJ6a0ExNDVSdXVoaThxYk5NLXFlMkhWTWNaa01uMTBNYmluZWkxbVkzTEVPYXpwVkpyOW1UTWZ1SVNrdERyUlRGN0M3NkFDSHhpcnRRNVlnWUJiREJYcnRjZndTVFNaal9VSHV5NDkwWXJQMEd3dWNPNTFCdFY4UlpYTVdBM29pUWsxNkh2SE9lSHJ1V3VUVndHQ240MnRwT0dwN1V2UktPalZj0gGOAkFVX3lxTE9ZNlRVS0dmREdHVmc3anBPQVc3SFBvRjY5Mm9BSW00SUxiTU9CUFpFT04xeHpPRFBTbkNMMTZEVHJDS283Uy1MeGE0eGJiNlBGcDZ0TFA2Y0ZjNktPTXhtakE1WUVyd2xjYTFySGk0c1ZTMjVqVFNOaTBoelMtR2JBa3ctN0Q4MS11UkR6aXNlMTBTTTBJM0J3MFVrSmJwbGxFSGZTdHhIN2dhdGtRYnBheE9NYjVCZ2x6ejI3OFg5WEFkdExKbk55XzNxeWhMbVZ1anJULUtKU3RJc0JSUVBCNkhRUmFfdEdlU0VMbGxlakFnY0oycHFaM0JzMTZRcFVrVGZ3SGhqbm8xOEVqdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T14:50:27Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Trabajo aclara que descarta volver a subir el SMI en lo que queda de año - Diario AyE",
    "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxQVnhJeGRaRDJsamwzMGViT0tjdU5Nb0xyWTZ4Zm5RalNwaUZVN3pxVkxMdlZ4Q1hqMWtwMDhjd1JNeDZSR0xBVHJmdXFJYUg4VVRPajdEY1F0U3RVMHV6b2daRVNUV2RzM05OcllaLTdKRUw2R3lhQmtLRDJrcmZNbVhMQVF0R18zTW1iYUhPSjJYMjFVYW9OR0JQMVM4VVpwWkt2b1U5eDVPUmFpN3dNbHQxcVU2dkl1MEpPc3dSZ2NNY1dKenZCOFJVM0E4ckZqSFVsYVQydkFyRDhuNi1GTGlaWdIB6AFBVV95cUxOX0JPektlVGVUSE9IV012QnpvR194d2V0WE5pRXUtZ21admhFVHhQRndIUmNHS3EyZDRLVUVuZl9QVTgxYUJpb1BEVEN4bWl4TEFvU3FjQ1Z5RjRjTGMtT2tZbnZDNnVRNUtqajF0dGYwbjdGZ0V4X1VaRTQtNUNubzNoNFJUZ2pYRFZUaHktbEk5VWNHSFVtb05UQXpNMDFpc1htaXJlVGpxVTR4VE1KeWdDT2YxdEt3ZWFpbjNPOTduWnVtaW5MS0FDZmE2VUVWX2ZqbFYxR0Vtd19VYlVHbUdmaXdYWExz?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T22:20:51Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "SMI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Qué pasa con tus vacaciones si te pones enfermo o coges la baja: lo que dice el Estatuto de los Trabajadores - Málaga Hoy",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNbHJKSXNYN0hiN2pWaW5FUXFRakN5SFZxQzBVbmVKUWtWUDRMUk85ajRKdTE2RjVIUm94SXN0UFBYaVRBZXhOb3Qzc0tiMjNhN1BJVWt3V1RZbWkzQjJDYzZXZHNiNkRsLTFSODA0RFV4bFlFLXF1aHhPV3BrMTRvUTl2Q21uSk42SFdPMFBXUk1vdVZRMUVBN2tUWdIBoAFBVV95cUxNXzdIU3hFNTNLWklsRmFnX1N3OWhGOW5FOG5kdmVuLUU5UTJGaTdTQ3FMRlFKMWwxSVZIU0xPaGhvbzlQRjBOcE9UNDdiTnRnZ2k1RWs2WVZLdXJMQkxVdWduckFHME9XeTJmNWVlNGd2YVkyWXNSM1ZuNFpDM1g3anJmcGM1cmlOVEU1LUlEVzVNR19USk1QcEkwaWk0SXZN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T04:00:56Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Qué"
  },
  {
    "titulo": "El derecho al descanso que recoge el Estatuto de los trabajadores: un mínimo semanal de día y medio ininterrumpido - marca.com",
    "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxNUG43MnBoc0lhdlNZUGE0UmxLTmQwSEpmTGpXeGFhaW1NN0NCcGh1QWFsM3dlZXc2LWlMSDhpVHZBbDNZMFRmNElzcGsxTzBKXzg0U1RKaTlrdUxuUkpaR0VmWjZrVTdKVHFtR2VDU1ZhUjFkUFhoWVFmVGtIVklVbFZ1Yk9IYlhjVkJPSXhwLTNmMVZPQ0lTTHBhVGlleVFFckpJWk1WSFB2WGFpZmJHVHVNR0dhelFWQ2ZPNHJ1WkR5U1RMY2lQaWtKb01DR051blVGOGxlWEVFODDSAdsBQVVfeXFMTWdha2lDNGV1ZFZLYXlqeHhsWVF2Szh0OThWUi1OYkQ1R05aTVJ0cEVLVXVFSGtUTVlvY0lJUVp2dHBTeUcxRmFKSFhDUDZtUEN4Z2lGU2JVY2FTQTlrVTlTZGF0VXVPaDlBSnFjLTNMb3Y1WnBqSTRxVnB1MXJNcVBwUG5GRWRoTERTajFfSmpVZmszWjY1VTlEMU5ZMGJtWnJiazdOUW1udUR4Rm5OVmVQOXpBbGxYNURWS25va1pHbjdxOEpaSzFrS0R2LUZGMXZhWWYxR3JyYThn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T08:42:01Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "De la reforma laboral a la regularización: las claves que explican el dato histórico de afiliados en España - Diario Público",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQeENqTjlSXzRtQmNqSmlPMTd4T1RtTVZrX3QwbU5JSVlSVHdrT0V2ME9zekVyRXYzRjc0eURXdHZCLU0tZFY2bm00SGhNMFdCSmtwYThQQ2Rqa1dtLVFHZnFLOThJMTJDWFRfU3RRdUc2ME9UTUZqMGcwdkNGMlJfeDNjTkFQanBvRFhBc1VLUVBFaUJpN2lxVUQ0WUs3REtGMEFPZU15OFpIUkNTd09FN3NsZmlaZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T08:12:25Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Ministerio de Trabajo informa de que el paro juvenil en España cae a 159.562, el mínimo histórico que impulsa la FP - moncloa.com",
    "url": "https://news.google.com/rss/articles/CBMijwFBVV95cUxNeFJpQXlXOWZvOVNfaFVYZ2s2WmloMjhUZ3FwbFUydzRXVnJLeWdqYXI0a3R4Rk9WcTlaakpMTGNtaFZ0QTh6QlpXUVlmQW44VVFDOEhETmdNZWI3YU52WS1KaVBreHlHVTk5eDlFTGM0eUJTS3NXOVJ3aldZdVpvRmM3NXlfaDRpamg3MVZXWQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T07:19:55Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "Está en vigor: trabajar de noche entre las 22:00 y las 6:00 supone una \"retribución específica\", según el Estatuto de los Trabajadores - Business Insider España",
    "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxQTFpIdnNnc0lsa0hBZy1jLTNoU1RLT05uVW1mdnZ5THdYc255cVFvek1wZFJtd2pjVVlkMkR0bmxSanlJLWc2TWc0TTZjQk1EdlMwbWN3NkV4UmJ1dWdSN3F6NGNEcmxSamVoODFQTkdERHpZamQwNm1tRTFtaVJ6eGFSZzUyNlNSMVJvbkhBX0ZMTXJrZ0Vn0gGcAUFVX3lxTFAwSmNoaWt1RXREXzNucEZlS3NOaVBXbFZpX0hGMmIyb01uUFJfSzB3ajFRU0NKcFlpWWh4ZkIxbHhNZnI3TElCNmRlY296UGg4ZG5RekFHOVJSemFPYXVaV1RJXzZvRWVEemNyc00wdEpzd3JQV21TSk9fU3NWM0dLNmFNWnY3MUV1Qng5SkZkVmowcDdEdE9iTTNMRw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T08:17:31Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Juanma Lorente, abogado, sobre el próximo festivo del 15 de agosto: \"Si tú no trabajas el sábado, estás perdiendo el festivo\" - El Periódico",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOSFY1T1UwMGlfTXhmbXptQ1lLS1p3aGFSbmFSTWVRNGxhdUw5WEFGQnlFR0E0NW9EMF9NYnlrTnNkX3RXUkc5a2x0c0dZbVBQSUt6MXZSRFlZdUNXSU1Bdi16Zk5GSzJrRjF5aTR1Y04xSjM5aEdJVkdOTDRuVXVHYk0wczlZUVFTS0FDVTNPNVFpWC00UFdGRGs5cFljdUNjaTZmeEJhX09jMzl5VWJ2V1JSb0hjTFMt0gG4AUFVX3lxTE1OZWYxZUJvczJ6Zm5GMzR1a0NSTjBfbVNpdWpuQTJ2c29jaG5CVlM1Yy1FN0xGZ2cyeU83SVl0dTZjeXVDa1oyLWZrZkx5ajR3X0FqWkRMM3p1emhQbnY1ZEl1OGViMDdqTXM2SVk0QndCRnBkNEFydGZWVUxRYzlSUmV4M2JLRWZwNkw4U3I5eS1Gd1o0c2dpblh2R000NXQ2dFNaRnBVUThvTFVneThYb2F3MDJTQjc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T10:32:08Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "El Periódico"
  },
  {
    "titulo": "Sube más de 15% el empleo turístico en las islas el segundo trimestre - Economía de Mallorca",
    "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxPZElwanQ5ZUxscXF1QkkxdXJXQjVweTEtRzZTZWpxVnBkMUxuam1wVVlNNlAwNmxyY2JFVzZzeDdTZ3daZ0VSRkpIeEhGNFNoVlhlclB3V1JueVJHbFAydWNiS2NqVDltM000OUFob3pPSG1oTnhFdjNUdi1hZlRrZjRNeDU2REhCb3Iycm9MZ2lTblZzU0lJTHpMWHE3bVZwYUtzbDlyYjFCMUlzanI4M2RWcmxpUTlUVTlZR2N5LS00dzktTVF0cjhXN1h1Si1hNTZNeA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T10:41:49Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Entró en vigor: \"Los trabajadores con 1 año en la empresa tienen derecho a pedir una excedencia de 5 años\" - El Español",
    "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxOWXY3cXhKYnY3bmFnMm5wQ1RxS2hJemRGaXZlc3AwcC1rR2Zfc1U0cG1wMkpGRW1XSDVlZ2VVVFZRNFVtdzZlc21jRll5ZnQ5VmVTU3ktSjZ1VTNITExzaEw4dEp2XzZzc2RkeU1fay1XOG5kNl9OZHRWLVlVOE1vTzd4NXRMLWhTaUxjQkdSY0NXVG9TVm1TSWJVa29zeEhvblVzZFZFLURqcUtQWjVMYjJyWXFfV2VDd3F3MWxWcGtVNl9WNW9xM3dRMVoyUXdCbWVBdUNaOEhGY1FZ0gHiAUFVX3lxTFBRWk1kaHZKMFpDUWsxQ0V4MGxYdVBTcG9ESmUtR0RucGlwc2hSa1hsMGt1ai1XbU9fcFdZdnZRYjVuZnE1VHlXTlVmQ3FjOWpPREhWZmt0czlxZ3kxMENuS01ZVEZzaHQ4VzMxTWNQVnhGc3VuMUVqT1lwM3laVUR0VkZqR1I2ZFhrdTNUUFFkRFl1bkV6MkIweHFJdUFMX2hUQlZRMnpoeVhmTlZsYWFSeW05NVZmb21wOTV2MGVlTkI0ZVNjRnJIY1RiN2I4cUszNkVSSHNxZ21YUURsdmE3d2c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T05:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Español"
  },
  {
    "titulo": "ANÁLISIS: Lo que falta reglamentar de la reforma laboral - Ámbito Jurídico",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxPaGUzNUdGOVhlcW54bHRncHFlc3QzUGlKSGdVbUMwa0R5MjJ2R3VXMXRhNUxYa0FFOEV4eWVoVmpsbFhkdVppTGJTeVFtQzRnWjBMNG4tY1piN2hXOTJ3NlJOZmh1ai1QNzV2OE9FazBEUWRDVUJiaUFsWmFvd0hIRHAzV0N4dG85VEw5anhCVFhyeDh1WWllcFNScmpTUjZaUFpray1zOVkwdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T08:50:57Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "ANÁLISIS",
    "ubicacion": "Ámbito Jurídico"
  },
  {
    "titulo": "Ya está en vigor: el Estatuto de los Trabajadores acuerda que trabajar de noche entre las 22:00 y las 6:00 horas implica \"retribución específica\" - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMingJBVV95cUxNR1hGdGk5WC1aZzQwNWNldW01LVd1VXBvbnFSYmdHSG1pU2hwU2xTTHdDelZXX3NUS2EwQjRkckhSZEdHenRmWnZhOUE0SUFvc1YxVHRWWF9WS1dCckxFVmlUSDcyVmZST0I2SDJYeVJ1cGc0Mk5XcG5MMVhHZWExLUJHcUpRamtkNGYxd1dqQlZuQXlJak9za1pMSUZBdVA0RkdNR0ZPbHk1Skw0TlhMdkV5OGZLTUl2TllwZFE3WFphT2NoeFdVRnNyRE1vSEl1UXU4bk11RzJabkRQcGZDWUJaamctSWwzUDByQVdqM0NTWUY5eUJIbVVnUEJ1bTN3aXc5LXl6bU9NaEhRS3ZwTUVzYUszRktuR3AxQW930gGeAkFVX3lxTE1HWEZ0aTlYLVpnNDA1Y2V1bTUtV3VVcG9ucVJiZ0dIbWlTaHBTbFNMd0N6Vldfc1RLYTBCNGRySFJkR0d6dGZadmE5QTRJQW9zVjFUdFZYX1ZLV0JyTEVWaVRINzJWZlJPQjZIMlh5UnVwZzQyTldwbkwxWEdlYTEtQkdxSlFqa2Q0ZjF3V2pCVm5BeUlqT3NrWkxJRkF1UDRGR01HRk9seTVKTDROWEx2RXk4ZktNSXZOWXBkUTdYWmFPY2h4V1VGc3JETW9ISXVRdThuTXVHMlpuRFBwZkNZQlpqZy1JbDNQMHJBV2ozQ1NZRjl5QkhtVWdQQnVtM3dpdzkteXptT01oSFFLdnBNRXNhSzNGS25HcDFBb3c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T14:02:27Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Es oficial: la Inspección de Trabajo ya multa a las empresas que incumplan esta norma del Estatuto de los Trabajadores - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPMTdUdU83ZmV6Q2pvbWdXSUJlOVhsY1RZSEY2YzJfc3Y4alZHUFF2NFFaSEdxU0ljWF9CQ29SNUhMOXUxdE5pbHptQVc3Yk53VkRaMms2aktvUklETGJKeTBwcWtpejRINm9adUw2aHdQdmcxTVJCbkpsOW1Cb2EzZEp1bGREeUVuZ0FTT252bzNoeU9uT0xIUy1NMk5kZ2hEQkFYZFNfaHdac1RZYlM2dlJWSDR3LW55ay1XNTBVR3FyUDZ3eWhV0gHMAUFVX3lxTE1BdHBxSnE2LTN0LVJLYWN4SjBmTktjOEplQkZTMWw4TXlfNTZBalJmSDhFZnhleTR4VzVXMmowb0g4cDZrSmtSNGNwUC1KTjViVXNjMHVHY08yMnhTM0d0N3g1LU5zdWlSQ2pKRjAzdkJvUG1uMEhyRlFXY2luUUlTXzMwSDhtenYtMjFjN0xLc1Z3ZkpVWDdmTXpZLXYwTzFDVW1zVW9JVW1jaEwtYU02LUlrcUJQcG5takVLY01NQ0VzQVJ4ZW8yR3d3Qg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T11:31:32Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Provincia"
  },
  {
    "titulo": "Es oficial en el BOE: tu sueldo bajará por un ajuste que las empresas tendrán que hacer en las nóminas por culpa del Ministerio de Trabajo - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxNZ3Y0OVJhOWFCUGhuY1pCbjRFVUpsVW5nbUZfa3l4eHZsbkJ2QUwzSVF1akdfYjEtdVdOT2pjM2Nvbjh6S3lGRWdIWWZEQnVoWk04WVdwRENaNktETDdJb1o5aTBWWDNfTjZSV1RFYXhzbURWTUdlZ1RLWEVmTFp0aVBIWEFKQnFzYV9oOVdlSVhZaHNSanJ4RDRnUjlZWnJpRGFkRC1wMTdQQ0gwbklOZDFaOXkzVWhXOWVvYkFR0gHDAUFVX3lxTFBKZHJMbktKTG5pUFFXSTBEVzFvMG1scFRDbWkxNU9qaXhudXJSWFd4c3Q4cnNXSmIzMkZnSDlFbnVRR1dnUU1wbnJENU1zNHlobWlHYUwyZy12YVlIcGUxSmVwUWgyUFBNaTJneERLSmRESERTc1Q0YnZKa1drOFdqWV9HakZibW1EX1JPY2FPakZJckFHQmg1SldWbW5WWDhQZi1FbDNNbW1LYW5ablFmN0RCUVlJSVlZNEdETGlSaDZ5Zw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T08:00:54Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "Confirmado por el Estatuto de los Trabajadores: las personas que enfermen durante las vacaciones de verano podrán recuperar los días - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPdHZnNVZtcGFucWswMEFmNWlSb2QwLTlDT3ZuckJtZ3pUT2EzUjNFbVQtck8weGlTYWVOb18wbF9EQk92QUZ0MkpJZk5BVzJVdko1NjNJM05KakYwUFpnWVBMVWdQRW9hSURLRDBJQS0yQ0o4NTNUdm9CcUEwVnNUR1pHcE1naGpmdFJBNWR2eExNRC1WUzBUdElQcGVRNmh3eWVZcFZkMHBtVDZSWWY4RUhMRWlKSDhYY1g3MVExZFBuRHJITkU0MHh0bEs2b0p0M1RLVU9n0gHbAUFVX3lxTFBXdnlvbmhTLVB5aGxPZ1VpXy0wM2xGN3RxbnBRa3ltV0VnSXc0Z3h4WEp3RTVwWC1Scm43WFNiQUx4MFRMa3VSNWN1Tlk3T3ZqREJhWUoyN2l0Y2Z5amgtU1pUeGZmQ1FORmplZmNrOHNMMGFfWkZvMHlhMGNueTY0bV9JM3VHY3pnd2xsOFROb2dsTEtEUHhfRWFTUjY2YWZ0ck50dFdBejVHb21ZZXVWV0IwdlBtWGpNME5uZW1zOVM2SllKMWduU0YwTC1GM3RPZ3ZHc1JzV3ctYw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T06:00:26Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Provincia"
  },
  {
    "titulo": "A horas de dejar el poder, Gobierno Petro expide decreto que afecta a repartidores de Rappi y contradice a la reforma laboral - Yahoo",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxOdXJDek5wY1ZfRHpuVlZNMjQ3M1M0WHlfT25OTjZBelRsbHB2NFhma0xaemFaRXlSVXlOcDZDTzQ2bTZYd2tZQ01vd1N1U05IQnB3MlBzZURaQW5EdlZDdVR6eG9nOTZJalY4WDRmSTc5WF9sU1dxTjBENXE2azNoSXk2UzZEOHM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T20:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Yahoo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Frente sindical argentino denuncia reforma laboral - Prensa Latina",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPSjFQTW9SWTRXeFhrTHlpTkdFUVU2cldGZVVJQVg1QnJzM01YQmpVSUx3YzFXeHc0WlpabGEtZ1E5UU1iZnhCeDdVMVJXNC1WTUZXNjJ2Ym1qSzFPMnZCTjVwbGFTWG16UDNzN3EtZ0t5dDJSYU1EbElYSWgzemR4SllXdU15dlYycEpOek01NTNMYi0zelE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T13:13:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Reforma laboral: tras el acuerdo Gobierno-CGT, se destrabó la renegociación de unos 800 convenios colectivos de trabajo - Infobae",
    "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxOLVF6am1jRUpXbTVSUDVNRXZFS1g3NHJ2REMzTlA3bUxucXlybE56NFYwV2R1LV9ybm1FQm9fVmJjZGpTY1padDUxdVJOWWZZdnk0UVJyQ0RNN1ZMbzMtcWlYWEhGSThNcS1fcU9LS1h2QXZIQTFyYVRtQ2wxd0JYazQtNlZ2eGgwWmtJMkJmVnNwVjhQb1VsaFVvNWlrOVpGSmowY1pMT0w1dXpJNXJiRzNJVGxhNi1FalZZd1gzQTVKSkJXa3pCaUNmZTVwN0NKczZmLUhCVHFLV08tVVZCZ1VwRUozcHB5YTdETUVjYjhTVlJZ0gGPAkFVX3lxTFAwR21QZFd6MG43UjAxQVpSVWtSV3RDSjEySk51czh1MFNVZE5WdkczVzFtajE1YzdMS0IyR0NZOUtTWk1uSHZqWGxxeERaYmpCMHBjZm9ZTmxHTk9CMUh0TmxwSFI3REZOSFU2YWhodV9pTUIyZlhKNllBM1hVS0dFZ1gwTmFpUjJVdGZoQThoWWpHT1Zob0RBYnpvckt1TWJoR2xueXZhc21odUVrdldTXzJCc2hNLXJ0STBIZjZxSXRBd2NnblBVeERZNFF5MGN2bm5TNzM5MEJaVndpS2pJR2wtelRvakprUXZpZzd2M0swcE9PM3ZtYzNsemZHWkc5SWRrM1REdGlOVk85dDA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T08:11:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estos son los últimos cambios de la reforma laboral del gobierno Petro: Falta aumento clave en el salario - Valora Analitik",
    "url": "https://news.google.com/rss/articles/CBMi7AFBVV95cUxNWDl3M3BxVnJNYWJJMGhwdndFdkZXSG84YUhpUU8tWDNzNE9DYVh0Y3d4ejltdjlKdGlfbXNPZDhxRzg1OHFZRXprRGVNRU1IY01FaFBZV2VYaWVCcE9MY1ktQzVtMFRzMFF4TTR0MmJMMDFENWIzaWQyX0U0QmhQLVhOVkU0c1Nza1prZjQ2cUVRV1pneFc1QXRUelBJQXRMZGtvN19hV2F1NXRLM1pfcGl0OXdzV0RqV1pHZ3JxbFgyMWpCekY5V0pPWTFndi16dlBLZ0VxOWl2bTdLSDZiZEFtQlpfLTdBRkdVNNIB8gFBVV95cUxNMG9KblNEb3ptaDlGUkh1U0xCS09jRUZ4YXlHOFpkemkzYldZaVpRNzBxcGs3TkwybFpvTXEtdl8yQlFTei1vY2dwVDJUN2RmUEV2eGZjTmZzc2oxRXlNWWlJSkhPcm5GcHVpV1lXUDZIc0o0OEQ2QkpsMlpBNEdZZHZYUDB6NFFaYkljdnlTNWNNZGdHdkpWSURQSjllY1dnV1ZiTkR5Q1ZUaWtGUmx0N3RXS1YtMng2SXVxVXc3bXdiSWxubmtvN2Nta0t0WHdWanNMZjM5UlZVeUxJWUNNTC16NkFkMUFIYUlpTnZSUHVjQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T22:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Las federaciones Sanitas y Solidaridad Sanitaria han presentado al Ministerio de Trabajo y al Ministerio de Salud un conjunto de solicitudes para modificar la ley de salarios en el sistema público de salud. - Informat.ro",
    "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNMF9vYWhBS25EX0JKek9XMkw0Z1ljb2FkRkg5LTczTXFrY1V4QXVFMDFrZmRZNXF6UlBaRUxaWlVhLUkxU2QwRTBEZk5fMi1jZlpWYkxTUkxfOC1IOVJsVEJ4c2VOUGNycGhzbjhKRmMxRldMS3BWbDFrUUxWc1R3bXktT0tkZW5LMmdKTTU1cmR5Q3c1UHNtbDlsMFlwNTBrMjl2RGVzTjRYT0JjTTFsUG14MDFObUN3cVg0b3BOTzVqanB2OG9xdFZxODM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T15:36:25Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Sanitas",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "\"La reforma laboral provoca un retroceso al siglo XIX\": sindicatos argentinos denunciaron al Gobierno ante la Comisión Interamericana - Latam Gremial",
    "url": "https://news.google.com/rss/articles/CBMi7AFBVV95cUxNSzhYc0dFdTJhT1ZLWF81VHFaOXpVY1RYSzVEUWk2UFpiNlJBaGJQaGpWNXdhUE9FMXlkUVNINmZxaWZySnRZZnZ2dklOS2RXZWFVUDdESVNWTGxvWVByU3R4RnBUeElPdEpsczRFcVlDd1A5S0sxR2JPN0I3em1YWGxlX0pqTVM3WkxWVDVWTjNnUkkxd25YNzY2ZWZWb2JudWlTVzRqMW5IYjJhOXZfNlQtaGxfVXhVRzhKN1dJazhEalNaSkUzaUhQUi01MWxyUUluLXRzQTFjSE1JcTR2SzdKRVdKd2hEc3M2Mg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T17:17:21Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Comisión Interamericana",
    "ubicacion": "Gobierno"
  },
  {
    "titulo": "Ministerio de Trabajo - mt.gob.do",
    "url": "https://news.google.com/rss/articles/CBMiPkFVX3lxTE1mdnpiSWp5NEZ2bm5yUXdtdlhIMzlyUHgtSllwM0NUcDAzOEFsWElzSkVjR3ZCYTl4LWdabkVR?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T18:38:14Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "En vigor: \"Eres trabajador nocturno si realizas entre las 22:00 y las 06:00 al menos 3 horas de tu jornada diaria\" - El Español",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxQNnk0QjkzUUxEbngzbkNCWllSLWNzUG9Ba01mdkhWYmdQbWxQZ2U4ZUV4aUtRT0JTSzMzSExjR3Q5dklYekJGeDA2eWF5OTlWTndZT3B6R3ZrYWJEb2REeXBtZGlieUUzcFFKc2lmRWx0dThFVDVlX0dBZjktblZnbnpnaHlTYUlrdHZJbWhjZDlkZHFMZ25WWG1vU3JzejJiRkIzUGhmcUo4RjlGWlg2dlhxQWJnZUhxUUg1SU9aZkdpaDJUci1Bb0M5WUhMMm1BYngxaml4Ym3SAdgBQVVfeXFMUDZ5NEI5M1FMRG54M25DQlpZUi1jc1BvQWtNZnZIVmJnUG1sUGdlOGVFeGlLUU9CU0szM0hMY0d0OXZJWHpCRngwNnlheTk5Vk53WU9wekd2a2FiRG9kRHlwbWRpYnlFM3BRSnNpZkVsdHU4RVQ1ZV9HQWY5LW5WZ256Z2h5U2FJa3R2SW1oY2Q5ZGRxTGduVlhtb1Nyc3oyYkZCM1BoZnFKOEY5RlpYNnZYcUFiZ2VIcVFINUlPWmZHaWgyVHItQW9DOVlITDJtQWJ4MWppeGJt?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T12:45:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Español"
  },
  {
    "titulo": "Reforma laboral: 800 convenios destrabados tras acuerdo CGT-Gobierno - Mundo Empresarial AR",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxOU09jLUM0ZkRSVGtaMjlJSjc0MGhaV2FnUGRKYmh6aU42bV9xQ0tYQkVXaDNnWlA5NkdnTk0tR2JfUjRMWGtKTTdmU25xVTRMTUQ0QU1YV2E4TDBQWmZwTnluM09UU0J5S21rSkNtNEpoU200RllXMGVoRWRvREYwREJMaFZnb3NqeHcyMUZLR1dlQVgzYURnZ2ZMQnU?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T15:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "AR",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Empresarios desilusionados por la marcha atrás del gobierno en la reforma laboral - Parlamentario",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxQcmhIbEdHb0hTWWRxWlVPYVpWVzJCMV9XR1hqaXFlM2ZwNmo4eTBSbDBkT09ybDVubTFRanFRNGVFbGx3bUo5V1Q3NHNlZmk1eFNYMGktRXJ6cDJkSzhpLVVjTERIdzJhNk1sdlJiaVVoSGdCQjRzYlV0bGh5aWszQUJBcGpXbHFRY3VlWV95T1dXNldZVGpETVBtREE3cXkyUWJuMGFlOVAyVE5wVktaUVFkU2RRRWRqbENOOWZNckc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T15:44:39Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Exdirectora del Ministerio de Trabajo denunció a actual jefe de despacho de Laura Fernández, él niega acusaciones - El Observador CR",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPQzAxdEhfNE9KRlJ3YWVRbXZXNDFDTUdwVExDUXFMdnB6MFdNOWFoMjBTZ0hLdFVTSDRkeFVjSWQ4OU8tOU95enVOQ0tyVE1YeVdOUy1RbUNLUGYweUx2MjdJci1kSTNvUHk2Z3JlUWZiRlhMR1FSOW9WaFJ4d1U3Vk1TMTA3NkNpc1lMSFZwTXBRZEdhYlFqN2tSTTBJQzRCaUN2RE9JOFBwUmVTbmo0OVB1MzRuQXVfNXF0dlhwa0dZZkNqV1JZUWlYVk96QlQx?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T23:17:09Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "Nerea, administrativa en recursos humanos, sobre las bajas y el absentismo: \"A los directivos les perdonábamos las faltas, a los trabajadores no\" - El Economista",
    "url": "https://news.google.com/rss/articles/CBMisAJBVV95cUxNOHBVVHFyRGRKdGl1X3VrVHlBSEdadVRFTGJxcFNPV2o3M2dvT0V0X1NjeC0tdlo4RGEyS240Ti1yeFBpaThkSk5CQUlPb0JSR1Zac3hHdU52em1OM3hUSG9rdjVNbDhIN3VNdGRYcWU1LW9XamdrOEY2dWVpNldmcFlYMDJOQmU2Q0NodjJfazB1QkJuM3dKUThncUVFZjdiTTZiZ0hGZmZjY2c5dG5iSWdMSFNNVW01RlhpRUhQYkxCc2MzaGZEWkU0TzZCVWJWMVdCLV9jT1B4ODJmeWxfRXBVaDlmN0dCOEVwMnRCSGo3RFJqRFBKT3VLODdCLWZ3S0ZHQmI0V3M5dWsxTWlrdFhlSDl4ajNHbEU3WVNXamxjRFRHMGtIVkplTnN4ckpW0gGbAkFVX3lxTE5Ea19vV3lOZ2RxdTlHWUhlNm9ELWZEYXRWV0RNZDZlczVQeHlUdkMwS2ZSVGdnVVdXMFNtQzR2elpJcVFhd3FrRmJ5Tl9QdzFSOTRTSmlUM3dqM3ZiVUZiZWNZcjlycVplbG5qNzFuTEkyT1RvOG1Jcmk3dG1qanhKa3JKNWZNSWpmNjEtbUM2YzNNcVFZYi1laFFZeTFLd2N6NXhadGRPdElHTTVEQ2VqWDZmelItSG12NXRUcVc0V2ZOQl9jSlJrUVRDZlEtWmRCOFkyVld5bWFJdDBFa0VzVkFmVUo2NHozbUtEUUtVUXh4NktiUlpuanNLNXRNb1pVMUh2bkRGSF9zcDVzQ2g5SVVoOTdZWEQwR0E?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T13:54:35Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nerea"
  },
  {
    "titulo": "La Diputación define las convocatorias para un técnico superior interino de Archivo y Biblioteca y para una bolsa de empleo para técnico medio de Turismo - Diputación de Segovia",
    "url": "https://news.google.com/rss/articles/CBMizwNBVV95cUxOMEVLSGZWenFRYjk2eHU0aEltUGx5Y1JnSHBKU1hTVkxSQkFzbmtvX2pORFlzcE9FaVB5Y1pOemhVZ3ZZS2c0OTZzUzE5WmFLdS1udmUwY2hzWFdLUjhVZjFZNVVIZFN6X0F6b3NlQW1SSWdXb3FFdFVqXzJwakUzNExNeWJ6eU1JREN1Rkh1LWZzU2t4cE81cEFadk5NazQzU29LRElmTHRyUVFZRkhLdTZYY19JZnJwQWZKMzZidzJXcWthTHdsbkd3SGxPakwwdWltbHdFelZmSlFoZHFrb2N0YURNenRZeEFLbWc2X3RrWE1ZTEl0RFpyTUU0Zm9jS3FNZ2hCSFN0TXRfWlgtTDlXYVlhR0x3TFF4aDJaTXZkT0kzOHBRSnhJVld0TWQ1RkxjQ3REdDMxc2I5ZG5GbjZwa1FqTGNPVVBzUk1SSXY0dzFrUS1Sd2RUSkxCcHAzTjNWSlhncjFhQVVEREp4OVVBZXNjZmZnUE5jTmVxNkkyVUNxYnBTWEtsYlJmWGdpT09nRUZmSk1FVUgxYlphYVVndC01bllQaGhnZVB2N1FTdDQyMHRkMEpzVksxWkFtZElySjdya3RnYVpsN1pN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T10:44:28Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Archivo",
    "ubicacion": "La Diputación"
  },
  {
    "titulo": "Gloria Cuadrado, fichaje de Ahorramas para el departamento de Recursos Humanos - InfoRETAIL",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxQYy1zNjcxdmpNZ2dNOUs1ZUJ1R0VQOFhOM3FpV3pBcGdKSFBpeG9iV3dTcmxCZ1NEblFHT01BTi12ZGhBU3AwMnZGNVdoUndpTEw5TnZOZFphb1BEelJvLUpPb1JWT1hESUp2WkNYeHl5Q2Vlek51R0VmbjJPMGlZTnJxZENNNkdyUjBnS0dDaTlmQVZ6NnVZZF8xVDZmU2J5Rk95XzZaa1dNV0NEQ0VKaXJHb1FPVTNvY2lKNEluQUMzcWYyWXR4YmdwUlhzX2dvWDhrUEp6TzNjWnlWRGZ6UlVtOGpLZUsxelow?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T11:16:40Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Ahorramas"
  },
  {
    "titulo": "El CSIF pide una auditoría externa sobre Recursos Humanos de la Autoridad Portuaria de Las Palmas y revisar las competencias de la presidenta - elDiario.es",
    "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxPYXhZUWxpaU9CZDJFMHhXZDJvZTAyV21vTFJERVI4bEdqV2cxTk9GTHNmdHA1Z3NsUzRtaDRoTi01MnZnV3F1d2dkN0pjRVBGVlhPYmxhWl9mZDN3bktBZndKenNyTTB3eW5wTWZNamprdDdEX0FDeDQ3ZTV2emMzSGRxLV9SZFBVc3d2aEZqdjFrNFdOUnIzSDM3bjZTNjRDdUhwRXJVNGNOQV9iLS1mazJfSzdWcVhnU3ZmazBnYjZZZUt0RnNhY3NqVGxmcHRwM2lLTUVXNGdLcEdyekE4d0RLSjExVWF4QTNJb3hCUzBRVU1ZWGfSAfsBQVVfeXFMUENkSnhBNm1TRjZWUG9ObmxxMms1U09WSVhPNDdQTlYwNlZpYllKR1Zyd0h1TU1QRVZlTnA1ZThmNVBldVc5MmlqTnVWcEpUM1BaVFRDUU85Z0doamx0MDloUHoycXJEaDZnMGxpbEI5SXJHR0JuNTVyUF94Z0h6Ymc3QWdHU2lnWkJxOXluSDVDQjVjQVlGM3pmWlZYcEhaT2JZY0IxVlplTDg4SGd0R0IzS0xyMjRLbllvQU00YXY4WHEtRjlYZjBEcTdGWF9wMFJXTHZPNGNKTEY5dUsza0pOWjZfUDltdUcyRmVIY3NqS3dMWXNSU21SMlU?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T16:31:12Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Autoridad Portuaria de Las Palmas"
  },
  {
    "titulo": "Francisco, trabajador de Recursos Humanos: \"Si le caes mal a RR.HH te van a impedir muchas más cosas de las que crees. Incluso en situaciones de conflicto\" - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMikAJBVV95cUxPX0hUWHJ2WklHUkd6dW1SRXlFTGQ5Y21wUzJYb1Y0SDVHcTlzZHFvQWtLbUlhUzBvNzdockVGal9zbzFwS0FLQ3dLbW9CbndoYzJqNVFBMUt6VHpHSXFtNVQtY2hwZ2JBLUpiY1JJS3NEMTdtLThMSEYxUENFZWFsdDM3VHVCYllON2xycTRjUUhwQ3d3MDRhMmhGeFlOUUgwUE1CTTdVVHZOOWg3Y010Q25WNTVqWVJOLUxjYkhKRFZ6SV9tTXJ1Q1dYX01CbFY5alFKRHRKNHVydjhLSU1uVXlVU1NpanQxbnotRXdobm1VWnhXalgyUnZPZEJmMzZsdlh6ekY4RmRpYWlaMGhKUdIBngJBVV95cUxPZmlqVmVWbE14UmpnWDZUd096T3JONzhNQmNjQ09yU2NMSUhmMHJseHVRZEQ5cWpvNnFnejFUb3FMQUtteHBUU2JZQ2U4bXpsZTFzaUlBNk82LXZMeWhZZDZYWm9LNHNGSVVlTm8ycjZKUE9wYUJDdE9WQ2gyX3IxSzU0cmVSbkJxSmZkM0g1bjZyYmt2d2QwVnMwbGMySUhta0Z4aUwwQS1hNFQzN2d6WGhMaHBoSWxXajF6ZXc1LTIwbGl4bi1UR3BxN3Fja0oxd3VlVG5IblczTjJnTGRZUDUteXFrd2tYRWFBNnZrTFZzdGVzenoteVZhYUdpTnpKVnJDYTk2T29SZENHcG9zbkQxQUVBYk5rX0tEYjdn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T16:43:28Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Marta Suárez asume Auditoría y Control Interno en plena tensión con Recursos Humanos en el Puerto de Las Palmas - Atlántico Hoy",
    "url": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxQREdfaU1IdUUxcERieGNreFJTczRWV01XYlpMWmhWMVdXVzhsUWNlbEZINzRWWTBNaEp5NDlPaEFNd1hBRW96UTZlaFFOSGdxY01PMmRBVWhDN1RZVnEzWl9UZzgtVlRMazA1cnRYUUtGaTg0Q1ZoZ2RNWU1TamZhSUtPdUZBNGVUQ1RoOHUzUXZNcTJsT054YTY5TEdheGVrelZxelBOeVJrXzF5emNZeVVvVUxQVUJfcG5MNEhXRlpneHo2VExZT2Q0bm1pRnUyTFBDcnBMZnBCWHJDNHB3bVdycnYyeVV5QXc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T04:00:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Puerto de Las Palmas"
  },
  {
    "titulo": "HR Startup Competition | Tres categorías, tres ganadores y una misión: reinventar los Recursos Humanos - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMi9wFBVV95cUxOU3ozUld2XzVMclpzQlBlZWNTelY2bHBHa21YUTVNQWlrS3pGX2RQa2tJbi1qejN0c19hYW0wdnRvdkNaWENkZnJlQVozaVlSREY1WXFmYlNCSXN2NTZRUk5FdHR5eU5xbWtIS3NrNjBqVXJabmZCVkFneXZ5R1cyeUpnTFA0UVZjT0ktWlF5clN6SkdFbVZPUXBheEVYaHFXUXdtcXE3RHBNbjg4cDZkS2RFbmJQYmFUM2g5eWstWWhHcmduaXNPa01BdU1mRkJFYlJJMDBXNHlDaXBnb2hCaVVVUWlleDE3aFJTY3RJemJXeGNOd1Fj?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T22:21:55Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "HR Startup Competition",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Ayuntamiento presume de tres reformas \"fundamentales\" en Recursos Humanos tras aprobar el Reglamento de Teletrabajo - Diario de Miguelturra",
    "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxQWGRsLS1tcG5UQnFPb0tQbF90Q3JlblJzTFgxRjJJVUNwT3UtaVZGeUJaSFJuU0M1SHphVFN4UElCbDUtX19yQ3lLY0hJVXhCOTRYNDlqbXhwbnVhUE5fN0JXZjZGY1luejBtRGctTmxodG4xQlc3SDV3NzJLNWlfMXZMb2NLZjBDM0c4TzZsUnBaeTNVRW5UeXhKbE5TVDk0QUFuRG5RZ3E3TUJRRlN4VmZrYnljbklreWh1bUw4NXNXLVBPRGxLUVZNUTJNaWM2VjdUMVVYWkw1TkFZVUVSNTN1OA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T12:00:57Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento"
  },
  {
    "titulo": "Recursos Humanos entra en el centro del negocio - Revista Capital",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNU3RTLUNNN3JOcWgyVTRBMFBmak9pVXNlWlZ2YTg4ZDBETi1zMkt5aXZVR2lPREtSRkh5RnNWdUxnRl81RDhqbkxxbHRpTFNTN1BGemREQnFVZlVibnh0VXFSbElOalZjTGxSMnJtZkF4OC1OSlJDTnFRVFNmNG42M3hKWHRBR0RyS01GcVpUV0FLN1c3?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T06:00:51Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Laia Calsina Blanquer supera el proceso selectivo del Ayuntamiento de Manacor y se hace con la plaza de técnico medio de recursos humanos y será nombrada personal funcionario de carrera - MANACOR NOTICIAS",
    "url": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE5XZi1sdlF6RGxmOFE1UDRCalZYUDl2NUtKVGFiYkFOZEJ2djNjdFJGd0pZSHNYWkNDLTlpUS1EaDFRa2N2SHd6bFh3V2dLamNZNmFDM1dHdkhHTmhEbGw3Ykp3?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T04:58:48Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento de Manacor"
  },
  {
    "titulo": "Orbio AI cierra Serie A de 18M€: cómo la IA agéntica revoluciona recursos humanos - El Ecosistema Startup",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQaUhYWmR0Y2hsVnVsNE9oU0gyYmxmeVhwcURKLUJqNWdnWGdESXpPWVl3VGpubEZkT0I4czI5enhLMlo1VndfdnZXMWlIdjBYSGNZbS1MQ2E3RmFYMWlja1c2cVNkLU0yRGc5RnB4VTZxdHF5TjZ3Qy04OHIweXlVX2R5WE0xQ05wZ1pMbkNOVzNVS1RCejhLTXREaHJIcld0TzJCenFSZTRBNTJaLW1Oaw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T17:54:33Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Orbio AI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "David, técnico de Recursos Humanos de Aldaia, se planta con 25.000 euros en ‘Allá tú’ junto a su hermana - El Periódico de Aquí",
    "url": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxPMC1qREZyd3hsN1djdWNiZTlHbGRNUjV5a2xWSVJrdlA0T29uS3liUGswLVVqSTNiWGVFUWNfenUyel9XWWQ4ZlV5ZURFUVlvckEwd2RUemR0c2RBdUVQMmxqakpzNWJWb1V5Wm5jR0J0a2JTOUxxa0wxS2dlWTVkTk9YOWotY1JmTUxaSDlsUy1Ca05sYk1yRzN3VnpDV0VNektWWTd2dFcxdGpPWjQtbDZacHgtWlFvU3FYemxEV0dGUkphWHVfb0VsZ0c4UHROREQwaFAwYVFxaVNMUEtKTmtJNlZFcTlNX1N3NEF5amE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T09:01:20Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "‘Allá tú’"
  },
  {
    "titulo": "«Seguimos imaginando que los ciberdelincuentes trabajan desde el sótano de su casa; son organizaciones perfectamente coordinadas y con sus propios departamentos de recursos humanos» - Faro de Vigo",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNLTZWWTVFcXJSQkI4cU9FVHpzb2RNNml3cmxhR2tzODJ4TG1MRDd6QjVuNFlvLU8wSk5rZzVTSmVuYnk2bzlGYnIwTE93ZEdGY0ZtcTM4R0FqbDNsYmxZOGFmZE4yeU4xLVZaRU5nb1VrV05rSEJRSUMwbklDX1NENVFqX3VJV2hTaEdVOHhZQTJQWGN2SFRuVVNscHJRQ3VySDRrUnFrOVF3c29NLUNR0gG0AUFVX3lxTE15V1Fudk9KWmhpRFVfUVQyX1U2ZU85TmNGMi1ucHlFajlpY2h0SF9haUVPR0ROSElCck5RX3FQOC1Zd1RSekIzMkRVYlZWQmluSk9aUk5LSjY3UXRJczlhYm82UXVzbXdEZjU3THE2WU1SSkgyaG9LbXNCaHFnQ1hqMzBUOVBMZFBwcFVaeHduWlNfdDhIMWFvdlFYTzJ0TnRidjZrU0Mwdy0tSzZEM2lqdHdTTA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T04:10:03Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Faro de Vigo"
  },
  {
    "titulo": "Señales de que estás sobreviviendo laboralmente y no construyendo una carrera - emprendedor.com",
    "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxQUGN0THJRa2ZGdmtteExqcWE5ekxENTNCbFhsMU1RcHBiYWIzT3F6ckhOcjljWTNpUndZdVE5MEhoYnpYSlp2czlvczg5cEVUc1MyYVc0SDNoelhoZWtvV08xV3gwOHRZQnU5QlVRQXpWSDlCVGVIQlo3NE80bHd2WnJ30gGHAUFVX3lxTFBCUE5QTEJQajBqaGZTcnBaRHpTZHVkWktUQ1VGZzlkMlpTQW8talBtaW9zV0FmZGhOQkc1YXZzaDZKaHhja3hhWUR5cWJ4TzQxNU9zZVc1TGFOSHhBYW04dGJGQ2tjSlk3MmxjbkxsZU5GaEtOQm5RYXVoQmRCVTItLXZBMURaUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T19:05:58Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Promover la cooperación tripartita en el desarrollo de recursos humanos para la ciencia, la tecnología, la innovación y la transformación digital. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPUElpUFhldWZxMndOcWZ3MnNVdndXTWhYcVYzcE5yclBrVXVmRmc0R1lTcFJQMDNlTUttblQ1Z01KZkgyRUpHd2szcG1FYWFsMURJX1V2TV82NXZuS25QWmZBNFQ4U1VUU0dFeVUzTnAxZlB5eHRFX19MaEc2d3c4N3YxUDNQY09JNXpwVHhubFdXWHlveTZMUm5lWm9nUFhXS3JNRzJ6YXBaWDVOLWpaSTFzREdGY0tIeGNZc1p2eTFQWmxSOWhN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T09:36:44Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Opinión| Talento mixto en el sector empresarial - EntrepreNerd",
    "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE5FWk5Cbndfd0ZjVUNpdGZJRjJXTkkyUGlIUUhyQzhMZ2xrQUNLeURac3JEOGFVaXNKaFRTUGJyR2IzOGlFMFNjVjVBYVlRc2k0WDNxRHRiR3BPeGFVRDRmSEF1SDRnYUs4R0hIeU94YTZjVlB1dlhMSF91aw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T21:07:14Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Mejorar la calidad de los recursos humanos en la era digital. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMihgFBVV95cUxNV0E3VFpvcW9aa0RacEd4c3lCRGo0OG9rMXpldU1aWTVjM0UtcjlFd1BreTFGU3BUeDJGenA1b293Q2RhdHJwczkyTU9DeGlTQ20xS2k1bllIei1IU3E3R2lUMmFpM1BmQ3R4cy1uV3hwLVplSmpEY0Q5SGFtdW1zbU5UWU5SUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T23:32:50Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Desarrollar recursos humanos de alta calidad para la industria de defensa en la nueva era. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNZll6ekEwYzJIZzZPaVhab2V0dFE5b1dYaXlhVnhnMGhsdlcxYlFWb2JLT19ncVJJUFY5VlJ0ZnZNcGRHQzFwdEFhUTBTNks3TXFQWXNBLVpKTk04eDNDdlFlUFZxWFhfVF9ZZDRqVGVYTmh1amdlOGotX0ZfZklMeGptRDBSeDd2VUFxbVU1cENYcW9fMXhpbUNXRQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T16:08:38Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La formación en recursos humanos vinculada al empleo en la trayectoria de 20 años del Grupo ESUHAI. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxNUWVINmJGeTcyWTJwM0ZHU2U5M28zR0Z1UWk5UFVBZjJFQUtBQVBUamJ1RlZjWFF4U2Q5MXlVWkZ2QmxZN0VnYTltS3ZqczlnVVYtRG9LcVVnUFpFUUZCS2tPQlVKeUw2ZHB4NnRTZjg0N2dfRlpuREgybnU2cXlKdkNKMWtwUEUyMW5NdHVFejA1aVdaLVVadGozTXczOEs4QVE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T12:50:31Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Grupo ESUHAI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La colaboración tripartita genera un impulso para el desarrollo de los recursos humanos en ciencia y tecnología. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxNc1UxNjFHd1pDTHh1VVpuNmVaWmN3cnZHZUh2ckFDMmNsODhNSjV4NWJoMXRTNlJxZFlWNTNtMm1xUFppdVQyai05dFR2ak1WZVFqZm1YOXN6bXRTQ2hSTlJBVkJZaDdwUXFwNkVjdW5VRjBQLWJwcVMxTXQxOEctQms1SEE0NGlaYUp3anVMc3lkai0wQTBJ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T07:36:38Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Capacitar a los recursos humanos para dominar la era de la IA. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTE1Gd0Y2dXJGaUVpQ1dmMEVnUEphaVRnRUpzcVpJb0dEdGp3SGx0RTRUd0o0MnRlOVZwVml4Y2VPYWlya1RWc2RCMThOR1hPZGtYT2d1ck5KTDQ1cWlpQXZaNVJIOS0xa1IydEtBeElDOA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T01:04:27Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Qué muestran los datos sobre el rendimiento y la productividad de los profesionales mayores de 50 años en las empresas - Infobae",
    "url": "https://news.google.com/rss/articles/CBMiggJBVV95cUxNSDFmenZRVXg3Um1EWG1vbUs4bk01YTRIMnNPMEQyeGlfNng0cFZCR1FIS1VIX2hnZ1FpejkzUmNMcmtBWVRnaUNXY1FvTVR5b3p0SVc2NkZCbm1VVmJ5THZ1WWc1WEVtR1BIdVpTeVZxVVY4Y3RsbkZzVU41bzloTzhkODlZNnZxMlJGWjB0dzdoVndtdWFBdjNpN19mb3ZydVR5TkhMZFllbHJKaHhCNVJkRDN1S3pfbW5xNEwyV2U0ZGhhaTJiMTF0RldCQXhtZEhlNk5LemM1MHlZWnVtMDQ2bkRYTndoS0ticWV1V3Z5ZXYyMURnSG1fNlZIV0J4dUHSAZwCQVVfeXFMUDRlcXhMZHpaNldiRTlmLUhnNGgzUk9QQTJSSkloNXBfd3dUak9WRGZKYUZ5aDF1S1htMERFV0xoWC1mQ3V2bll5MWlzVFExVlUwWHhCd19LWjJGT2N3d0xNNUItbmxuN1g1Q3pkRlF2cGNNRE1GemNuTmVKblRxOE5hdjBPbWZlRUlfekk2SmRjZVo5Q2p1cmx2MUxPSXVFUm5uMEJUZ1dOQV8tdk9EYlJ5YThNRnRPU1BJU3V3M0czUzc4TUJZMkJPM2pkVjBEVFNhS1dZR2l5NkZxbHRiZGo5eGFBVThxdGRORGNPMjJadzJEVmFkaEItNUtTUG1tTnA5c1ZSU25VWmNwNXlKb2RQQ0k1ZGdhUjFEMGw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T04:05:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Generar impulso para el desarrollo de los recursos humanos a nivel nacional. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFA4YTFpWEhTdlBlWHA2eEplakw4QWF3SXV0TUlwNDU3WFBmMldYRE1YeHRyQjdndTgycTJfdE1uV05HSnFiUlQyQzlSd3NMdWJiV2ZWOWw3TFgwN0hidnpnRDVQOUtiRE1VSzFVQXdzSTNhRG1INWhzZTlTaWFVdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T04:13:34Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Desarrollar competencias en inteligencia artificial y preparar a los recursos humanos para la transformación digital. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxQZEFQTFhVSk1SVm9PSy1CeTd5bml0WDQ3bEszUllvX0U1UXhiZEdsOWhfdVFNQ0lKTjRWZHQ2MHl6cFlFRXFia3lsZlZYeXFOUTRsd0xodnB0Vlg3cmtmdUJtUV9nQnVtZWg4N2Z6QTVNRDUwUVFIanl0ZkJhM3RtWWNOMTFieWtCNnIxZDJkSVZmQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T07:00:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Los miembros del Parlamento proponen formación gratuita para el personal de recursos humanos del sector editorial. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxOZnBPMm9RYndRc01kSEhEYk1aeWIzY1hQZy1NT2RwN29uakNBRmxyM1VDYWhhc3Q0Zm40aGR5NW01Slc2aG9fZ3daeEkxWGJVMWpFVVZrM2xGQ2tKZmdIa1VPZmtCTncxeEhienV3SW00VGRQVTlJRFo0czAwYzdOZW95VDBEblJJWGtUNkxFU2V3empOM3k0?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T08:39:19Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Parlamento",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Complementar las políticas de desarrollo de recursos humanos en la industria del petróleo y el gas. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxNXzFzUTZoYXczSXdlcXY3Zm5sdWQwVk9TTG1uSWtkanhlaHJyQXJqWGdlR0l4aW5WNlpYcXZKcTJNVFYybmZyd1VHUVZCTWExaWlpT21PSHBDSmgyZjhrYVF5WWhleWU3VFotaV9abWlibTQxRVFYS1RXSkJxX3ZTamU5ODE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T16:14:22Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Cambiar la mentalidad y preparar de forma proactiva los recursos humanos para sectores clave. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxNSG1lUDR4RHB6VGtXM0o5TmF0cGk4a200NWZldzB4dTdLc1pqOW5PbG1HZmpOWlp0VlpSOXhsbHBHanVwRnFjREdmMW11TFpfRHlsOExGSWZQUFd5S0hBZGd2OEtWX1lHdnI4UVdMRm5FQ1MwVGVoOUZuZnpZUkl5OU02MVBSWjU2M0c4YWNwaVN2bC1OV2Y1MHZuZEtRMnNCVWJ0Q2tn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T14:15:23Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Fortalecer la cooperación para el desarrollo de recursos humanos de alta calidad en el sector de la salud. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNeElhTmQ0aE1YeHhQektDNUdNRWl5bVFyVjlwa2ZLOENBVW5uZUJQcGNlRHRQcTgwX0I1WFBuOFN5YnJFVGJvUDNQRmUxMlFxZ1FDNE5oRmdQYTJyZ0tHbGdYMm1oeTJHYmFfdUJ2Q0k0SnpteG1CYURIVVJzM3RJNkRuTHhNcDQ0NzVOWkh1MnRfYnot?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T01:28:49Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Es necesario prestar más atención a las políticas de desarrollo de recursos humanos en la edición digital. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxQczFhYlZQV01TeWZuSGlCVUhuMGRPWi1VRWNPTVB2aGRNandxZk0wM0JSOHJPQkFSeWZ6Vm9tVFpxemw5QWx2aDFYYTl4TWh6bHBTX28wVHhjUEJKTzU4a0VYNVUwMVBXd08tVWFicGx1ckdhUjJWRzJFSVhOczhqWm9za3p6UnBnSDRiTFRxc1VUWWNZODRKYzNpbm82Y0tm?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T16:33:52Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "VNR - JR East: Fortalecimiento de la cooperación en la formación de recursos humanos e intercambio de experiencias en el desarrollo del turismo ferroviario. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOeWNxWUhVb3JERE1nQ0RhMmZpMHl2QkFoY18xT3RJYmZFZlJHNy1Gb1BiUEhVMDJJVnBjSzE5VHI1WVNMMlZpRDBDS1U4b29JeG9SUFhaX3IxczhxcUpFVElJS0xQOVhKVzNsaEQzaDNFS2NCTFBBYUttc2tMX25NWGtKS2FHNDJoN2libzBnOGcwZEdNQ05lS0xuYzdhZFRYOG95MXc4X1VUTnVpZTd1X2FsWWhaWW10dzBz?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T15:46:56Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Randstad busca cubrir unas 2.300 vacantes para la campaña de vendimia en toda España - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxQWUNmSmdkS2FfVWF4b2NRM2VOMENDbFZrZmVaOWZLTkNnV2xUbG0teVZzOWVVTlE4ZllIWVpUdG9Tajliem1RY01GZWFUUTZKWXA0cy04SnNBb0k5TDlyZ3FpQTh5OGNfVndmbWxsUmtfam10M3NLNV9CY3RyQkFnVzh6UEVPM3g2U25BU2ttay1vQVl2NWdSdExSZXViYmVaNFIwa1FCUVZvYkFzV1lRQlhvT0YxWnE2cExtbWEtLXBzMEVYcEZLeEFNazNWWTg2alJBTEo5dVE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T23:32:45Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "El grupo Adecco lanza Reverse Matching, una herramienta de IA para recomendar empleos en función del currículum - El Diario Vasco",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxNT0d1cjNhMmxPZU1ud2d2V0RtOUZmZFVvYlFoT3NUMnlEeUNDNlVpOGtiQXNMdndoWV8yTy1XNk9Scl84UGF6QV9ldDg1SmhybHFWaG03cllLcWxJQ2x5T25CRFZrRm55cHdVR09JRjktSjdua3V1eE51RTF3M3hmTVc3cnhtSms5Z0lWZFB5RW5waEFKcGxfMTFlMktPd1p4N0FXQlRtai1EMGs1QnpadDZMTDlQaU0zdWfSAb8BQVVfeXFMTUdfNUNHbWRkLXJKY28ySExhRGxXaW5jVVJDM080bnc1ckZxSWJEeUd2SFlHZ0pLSGhpT0c2MTV1NUNodUtieUNXc2dPWW56TWp0anJYNXlXaDNxekE3THhNYkRRVEhZNmtxWkxyNTdYVWllLW1yS29zUUpvbjZ6VEFsV2hjajZfQzlrbWZCdkRqUFR0RmJNN1E0bk41Mk5tbDM4c3ZETFVmU3lMMmFpS3ZZT2h1VGVJRldxV0wtbmM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T22:12:28Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "función del currículum"
  },
  {
    "titulo": "Adecco refuerza su negocio en Iberia con un crecimiento del 22% de los ingresos - El Conciso",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNMHlzRnZ0Q2lJVUppb0pTdmRhX1BrX2ZldGtNNkVfZHJMaGktVmhkVnRrdmExM0NHMUdLRF9Yb0tYUGdGVTFIVHlTMWRJbjVKUDJQUUVKZGwzeTZOcUZKaG91bkJaa2JtN2JGbWMtckVjLXNwcjlpRzdkcXNqWVZudjNFYTVsWHRzWGJQa1hkTk1iWXRJ0gGaAUFVX3lxTFBaM2ZKeU9hY1FwaTJHUjYwV2UyX1NwZjk5NjBfRktSMjNZYVBaZjVPY3lUSlRNZ3RUUnRRZy1jMk9acXZDZEstWmJmNWhScmNOVFc3M3F6cnN1c1Btd2lEVGVzcW5PQ2NHSVV3UHZVRGx1V3JMYmlYenBXODQ1dFkteXAxZHVNZk9yX3owcFFTTGpiRHVBUWlrSXc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T11:20:45Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Iberia"
  },
  {
    "titulo": "Price to book forward de Randstad NV – EURONEXT:RAND - TradingView",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxNejlxc2dmakl1TlNtMmljVkw4YThFTTNMcXBfWTlvR2RrZUpKQXV5cmctdEgxd0g5VUtxWlIxYW9NU2dOZ2dkMlFJZEJDbGotTVplYnBKMy10NE5wdTlGb0IwMXlILVo5VGpBdF9xZ25qd1dYcXFTejlKc29KU3cwZDlzTG9ZU2tCSzN6SDRUYzZTdzNYWjZXSjZNR051UQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T04:40:59Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "RAND",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "Adecco Iberia se consolida como motor de The Adecco Group con un alza del 22% en sus ingresos - El Confidencial",
    "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNQUt2dndTazk1NUdTbnpKb1llYjZTRFlYdWpXMzdtQmpiZmhDWVNybFRSeGY2andxSkIxWE5sYnF4QS1fR2kySUtyeHo5NDBMRmk4dFJTeHlfWnAxUjFfUXhlc0JMOEo5NjZsZ3poZzRYUklyV29vMkZhTVlZVnVuUmNTck80b2VvOFV4SUFhcFJfT1ZHOTV0YWtIejJvLUQ5MG1PVEhmRQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T14:35:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "The Adecco Group",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Resultados de Adecco Group en el segundo trimestre de 2026 - PR Newswire",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPZmw0Mmc2UmpuYUN3c19vSnJId2FXNTJSTlpUMlBqR3E1bnBiZkdPTEpHblpKM0RYaTRYdlgwZkh5Y3BWZTRjNXh4YnNDWWxLanhjSENfNHBQb2NhQVJCWGRKSncxMzBQRFVVRkduY1VnUlBwYm9aMVRpNl9KN2dFMHJReWpicFRxb0pHVGZBbXMtejNBOGV3bjg3aVkxLWt6OEZ6ZjlTQ0I5N0xDanM1N0JzUGU?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:33:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Reconocen la antigüedad a un trabajador de Gullón procedente de ETT - Tribuna de Palencia.",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPbGdJVkxiTVBjWVp4blFsNU5rZmlZSjQ1ZTJ0QTItM1BqYkowZ01WZElTWEpvNHFXTENITHBrS2pId2ZGZXN4RUtKZDQ2U3RJQXdvNVpzdlF4aGtBUkJaMmpxc0JoX2xRaHVTRkx2M2p0Ti1iMC1uOWpCMkZ1bTJFQ3FsRmpFMlRxWDdyZmZEa2FKU2R1V21aQW56aWkxeXFPdlB5Q2hKalc3d0RXcGZLSDRhaHFYZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T15:55:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Tribuna de Palencia"
  },
  {
    "titulo": "Adecco oferta 200 puestos de empleo para el GP de F1 de Madrid - Noticias para Municipios",
    "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNOUFmRXNHLWdGdUVpVzdvZ2xtOTBhcWNaNjlmNi1ZOTJuSXotUFFEV0g1RkUyUlFwRGZMRUc4emR2aVUxZVUtUkV4Zk9PZnFrQjBRTFBYWjdEaEJPMENMbUgyS0pkaXFZOU9tY1pvWE4xVXMxaUtzb2RHZE1COGx3eHMwRE5oeTBDR1BycGtkRklBZWs?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T11:56:28Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Madrid"
  },
  {
    "titulo": "Oportunidad de empleo en la Fórmula 1: Adecco busca más de 200 profesionales para el Gran Premio de Madrid - larazon.es",
    "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxQZFpEMDFRNTdmLVN0T3lXeGw5YWJCTGdFSjZET185UWRyVXNrYm9BdzVFVVdob2NzbnAxMEV5c3BZN2VnUjgtYV9TWVhtS1NvLUtJTkJzeURURGtMZ0J3TWNHczZzbHFBeWVQRXZnbmUxdTRNRW9VU0ExdnhJNVUwbkdXMkVmVy1pWXJBRWUycHJwWTM5UGg0cHhhNzFJOGZkUmxqbUpIZlcyaDYxYjJueEg1blp6N1d5clV2ZzFnalAydEZQYWI1MU1JaGl6NUtIUWtWRzNnUnJYZ3dRclNDVzJNMTVrYUHSAfsBQVVfeXFMTWE1VlFzLVkyOEdBNnRmUEludkJsTXhoMlRDMTQycjdieTA1a05DbUs2TVVIQVc0X2lMYjdMY3IwOHZYU0UzMDVGTGdKVGZXbTRObUJUamxDc2FJYjVYbzhIY2lGR0dDQWptRnNsTEQ4SzlIcTR2NmlhelFTYlFIQUJDaXpzbDJyNERKb0VVSzRsN3dPMnNlWERqd2Z3d3psYl9TNmFNdkxkMHVsMk9pVWt0NEpadWNrSTVoZ1dfaUViUFdya1RKSWh0MkhuYTlqVm1peTJOSTMxT2szWk1adlBFQlZJUzBKQWxqd0RuMXJxZFdwWmloMmdWUXc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T12:04:52Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Fórmula 1: Adecco"
  },
  {
    "titulo": "¿Por qué cae hoy la acción de Adecco? - Investing.com España",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxNODI5cGlZWG1TWjQ3ZGJUNHQ0U1lxbHQyeW80ZWVidWhJR0trVk9nR01HQ0xKbk5iR043VjZKRHdZcVFpUExOb19WZUluSXJTakhkQmF3Smg0M3M0T2VvNUpQa2pNaTBjUl9mek9SclVQcm92T1lVY1lhbVlSNlpNSlFGN1lvZ2RzTFh3REZxRDYxbHdUZDBfQ19BYjA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:43:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Una falsa ETT deja sin cobrar a 15 temporeros durante la campaña de la cereza en Caspe - Aragón Digital",
    "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxNbTREV28tSm40R0RXdkRleUl1X3h1U3NPaFZwYWtKeElZcnVwU2RueDVLdFRhbWpXUFFOeHBRR1pCX05YX0FqYTROMmFyYXV6b0pvNTk4WXk1MkU3TUFYdDZZbXJmRmxSNGJkNkxmaFdqUjI4TU9sT0QtVFZVQlZaM0o0NGhwX3JtUzdicEg5cGRHUkQtLXJJUG9JWkgxUmxYWmh3cHpQMGZ6b0VNNExwNHk3Sk9VR3F2dHRWZXJkbmJIWXlCeHpCQlVnZ25lckHSAdQBQVVfeXFMTjBzcHdILTFnTTlJbVJLSWYxRUJDaDI5UGpRZGUxTFNHUDM0UG5ZTUdCek9GU3NyTTYtcHZTd0dMd3FIRVlJT19VSldfZGtvZmpSbW5lNzNxcHNBLUJyVjN5NEI4MnNjSWc3NzFTaHlRbU9DZk9TNUtnYk1GRXRpTlFRSU5rNUd5Qi03NS0xX2RMS0NCU3BmMmRya2tnVnlORGtrdDJFXzcwNzdZUHhrUkJua25RTURoQllSa1A1ZGwzTFMyUjNuQlQtemk2NFNvaTdvY2s?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T10:02:52Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Caspe"
  },
  {
    "titulo": "Adecco Iberia crece un 22% en el segundo trimestre - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNNVIyYVlvdS1XUjBiNnhKY1ZMc01kazZPR1J2a0VqMld1Q2RjbVM5RFE5STVIWGVGWUhfYi15Yml4MTZZQVBpWmtDSmh3NnNxU1RHNGpTaURzQVUxQndxMnVUV2ZsazkwQ0U0QzVSNDFwbW51WHlYUjJIYVo1aXE5d3dxSGE0M1B6Z2RyYUgxaS1ISHk0Vk1iQVA1MGF3endJUE43M1VjWm5fdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T00:09:38Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Adecco profit disappoints despite better than expected sales - TradingView",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNSGIzVy1wWU04SUIzd2tnWmo0OVpmM1ZCcExjN1RuU2psZTZ0UlFZUU53VG9nM3ZZSjdTem9Gak54WHM0R3pFWU1IcW1xaXJvUURoRVZWSGVON2tRUmRObk9VUE4wQ2t6ME5QZUY5ajJJTzB5ejRJV3paOXVwZk9EUUFhdm1fX2hsdE13X2VvTlEyUi1KRmRnemRWcWRmSWtobTMzVjlyTHpCRTlOcDZkdVZhbUVYY1d3NklnUFhabk1nNTlSaTVTZA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T05:25:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "TradingView",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Informe semestral 2026 del Grupo Adecco - PR Newswire",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQUUlUUnlCMzl4YlZOUjVWbWtZOFA1WlJ0SWU3a01Hb2xHQkNOSV9ab2dCT1AzVVFVWDlMT0xxaTdUQkNIZmdKUzNOU0dDVDFoNzVDRDAzWnJVbnBlR3R5WjJaTkVoX0JhdkZXLWVjMFg4TUdJY3luVk52bUg2Tm5ISHhLTXZjVWhPa2E3aVNOazFPOW9GNWUyNUV5MA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:15:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Grupo Adecco",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Empleo temporal en el Gran Premio de Fórmula 1 de Madrid: puestos disponibles y requisitos - Madridiario",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxPMlhucXBNNVFCMkxIS3JaS1VfWXNGREpKTmxadl9nd3liMG1NUGE5emkwSWJGUGZHclEwRm9PUjJxY1FjYmFGeGhYWG5vT3RlOTFZTVNfemFJZUNJRm53dmxwaDdya09BbzQ0Mi11X0I2S0sta2xXdEhPbFplS0JodnUwUDRUVFNOZ0I3N2xkLTctdGxSdXpCWlJLN20?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T14:45:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Gran Premio de Fórmula 1"
  },
  {
    "titulo": "Adecco prevé que el empleo siga creciendo en 2026, aunque a menor ritmo que en 2024 y 2025 - Huelva Red",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxOaUlNbHphcEprUmU5bmc4d3dzODFsd2lnWHhIMXpRWGFNOEdoT1hKR1Y2UWhiWHNUckpUZXZLXzItUWF0ZGxOOW1ESlNFT2pIRjFiMkQ3TEg0QmRJUTFKcWNlUzc1dWlVM0hNYTB4amJoaXlTc19HVzdFNnFmUzdmazVzeGlFbkVGWFRDMHJhV3hKS0cyQ0pVSnNJR2pLN01MeDR4Y0hEYkJwYkJoeFZrNktqM0pYNXRQNXdNblh3ZXQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T09:32:52Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Huelva"
  },
  {
    "titulo": "Adecco Iberia crece un 22% en el segundo trimestre y destaca en el sector - cordobabn.com",
    "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxQSnczUFFoQjBIa2dyQWtNeUo0R0pfUWlseFREMW9wT0YxLTlJbUVBNlhQd3V4S0hMbmF3RUE0dWJYTGVZWF9ZZ1ZEUXJ4aVltLTkyX1IzZHE4MFRVSDhfckh3VEpzOVNZRW80VzQ3blo1S1doSFVIblBBUFFNMEhnZ2RxYkxiS24tdTZ5dGl0U0tRY0tReGdvRDJCWkFiYWdCV00zaXV0YmFXMy1yNHZpWG42U0RWRDc3TzBQWkptX3Z1a0t6NXBOOHJ1dVNuYWozVmfSAdcBQVVfeXFMTkZ0R2h2M0JrVmxHNU9SeExiUDFwcVdlR0s4VXQtS0tHM1Nad2d0LTEwa3dCWWRQcjVpMmppdTR6M3Jra0NEenFLcDYtUXZEbUhPQlhEMnVZaVB5dWZnTzBoQnN3YVZTRk5qWUNnZ3ZIeWNScjJHckgyMzRjeEdzWkRhZ3pOWmtHMjdreGp2X1A2WFFtYWxEUHBNaGtzTGRTN0h4MVF5bzNqckdUcmlEdFlXQlR4SW5TQXQ3RzFHakRIVVo4dEZIc0dVYk0yaVlnaW1kYUgtTFE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:14:22Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Adecco ofrece 200 puestos para trabajar en el Gran Premio de Fórmula 1 de Madrid - MadridPress",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQTUw0T3dNZ1hwUE13TkZqZVVyS0l1OTdJR0N5YkxBTUlNTndTUmQ1Z2l4eXhKY1NrRzV2d0cxWlkzbEFTMzdDUVBCVEoySTlxUkN2bDBJYlpaTUlrZDNQVGF6dHJuNjF2aGZYXzVxSlZwdGxPczNlVmlraFJFLTVKdW9QTkxPcHpYNUl1OS11OFRmS0ZfRThsTjM3bUc5US1YOWdHRkdzd2RMdzR6dHpncHQ1b3BLdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T11:09:33Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Gran Premio de Fórmula 1"
  },
  {
    "titulo": "Adecco busca 200 empleados para el Gran Premio de Fórmula 1 de Madrid - La Voz de Madrid",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxNak9EelM5dzY3OHlubHJfR2IzVUY1dERlZF9mbUlyZHhBdHk4em95UHRjSFZnQWJ1Q2tNeTF4NllXWFBMNlhGVFdlemlLWTVMNmVsWjNSVDd0djFheEZoT01ELUJXTXBYSlB0N2t5NnctSzRjMWU4cFFZcWNhSGVnVU1ZWjV2enA1eUVTam1GMHdtX2U1c0dfSU5LNHpyN19weVAwLWpBRE0tWEFLanAxLTRBTm42QQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T12:17:10Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Gran Premio de Fórmula 1"
  },
  {
    "titulo": "El absentismo laboral se dispara: las actividades turísticas más afectadas por las bajas laborales - Hosteltur",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPeTY4M1pWel93Wjkzam5aZGNReFNmNERMRGNtak5NYUhmNmFsMnNyOFRTTXNDRXZfTzdmVWRSdWV6VHNaRXduTHppOGtHTHlTRVFoWjYyaWxKMl9JTExScmZMU3ZHQ3FZYmlUMjhmS3NlWXYtZDkxendmSno1cVViWlgyUUZZZGxkMWFmY1hqandaeGk5SWNNMVh5OGU5TlhkMkNqcEVTX0tIUHdkWmowMDNPRi11NjJtQXpzSTVTNlJvT25QYlJRSnJJT3pTRDVP?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T11:11:31Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Sergio Rodríguez - ACB",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxNM1ZDdVZiV2Yxb09SNHlfT1N5b2JtZWdqS2tJQXVuRVgtaHNldVhUM0g1M09qMUk0Z1MzUUx0Zzh3RmZuS2tySEZYeHNXWTU0Nk9XdzNpZUJneUNMbndfMGZ6Y21UMnlTX3lHTUtHMklzRE5fRmlLMGdQZTduelpVZWhUNXlkZ081ZWlvamJTdWlXNU9JVFFXREhWdTFqUk9RamliNEdkMTNpRm1VM0F6RlpudXhzamtxNm9zcHNmSEFQVEdWRjRxMUlQMkNublpDMDVQVDhBRTY?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T19:38:53Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Pancho Jasen - ACB",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQU2pUMFRUVEJyZTlSUzEyeXp2bUliMF9aM2FvMVBtSlM0NVlxZXVHWVZzN1lRQUdPSjllUHJFOGFuU3B5NWg4XzczTng4SmtaY1BuLXJjU296S29BT01oNzZHemxMNXJ1T2ZhdDBlUjRZMUNNTjNvajA3dll6dV9TRzFacU9QVzRzT3B2NnRaSjZyYjFDWmc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T17:47:47Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Informe semestral 2026 del Grupo Adecco - Bolsamania",
    "url": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOLVAzYzRaX3Vvc2l4S2gyaTNfQjdlT0E2U2VKRUJVTUlMVldTV3FoaTdBNzlJVTQ1bzFnaFpyOXZleGdwZmlMNkdWYklnRnRiMUxoSXBpNjFGQ09wZ2N6ZHJ2bV9CTkt2SGpNQkt3RDByS2FfUFFaWDNGSG5tMEkwck16MFItNG9iblVXcERfeEJ0aV9wcGYwUmp1bmxlOXotcGljWVpncXDSAa4BQVVfeXFMTmlqRXFjNjVDZjJGbVlaOER2NExQcGF1YTczVmFGdHNfczF6blp4VzZPWTBIOUN0NFZZQnRNMzRJeHhRcFJyUDl4WlItN0FyeURwNU1IMmtUZXFfNlNYZkFFbF9JVEd0TmhGTXRIdFg1Yy10XzFSYXVCNnNVWnZKZGdvb3FwUC10RTdsUVA4ckZFTGU4SkFTejF2SGNkRXdVVzRPY3BpSTkwb2dPQnNn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:15:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Grupo Adecco",
    "ubicacion": "Bolsamania"
  },
  {
    "titulo": "Profesiones mejor valoradas por niños andaluces en la XX Encuesta Adecco - cordobabn.com",
    "url": "https://news.google.com/rss/articles/CBMipgJBVV95cUxNeElrZ3RKdFJQVGR4UWlqX1VsX2dodzhnVl9fSDZfZ3BiXzl4MDVYRWxRQWdydXMzZzZscXhUS29LSkZ3Q1N1M1ZEeUNTRmxPeWFYSmhUTFhmOWFXZUFaX3lRRGo5UGJOU19WbU1TdmFxVXVmRGpsUXp2ZVBJLUtDSl9MS1JydXVJVm9BSU9JVk5YUzlZWmRDWV9xWC11bU9FZWMtX0VxY1FwVWdBNFNKNUxmQko4VkJxZTFtQ2liSFdsOGpoaUtGelZhV2tWc3B3dE1XazNiRl9XZ0pnRk1wQ2V5eUE3Rm1zRW9LZk9GMllXTHp1TEtnMXQ3ekV5R1NHOVByUXU0RTBzZmFqdGtYNEtMU1dGZ1FvZlRKaC1ZZ0ZlNllBN2fSAasCQVVfeXFMTjRUZnVoOG05dTVONXlXYWJ4aU01TUNveG8zUFVQX3ZlMFgwWVRHS1FXOWtHejZPTU0xam5WeHNTajlkT3BBWmFfZ0MxMkZYcHRsaWh5V251OFVhTzgybEFBQ2RLNER1QnVhUDJaeUs2R2Nad0NwdDNnLWVnVFZ1Q3pFdUxhcDJiWHNBa0d1NG5yclNMdU51cmd5SE50VkR3bmd3Q1JGcG5oX2pxM1lLd0dpNFZEaVJTcFo5b0pLN0ttVHhIclNVeWtWNk1NRVJIV1dXTmU1WV9SMDJhUEhsUTFHbHYtRHA3UnlsbTRfQU94U3M4a1JNanhvQXl2eDJhbUtvUWVlYWpHeXc1b0tHYjhNbXJGd3BqRjBZTXBZcGNmbWZ2Skc3OTVnbWM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T08:22:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Partidos Juan Ignacio Jasen - ACB",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxPSnNpUTNqMEdXQ1NSb0drWFB5YUtNRl9rZVNvR2dsTHBhMlY4Z0JuSGhDVGthT0xzM2JhR2dNb1dUaTViSWo1a25OMDZjS1VpaElXczlUY0JQa19pbGVPZDlacHljYlkzSzVUVU5zSUlIRXdxemxJTlR0WWRmQzRPcnBDZlMyb1RLSldiWFpCcTRjRmJoVWJvbFRISEg5aUYyTkQ1YmVsUFFuMnN4eWdOX3ozRnVzNGM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T22:17:27Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Una falsa ETT estafa a 15 temporeros malienses en Caspe y desaparece sin pagarles - moncloa.com",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE9ZTEdYelN0bDVhUmM0SkJ4bXhSLWZsMC1WQ3NzVTdDMF9xS3lvbWk5SEFMUF9WVXFDanVSZnF1RGJISjlhYlB6dHNEd2FxYzAyNV9QWWpBUWF6aTBGOHF4YUt5djlVdFozRmhrcXg1ZEhCUTI3a2c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T10:30:43Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Caspe"
  },
  {
    "titulo": "Juan Ignacio Jasen - ACB",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxOR0RSaXFacnpTYXdqRTgzLXJHdWhJSjkxY29oUTk1U1FFdFlVNm45anFiZFNya3RJb1RacmRTaGZjTXJ0MXNjZXJfb0FubGlkRlpGTnNMaVNTWjM0NjFURkJKdUt3UnZFSFViU3lIcnpUWXVIMFVNQ283d2hEMHR1OTc3ZFNoYWJLV285aUpDc0VSSy02RUxxQUhiQzllWEM4NURtWjlwRGFIN0k?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T21:46:37Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Marlon Garnett - ACB",
    "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxQNlcxZzJCRXFFR2JiamZTc1o0U0JfbEtOd2tCWXVIcXJTLTJlNk55TDZhSG1RQTk0NFF2WllLZHhkbHphOTRhRldsbHhBZGFiVDkzdVplUklKaTlVVV9naTVRVEY4dWRrOXNFcWJBV0ZaYTNTZ2xrQnhDdmxtX0FkOVhySllFWllrRmZscVJrT2wwUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T18:43:30Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El 33,8% de las personas con discapacidad en edad laboral en Extremadura trabaja o busca empleo, según Adecco - HOY Solidario",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOUU0wX3JEVURpZ2xJSUw0czZ3SEExbm1JWXc1aFNmV0w2X3U4S3BxWjNhWWJhM3EyUkRlRUlZWEh1Z1JlWXU5WjJXeU4yWkdwaUExSHUwY2lYT296WTZVRGpjQXl0LWtOVjIyVXBFemZ6VjZiNFRXSDluSGQwazl0aFktQmg5Y0lDZHBrXzgteTdBQTZCN1NJUUpqemVGdnJJNGMySWJfcF9Id9IBrwFBVV95cUxPejZ6ZllNYXJZeFFRdXJRbFlDa0JxczFiZi1xazVnYldRN2tUWG9fbFQxZ3haS0I5TEYweVl3Uld4cDRVMnB0a19FWllleG52VEFtQUhGNklLVWpyQlhZTWJvd2VzZHBHNjVsaTkyMHYtRjZGRXZfcDl3Tl92WjdzQzJ3LThGdzBqQ2otUkpxOUR0anB0ZjVkMjJ5OTY2V0FXMy1kUjRjOGk3cnNwazQ4?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T11:53:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Extremadura"
  },
  {
    "titulo": "Entrega de Premios Legado en la Gala de Manpower y Brain Co. - www.revistaeyn.com",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNdFZkMFR4MkF0YklWeFNUQ1BkQXZvRG1PTzFKSV80Y1BTZVBCQ1Vqd1dFb3JTdU11TTVsdzZGNk93bW5LVm4yVGV2bnBCdnByZDJPaW5qeGkyQl9teVgydTBQZzgzcGJadVpOYlc3aXotOXBaOV9NWmNDNnF5UENGazlBa2FsUnI3SGs0aVRjR2c1VVJBSFFNdTdua0pzMU9MY0xCclpIdm9ZVEVZdFA0?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T21:46:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  }
];