const window_news_data = [
  {
    "titulo": "La reforma laboral obliga a replantear la gestión de la incapacidad permanente - Diario Jurídico",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxPZkQ2WEtUOFJGTEJsMU04RXJxaTJsZGcwdG1HTTlDSkQxYTN2bU02bjAxR2xkbW9CSnViME9DQzlJRnFMbWpjbldLY25jbjAyd19KOGQzSkNlV1BsX2hyZWk3VlA0NzVoYTBYalpIOG1XQnh5bG9BSDV1SUdwbTVQTVowc2ZyM2xPYmNfbnRwNzFjT1FZNWcweGF3a1ZkMEItNDl2X0o0WEwtdU5rcHlsVjRud0h0VkpFMzY4bl9reVBtdEl4MkprazQzdzFWenVXN2RYbXlTb0NfZnBHLTFwU2FBQU5LR1hlSU5N?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T07:00:11Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "272.172 trabajos desvanecidos en 24 horas: España sufre la mayor destrucción de empleo desde la reforma laboral - El Español",
    "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxOVHBSMWc5NEVzSnBaTWE4dEg2cGN3UnUtb3FZNFpCbHI4UHlCYTAyLXVjTkhFV3Iyb3NBN0VxdktOX1VLcXBJbldmbXcxb18xUmUyVEJGRjc0OHVYdzhlQ2tRZnpZNHZUbFBRdE50SzVEejJUUnhaeTloQ1p6bTF2NThmVkhNSTJSX0NhMkx1YXdKZlNGTVhreVoxTXB1OXRVN0RRRC1hekpxUnB3Y0lEVE5HeTF5T2RQb3JwdjFPRFRXdFdvVW9HVWl4TkR5eFhTZmpTUTBWWEJLN3BvMXNWTVQydGRCMzRnLVRwcEJta0xyVWZW0gH6AUFVX3lxTE5qbHl3SkJmNS13eXZOdXYtTVJWVnBBeVdBcEtyVjFfVk5NdzR5SmVFQ1R4TC1WWHhVRGpzNllFVW8tNDFISWl3TVlldktYcFIwMlNtMzd4TV9mNjZFekY4M3RTRTdWVEJFX1I1c2tiTkZMMTFqM0c5SUhNeUs1Q1lYaFR1RjRIenM3WGtIaTZlaUk5ekZWVkxveFFVVk1kYmVzTUJGd2d2YllLbVh4bmc2UEtLWmRFajUxZllBUUwzMF9ULUd3Vnhyd3JMQXNaTnM0a0t0VXNYbmJhWUNIU3JWN0VBcThGQ3hSbmV0UmNuNWZXUnFTV2p6QUE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-06T23:49:36Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Español"
  },
  {
    "titulo": "Despedir a empleados en el periodo de prueba se había convertido en una forma de despedir barato. El Gobierno ha dicho basta - Xataka",
    "url": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxQekR1Q2NUcnA5cUF2YzRUeGFQeXdTT1NCYXZESlhuLWpGOEl4NDN4N1JGUEFTY0FfZFFtalItVXQwdkwtUlByU1VpT0pXX1ljQVFsUFBfVTdYRVlZMDVXQllDX2ZmWVpLVTNFLTliQUxLeFpPdUVoYmpTTDN2M2c1MmlHU3lXMHFwZHFqRllyMEE1VzN2dzZsanl1aHZJdDBjaHpCQ2hOTVNjd3JPRTRzT3pORjllQjV0bElucVdpUDY0ZEMtTzFvWndRTWRKenZ4U3hxNi1hNDRGVEo1XzNYemhn0gHnAUFVX3lxTE82c2RoM09XbWM0VEFib1FLSkR2YzF2YWdFdUZLOFRicEJmY3dob1o3M25CNllENHlYTFhaWHJBeW9WMjl1cVJWUXRrc1hmQUZOR25zWUtpYW5iOVA0ZkZteld3UEtMVTl4d01vbUoyTFFDQUV4dVpOVUlFdnhpQnR4ZkFKWm5wT1BWNHpFSUdvdlhzdkpyeS1WcE5zV3RiWjZzcHQ4M3VhQ3VHTXYzWjd5U0xLTElsN0lsa01RRTJtS2pBQzZxcU90RWdoYWI5endlaXE4MjhvWVpwZVVidVFxWnBDT0Rfcw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T16:45:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "El Gobierno"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: \"Esta ley permite solicitar adaptaciones de jornada para conciliar la vida familiar y laboral manteniendo tu salario íntegro\" - El Periódico de Aragón",
    "url": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOb2JGbjdrNi1fU25tVzJHZVV5eVF4RFdtUnAwbG8welZtS1R5a2lsdGRheXNWU3haQjJDM0lwQUE1TnczbTVJOGQ2aUtoZ1BBbnZHZlB6NlFvXzZPQVVsNk1SMzFqazV0a1hKdS15dlphcWhzdXNQdk1ZZVlvdzllQzZuN0RzOWFXS3ZraFEzX2RMZldJQTNiZUhLcFpyeUFoaUpjeDRPSGLSAa4BQVVfeXFMTjVPQ3R6T1NtVmd2S1BoQVUzM1RMRjRuS2diQWFIdFp3bS1JazgtVUhMeFZUU3RuWldCZGlTMXJGdkxQLXAwRk1sbFVZYTJzTE9EcWw5RktoOWVJN2FfTHlJU0FKc3FUbzRvRUc0bUJOMkZmYVdwWnQzcWpuY0lzMXRERXBGLXJMTmduN2t5b0lhU1BzOTA5S1d0LUgwZXp5S2p6cUI5YmRaVGFGTGpR?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T15:00:29Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: hasta tres años de excedencia para cuidar a un hijo y dos para atender a la pareja - Líder Actual",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxPUnpCVEY2aW5jZE1raklxc0g3VVNHTUJqcGp5Mi1CNXJGRXVUODRUYkhUR0RzQzRyR0tqcGRiODNmRUxQQUl6U2NhZENxa05qejBHVjFxYnBiMlktV29jWXFOSl92UXp1LVBndXF0aHV6UE5OOTJxcnIzclZqSXNUMGdCY1RYejk5QmhGNFR4TjByUDFKUUhnNExDanVVaHBqek1vU3Vn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T15:30:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: compensación de 5 días de permiso pagado en caso de accidente ... - OkDiario",
    "url": "https://news.google.com/rss/articles/CBMi9wFBVV95cUxNR09WUXhUU19TeEw3cHNXai1HcTNFNkRiYjNaWGI3ckg1S2tkUFc4bFRWLTZQdmJuS1liNmdKLV9jUmZtNnlCbUwyNzBBRWJyWjRiSlRzejhfTFAzUUF3Z1RpRzFjS1doRU5SWS1KZVlpeGxuYVFsWThMT0M2X0p6ZUlRd3JrVmJLWVJlV3FfaVhRWXJ3S3U2OF9nNDNCdTRjMDBnUHpzYk1Xei1uS3oyUDBuOXFCUW1vLXBxVzNyVDhieE9zcjZxMTlGbGJWNTBkMGEyS1I0ZWhYUjUxOXhROGpaeEJVNldhR3VNamtvYzI0MTlrUy1N0gH8AUFVX3lxTE9GVXRsUlNCcjBJbkZLbHlvT3Rncm1wYnFqRENjSVhieFhaRV83R0p2S1ZhY1prS2JHdlNYbmFSaElHX3VXaEdwXzlyVHJDUHBHd0hjVzY2dUl1R3lOb1lKdUFhbnhueUVSY2plbnB4eG4xb1h6MFE2dzhWSFBHUlpCdE5OTmtPTm1PZTVVVnp0ZmdxSVUzajM0d3o4S0pLcWJGWnhVV1FOWFM1RERjWVo5N3BaamtzMERfQTJ5QjJ0SXBxVHlVWXhTN1Y2VHhEUFhVVWpWeUNMc09xWW14ZVRmbDFUWlNnTlpqM3VBU2c5cWFOQVRSMWtLeDg4dg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T09:19:32Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Las empresas tendrán que detallar salarios, horarios y algoritmos - Mundo Obrero",
    "url": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxOVzZ4YmY3cUw5ak5mY1BsenBBOVRiQ2dJRVE4MGhoT3pFMW9WTEpOWXRrYlBKVzdiNEtfUDNLb2Q3a3VDVkxCQ21TMVdwbGRaZ0g4c3hTSGM0M0ZNVkRDSWRqbjZUOHh2MWZHTTJjVnZqeTlhLUh2TmcwTVZiXy0xUkRPV0dPZjdpak1NcUZvbmxYdDFzN1E3cEVhNWZVSGNVZXE5MGJtZXBhNVdBRVl5OTAtd3ZqUktEUXEtV2t1ZTRzclZ1UEJqS1lwamNsTUNQaTE0cG93TGc3STI0NWRUblhRc3ZsUkl2RHFaZXUtbw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T16:43:30Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: tu empresa te puede despedir si empiezas a recoger las cosas antes de tu hora de salida - huelva24.com",
    "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxNQ0dJZXdxMFNqQ3hUUFZJMDUtWDFwenQ3M3ZpUUxXVkJpU0ZfRHY2Q2o3RUk1OTdZc3FXaTI3ZzhRSUdad201MW56cVlrQ0gtcFhBLWlrSmVwbHBxSlNDdGFqQ2xEa2JLTzN4ek02T3BMVEs4bjhUZE02SkJlODMwTEdrZGFpcTFxVkRkai1sbHgxQW1QVktwRzJIQ3Bpdm1YcDVMaFdJTnQyZUF0a3JPaHFYbEFwVjVwT2NzUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T05:33:37Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La Ley del Estatuto de los Trabajadores que muchos gaditanos desconocen: te puede despedir si empiezas a recoger las cosas antes de tu hora de salida - La Voz Digital",
    "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxOQW5uRElKbERQZG9JZmZGZklwTXQ3U0p4QVJJNVJkblpZSGdkMlBwQmxUdER1dFVYR3FuR0J2bHJCVGV4VHduRDROWVo5cTMwajluWDVkOHhIS0lCRkpGYk9ya00zS0YtbE5zQlRVRHVkVjJZb3V1cEdrX1d3QlhrVE01X056aXlsV0R0cGdxLXFzN3VBaEZlX1F4WThSbFpmUnB3ZmFRN21QYUo0Wi0zNTh0bVdLRmNIUFF1OTNMZ9IBxAFBVV95cUxOOHdzYVZ6SGs3VzVIT1FPNnBiR1VXa1VnUDNUeEFLa2VpdV9sMzBWZEtWRURoTFUtT1ozVTdQQm1JaS0wOWtwTEQ5QWx6bmNLUEVrVmtRd240NTFxUEFSTXNkcGJQV2RzZnBYT09wT1BUWXQxWk1scURYbzdVc2VLVWVYU0FFYUtaTkVLbFRQaTloc2NNZm05ME84emhZd0Iyc0k0SDRaSmVLdE9ab2llTkJjWV9SdWZwSGlmbUF1UTVzYmVt?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T06:56:24Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "La Ley"
  },
  {
    "titulo": "Es oficial: el Estatuto de los Trabajadores permite pedir hasta 3 años de excedencia para cuidar de los hijos - SPORT",
    "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxNeUtLak9tUWRFVjR4WEx3XzRJOFFpam1ZZ2dfT2tWdmJZLXcxdEJJN21yVmVfYm1iOUJIQ3FPWG9nRVlzUU9HcXhMWWNrSW9Tb2xUb3FWYVVOcFgwU0N5cXAxZUM1LXFFemZNYXR2UGNwclhaeTNiMkxCNHVXdUpCbUVoVXk4Y25DMnRFajBzbFFPY3dja3ljbzFxY3ZJMm9XZWd5aEd5bHJYcjZMN3FpX3h1MERkYmhkMm1CS0c3SkxPUdIBwgFBVV95cUxOc0h0SkQyWFVIVGZ0X21ZbGlRYTFROEVtSXJvd25YZ05kcHlIbldqbTd1VWY0VlBsaVRid200Z1BFSG11YXlRdnNUZG9DaGdNbnQ1Zm1RSkRPMi15amdJVklidnJncXA0LVZQSVVMbi04WDd5ajhRMXpodnhxUC1CTFptcy1HYUl1TFFYN2laMGdzV2pyZXdPYXlYRGdaQktoa3RnczZWd0I2S2lXbDZIWUdUa0hMd25PYkdsM0t4eEdoQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T11:49:18Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "SPORT",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "¿Te has puesto enfermo mientras estabas de vacaciones? El artículo 38 del Estatuto de los Trabajadores aclara qué pasa con los días perdidos - Vozpopuli",
    "url": "https://news.google.com/rss/articles/CBMijAJBVV95cUxOUE9zZEU1YVJHYzFBZlEyQWlYdXhMcmhQUk1OcEc4eHZBNWJqQVpvUS1ORTBaTC1KQ1d3eF9laGFzeGp5RlRhUU5EQjVYaTVFSGZWZ3RrdXV3aVc1Y0RaS2l1Y250cmkwMnlpSkZxOFk3RnQzbHZuLXhwUTdwcVVIUU8wMl81eGVJdUl5aWs2N2FNUHpvaW03QjVCM1JuUkJmSlNnaXItQzgzS1VRVHF1eFUtNGNHMUdEOEpRMTNyM0I3bmtKSnFxQjlmMWwtNVBscmd5ZF9EZUpnRmphUDZGUlpodTFKd3cxR1MyQm9QekZiQkpYUzEyNHlwN0xNbWpKaUtqekNZMEZyTVhW0gGSAkFVX3lxTFBFR2p3M3Y3TzEySXR3TjNvZUwwbU43QTk4SXNnVmV2aFhKN21TYUlYY3dFMEtlNjFWeWlFNnBmUkZsOFJwTDJfRTZFZTVjX3M4WkJIV0dWYzFXV2xXbmdrcFM0ZzFzQ3pDdVBiZzFSZnBUSUNOeWF0MmRCS1pCUklRd08zdTVJampLbWdZTWlBa3pyRzFyYTlrQUFoUWRvbFhBQ3d5ZEcxemhoMHFIaU9vVUFQZVQ1anE0alRENkFnS1JFdEVqbk1aLU5ibm1qR1FXUzJ5eU9YcU10aHE4cEJrdFpPM1J3WDZTM05uMnBDZC01cVFTWkZpbjI0ZEl6TVRfSVJaMm11X3ljRjc0ZUVlVWc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T10:09:42Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El artículo 46 del Estatuto de los Trabajadores lo confirma: los trabajadores pueden pedir hasta 2 años de licencia para cuidar a un familiar - El Cronista",
    "url": "https://news.google.com/rss/articles/CBMilgJBVV95cUxOOXFNOW12bWl4MkdFdnBCZ3gwc1pZdC1OdUs0S1BaZm40Q1AtS1pLYk1RS3ZkdTV3a2NDeldfdF9CSEJSUU9WV25xQkVFRlZkcnRkbl9GQmdxenBnWlJKRS1oMVQzSHZPdHNrN1M2WHlRZ2VlNlp4UV9Ieml0SzZtNlhfNHVyUlViYXdaTlFIaGJWVDRodk9pYU44NVl6RDNZZU5CakJJb3I3dGRjajFwcXB0cUxFNkRaZ1dQdUxnMlE2VW9wWkliREQ1eHREbUx3TXlBM3I1Q0Y5V3ZGS1Y0TkRUeDhsR1A4NHJ3OVpxYWlfMmlXVldHSmY5OVVrUUI5QVFHWHFLRzdQa3VZZE1ueExkYUdNd9IBsAJBVV95cUxOV2dUeWhZMXAzQ09lOWdDXzJzUFR1blVwOTdEOF83X2F0RUotcnRZOHNIWFRkYXhkYzdjN25oNXhURGVPYVRGM3B2STVZSmZXdXcwQWdDTUJGOE52YS1ORG9XbVljVDdoczFuR3JVYzZ5YVVWWTRyaWdlc2JvN1ZoTTg4amtMVlg3STJueXdGZ3JqRjdtaTZwWXlWbFM5b2ZSTnR1VmFUYi1INW9aakxXSEdLN3NvQ0lCYnRQaDVxcE4zSC01X0FyVkE1SFlGOEVtaWtBSDBsNVZxVXJyQzIxQUpPNC1XWENBWl9RZ01TcnBYT2NOUEdablIxc1o0Wl90WV9UMHdWSHd2V19BVjBGdDJFbUpTTzl4Wk5HTndOOXJvd21reDhCYy1qeEdDUXla?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-04T15:07:23Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Trabajo endurece el periodo de prueba tras dispararse las bajas desde la reforma laboral - El Debate",
    "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxQcnQ4TFpLM0JydS05d3g5Um80YUViWUVPMHFSNFVQaE9sV0xtbTktVE9GTjJ0X0NFdnhJZ2ZJNzlfem1MUlJGWkJRUC05RGtlWDgxMlAxdDZYWHZsRGZwMlB5MnU0aDExYS03eWVUbzIyaXlZWldyOVk3VHA1SnJtYVBXTmxEMUZxNHkxbzVrcE1weHJqXzBHSXdncEt5QkZrTVpCSTY4Zy1xMzgxbjl4ekNHd2dHXzZjNkRyM1ZCUS05VkXSAcgBQVVfeXFMT1FRc1ZnNElHczZrNzNpQ3RDYnBIWDd5dVFIZnFmcVBXWnJLd1hoeUVvaXJIODZrZF9hcllCT1RFSGtBWjI2OFdTTzNOdHFMNkRyODZ3Mk5SMkJobU5UV3hRRTc5cWQyZmgtQk5WVWVTSVJWU1pfSTVrSGVzU1lIdWNsaHBzRmxoc0ljUFpUaUFLRHpUdlFBOEdXT0dUUldfdnlRQjBvMzZ3UjRWMkFReUJWWkhZOFVlSVpVcURmOElLejZEX3Boa28?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T02:20:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ministerio de Trabajo analizará impacto de la IA en el empleo y en los derechos de los trabajadores - Infobae",
    "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQOE12U0loa2xpRXQ4d281ZVRmUmVYTnVhdmo4Y3g4OWpTekdoeTUwa0RBUkdCT0ZKZUthLV83VXlOTUhLSUpJWGx3WWRZazFWSTV6bFJPTkVzZDV6cHpLUlQtZm9Id3BWS3gyZjBiZjBhaUJyY2RxZjJmd25oZ0dhczlQb1BUYW5hX2RWbUpVdjY5M3VxVGE1b201WGhaaVVuZUxpWVd5a0hoS2l4NmRCZXNFMEJacXBqR3oxMWtzeDd3Q2F6Y25KV2VFSW0tQlNnZWhfSXRxTdIB8gFBVV95cUxOY2pBX3ZtRHZsZXFNQzVjSEVTWjZ3S29YZ3k3QjFfR3czUVBSR3NCNXQ0UDJ3VklXeThFT0gwN2gzZkJoSi00Z09WVUtocElEVHplMWRHNlVFR1JjUGJiWnFndVllcXJFdEZUNWc0QVdEblZlMEpTX2ZvT0drVGlPYmlnUllFRDJ6NEx3ZTdZVEpJbjJiNjV0X1J5cmFvSkpUd3dwR0EwQUNmWmVNeHpmeFJKOUJ6dXRYOU1DT1V4VVFFNDdMNnFvZUM3cjZSbkp3aHlLSTBaVUNyWVBIcE8tYWYwOElvS2xWT0xLWXlHTE9qdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-05T21:53:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: puedes irte de la empresa con indemnización si te cambian el sueldo o el horario - Líder Actual",
    "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxONnhDSGtLcTdxOTk5NEY5YkFBN2JHcGQ1NDZIZU5QaTNTbnpMZlBxMU1iN2dTUm9pUTduR2ZuUXJOdjloZFhZU1AzMGNHMW11bjBlcmlxMDdyMVoyblNQM0YtM3p3YjdJUERTQmgxUjlCTXpramxjVEU3a2hmeXpTUUI0U1duc3Bia1YyLUlTbkkybkdZUVdvYTBKLUQ4dktTOWRUYWt1VEE3Zkx5?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T11:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Avalado por el Estatuto de los Trabajadores: los trabajadores deben tener 1 día y medio de descanso semanal - OkDiario",
    "url": "https://news.google.com/rss/articles/CBMixAFBVV95cUxNYWhZbmNVWWhoeElfOFN3YXoyeUhBRkdmcGRnM2x2NDFLdG1HdldZQ3hJMVNUMVhaWTRESmlzd1VDVG1kS0Rmbno2ZkpoSkhXSUM4b19lTjlNQkxXUkpmWUMtRHZfejVxdjZfbkR0YnlybGlVbDNpSFIzTFdGdGk0QWx2OVBsbHRicFlGdkt4QUs4RFo3ZF9VZW1CSlRvamJUZUhHSHlQbHZrbktEM3VJVHJZaExyanRVRy0tZDFRYzFTMFRh0gHEAUFVX3lxTE1haFluY1VZaGh4SV84U3dhejJ5SEFGR2ZwZGczbHY0MUt0bUd2V1lDeEkxU1QxWFpZNERKaXN3VUNUbWRLRGZuejZmSmhKSFdJQzhvX2VOOU1CTFdSSmZZQy1Edl96NXF2Nl9uRHRieXJsaVVsM2lIUjNMV0Z0aTRBbHY5UGxsdGJwWUZ2S3hBSzhEWjdkX1VlbUJKVG9qYlRlSEdIeVBsdmtuS0QzdUlUclloTHJqdFVHLS1kMVFjMVMwVGE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T15:16:56Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Ministerio de Trabajo ya prepara la reforma del despido \"porque despedir en España es baratísimo\" - Líder Actual",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxPeU5GTEF1S0RWQmg5RnNZcG9BVVpRX0JzcTRpYkxXTkd1aUlPWjl2eUtfTEtpMFY4UTh6eTZtRE8xX0Vla0hqRTQwNlFmZlBQSnZUaUZtdmJjOXFRM3ROVG9kUVEtRjd2X2hBbzd1NmFraWE1c1lfYXk2cVZlZFd3N1ZQNHR0eHF5TlpYUGY2d3A4M3VqNWpYdmY4V1Z1dw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T09:05:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "Trabajo obligará a las empresas a ampliar el periodo de prueba más allá de los seis meses - Líder Actual",
    "url": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxPOHlwWEIyVWNxOFEtWlZVZlBKSjVfb1VCVURRY0V3UUJ6X0tkV0QwekQzSHJxZ3Y3ekE3R29MXzJhQUdFbk9sTTRxNGg5RE1XeVF6VkUwNkJDRGUxUWpkdm5Rb3NtQXN1dWRfN2RpaHllWGhoV0dqcHdyZDR4ZGNjc00zY1RQNUplUzFNV09Sa1hvUk5TbWgxUEJuUnlPUnhVTFdmdWFHaG1iTGxBdllseXNsZEpWa1dwZERodmZVNHNYYXJINTRtYXRzUVY3Z25iVGUzSjM1T2VfaElzdGpfeFlR?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T09:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Giro en la Justicia para la aplicación de la Reforma Laboral y un fallo que elevó una indemnización por despido de unos $6 millones a casi $160 millones - 0264Noticias",
    "url": "https://news.google.com/rss/articles/CBMiswJBVV95cUxNV1l4aHQxWjJKOFVMbGZHMURVUGgwVnRJNzBpMFAwMTJOM1pmSmlZWjh5LW5GN0N0c0c4U1gzX1pCcHgyOXJuWG5GNHFxRXppLTdaN0JaZnRzSXFkVi1zelRuY0hVaHBmT3RiZDlwSkp0ZEktXzg4NFpvb0V5NWxVbFJHVE9fcWJPbWVKN2ZmTTJibXVLUnFiOEFDMDB4WFNkWDZCQnhIaEdzMDlKYVl6cFV0Y2U4V3VKYlEyb0c5Y3lQbjlKS3c5UTAyQjBuT3ZzNjRUaU9EZ0RobHBGNEtYVTNKVy1HU05qeTZTbHpRam9zcTFVQU5JTV9yQ1RxckRId3dnTERvVHpud3FVN0RNRlZVMWJVMmZKNWJFelVDbTkxVTh0LXhNT0tIUjFkbUo2Y3cw0gG4AkFVX3lxTE4zRm1XLTdZZnB5dUtaSW9VaWxjZkdfQlI5YUhHZjQ0MEtfZnpPSm13SW55LWdMd2d3N1YwVUY2ajU5RDc0dUxkVkhVR1pZcndQT3lQUHlfSFhTc19SajE0SmktMVRLUWlSdkpENGtIVFJJU2xqX2V4REdyVHhfRnRjdlpNRVplTGl1WGx6U1hmM2VZWnRaSER2Qm5DTmlKaXFrX1RSTXFBWlEtZDZ1WUUwNkRoc0k2M2VYZkNERWZ4Vzl4ZzFTZ0VfTXlTYWFndzd4U0U2a0ZPb0xHeWN4a2ZURndIZmxWdWZaY1IybnR6c29SRGlCVmNDV3FCc2RxT0xKYzhDNHA1N29tcVBnNi03OHQwU0V6V0d1V3gxZDQ2ZkNuWjZkMEFOLUtqSldpTFFveXExY0pGTg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T09:41:32Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ministerio de Trabajo intensifica controles laborales y suma 9.327 inspecciones en 2026 | Economía | Noticias - El Universo",
    "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxQTWJTTWxLTnNnelNzOXJiVUp0dk04NnYySzN0VC1xZnE3ZzR2NEs4MjBQb3BJWm04aHJ1OWdFaFo0UHlNR1hZMS1KTDBjdzdSUHJyT1Izd1gyWFJEN0ZKRmhNNFhOUDhHRlpTNThIdWJUeWxMbDlJM0xFNUg3bm1aQlh5ZThvbm1QbnlFa1p3MnF6SGNNLTUwX1pDbVhXS1RwZ3VCVWhYRVpaQ2R4a0xoeEFYeFZVSGc0eEJUR2pKbzdjWFJIdVl6OTZPTy1BSWM2ZThhQw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T11:30:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Salvador: Ministerio de Trabajo aclara que no hay una propuesta definida sobre cambios en la jornada laboral - Infobae",
    "url": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxNYi00ZHY0UXpqR1c1c0s0RE1HeGw4QnJTbmYwZFVGTkZaMlFQdm5qN2NzNTB2b3JWcEVGSUNIckZHMy1ZS29lNGI3YllaYnNSemgtRU81QklkUGVNY3VJNXRJbWFUemFtd19mZDUxV2lQOWtZWE9ZWUp2YkowczRUNmJkN21wMEk2THdjd0VqT1hudVQyaThDT2RhOE1wal9Gc1Bha015Rnc5SHBvd1E5a1FsR2kwRnQwX2F4c2JRNE1QNGZLaF9oN0tsXzFuZDM4dzdXcEEzZWowcG1md2NhRURrQllNRGlUbmRFTl9Oc9IBigJBVV95cUxQMnJMUFRTMS1LdEhFMVJNc0VIUHAzVnd5WDMxUDh2YllVSU5GQmRaWi1YTHJ3MG14M19SSnBCSjlUV0hiazJxTXJ4SDFGclhlUUJWSDVGdU5NNTllOFVFZjBGMlRYQS01UlZERmVPOFdEYVpXRmNNMTBKUVhrNWx6YnVxT0w3VWNRbjJTOUd5SC1qWkFLa2VjNWpJYVZyWnZJdUU5Wm05b0F0YjNJcGw5NFlsWHJkcmNFUFN4QmIxMzFkQUt0dVpLZnNOZjRyU1Q0RkMwOVRyMFFZSENuZnlSbklYeFlTcjFmUTB5SjE3Y05fX3BwUGJMcDNuYnNRSEhkZ1JDMzV3MzQydw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T04:52:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "El Salvador"
  },
  {
    "titulo": "Gobierno reconoce que la IA sí amenaza el empleo de peruanos y analizará cómo evitarlo - Infobae",
    "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxPVHB2d1J3cHpjczFGaXIwbFhfVmd2RUtxNU5OV0lzWm52ZjllRVlLcmplZUVXSk56eTVMSTNUY25hTElBSkFsRXZFYXlRT1l5N1NucTBLc1hnd3NDMUozTWtiZTlraXkzWXl6eFQ0X1dHZWpCTnRUZjMtUTczWnVuc3NjV2NiQzI1Z01VZHc2RF9xNWRkenQxM3d3ZEhhUVdIOWVqb0gwWlprbzU3WGhpZzB3V3YxZHBPNmJaNkN5VmZUdFhXbmfSAeABQVVfeXFMTkJ3UzFoczdBLUU3RVJxTjR0Tk8yaEdpQXNCOXJOZjlURjZBd1lyZFhjenhrT1dQN0dqNWVJUUVqV0NwYTF0VDVZeHVxVGFaR1pLX0lOeEM0dTBSOWcxQmtoRXVjTE84dzhzc19DNE42WWtzSEg3b1ludUNGeFYyS1EyUER2MnMyZzVSNWd4aklEbjhxb1RVUVZRdDJncUh0VGFySzNfcjFVVVIydTdvSGc4LXpfN2tYRlliYkU5X3NjOGk5V1IxWksyWVpPUFBocmtSaC1zNTAzZmlWa3ExeFE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T16:37:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Infobae"
  },
  {
    "titulo": "Ministerio de Trabajo imparte charla “Cuidarnos también es Prevenir” por el Día Mundial de la Prevención del Suicidio” - mt.gob.do",
    "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxQSFYzSUE1dm92MldZRHhRbjlZT3hFcHA1MUMyeXNXMUh1ZHRHNTJKemh0YTJYS3JjNGpGNWZQRlk0Q2dwMllhMWVCV0lFV21sZDVhcjVVaHlqdFc5c2ZkY1ZhZGNqVDVMYTVidDR4VnVDY0pvR2c2T0RhdWl5Z05BQWNNdGdUMU12MVZEcTBRT0xSeW1ILUJ1eklidzlpM3BScGM3bXBFRUE1Z1o2UkJaeDdLZk4xMUpNcllFM19wZmsyRnEyYUp0Sml2ZGhnWTA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T18:31:25Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Día Mundial de la Prevención del Suicidio",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "UdeG se adelanta a la reforma laboral y reduce 16.66 por ciento la jornada de sus trabajadores - Universidad de Guadalajara",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxNVkNEN2xTdERfZGtlcXZSOHFZdGJqOUFDQ3QwNFRaWkZKRzJ2QkhLR3MtTE9fR2VPV0hhMzNSTzFQNG9jaU0wSXVST3R1cjFXR0ZQdnlNQ29Gd1RMdXM0RGNSM3lZTy1ZNWZWdFhiekVxYzgxV3dCRzFzRGEwZU92bzZ5UzRNZlZyUzBjZUtlbXpOazhTdnZFaklQSE41b25sY2J3M2hBWXhhY0ZCZTFFeEhwbE9FYlhiWFE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T13:06:26Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Universidad de Guadalajara",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "MTSS fortalece herramientas para prevenir la violencia y el acoso laboral - GUB.UY",
    "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxOWDd5TDZXdlhXemc2Y2RJZTJRRWRjRklqdFZzUHhjR0lHRXZZVURyaDNqTXphd2Y1ZllWM3hROEhOcTlMZ3JBSnppSUthREtXMDkySEUxYW4wWm9sM1NuTGZkNUVENWgweUtkNktpVHB2RDBESU9weUI4YS1WVHM0QmxKTUNEMnl6SFN4clZQejIzVEFWTllSZ1YtMkJHWmNzZ0xORU41dEdMUkRXQ0VncDBwakJFVHE5aHZ2UDRTcHdzSzBPSDJXVlQ1dm9KTWU5Y3p0c3lSTVBFZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-04T17:25:30Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "RDEco: por qué el RIFLE de Reforma laboral puede reducir 10% el costo laboral de las empresas - Perfil",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPX2M1bHZnaVNQY1FGN25fU1BkMkYyWFVsa1N4bUVjckxleVBvRzVWZEFXUHdqSkZNTEZPV3VlOGxTTHRtcXB3WDlDSjc3dXBaX1pXeTV1STcwOGlFUEllRW5PbFBDb2RrMlI4WUwxTFltMGg1MUdNV0Q4QXlGUFdMdi00ak1mUGRNc1FHOUtWRkRtS1IzRE8zc1p4eXJvRmROMWxEUnk4X0p2UjVId2ZTZ0dKalVpV3otUUYzeUhpMElrSXhFOGlidy1VRlVjY09F0gHWAUFVX3lxTE1iN1VzRUh1VEZNOXpsQWZqckUzbnFIYnJyQ2plU1hnMjg0NnJocjFvLVc0YWFiOW82UTg4dFFDUHdwdG1hYVg4cmIyVTB2S0NTSmlWWUc1VE5pSkZHdHpnbkFVSmFnWGQxT3k5MzR1RlpSMGdmMHhsNFBUaW04NUZEcWk4emo5Q0tiRW11ZUpCNExobGptTndXNjluVmdKWDhlVUxvanA3MUM1Unl4REZaVmt0ODY1RVJDcXY1ZEdSVVNuXzJZOXlHWUk5Rlp4ZHQxeTAtNFE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T12:45:36Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Disminución de jornada laboral | Forzarán a los empleados a laborar más horas - El Cronista",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPVUdvbFpja0s4azBVNWU3RUVFdkdvWnNScmdUblJCeE5GbllQUGFvOTByWDZLc0JGMktETGl6LXh0a0Nya2RNWFhJREFOanZiRXo4RF9VaGRzNUd1ampQNzNjNVpEX3lZTlNETWMtZUFxQU5OWjlycllwQXZXdVFxTmg1a0lwT1BhS29kLTRxVnBqd25ZTVFLMVgyS1RkT1JXaF9INnBMSEJiYjFhRzE1c3FRRVBOekNBSjFRVGhVeEQ5Qm1PeUozbzVRTDkxaUcyY1E4MDFn0gHwAUFVX3lxTE9hZ1BYYjdQZU5rTkpEV2RPT2JNSmYyRmhSYW5FanVTem1OTGwxQUE4RzJjbEItSURGcnBWYlp0OFA0TmhFZklPZFB1RzVMVVFjMHpxUHRWc0Z6SW1TTE50Qzdsem1TTE50X1pPWkZWWS1tNWdISkpwc09uSVRNcjhJNnJIUnBJc3A3RWZJNkp0Um1UcDJ2Y1pXVndaY0FLLVlfVHJZYUNqTV9LcTA2cHkycGFlN2s5alBHaEJJY05sSVJyUU55c0pySjliN0xSWU95V3Y5Vmp5aDM1cHJ0dHJtN0UwZXl4cEJaZmxWSWtVQg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T13:48:07Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "CREES advierte que reforma laboral puede quedarse corta para reducir la informalidad - Acento",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPZXEwdElxUmxBVHF6aS1RcUtib2hFZUM3VlVBQ1JmQUQwaGpISk5CVFZ5cmFDRmRKQTF1MUZEcXFxbVU0amlBbFlORVJYZ1BsdVRXa2RBRlhJdWtYdDJlcVpodjhKNEVXdGlmVGFKVEJ2cmU5Q2R3dGZCUm9WYWZSeXlETmh5MTd4LVhrdUlXNXZzYkdwejlDaXlyRTItSFJselNocHFPTVBvN1NNRnc1OTJob05jVjBabFhKdHhGeURKS0RVZjNV0gHHAUFVX3lxTE9lcTB0SXFSbEFUcXppLVFxS2JvaEVlQzdWVUFDUmZBRDBoakhKTkJUVnlyYUNGZEpBMXUxRkRxcXFtVTRqaUFsWU5FUlhnUGx1VFdrZEFGWEl1a1h0MmVxWmh2OEo0RVd0aWZUYUpUQnZyZTlDZHd0ZkJSb1ZhZlJ5eUROaHkxN3gtWGt1SVc1dnNiR3B6OUNpeXJFMi1IUmx6U2hwcU9NUG83U01GdzU5MmhvTmNWMFpsWEp0eEZ5REpLRFVmM1U?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T08:00:41Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "CREES"
  },
  {
    "titulo": "Castillo: “La prevención debe traducirse en cambios concretos en el trabajo” - GUB.UY",
    "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxQWjFnM0ptdWk1UWRyV0RDVGphcHJDalp3UWtPbkJydW9UbmlKbHRRS2IxS0ZibUNUS21WcTNEOVhKYXk1d013NXYtaXM4Qkgzb3RGbkxjM1BQWDB2bnJJN0Y1V1hEWGNvLXF3UGlVdmY3a0w5dGNBZ085eUthOXpuLVRqQkRkdk1iM1BENG9DeWdvUTQ1OXZyczc5aUhjMEU4VFhSenV3QkRZc0RieHFOcTBsTERBdFRDWEVDNTBWVk5aaDNNNm5hTk5aQUhPaU12TFhyUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T16:36:33Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Es oficial | Aprueban la reforma laboral: ahora los empleado deberán trabajar hasta 12 horas extras sin día de descanso - El Cronista",
    "url": "https://news.google.com/rss/articles/CBMijwJBVV95cUxQSmp5YUFaWkViU3NyUHlJcVlVaXR4aERVa2UzemxmY29SLUgyb3NRSnhkeUloR0gzbWpKcHNDNGJvNkpDamV5ZXVOb3Rrd1FzeVBxdi1rd3FacUlFa0t4MXNNd3BraW1IRnhDTE5vVTN6MkZ6WVptN0FwSEhNZm4wRzJxQUI5NXp1U1NWOVZaakJReWJoWWZudzF5ZnRGTmtHZlc3RWVWNm5WNHNBUW1sa0x5akE1S2dHcUtOZDJza3ZxNlJvVlkzeWlzWlhwMU9HZ1NhMHFWbDRzc1lVZ3k4QkJNcjRyLVNiVTg0VXFMbVZaal9EbkdyendoUEVNbGZsWHpESlVSOFNvcnUyYnlF0gGPAkFVX3lxTFBKanlhQVpaRWJTc3JQeUlxWVVpdHhoRFVrZTN6bGZjb1ItSDJvc1FKeGR5SWhHSDNtakpwc0M0Ym82SkNqZXlldU5vdGt3UXN5UHF2LWt3cVpxSUVrS3gxc013cGtpbUhGeENMTm9VM3oyRnpZWm03QXBISE1mbjBHMnFBQjk1enVTU1Y5VlpqQlF5YmhZZm53MXlmdEZOa0dmVzdFZVY2blY0c0FRbWxrTHlqQTVLZ0dxS05kMnNrdnE2Um9WWTN5aXNaWHAxT0dnU2EwcVZsNHNzWVVneThCQk1yNHItU2JVODRVcUxtVlpqX0RuR3J6d2hQRU1sZmxYekRKVVI4U29ydTJieUU?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T06:57:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Cómo la IA generativa en Recursos Humanos personaliza la experiencia del empleado - news.sap.com",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE9LazRldnR6ems1dVpjc3lxWmlEMm1uaHNEVTZsQ0xhbzRPV2lCYXFQQWM3QmlhQjVSd1lWeDc2VWJvNGpqV29iektOdnlEN0NXaGZMVUlVM1RlVDRYOURFY3N6N1FjbTd2SHdKVGNGaHNXcmtXbXZ3Tg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T08:14:07Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Gómez Caamaño destaca el incremento de recursos humanos del Plan de Salud Mental 2026-2030, que incorporará 100 nuevos profesionales ya el próximo año - Xunta de Galicia",
    "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxNYUw0RUkwWFJJeVFsbUdrZjVLeV9XVS1JaFZMZXo4M1Y1cXBZaTM1ckhHcmxzMThkNS1PWkhnRG9FZE1aSVF1NzdDeVpRb1BGUmhTM1pXUE5XSjhCbng4Rm1TVExlSUtobVpoVzJINXpOcEViSXl6RmZYOWppSHR0Uno2bGVfdlFSTlliWGhQVHFKN3ZOTmhuT2t1TWJ5Zzl4LWNpNDRxR3E3bjJ2bUFmb0FwdUJkTG1RdlB2aWNOcUtsUjBLd3VRNFZVcw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T11:03:12Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Jornada Empresa y Juventud: Conectando Expectativas, Talento y Oportunidades (Martes 29 de septiembre) - Universidad de Murcia",
    "url": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxQUm5tRy1Fc0kyWlpfTFMwbnpsUUprZk12Vzg1QXRwazVrd1U5YkR0SHlrQXZBMWNoaFlZZlZrRS0wUUE5Ynh5MzlkZEZnQVFTQUYya1VTZE9SaWdVVExuLXlrSUZIVzBPcmMzRUI4LWdIV2dJVXpwR2htX2FwV294UDVtS3RwTUcyWDdDRlBoRXpQRnM0Y1RGSUNKR0tqazBfbDVaZlg1T3ZrdUhQMnE3dWwxUlY4THZHNTV4ZkFEQmRTdVBQR2ZPSG9KTWs5NVBxeXZyaDFXN2ZuT0VmT2NqLQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T14:40:29Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Talento"
  },
  {
    "titulo": "Irune Pérez de Urabayen, nueva responsable de Recursos Humanos de Maier Group en Navarra - Navarra Capital",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxNMlI5NEVxZ0JienUwaE0xc3lrVmlhb3M1bzlHYW8tQ3Y3TzUzVUJ5QTItRWFGUnZ6YjVucHVxUUdha2xCektqU0F3aFp6b09qVUROanAtb2tDcVhtNmdDbTlDbHRaQ0VtNlpDZm1IUDFEaHRJMTB3WHoydmRkdHFINmk3VTB3TGdCdF9feHdhVWUwYXdSYlJWWEZDQ3k3V1c1NFpwbXRMZ2lRZ0lBU1RMVFR3Um8?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T20:45:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Maier Group",
    "ubicacion": "Navarra"
  },
  {
    "titulo": "Rafael Alonso, experto en Recursos Humanos: “En el estrés laboral también puede influir lo que hay entre lo qu - Diario AS",
    "url": "https://news.google.com/rss/articles/CBMihgJBVV95cUxQT3lyTzE3bVZqNlJ0OHFkTkJCN0k0MFUzSEJOY2JGaW5rX3hVN3IwVGhGYmhRWnVsci1wbkFmVFlVNlVaUUlQdXZfTlRlVlQyRVVTY2tCRlBYWEtlNUI3eTAtZWdpTXdRd3QtNk5aWk5BdldEU01CVkhGMFFZSkFsdENSQ2hjMUJGRFQ0RUF2bDRkOVp4NFF2TnNZQjZSX2hVSnE5eGZxUjBYX0h5YURfd3VqeTBUSEhNeGFoQ0U2X0JJSFJZUTdoaXdmQ1FsM3l3b1RzcTg4ZzZtTjkxSGVNSEtyb2NyM0VCMW14aWpJV2hwY0gtU3hHZ3ZZcDFTZE1ndFI4Wnpn0gGaAkFVX3lxTE40YkVNUFNvSndXanBBZ1lHWVZYYXhVOEhVamtWTjVZWU5Xcng5Z0U3UW1aNk9ORzVBUGhiOE9JUmd3dU1IT2M5SGZyTzVXWjVEMmdyeEdlbnF0bGpOLW9wT0NqcFJlcVBqdXNoMFFOTnE4ZEJoVFdYMU15R0ZEU04wU1BMS2Vfd1FjeFFaS2JuNTZTR3YwZzFuUW9fVl84Q1dHbVpobkJFSTEzek85bDcyenlrdVFkY0QxRXdMamwtRGNKWmJzSlZkSTE2eTRnWllvdTVIaG9Lbi1UQnY5NnZfWHlyN253clNyWlB1V21yS0poVEhPaGFmSDd0Y0h5ZWxzZUV6RVNvZXpOVUpVZ0prOS0ycWpIQW9NZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-06T13:13:11Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "IA y Recursos Humanos: la clave para convertir la eficiencia en ventaja competitiva - ORH | Observatorio de Recursos Humanos",
    "url": "https://news.google.com/rss/articles/CBMid0FVX3lxTE9EMFBsMjBEMG5famdGdkNfbDRmVTJPaWE1dXdyNXlRVEV2Ry03UU9paHhWTng3SktQaUx4ZGFobm45MUNxb0gtaExjdm9yM0R0eUVObWJVMU9odkp5NGJvZ1JlTmFBYkdVbGJXWGxLb29Fa1hvcXdr?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T05:11:11Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Observatorio de Recursos Humanos"
  },
  {
    "titulo": "Dia España, reconocido como Top Employer 2026 por sus buenas prácticas en el área de Recursos Humanos - diacorporate.com",
    "url": "https://news.google.com/rss/articles/CBMic0FVX3lxTE5xaFJnMFF1em44Y0J5MnZ0emQ5RVV5WmgzVm8xeGdWZDFxa3RQSTBEdllBbWhKbHpZTVVHLTJMajdTU1ZsUUE4dzg3ak1wYjJtZ0tBZldpSExOX2R2Rkh1S0lySjJQWFluME52VXJ2TENrNzg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T09:17:35Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "César Vázquez, Director de Recursos Humanos de Dia España - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPNzhhTHFDbWkxemVYbGlKSk1nZVV1Q2tGSVMySnVqUFNyS0xHekZtSTNVRWRNNXFMME5fWUdXY2RUR1NWUUcyZG5lWERuSUlYVThia1ZNeDZhQ3FGNENqVjdvdXd1aGp2UTRMeER1THRUTHNMSUVQS0doMzA1eUQySldQY1ZnNHAwLTltOVRZT0ltZmFNTS1sbHQxOXNnYmlPRVk0V09qQkJzSnBhT0NQOVVB?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-11T01:21:33Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Recursos Humanos cambia de función: de gestionar plantilla a decidir sobre talento - El Nuevo Digital Murcia",
    "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxQenJXYzVOalg3TVVQWVBRcnl6bW5QWEZhWUo0NHhPX1FNdzZ5OWctWTdtWFNIWkkxNHFBaVZfQkJjcVpKVlFzZkp5TmlBY29FQ1NPdkpXUUhoRTB6X3J5bW1VOEsxb295Wk1pQlUwdFVUUXdlczVpdjJxN2d6Y1JoMlFrRElzcC00T1VTY3hNaUY1XzBJSmxNTnR0Z1FFNl9FWll0U3B2a2JkNHpSVVZCbm9rek1kT1JtWEhDcFlrRQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T11:39:58Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nuevo Digital Murcia"
  },
  {
    "titulo": "Axa ficha a la exministra francesa de Trabajo Astrid Panosyan-Bouvet como directora de Recursos Humanos - Inese",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPbjBIbm9vZUlwaDIzcEZqVEQ4eEdYcjk5VGlPbFExSHRjNXUxY2RqaGhzRmV4Z1BtWmlmcVVIWkpzVXBBT0pPUHM3bzVZUEpicUJlcnJVQTRvWGZ5RmRIQXQwN0pkakh3a0QtRzV6T2dmNk80ZDJnV0txOEVnUTl1ZXQ1ZnR6RV95U3lVWkxwT1lEV3V1Si1OT3hZUklxQXpUWnhteC1yZTFOLVZsazU3N09obVhzNERMZFdubC1XRTlDU0h1YklUbkFMMjVqSzRR?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T09:32:08Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "DIA España, reconocida por su política de recursos humanos - Revista Retail",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxNZUt5OE1wOTRFa3N1c2did3o2NEtONTQ0RkduZk5jWDB4eU1YU1NuWE1vLUZFd3FsRWFnaTl0bVZ6NDJxSWc3LUZxOGVUYzVYdVNXTmhZYnZJNzlveHUySEtzay1pb2d4eDgweXg2TERndnpoeFo1OEVuSFNvMVlzMEZEVVFPVEkxOGpEUXE2YWQ3RGRkSDZkT1JwbHJXU1NieEFkd0M5YldFWjh1S0FQQWozTzk4dTI2YmJZdDUtVi1RRXFTQ0xDdEdkRmtPMEpS?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T13:47:14Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Revista Retail",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Volkswagen AG nombra a Erika Rasch nueva responsable de recursos humanos - RRHH Press",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxQeGNKWnRUU3ZZXzF1cFR4M3FKSnNQUy13RXhoa0VoT283Tk9yLVZNdmdNcGdHdktGaUtmaGloZ294U3dFNlFwaE9tQzJmc3pqT1dGMDFjZi1CQjZ0S3F6QXRCTGVrZEk3cGFmYm4zajE0NUViRDJya3kyS0lqaWJJNDhTYklSbWtyeE1IaGJFUW92YkU1TUJvLXZGQ3M?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T09:15:56Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Volkswagen AG",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Caamaño destaca el aumento de recursos humanos del Plan de Salud Mental 2026-2030 - consalud.es",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxOSHI5bEhMc0toNk0wOW5sZFZLQ1V4elJ6VHFiT1haMVgxZWxfVE1ScVhJRVNnZEhuekhBMFA1bXlrV3dRT0V3TlRxd2dOaWxDOTZGaC0zVkRPNU9STG1uXzdvcGVVNlk0NW9OdmZuNG5jNVM5YmlGTy1tNWluaXRwVzM4UHFwMkh1MGtDQ1JxNnVsYjBOZkhIM294QjcyZkNCMEZBWnhBQXcxQ2RaVS1PQmJSU1FmeXAxNGJhN3Q4MVhRT25VZVhSNw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T15:00:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Bill Derrenger, nuevo colaborador especializado de Foro Recursos Humanos - Foro Recursos Humanos",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxNWXJzN3lVaG5ENlp3OGR3WHVDenc5V0lRRmdnLUpDVHhZcDloMFhXd2czOVdnQWtQeUR0eHl4dXlfWi1qTHFXNlRIUFpFUGk0OUhmYW40UENDNE90Z1Rockd1V3VTckdXTThpSXRFSGNGQ0FQNnNtUklRRm9xeDdQQlhoLWVVUXdUTGtzampKbVQ3WVZZS1E?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T08:30:28Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Foro Recursos Humanos",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La directora de Recursos Humanos de Tapestry vende acciones por 670.329 dólares - Investing.com España",
    "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxPazB6blU4b3p1UG9MODlqZFRPd0hPbEpQVjhsQ2sxeUlQckFhRDBqcklHQTJKa0RSS3pSNTlzSGROSmd0amN2blR6SHFKbmdjd1VWQ3FnMGF5OXdBNnZFMTZqMjhLN0lhckZ4SkJiRVlndTBDenJHZTBWR01GaUxGUG01S0Y2eTN4V2M0WUNBcHVIemM3Y3JwdVUzVTdyNDUyQ0d3Zm43TFV0Y28wdkxxV2JWbjBrWWVNSjRaVWhCdkFwTDV4Um9iM25ZZkpINlg1aVh5NDlmb0dsQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T23:02:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Sindicatos coinciden en que el PISA en Andalucía es una \"llamada de atención\" y piden más recursos humanos y materiales - Europa Press",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxOTWlIcWY1d0N4SWJfSWZBdGFZclp1S250LUNZMTVTMDdJaVlCN09KR3F3bHI1cWxKQWx1c2w5Q1V0UHlFQm16ZW5zeFl0RmVmQ2R2UUszOTNVTUJ1eXhRd1NQSjFoTmxiWmNGa3FSMzJxV1M4U3pycG80TW9UX2Ftb09lRE1yc05pSWo2ZHhIUk1wbEYtNXp4d19YREx0b2R5VzNSRERtLTY5b0VaUVc5eFRhcGRycVVIZ3NLQk1sUHBhR0hyZVh6QldzdTVsUUZqTDJ0YTl3MDkxSXZzOExLY2V0M0pMaGRWMy1v?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T11:42:51Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "PISA",
    "ubicacion": "Andalucía"
  },
  {
    "titulo": "Top Employers Institute reconoce a Dia España por sus buenas prácticas en recursos humanos - RRHH Press",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNLVdtNUlNd0VKMEk3NU1oeHlsMl9ONGJiWldxOXVuNzJxYU5iMUJhd0Z4eFR4Z2RGNGppZ1hLaHF2M1FJOTZCdG1rNmtMbVZPNU4yZ1p3cmlCZDJ6aUdKaDdLN29USVpfZWFCWEM4Qmx6eF9menlBaEtPd19rNnJjQmhycTZTa1FiVXdra0tGZ3UtaWlhb1gzYXRlYw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T16:58:29Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Top Employers Institute",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La Comisión Europea renueva a la Universidad de Burgos el sello de excelencia en recursos humanos para la investigación - El Correo de Burgos",
    "url": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxNLWdNTGlseUl2TWFMT2VSZUxBaWZEOG9fMjFwalNjMUR5UnNQR05sZ2RYdHdXeXYtMHo4VFQxeW4ybE1oRE1JRDB6YWtXUl94MHpFd0Z2ZjZnSXRNVVBha1BSU204VzVWbnIweEVEYVZsdmJidkx6Ti1PbFoyaTZxNm9SYVZxVG8wVEhaOUVqMFdHU3VCVWUwZlR6U0lKVm9sT1ZUa1lLZWdEa19vSUJpcFh1ZF9FemFNNnJKWUx2WmN6RDl1T3ZOcHBMQmZjdlBCNmhpX09NazVBVGNKSjM5bnhqNVLSAeoBQVVfeXFMTzBQcHlIRUhmQi0tdWlwYklZUVVScUtuaGtmNUlxZHhMNF9PQUwxc2l1VUpoTThvZUFibFZtOEZKaENkNkRmX0ZFeEJEUHR5MVBKeW1xRzhieWlfbmRZY3RINDh3QUNrUTRZaFVqS3YwcGl1U2psNmFUdkp1NEw5WDdSSXN4ZldiMGhfTzRneGNsOTVQaTZwS01QQzZwRVY3VFVYZklUTUplTDBBZFlUMTNjS3B6VlpLMGFfNmcxdUE5MmNEZ0EwWDNUYjBJRDVJQTlydWduVWdmYzVjTEhPQWVHOGNoazVOaDFB?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T10:11:12Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Comisión Europea",
    "ubicacion": "Universidad de Burgos"
  },
  {
    "titulo": "Prohens inaugura el curso escolar en Formentera destacando el refuerzo de recursos humanos, servicios e infraestructuras - Forbes España",
    "url": "https://news.google.com/rss/articles/CBMihgJBVV95cUxNU2xtazdmRWh2VGdCSkowWlY1aXBKNWo3bEFTZW84aWF4M2gtRHRwOGVBcHI3aDEzX2ZOQThXOUpwN1p5bHMyMDJaSDV5cFVKamJUOVgwcGhWX3dFajZFY2ZER3E3VUFHWlA2c3Vwa3dOZFpxQnFQQXlaZmpFelN5TU1lNU9KN0V2MXdlUVNLQ01rSV9wMWVvaDhDTnVhZDNVUzkxWlhYbm9VTGpFZFo0RUs2OVhyZTd0X092Wm9nNDZLRWNxWFM5ZDVMeU1LRERwRm92VEZrYjN2bm5xXzdSTl82YWstMHNOdzBWdlpvM1hvbTVjLTNQSDJraGlqdnZ4UVpXMUpB?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T11:19:28Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Formentera"
  },
  {
    "titulo": "El juez prorroga por segunda vez la tramitación de la causa seguida contra el alcalde de Azuqueca por supuesta ‘prevaricación administrativa’ en un concurso oposición y cita para declarar como testigo de los hechos a la técnico de Recursos Humanos del A - El Heraldo del Henares",
    "url": "https://news.google.com/rss/articles/CBMixwJBVV95cUxPVGVsYV91UlBDd0JVeEFyaUhGUndNNjc3TXdaZGJsa0pNLTFwNmF4RGYwenZETjNKZzVjM2tKbHFidU90WnZVeGNHM2JtZlg2cGZXdmc5V2ZQMF9FVUZwcUJXbmNTX0ZwSTh6bjFtNjNpMThqTW1ZUE95NWZpbzkxbmVnVVFQNHlEb1RrWlpFSzl0X09jU1Z2UjZMWUJ0WGhXZ2lDcjNTNkxCUnBrMEYzc0tEbHprWnV5UTVsWUc4TFhLajBLM1JfVjl0ZGlQc1FzTGl2LWJsQkhSeDF1UTdCUXd5dTVWNjU1emZ2MTJPX3BXR0U5R0pHSFoxV2ktbnNmZVdoTWdwMjV1MjJUWmZnNHpYbHBXbmtMWldLMVBwNnI2MVpxNmpKWllKdldqY3hsOEhhazF0SWZWanpleDNYVzVvT1kxM00?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T11:15:08Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "’",
    "ubicacion": "Azuqueca"
  },
  {
    "titulo": "Uniper se apoya en Celonis y Microsoft Copilot para la gestión de sus recursos humanos - Diario de Sevilla",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQU1M2VlhydGdCeEJNbDhkb3hCMFlQZkJKRUROQXNFUS1venQtaDNsdm92cFpiY0EyOGpZR1VLdF9pMWJjR1BHSDJHZFhHWVRoVVdsUUxTZHMxRVdPUWJmaWN6cThJX3FZa0F2bUJTS3VyVDRMd3NiWGRnWFU5NzVaTHVXOFNBcHY1dVNGX3hzWlI2ZVEwOC1CbktNY2s0YVRQUElmcXJ30gGrAUFVX3lxTE40akFXZG1sZjhjZmtwcF83cW5xT1k0d0tLckE1aGxYSFRSa1E3UWtYNjR2SHQwY1BQcXZtVHdGTDUzV1BmZmh6V0lianpwYkV5NnRucEphVlVkbTdwR0FUa0VzNkNGS1ZYdDRLQ29zZmJlMHpkcFpReDV0eXlFek1fRGIyUlFlbFYwaE5wZFFsdDRNSlB0TTk1LS14YkdIbWNvZDN1bzAzaUI4OA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T19:07:38Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Celonis"
  },
  {
    "titulo": "474.942 euros permitirán la creación de 22 puestos de trabajo - HOY Almendralejo",
    "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxQcjgza1V5bHJRb3ZlQWV5NzdHMklkRkNORE9ka3JGQVRQalNodi11TlZIaDhqUEtvdW1raGJoMVlPejhaSGE2ZmZraUIxNGFaVjJaQlctNnpKSmY2NmNfMmpNSUF5RDkzYWxpQjJyeFdwT1hnSFNpc1ZkNGJMZ2lJRHhUenpUVFJSanY1dm9FMjE2aFpHbGZzMWRTNmMxNDVG0gGmAUFVX3lxTFBUbF82bmMzTlpLZ1gxWlRwSWFFSFpqZjNyME9KR3dEUXpyVHJGV2JUSFlnNzBxc2hKWEFDZUxtWG1DOGN3a1hnQ25BWU42OUhIcTdzQnRqRHhzdGNGbUtlUTNHU042TkhVNVcxLVhYOHl6SHVLSF9uWFRpb3NRU3dFd0pkWWtYd0lzTnp5aDVQck9INXJTaVFpaDJfMDRxTWNnNVRPWVE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T15:24:06Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Almendralejo"
  },
  {
    "titulo": "21-O Sevilla – Personas y marcas reflexionan sobre el futuro del trabajo - Foro Recursos Humanos",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxQWWNVX0xoejhuMEt0WllUSWc1VEQ3YXN6YjlnYm1GZWF6RGVZeEhHZHZKOTQ0RjBsNmZoYUF2eFJnbHhuTHUyY0ZYeGFDOFZ4UXd3dFhnT2xrenFyNG4wWERWM0FUTTZNRktCS3c5VjZrbG1LM0Rtdzk4TU80ckQyb3dRMkwycDA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T15:57:20Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Sevilla – Personas",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Guillermo Rodríguez Iniesta toma posesión como nuevo decano de la Facultad de Relaciones Laborales y Recursos Humanos de la Universidad de Murcia - Murcia Actualidad",
    "url": "https://news.google.com/rss/articles/CBMirgJBVV95cUxQY0NUN0o0RUk4eU00RXUtejNDeDBHYW55OWs3YmxHOUFsU1hMRzNMYkxMbTRFU0huTDNXcFVMZDZGUkhSTFBBdGFqMTUyOVZRUFJMRE1qYWZjZ2JudTRvamJiTzZVcm1UTFk2MGZpa2NqY2pvaDB0TXF2b2dSU25PRlVhUzhIRWJ6Zl9MYUxNamFVRl85UG9QN1Nad1g3emF1b3VLT2Q2ZHdyemV3T0xKdGZRWW9kb0pFREFSVFVHRjNLRTRtc0RuYTJ5Ym8zS2ZjUzlYYmc2UW9aRHh0bElSOXowLWdiOUtzbE12bWZ3SW9MQnVYMTFSa19rTVFfVnJYUGduOHZCSHNmZHdadDIta1g1NUdtbjlFYVFaNDFKMHRkNWRIWjEyckhEV3Y3Zw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T13:22:33Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Facultad de Relaciones Laborales y Recursos Humanos"
  },
  {
    "titulo": "Cómo ponerle un límite a tu jefe con clase y evitar problemas en recursos humanos - Telemundo",
    "url": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxNcDh2N3F0TmVtdncyOXhFckcxb1RzOWlrUWYtck9xTnVfSVNyWGY4dTNkZ0tWMG0tcVExNWM3R0ZDRDBvTDJVYmJTck9kSGxmTXlLYVkxbTJ5WUNOZ2dfdkpBOFVnNE1naGNxRmlCSnpyVWJsQ0xSWjFhZDNtbF85VU1WTE55VzdKbWVjeUhRRXE0RVlNaGFSVV9aTUIxR0FvazhDUjdwUFJCWTBqRFV5d2diX1dSZHFDM3E5UzRIUTBNODdYUUM0VEY5N18zbng1Z0w4MjlSYkw3UHVQbldTbw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T08:02:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Telemundo"
  },
  {
    "titulo": "Una exdirectora de recursos humanos de sesenta y tantos años inicia su décima aventura empresarial, aprendiendo a gestionarla con la Generación Z. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMipAFBVV95cUxQUEtWOHM5anFNNl9WWndGV2s4a3FEemtJQWtSWkNwc1IybzFObDF0NTV2U0FGX0lvcmtUU1I1el84NUVYak9HU2VmamluZmdhRFljTmhCSm1jcGhYdkNhblNLaUlPbkRPNHNBRWlydU1FMTQwSDk2azQwOEhSd1U5VkN1N1N0RzFVZHVfSVhhdVRrT181OXBuY3J2bTl0dHUzRmgyVA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T01:28:22Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Generación Z. - Vietnam.vn"
  },
  {
    "titulo": "Nuevo Máster en Recursos Humanos en la Universidad Tecnológica - boletinbien.com",
    "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxPcVE4amF2QXcyQm9MQ1B3cWRoSXNYZDRhZlp3b29zS1ZXS05vRUlhNlVqOXRIVUhnQnltMnItOHBpYzJGbEU4a1cwVG53R1Z5UG04azNnaEpQOC1rQ0ZxVXZHYldydDlHMER1c3pMQjVlYllBOF9OZVFNUHJlZ1UyeDdsUXZzSWRiVmhaS0d2SzFWUmxhU0hDN2NrN2xTdl9seURHR2dsVHVfTUZtdk53NUlmZzVmMlp5eUJ5MjItSndaSUt2NGxCRm5hTmRBenoyb19xRzdUOXBhTkVpelhPUVhzcw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T09:57:56Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nuevo Máster en Recursos Humanos"
  },
  {
    "titulo": "Importancia de continuar la digitalización de la gestión de recursos humanos en la APN - aps.dz",
    "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxONWs0UWYycmtmSHpsTWdSUmtUNmM0WW5DUzFRdUE3M3owa3lnMWJNVDBmT2JGZHN5Z2tlaXgwMHNpaHJ0STRlR2ZtLWZPSEdvS3k2MUdlWkJJQndtYzZoZVdMS1ExRlh1eTN4UGpQVDhvNHd0Snc1bjl4M2h3M1BvYmpVMEhLRmpLX09LQUpWVURSbVRwVDZ6OVM3ZGdoNlUxcnpFdF8yNkEtSi1pNzYwUExjei1BTWVVcnRCbGgwQm96UnI2dXpTNDNHbmJ5dEhrWHBfSGtyZmRLR3RYclE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T08:11:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "APN",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Un gran porcentaje de trabajadores no sabe si su empresa está al día con las normas laborales - Infobae",
    "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxPVnpBQWpNTnNuQ0hKUTZtdGd5a0Y0MGQwT2VHc3R5SzhObUIxbDgtYU1US2RqNE8tMDFFc09LdFRXdDUtV3JfMVFVbzY1ZEhoNnpqRWJxY2FLUFNhLUJyU0N0c3doOENnUUpBcUlPdjhyNE9LQkVCdTdlMmpqTjQ5R2huTk9rTF91QzdMQXhrcUFHNGpxdUZxWTZUZ2g2akRDQVhrZGRMbTJCVWFzczk2V3BqVXZEdDZLSGhwb3V6Z1pUQ1VPUm9JZmJYbDZ3aDTSAeoBQVVfeXFMTmctM2tkdDRHd2NYamczb3ZPaTlnSTZCRUhINWR0dERxSnVtbEd1S2lyZ1NreU9IZVZtcWZ3dUhwYVhiUVI3LXk3VDZCWlpBMHZnRUVjSHZOOWNicG9vXzRuWTJtaU02akluaHNzYVFwTEpvTlZwVmRlTUgwV2I4UWdRbXJEWUJKUHctb09uZkVickxhNWVtaEQzdnc1ZVcyZG5ZS0duZjJJQnF0bjBSdDlyeUstSFpQYXVMeGpkZ2NEMGItM1ZXdnZzMXQtcTFzTk5EYVhoOURFMnR0UVdwNzJiOEJ5dzRJZk5B?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T21:29:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Roberta Duarte asume como directora de Recursos Humanos en Maersk - dataportuaria.com",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxNdHNJOTJjLTJKYjNSUlFrajE4cG85OUlBZTFFU1RGLXl2QzV3VThJemRuWENTeWh2UjlEUTRvQVlqNjFTVThRaWFJWm5xMTJ0OHhndUxEU2NzVG11MnNybFNQSWxjVDNZTXN1bTRUbmk4U2pQOXVHWXR4NjltVzkxNU90TjNjSmJsYWpMMW5JMmk0Y3lfdmVJYmZyQkZKV1RyWEJPajFqMklRTjBuc3RubA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-05T09:30:45Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Maersk",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Becas de Adecco para personas con discapacidad - Ayuntamiento de Zaragoza",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxQQ2lLclhkS2hTTUY0aXByelhObUZqS1RMeDNpbWprc29famxBNjdwVzNDY19RWWNaZnFUZHcwU1RZdjl6YThDRFVPRVZSOHNWQ1R6bEFBb0lmLVl5UVRLZ05qWk9iMG1TbzU4WTJBZVdtRUVsMk5kT0loLXlDaXdUc0xaa1BiV3Rtc0tNSQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T01:10:54Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Becas de Adecco"
  },
  {
    "titulo": "Alianza de ARTE y Eurofirms Foundation impulsa la inclusión laboral de personas con discapacidad en retail textil - Corresponsables",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxNUkhnTDZTaG1DOTdIZ0lPdy0tdUxQNm0wWEN0WjRabVFDUmZ5WlVZZmgwQ0ZYcEtnMlZteXBpclFzSVp1OXlsRzZGamlqWHFKWHduZmJfa0lHTWozY1pzY2stT2NtQ3RGdFZWcFVrODdoSnFtZTJHMFJUcVJFbmNGMWs2ZzBRX1d0VGt1LTBsUEUxWmplalJ5ODlWb0xRRVZ4eTc2X3IzOTV3Um5IbE42SlZn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-11T07:30:14Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "retail"
  },
  {
    "titulo": "Arte firma un acuerdo con Eurofirms Foundation dirigido a promover la inclusión laboral - FashionNetwork España",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxQNFFjbnRuNkNEamhPb28xblNMN3c0SFMwd2lmekpUbUtqd3ZVUVQ0TWgwdzI1Z3Y2ZmlscDdVTU5OdjZVUmlnZkhjMU9Ha0EtZmFoSFBSaEpjNFprZ0RQNEhQNjNjWlQtalJrX2FranJkeXF2RllaVExnNV9CWmFZZnkwSVBDOEg4WEFENjQwYkkxNDNfaHQ1WTBQMHJwSTNiMVZlMFB2em1XUllQeWkyakZ0c1JyLWNuQ0RQQnB1MzNhVjlmbXNjdWxyeFVScHFT?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T10:56:23Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Las empresas de trabajo temporal incrementaron un 9 % su facturación en España en 2025 - RRHH Press",
    "url": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxNRERZc0tYd3RLVXA2dmdoalduMXhhOG52LVZNVWwyV0tIMWVTM09jVW1sakVNakhMaTdGVjZqbE1HUVZSZE5IeGJldXI5Wkxoek9paXVEUFFNU1V5T0R6UmNvMm9HMFVyRkhyYmxpWGlZT25qQVAwTGU1MkMxYVNLQ2lGbTJhdkUy?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T07:44:42Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "España"
  },
  {
    "titulo": "GBS Finance asesora en exclusiva a Job&Talent en la venta de Avanza a Eurofirms - capital-riesgo.es",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxPZkp1SWZyMlR4dkRoY0JRdkRKam1TRlc5MWpMZXQ3a1VkWHdQbFVCNzM2MUoyYXM4NWVkRzZ6R1ZDNjZlNzdGRVFuaFJYRWRGSmxiUXVqQjdzOEY4YmxvYkIySUo4enBuaW1TQy1sU3NPOGVYQTJZa3FIenhFZTdrYUdOV2dJdXk5S2RhM2ZKMEtjRnpzZ2p4WGRjZjB2U3BzcFJOLXNoTlBrY0ZvcnJQcDY2WlBDNWZVREE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-04T16:02:56Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Job&Talent"
  },
  {
    "titulo": "Partidos Caio Torres - acb.com",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxOd21KcHJfQ202ZTctMDQ5NnRGOEZ6VXpRUGlKMmxqSnNQTDBxaXZBOEF1bUdlcm5Qa3J5ZXdab1JyMVVhZkF5bzVZU295ZWpGQURhYS1ydHRxZlI5TE90Y2ZtVnRSQ0o2aXFVblVWZ3JicTBrOVdrNHp6ekc1LTBYMk1sbEJIM2U1M2N6R0VaenBVcWY4TUZPeENSSVp5YUxPak1FVEp1dHB3bnR4dDc3VnZzb0U?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T11:59:25Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La tasa de absentismo laboral repunta al 7,62% en el primer trimestre, según Adecco - Radio Intereconomía",
    "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxPV2ZvcDZ2bGduZTVCb0VZUVl0ZWRJdTNRT2F1RHVObUlDSHhQUlV2YmNBMUR0dFo4Q2NaRVJQS09ubmdjVU1WX0IybzVtZC1DZGhRRWRPUGFMV3Jvc0NrNDNEV2VfODNjSjZYOUJpVTZwYXUtTEJzZWlIRDhKWFI5YklXdmFubDhWNno5b0lpRExRSzJHMEROMFlCNXotUFJ1MTlJN2d3aXlzTkRkUmtybXN4VGtZSFN3LWxzelZtcVZ0LWdGSzEta0JZUTFxbFIyaWpnTtIB2gFBVV95cUxQNkJsRE5XbkZTWGhLVTVMaVEtRVcwMW5rY3JOa1BVVWJMbnQwTkdMWVBnQWFrWW1YTGd1TURwcE94Q1JVQWl6amtHLXAyaTgyLTRJSlJmU19RdjZydUstQmhFSWtEMHVsSThoYTQyUWpzcV9HNVZlWFVQdGM1THZjNVdNX0lRRnU0aUVhYVQybUVRWjJVRjJXVjljM21KX2oyQ2xpLXZZZXBWcU15RUR3aEFmODkzTnVCYW9XVkdSbFhaNXVoVlE5cFZSTmotZDlPSHQ3dm9BTjRHdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T12:12:45Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Grupo Kirol renueva su colaboración con Fundación Adecco para impulsar la inclusión - AZARplus",
    "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxNWU4wb1l1a1dkRlFqd1VEQl9jTVBFQm11emxNbEowYldyMGl6Rm9JLWJWY0FncnhjRFRDNTY1X2E0YjlEOG11QmN2TTJqM1VUZVpPUWN3OTg1TUVXbm13WjlLb3hKamJmczJKdGJ5SlNQc3BQQjNKUTYyZlQ1dW51OEJLU0dRN2FtZnU3N2JKTXhYai1XbXUwMndweDdCVWhuRVZTVEh3aHBYTzhFSHc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-11T05:31:11Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Grupo Kirol",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Las ETT facturan 6.780 millones de euros en 2025, un 9% más, según Informa - Forbes España",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxOb3FTakZ3QTFlY1llejVvZnZwSS1qN1JCY0gyR2poSVBaeGx5dy0zV1REQ254ZXBkMDJqUy1uZVVrRTc3YmxiYzFXenpwRVFRbHcyMDdNS2hPMnpST0RjU3UzRHg1MUNyQXM0OTlNWF9FaHo0MUxzZV8yS1VtSk56S0VGM0lUUU9jbHVjQU44R01RNEl1STN5QUVnc3E5NHl4UG1aR29zUGNhMjdWckFN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T08:48:11Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Las ETT elevan su facturación a 6.780 millones en 2025, un 9% más, según Informa - Demócrata",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxOR2FXWC12TEUwUDRjZFR4SURBLU9OZEZralA2emtKS2tiRUI0MVhXZ0xaX0tSNGh4aS1iYzE4bXBITzNvUGZWUGFhaHlsekNaTmVDLVZYa0dVSFdrVzBTQVhkR3IxRC1IcGFwSFh3RlU5R09iLWRZMGxJR0NtM3JqQWc2azJ6dDZ0TEstRGRnQ1o3TEtaNV83TUI4YnZiSE0zUDNEak9EUnVuWnJ1dXpOME530gG3AUFVX3lxTE5FMUFTdW5Vdndodl9XNDQ0TGotWEtVX0RHRHotMGtJOTJocnRqOFVickJIQndIN0NZRlJ1dGhiT1FjY2pIeGxsQ2pZa0J0Tk5vU20tS19iNWhPWnRkU0NTTVpWUE1aVU9tX0prckRqTVVoQ3dfNXpQSXprUnJydEJMLXdWajFEbzduUGVmc19neHQ1WkdnQ0VBbURhSUZRTWJ6WGU0WXVHRXRfLTN3eGxTVjUzal9LQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T08:51:09Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Michael Page y Adecco repuntan impulsados por Deutsche Bank - MarketScreener España",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQWEJBeGZwVEtBNFk2OE5pck5ZSXg0azEzRkQ0cExKY3pKLXgwTkJwSVRUNlBTQ0VDdFdUWjRYNHpPTlZzLS1xbkpRUVlYaER1Y3otWHQ5WEU1WDJHVDJNUC1yT0pjdXowQTF3MHFHTklpOFFjR3pmWFpHN1VUeV83cW1IS0NtRS1maFpRS3JjYXFfQzlmMWNlWWxyVkcwTEdfbTJQVWtMZTZuT3cwUFRkWXRyYXZlUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T12:00:25Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Deutsche Bank - MarketScreener España",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Adecco busca un Content Creator & Social Media Specialist en cosmética - EXTRADIGITAL",
    "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxPUGxfZndROEhqX0p5UjAzX3ZnUHQzbXJGSjVxRm9zNzdfUld4Yy1ZRTNCaHZrdGxXMTcxVUJ3VXpVVkFVN0RoVG5TUFRTMVJRMVhxcVl4VncxdkJ2ZlpwaHVGSW1lSDFaWG04MXZuUzB6QkJkM3RFUU1ZWVV1cGdKM0dKOU1IeGY2azdEblduRHJjOE55M2gtSXVGYWRRLTRwd2ZqZl9nQUNTOEpX?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T08:09:19Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Randstad impulsa la contratación en Almería con 200 vacantes en el sector hortofrutícola - Ideal",
    "url": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxPMDlaNjlyal9hVGRYOC1tU28wY3NwMEs4aG5fQ0N5WEFBYW83cm5vdXF2YTk1cVU3bFVxNHhkTnh0cVZDS3dqWmkzb1FSd0lhbG1HenJ3QTViRjFmU2tkRjlWcmJDdFhxSUpLS1ktdUVLVWItRTBPdldXRHlYeFprMUpjWldvb1FzS056UDB4YloyUGNwNm5UQlV0RDEzR0hYMmdFOTRlNkxld2ZRbEw3NDZScDdabG9wb2M2VTlkQ3FwWU3SAcMBQVVfeXFMTzA5WjY5cmpfYVRkWDgtbVNvMGNzcDBLOGhuX0NDeVhBQWFvN3Jub3VxdmE5NXFVN2xVcTR4ZE54dHFWQ0t3alppM29RUndJYWxtR3pyd0E1YkYxZlNrZEY5VnJiQ3RYcUlKS0tZLXVFS1ViLUUwT3ZXV0R5WHhaazFKY1pXb29Rc0tOelAweGJaMlBjcDZuVEJVdEQxM0dIWDJnRTk0ZTZMZXdmUWxMNzQ2UnA3WmxvcG9jNlU5ZENxcFlN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T16:36:19Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "Sólo buscaban empleo pero no vieron las valoraciones de esta ETT en internet: «No contestan, hay problemas ... - OkDiario",
    "url": "https://news.google.com/rss/articles/CBMihAJBVV95cUxORWdUakFDODdNQzRaRGdQQVZJNFJieXFiN1hWbjhGY3lqbjV2bVNBSXBxZmJCSFduRnZNcDQ4RzNKLTFlQmcwTnBPc1RtQndLUEd3M0NvWG9DRW1iSWNOWUpJSWR4TkxjVkxER3MwVUlHdWJKSEdSdEdrdHd5NDFia05WZjBVVS1BUWx4aWVWdTBMTmV2Q1UzMGpRLXl5c3BUcjFBVnUxVGRkRWluYmx5WTd2RWtPZ3lPbDZTUWc3RC14N09WaG9UTXBWNURZVVNWX2VTZHRNM2RwV2VHX2NDVmYzYjY4RzlOZTdTZFFTbzZaZ0NNalc2Z2lPbmRUaENjX2hvT9IBhAJBVV95cUxORWdUakFDODdNQzRaRGdQQVZJNFJieXFiN1hWbjhGY3lqbjV2bVNBSXBxZmJCSFduRnZNcDQ4RzNKLTFlQmcwTnBPc1RtQndLUEd3M0NvWG9DRW1iSWNOWUpJSWR4TkxjVkxER3MwVUlHdWJKSEdSdEdrdHd5NDFia05WZjBVVS1BUWx4aWVWdTBMTmV2Q1UzMGpRLXl5c3BUcjFBVnUxVGRkRWluYmx5WTd2RWtPZ3lPbDZTUWc3RC14N09WaG9UTXBWNURZVVNWX2VTZHRNM2RwV2VHX2NDVmYzYjY4RzlOZTdTZFFTbzZaZ0NNalc2Z2lPbmRUaENjX2hvTw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T06:45:34Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Ignacio Jasen - acb.com",
    "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxNZHl2a3diQm9xZkU5VmM4MFo3ZFlvclNpeXd4ODJLb1o1OHlqZFBwOTByQndmcVBjVHFGTjVjZWZXdEoyRkFMRnpucy1QTkZBTE9aX08tUUo4VnktYmVBeDZFeGFsY0ZMenp2SVNRZVBvUzhQYThTUzRWNUw1YWMzeDZDM01nRG0yVnZGcm4wTWh5VktOdE93Q0xYM1ZHRGktNUR5TGNqREtqYzEwZ00yZXMxUVBSTmpkOUJPOQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T20:12:05Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Trayectoria Felipe Reyes | Jugador acb | acb.com - acb.com",
    "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxONVFXSkxBY3dadkZTMWtCUGZlQ1Q0Ti14ZVdNNGNHLWE1V3Y1S2hTNl9xMmxXNFpoanZfUkszNXY3QU4ycGtlX09WOXZpbHYycUxuUzMyWE5MbXN0SjJoYkk0eGtmS0FBbHlzc1RZSnVCMEx3dmtRRHAzUlZSeDFtRm54MUFSeFZjTVQ1dG44ay1hVGZNay1CamwyMjU1MlIyNkhzXzVHTGhOcHhzSG1FcF85OA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T17:51:16Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Trayectoria Sergio Rodríguez | Jugador acb | acb.com - acb.com",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxNR0lNdnZQZXlRUXZxdXF1cFQ5V0l6MjdrUVpTal9JWFdNV0VUSkNPeUZpOVM2dDhqRy00S2NKb1I3SjFCbkZrQkJnV0ZNZmd3cmtwT18yOTlQNkxxWVkzdmxaQW9sTDMzOTZTWHNfNHZVLUd6aTVESV8wVmNCQzI1blkwS1VwcG5YMHFmMQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T21:15:58Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Gonzalo Martínez - acb.com",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxPaXhnVkpUZ2tHb1pKRXZsWUtOcXh3YnlRZ1JoMWZJdTZIMVhUS3FZWkx2d0RTYWZzN3VGMzA5VE9NMXFaWlhLemdjNk9yLVVYUThlYXJITklGVnV5S0ZQVVhuMGdDM19yalBBMDBuUWpWbGxjMjBYbVFqWjdyX19aYkI1VnFpMjdYYTVwNXhRel8xMDZzTTNyVC1hNFV0OXZ0RnhKdFE4ZUQ0T082TnNYaWJjc184UWlvbVNkVk85S3BvWHg2TFFpRA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T17:17:37Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Sergio Rodríguez - acb.com",
    "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxOTHhQWjVGMm1meGRIbjNIUWFBS2hLQW82Y2c1UEN6NzY3eXM5aHhSanFwQjY0aWlJMjhsVkF4a0ZKYjRmWnE1TkpwMHpiS0VrQVNhN3RQemJqQ0hqU2ZONk11U1hkR2wyQ1FqanlZYkI1dmU2WUtBaXhJcmpERS1wTTd0Q2VwSXhuTzd1NXYwdlgxUW55Rnl4SnZTeTZ0WE02QlNsTlRsanI5VkgtemJFZTVOb0RQd2tGOXJIYk93b1pURmtDYktSZzln?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-11T01:49:11Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Trayectoria Pancho Jasen | Jugador acb | acb.com - acb.com",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQS1N5YjA2djFKRjJNdjFyYWtUbHJnMDZaTmR2RWVBdkFVUnZqc2x3UXo1VGU3YUtpQkdaWWRuMVB4VUxleUtfeEwxQWJOTjJPbGkzOHdWVnBYQU9XcTZ5SFl6Ny1DVHBTbDY0WHlJLWdtRjNUa2tvM1R4WXdfNkpwekI4U3R4YjhPRlFxei02YVA0VHctQngxWWdJNW9JMVFrQUN1cTA3UFZGT0RlOUg5YzlONlY?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T15:26:10Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Anna Golsa: “Hemos llegado a un punto de inflexión en el mercado laboral” - Cinco Días",
    "url": "https://news.google.com/rss/articles/CBMivwFBVV95cUxQTzZPUjZRaW83WWxKQ2ZFd09CN1NNbWRpSV9YVHVlMTc4ZTVmT0pkQ3dEMlRwU01FejU5dXB4ckQxdGkwU0xTSF9IRVp2YW5acUptRE5mSHhjZkQ3SlFseDZ4MXdnZVd2aUNRX1FCa0lNRnB0bVBPM1NjeTF5NmJtNVltQktfNzNMeU1DTFEtWktWaUpnS0ZlbzNBMnJRVDRoZWRlblFfalBZUTJVMEhxV25VUldUSXVuY2VwTzNMWdIB0wFBVV95cUxNenk2OWw0VHBjdFBTUHdNUnRibmlYbWFDenBxdGp1TGN0MzVKWFdIeGh1c2JqMGdBYUd3YUtONEp3eFRmblBSbXFwNmRJbjVRZjZZLTlYNHEyV0NfcTQ2TVpidEVFcU5YOTVnNGU1X1VBTXk2dWJaamVjaXdlX0lmbVdHQ3FvYmhqNGFEWUwtelJaM3JOMDlTVE8xUUxFdTJ4VXRjb19sOEs5UExLMm1DTFNfZi1TQWI4UUQ2M2xLeTNKcElkTmM1bnE5RVp6RjY4NExB?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T07:44:25Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Partidos Andrew Betts - acb.com",
    "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxOMEhNaHdQeS1XU2g5bFVFRVJhbXRmWEVza0M0Um5fTl9YYjBnd0pQOHhMYV9MMUJpVFVQdzJaQ3BFSXlrNnZUaU5XbWxqNmc1M1NKRGMzbEZLTXdSRTJlckZkZ0ZoTFdwczRMdXNQRU1QMUUxQVE5T2F5UGE3VkNQNHNLa05GUEhBSjJGNjRmeGVKZjFERTBxY0lDbFJVbnNWTWZDOVZickNsUmhmb2lFX2txd216eXBCSS1zSW9FWUNWQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T17:29:34Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Carlos Jiménez - acb.com",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxQbm9TMmg1Vm1uRlN2WmNRd2tfb0R2VGtadk5rWE5jRHZVcFVZalRMSUU4a0hPQ3F6d1BLcGg2eFBWMU1ZLXNhYWpsTjN1QlFEV2JsZWlwc1NDLW9mNUJCNHd6UmhZeTJYbzB6eVMtVkZrMUtQNmV1NXRlWlJfOXNhYm9JMmFVZ1FJX1Z1c0ZRME9xSFI5dGd3NC1YcklkZDlXdjFlNm5sUHVDbDBEemxGd1lhenpISUIzUmJLUk5qTExpcThWVjRMZUlXZTY1WDA2?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-10T08:51:06Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Caio Torres - acb.com",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPR3ZmTGZKbmVUWWZxQmdwOGI3SE41bWpJRFBKa3A2dmdxbEhNWG1EN1ZYM0RnbTdrZUYwejNWeTJyLVZGaXdfakFzaFlucW5ZY3BtZlo0VEwyR0E4SjZlTGlTVTZiT281R2g5TlNHWW85Sk1ybHBfNHJtRXlHRk9GakRROHc0LWtremFMRXY2SjJCMUlhTHRYR0NuR0c5WDVpTlYxdHl5Yk9xSGRSVnVzOE5RVC1GVmgyaE40NUtPTURnSC03VHJZ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T12:50:37Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Felipe Reyes - acb.com",
    "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxQR1RnRm5VbUg1bTNiYXlfc0xiajlINi1vWDVRdjRMZzdyVWlWekJrSDhIOEpkZ2ZkRGtLSW9DbDBlM01oOFRPX040Qlotakg4RVdXdWhhZzU0YmMtcnU5em1wR0ZqSWIwNk9LbzVKRmpKYTVLQVBLcm5uRzNDUWt1LTJrVE1NaEpadGZCajdGNFItT0VJV19wb29GVjhqOVBjRERsMENyazEwUTlCQTlXR2lHZXBCSmVCdUtnS0VrcmVJdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-09T04:12:27Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Pancho Jasen - acb.com",
    "url": "https://news.google.com/rss/articles/CBMixgFBVV95cUxNeFBYWkJfVDhlVnBYbWJsQS03OERreHFIcy1BNVVJeWNLbTU0YVRRcG5lSTBpQTd1LUV4azlkSy1FYmRFaElXQ2l5Z1k5ZGdHNmRPX2hsRzBaQUdrcUNTbGJiYWdtQXhfVW50RzBfclVMamk0UHNDYm9URkdtWHNWMmxVWkVkRDd0UC1jZ0JiT1BQUUFablB5RjlqeElMbnZ3UkZ5MEwxc1hQcGg1UGhRUmlNVTVZSUN6VVJDdkpfSERhLUJWclE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T20:14:55Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Carlos Jiménez - acb.com",
    "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTE5OaGdZQ0w1THc4UEdQdjNmVDBuazlGSXR0UUVHemlNN3czWHBycG83TldYTFozel9WNnFPRS0tdm11WExCOGRERTVLMDVIWHhzRFQtZmFSRzhpWF9MTmlXX2ItdEN1TkhLZjQzbTBCQkhlVUJQR2JiMEpR?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T16:15:34Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Las siete habilidades laborales que la IA no reemplazará, según Randstad - EXTRADIGITAL",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxPR2xBejNCZ3kzR1hLVUVCY1F6WGk3QVZTSk5jU2xNdTBTR3h0UlQtaHh3Z0F1NVFZbzFXaXA1OUR4eExHaXhqeFBfMjN1OFR2Y0ZORmk2SGVqSTBOXzI2U2lOT3EwOWJIRmpiZ2luYzlJNXpma191cVpZTkxvWm1jaVk3Z0lIYWJhdnEtWkVkcEtMLXlQbm56SU9OMkFSY19VTUNhdmhBSGhvYVE2dHFJ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-08T19:09:02Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "Economía.- El absentismo laboral sube al 7,62% en el primer trimestre y marca máximo en este periodo, según Adecco - Bolsamania",
    "url": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxQWi1rRXBWOFBtdGJsMGVOQ1JTNDRwYjZQZGlVaTgxenMyR2JHWmFFM2x2RC1zclhYOVY2RW1WUnpNV0VJWjhmVTBsZC1TeGJsWFQzOVZqc0w2alFZeW9Na1N0bVJsRkgtdV9abXpZdGhqdU5OSUE5QjBCYUFJTkNQMFFvSXFnRWpCZlV1dm10MWprZlRjd3VoYUJWSDVOa0VJMVdHN1VpVFJPSThScS1hVlpaczFjTEhUMnlCR2pYTEJTVjlsVnE2WnF1RExXRUM3U2Q4WEd1ajg5M0R2aUZTc0hsRDkxdjV6bXROdC1Qd205Y0d0YVZzdld6ZXVxTVnSAYQCQVVfeXFMTy1rWE5JV0U1ZENoWFZzampQSUNDRTFETjRLRjNKazFXS0dEYlRnU3hxTzUyVHNXcU9MQTU1YUZCQjd1aVlraUxSa013d0hFZEtUSlFiR3FSMElyRWFkVFFiN2VIclFZRTJBdERmT1pjcXZTZjdVYnA2OC1xclh6UVA5UkV2c0JBb0stXzZjZU5lOTBOWWVSelpjbFdSVUphQUh5UFMxTXpEVXRwZjJMX0dtLTlOU0JCMnlOZS11LVFtQVpzVGxpT3VzRmlvOFdUYkwxVlQ2VEhFeU15ZlI3MTR2bnU2X2xlbS1aTkFmMlhPZHlEQXprUDRBSF9tbndybjIxQko?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T07:48:30Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La tasa de absentismo laboral en Extremadura es del 7% en primer trimestre, según Adecco - regiondigital.com",
    "url": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxPVmU0aVBRb0NLelRialpKMDZxYjJFUzlzOFMtcmlJdlFhUi1hU3l0cHRzdHUwbVRJTGdYdEpzQmpNa29LZ2d0Wm9GdFh3LXlMbzBjeU9kUDJSaF9kRHNnTGN6Rkpjb05CdUlXdm9xaTVDMWlJRml2QVhYUUVvb1JjazNTc2xyeFRDLThRbzhHX3FYOHV1OXRrN3l4d05vS1hQRGZ5UkRaNUIxRW5RbFg5TVg1MjZmUW4wbjVHc1FJTFVuaU9HTHhOanpXbmk1MXMtelUtT1VtTVVGVnNwQURr0gHkAUFVX3lxTE1pcTc4U05MNDN5bnZiQmRYMmEzcEx1ZG4tQ0h3cjlWRDZoWXhBLThMRGRYdy1OM3JYSWFHZTVENDRCWEhYczUzUnh6N055Wm00eXp6V000SGp1c3pzUi11em12NGg4TUtfc2F2aTZ2RzZqbDJqeEFTbWhnZF82SUhoaFRhclB6Tmw5Qmpyb1hxMmtWeVpkTUczWGdLVGtTME1DQ2dWMkVTa3F2Ykp1UEFFVWVsaWNNMy1ZY2tqZjRNRFcwdFhSYW1wa1BBRWRmSmx5RmNrUE01R3A1OTAxYXlIWDFiZQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-09-07T11:30:56Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Extremadura"
  }
];