const window_news_data = [
  {
    "titulo": "La promesa rota de la reforma laboral: el 68% de los fijos discontinuos se van a 'casa' en verano y ya son los nuevos temporales - El Economista",
    "url": "https://news.google.com/rss/articles/CBMimgJBVV95cUxNaUFWbjgtcGhXNll4RTUxQWdCQzZYOVFXU1pPSDVlM3NacXE5b0c3SkhHcHpHb2UwdXVRenN3Rm9NTDZlLXNfa19PMXVqdFVIanhUQmlBTU9FbXFJRmZlMHJuV25VejBZMDhZTVZDR1dXb1dPUEtUN1R3RkhwbVhkR01IdFB4WEdla1J4NHdTX0VFT0pTb1dIUE1FeGQ1X0FxbkVmZDFvNEpHRnNmNVQ2amMwVExKTU1GdElEZ2VibEpSMnM2c3RjZ2prZFQyU255NkdFOXZhV3plSE9fdk1ZWDBfUHUtVmk3MGlNaTRzSElzVEotdlltakNsMlMtSWxmcEpnM2x2NFpCSS1ZNy1JSDItTW9WOVpuTkE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T04:30:08Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo confirma: tienes derecho a tener tu registro horario y así blindar tus horas extra - La Razón",
    "url": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxONmdVbzJVY1pQQjNWRWpCWTlQQTVzbFl0bUdnUHFSN2dOWlozQXYyUVh5OEpqMl9kZVVMSFlIU3NkbmlqSGdHMmRYR1MxMzdNc0thcm1YWHlNS2ExbloyWGtsYTVNSWpzLTNOZnp3RHFwQnhlME9YU1dQcXBQTFF4WWx6V3NwRkx4NG83RkI4ajhJZGNDS2JNZjBWbjJOR1pPdzJUcG9hU3VoTm51djVFVERxbnVYVUhEQkR6MkVSLXVtcElzdGJDS3pvNkV4Y3QwOWZRaHNucFc0VlJUSFBodFBwRHN4d1ItdWtWRmFFeWE4UFdFNVRKTzBFRTNyUWvSAZMCQVVfeXFMTWxva1ZybkZjckFSajBYZE0xZl9vZjNpekZmYzVSLVlZOHRZckVFVVEtOVZ3MG1QaUF0SGxjajBPSHdvNGJZRGJNdGVFeVJrQ1FROTVUYmpEQlo4TkxMQTUwR082cjRHamdmeDV2U2hMZVVGVFN4WlhZMGw1Nkk0VjAyUnhmVTRDX042bHBsdWczRHlRMzE0SHVmMkktWHY2VkR3bVptSlBUaUxSX0ItTFJWYjhhVGNYNjRkeXZiNjl4VDgxR3ZEVEN2Rlk5S2hKNHZnbzRNQ3F3RlZMck91ZHIxRmtlVHlNUDd6Y3MweDEwMXkwWm4tUW5oMGRiTEQ1dmpqVHZWNWV1MXlxZjZHbFpOeDA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T08:43:35Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Estatuto de los Trabajadores cambia las reglas a miles de empresas: los trabajadores pasarán a ser fijos si encadenan 18 meses de contratos temporales - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxONWtINFNDdHkxeDJCVUdra29zU0dmNk5qT1otdEhiNm1qMGtvbHhLTGJoMTR2OWhxRm1WQlhxQmhaMWNoYWU2M3pQZ0syUlJlS3E4QWs2b2w4YWUxcExDRDdmNVVhVEFQM0N0bHZLWEZLcG4zSmxJWWVxTHhoa19tUmJ6YlFjdUU3RmhURHBDeU9rV19VWXN4am1lMGY2Q1VjYm5yVzhidFpHRDlyX3fSAbMBQVVfeXFMUHlZVmxiTEFTdUc1dVZNaE1sSElnZWJJUUctYUpYdVIzT1l2d0xLd05UYmN4eG9jWWpfQVR4UDc0Q1BJeEhCR1BndUFHOGxuSzNZaVNueXVrQk8zQ29FYk85bW9vdmNzY0g4NUFkLUZ3cHFhVVJBbWZNT0tzVXVWRW5WcTlvYjJjZFVON1ZTdmg5dHlWc1p3b3pBdk5MT2FmN0tRTzN5S2JHX3h4MTladzZhVDQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T09:31:17Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Provincia"
  },
  {
    "titulo": "El Estatuto de los Trabajadores lo aplica: \"Los empleados tienen derecho hasta 4 días libres por fallecimiento de un familiar\" - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxPSlQ5ZlN3NG9BNlZIQXJDWEZaX2ZYd1VrWDlMX1ZRdEhZVUNoM0oxdy1lVEpfZkJudmNUM281cGhOWWxIWm9xYXQ3UTlKTDNHRkNqTG96aV9CakpxeDU3elNJenpsZlpEMlFVekxHaERsaVh2MnVCNHFFV3JvVkJHUWlzTkJ5Zko1ZFd6Mm1jQ2VabjlvcVVVMFdNVFpRT2lKQS0wSHJ0eE5VV0pOc1o4U2drcmpKYVctYTZOWUFyd1dGLXVaV3ZTOFVZTWlNd3pza2cwejk4WmM0QUo3SlpqYnZEa1ZwZTZvQ3FjMHJFX0VoOVhDcEHSAYMCQVVfeXFMT1BUdFRqaklTMFNKWHVYbXVHdmE3a0JJeFNxWUYtcVFQM0xjVlhEUW5ZR1JzUGtKbXdPblV5VXBJOVRkSXJad3VMaUhHWVY4Z1VJVWNGREIwX05MT0x4enVWUk5NWHgyZk5KbFFTalhJZjlhYmY0RUJuaWZaYUpuZmhYdER0WkVzMjlLVFNiWlU3U2plMEV3WXlzcXlydUJOUUZYdTlBbWJ1RTgzZTFETGVTZFd1T1JoelBOcVh2cUJjMGw1a0V2LVd2MXRROE5udS15QURNUUdPNlRhZ2xiSG9ocTJaMHBIQlEtaTM2Y1hPejJtUGhVTkM0ckc1aVRiYUxFdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T14:45:49Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Trabajo aclara que descarta volver a subir el SMI en lo que queda de año - Diario AyE",
    "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxQVnhJeGRaRDJsamwzMGViT0tjdU5Nb0xyWTZ4Zm5RalNwaUZVN3pxVkxMdlZ4Q1hqMWtwMDhjd1JNeDZSR0xBVHJmdXFJYUg4VVRPajdEY1F0U3RVMHV6b2daRVNUV2RzM05OcllaLTdKRUw2R3lhQmtLRDJrcmZNbVhMQVF0R18zTW1iYUhPSjJYMjFVYW9OR0JQMVM4VVpwWkt2b1U5eDVPUmFpN3dNbHQxcVU2dkl1MEpPc3dSZ2NNY1dKenZCOFJVM0E4ckZqSFVsYVQydkFyRDhuNi1GTGlaWdIB6AFBVV95cUxOX0JPektlVGVUSE9IV012QnpvR194d2V0WE5pRXUtZ21admhFVHhQRndIUmNHS3EyZDRLVUVuZl9QVTgxYUJpb1BEVEN4bWl4TEFvU3FjQ1Z5RjRjTGMtT2tZbnZDNnVRNUtqajF0dGYwbjdGZ0V4X1VaRTQtNUNubzNoNFJUZ2pYRFZUaHktbEk5VWNHSFVtb05UQXpNMDFpc1htaXJlVGpxVTR4VE1KeWdDT2YxdEt3ZWFpbjNPOTduWnVtaW5MS0FDZmE2VUVWX2ZqbFYxR0Vtd19VYlVHbUdmaXdYWExz?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T22:20:51Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "SMI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El derecho al descanso que recoge el Estatuto de los trabajadores: un mínimo semanal de día y medio ininterrumpido - MARCA",
    "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxNUG43MnBoc0lhdlNZUGE0UmxLTmQwSEpmTGpXeGFhaW1NN0NCcGh1QWFsM3dlZXc2LWlMSDhpVHZBbDNZMFRmNElzcGsxTzBKXzg0U1RKaTlrdUxuUkpaR0VmWjZrVTdKVHFtR2VDU1ZhUjFkUFhoWVFmVGtIVklVbFZ1Yk9IYlhjVkJPSXhwLTNmMVZPQ0lTTHBhVGlleVFFckpJWk1WSFB2WGFpZmJHVHVNR0dhelFWQ2ZPNHJ1WkR5U1RMY2lQaWtKb01DR051blVGOGxlWEVFODDSAdsBQVVfeXFMTWdha2lDNGV1ZFZLYXlqeHhsWVF2Szh0OThWUi1OYkQ1R05aTVJ0cEVLVXVFSGtUTVlvY0lJUVp2dHBTeUcxRmFKSFhDUDZtUEN4Z2lGU2JVY2FTQTlrVTlTZGF0VXVPaDlBSnFjLTNMb3Y1WnBqSTRxVnB1MXJNcVBwUG5GRWRoTERTajFfSmpVZmszWjY1VTlEMU5ZMGJtWnJiazdOUW1udUR4Rm5OVmVQOXpBbGxYNURWS25va1pHbjdxOEpaSzFrS0R2LUZGMXZhWWYxR3JyYThn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T08:42:01Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Qué pasa con tus vacaciones si te pones enfermo o coges la baja: lo que dice el Estatuto de los Trabajadores - Málaga Hoy",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNbHJKSXNYN0hiN2pWaW5FUXFRakN5SFZxQzBVbmVKUWtWUDRMUk85ajRKdTE2RjVIUm94SXN0UFBYaVRBZXhOb3Qzc0tiMjNhN1BJVWt3V1RZbWkzQjJDYzZXZHNiNkRsLTFSODA0RFV4bFlFLXF1aHhPV3BrMTRvUTl2Q21uSk42SFdPMFBXUk1vdVZRMUVBN2tUWdIBoAFBVV95cUxNXzdIU3hFNTNLWklsRmFnX1N3OWhGOW5FOG5kdmVuLUU5UTJGaTdTQ3FMRlFKMWwxSVZIU0xPaGhvbzlQRjBOcE9UNDdiTnRnZ2k1RWs2WVZLdXJMQkxVdWduckFHME9XeTJmNWVlNGd2YVkyWXNSM1ZuNFpDM1g3anJmcGM1cmlOVEU1LUlEVzVNR19USk1QcEkwaWk0SXZN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T04:00:56Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Qué"
  },
  {
    "titulo": "De la reforma laboral a la regularización: las claves que explican el dato histórico de afiliados en España - Diario Público",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxQeENqTjlSXzRtQmNqSmlPMTd4T1RtTVZrX3QwbU5JSVlSVHdrT0V2ME9zekVyRXYzRjc0eURXdHZCLU0tZFY2bm00SGhNMFdCSmtwYThQQ2Rqa1dtLVFHZnFLOThJMTJDWFRfU3RRdUc2ME9UTUZqMGcwdkNGMlJfeDNjTkFQanBvRFhBc1VLUVBFaUJpN2lxVUQ0WUs3REtGMEFPZU15OFpIUkNTd09FN3NsZmlaZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T08:12:25Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Ministerio de Trabajo informa de que el paro juvenil en España cae a 159.562, el mínimo histórico que impulsa la FP - moncloa.com",
    "url": "https://news.google.com/rss/articles/CBMijwFBVV95cUxNeFJpQXlXOWZvOVNfaFVYZ2s2WmloMjhUZ3FwbFUydzRXVnJLeWdqYXI0a3R4Rk9WcTlaakpMTGNtaFZ0QTh6QlpXUVlmQW44VVFDOEhETmdNZWI3YU52WS1KaVBreHlHVTk5eDlFTGM0eUJTS3NXOVJ3aldZdVpvRmM3NXlfaDRpamg3MVZXWQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T07:19:55Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "El fraude de una profesora de baja 17 años que cobraba 6.174 euros al mes acelera una gran reforma laboral - lasprovincias.es",
    "url": "https://news.google.com/rss/articles/CBMiigFBVV95cUxPWHVDNG1XWHh0MjJkS1E4VTRyQWVoOFNNelk3THV0NndHenM4bF9DSVJmTm5rY1ZqZDRSOVo4T1BfWS1xSDBhNDEtcWw2SEZ6WDgxdUxXRlV5VU1XMkMwcF9sUkNzR01OSjNpT1AwdFdYNnowOG9MYjdlWG9nR2JqYlFDU0dVQmJtS1HSAY8BQVVfeXFMTlptV295SjNZWXlvMGJjclhxdjFIdzZkenlKRkVSSzVjOUtOVHFHeEtNWWtxaWdCNE1LUkNZUk5XMUtQMUFrbWlfMm5rZHpiTXlUdWVudWY1dXNySTlSQnJaZlZtYkNRX2pBMEJkUk5FM2NvbGtjaFhkNWZaSEpESHg4dFZvc3hZMGRYT3BhVGM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T22:44:07Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Entró en vigor: \"Los trabajadores con 1 año en la empresa tienen derecho a pedir una excedencia de 5 años\" - El Español",
    "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxOWXY3cXhKYnY3bmFnMm5wQ1RxS2hJemRGaXZlc3AwcC1rR2Zfc1U0cG1wMkpGRW1XSDVlZ2VVVFZRNFVtdzZlc21jRll5ZnQ5VmVTU3ktSjZ1VTNITExzaEw4dEp2XzZzc2RkeU1fay1XOG5kNl9OZHRWLVlVOE1vTzd4NXRMLWhTaUxjQkdSY0NXVG9TVm1TSWJVa29zeEhvblVzZFZFLURqcUtQWjVMYjJyWXFfV2VDd3F3MWxWcGtVNl9WNW9xM3dRMVoyUXdCbWVBdUNaOEhGY1FZ0gHiAUFVX3lxTFBRWk1kaHZKMFpDUWsxQ0V4MGxYdVBTcG9ESmUtR0RucGlwc2hSa1hsMGt1ai1XbU9fcFdZdnZRYjVuZnE1VHlXTlVmQ3FjOWpPREhWZmt0czlxZ3kxMENuS01ZVEZzaHQ4VzMxTWNQVnhGc3VuMUVqT1lwM3laVUR0VkZqR1I2ZFhrdTNUUFFkRFl1bkV6MkIweHFJdUFMX2hUQlZRMnpoeVhmTlZsYWFSeW05NVZmb21wOTV2MGVlTkI0ZVNjRnJIY1RiN2I4cUszNkVSSHNxZ21YUURsdmE3d2c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T05:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Español"
  },
  {
    "titulo": "Juanma Lorente, abogado, sobre el próximo festivo del 15 de agosto: \"Si tú no trabajas el sábado, estás perdiendo el festivo\" - El Periódico",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOSFY1T1UwMGlfTXhmbXptQ1lLS1p3aGFSbmFSTWVRNGxhdUw5WEFGQnlFR0E0NW9EMF9NYnlrTnNkX3RXUkc5a2x0c0dZbVBQSUt6MXZSRFlZdUNXSU1Bdi16Zk5GSzJrRjF5aTR1Y04xSjM5aEdJVkdOTDRuVXVHYk0wczlZUVFTS0FDVTNPNVFpWC00UFdGRGs5cFljdUNjaTZmeEJhX09jMzl5VWJ2V1JSb0hjTFMt0gG4AUFVX3lxTE1OZWYxZUJvczJ6Zm5GMzR1a0NSTjBfbVNpdWpuQTJ2c29jaG5CVlM1Yy1FN0xGZ2cyeU83SVl0dTZjeXVDa1oyLWZrZkx5ajR3X0FqWkRMM3p1emhQbnY1ZEl1OGViMDdqTXM2SVk0QndCRnBkNEFydGZWVUxRYzlSUmV4M2JLRWZwNkw4U3I5eS1Gd1o0c2dpblh2R000NXQ2dFNaRnBVUThvTFVneThYb2F3MDJTQjc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T10:32:08Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "El Periódico"
  },
  {
    "titulo": "Sube más de 15% el empleo turístico en las islas el segundo trimestre - Economía de Mallorca",
    "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxPZElwanQ5ZUxscXF1QkkxdXJXQjVweTEtRzZTZWpxVnBkMUxuam1wVVlNNlAwNmxyY2JFVzZzeDdTZ3daZ0VSRkpIeEhGNFNoVlhlclB3V1JueVJHbFAydWNiS2NqVDltM000OUFob3pPSG1oTnhFdjNUdi1hZlRrZjRNeDU2REhCb3Iycm9MZ2lTblZzU0lJTHpMWHE3bVZwYUtzbDlyYjFCMUlzanI4M2RWcmxpUTlUVTlZR2N5LS00dzktTVF0cjhXN1h1Si1hNTZNeA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T10:41:49Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Reforma laboral: denunciamos ante la CIDH vulneración de derechos - cels.org.ar",
    "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE04cHkwbXVWbmxnT21YTUVBSlJjQ2FzbjdnMFRTUDFTSGRaRVlHVTVDM0tZWVFxNEo5V0lkRXpoV0JNdXFqaGxyQmVfODZhYnVLZzM1cGM2WTNuZ1dTYzFoLXRnaVozNndx?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T20:20:50Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "CIDH",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "ANÁLISIS: Lo que falta reglamentar de la reforma laboral - Ámbito Jurídico",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxPaGUzNUdGOVhlcW54bHRncHFlc3QzUGlKSGdVbUMwa0R5MjJ2R3VXMXRhNUxYa0FFOEV4eWVoVmpsbFhkdVppTGJTeVFtQzRnWjBMNG4tY1piN2hXOTJ3NlJOZmh1ai1QNzV2OE9FazBEUWRDVUJiaUFsWmFvd0hIRHAzV0N4dG85VEw5anhCVFhyeDh1WWllcFNScmpTUjZaUFpray1zOVkwdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T08:50:57Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "ANÁLISIS",
    "ubicacion": "Ámbito Jurídico"
  },
  {
    "titulo": "Ya está en vigor: el Estatuto de los Trabajadores recuerda que los empleados tienen derecho a 4 días de permiso retribuido en estos casos - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMigAJBVV95cUxQbjZ2T3RveHNaY3g5XzZKOWZEc2tLYllrdjZHLXc4Y2lJQWM2NUdUN0ZLN0tUVXJHYzNVemQzQVhyenhndzN1WG1NYXFpZXhJR0tURE1HeFg1LXE3ejJ6a0ExNDVSdXVoaThxYk5NLXFlMkhWTWNaa01uMTBNYmluZWkxbVkzTEVPYXpwVkpyOW1UTWZ1SVNrdERyUlRGN0M3NkFDSHhpcnRRNVlnWUJiREJYcnRjZndTVFNaal9VSHV5NDkwWXJQMEd3dWNPNTFCdFY4UlpYTVdBM29pUWsxNkh2SE9lSHJ1V3VUVndHQ240MnRwT0dwN1V2UktPalZj0gGOAkFVX3lxTE9ZNlRVS0dmREdHVmc3anBPQVc3SFBvRjY5Mm9BSW00SUxiTU9CUFpFT04xeHpPRFBTbkNMMTZEVHJDS283Uy1MeGE0eGJiNlBGcDZ0TFA2Y0ZjNktPTXhtakE1WUVyd2xjYTFySGk0c1ZTMjVqVFNOaTBoelMtR2JBa3ctN0Q4MS11UkR6aXNlMTBTTTBJM0J3MFVrSmJwbGxFSGZTdHhIN2dhdGtRYnBheE9NYjVCZ2x6ejI3OFg5WEFkdExKbk55XzNxeWhMbVZ1anJULUtKU3RJc0JSUVBCNkhRUmFfdEdlU0VMbGxlakFnY0oycHFaM0JzMTZRcFVrVGZ3SGhqbm8xOEVqdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T14:50:27Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Es oficial en el BOE: tu sueldo bajará por un ajuste que las empresas tendrán que hacer en las nóminas por culpa del Ministerio de Trabajo - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxNZ3Y0OVJhOWFCUGhuY1pCbjRFVUpsVW5nbUZfa3l4eHZsbkJ2QUwzSVF1akdfYjEtdVdOT2pjM2Nvbjh6S3lGRWdIWWZEQnVoWk04WVdwRENaNktETDdJb1o5aTBWWDNfTjZSV1RFYXhzbURWTUdlZ1RLWEVmTFp0aVBIWEFKQnFzYV9oOVdlSVhZaHNSanJ4RDRnUjlZWnJpRGFkRC1wMTdQQ0gwbklOZDFaOXkzVWhXOWVvYkFR0gHDAUFVX3lxTFBKZHJMbktKTG5pUFFXSTBEVzFvMG1scFRDbWkxNU9qaXhudXJSWFd4c3Q4cnNXSmIzMkZnSDlFbnVRR1dnUU1wbnJENU1zNHlobWlHYUwyZy12YVlIcGUxSmVwUWgyUFBNaTJneERLSmRESERTc1Q0YnZKa1drOFdqWV9HakZibW1EX1JPY2FPakZJckFHQmg1SldWbW5WWDhQZi1FbDNNbW1LYW5ablFmN0RCUVlJSVlZNEdETGlSaDZ5Zw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T08:00:54Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Ministerio de Trabajo"
  },
  {
    "titulo": "Ya está en vigor: el Estatuto de los Trabajadores acuerda que trabajar de noche entre las 22:00 y las 6:00 horas implica \"retribución específica\" - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMingJBVV95cUxNR1hGdGk5WC1aZzQwNWNldW01LVd1VXBvbnFSYmdHSG1pU2hwU2xTTHdDelZXX3NUS2EwQjRkckhSZEdHenRmWnZhOUE0SUFvc1YxVHRWWF9WS1dCckxFVmlUSDcyVmZST0I2SDJYeVJ1cGc0Mk5XcG5MMVhHZWExLUJHcUpRamtkNGYxd1dqQlZuQXlJak9za1pMSUZBdVA0RkdNR0ZPbHk1Skw0TlhMdkV5OGZLTUl2TllwZFE3WFphT2NoeFdVRnNyRE1vSEl1UXU4bk11RzJabkRQcGZDWUJaamctSWwzUDByQVdqM0NTWUY5eUJIbVVnUEJ1bTN3aXc5LXl6bU9NaEhRS3ZwTUVzYUszRktuR3AxQW930gGeAkFVX3lxTE1HWEZ0aTlYLVpnNDA1Y2V1bTUtV3VVcG9ucVJiZ0dIbWlTaHBTbFNMd0N6Vldfc1RLYTBCNGRySFJkR0d6dGZadmE5QTRJQW9zVjFUdFZYX1ZLV0JyTEVWaVRINzJWZlJPQjZIMlh5UnVwZzQyTldwbkwxWEdlYTEtQkdxSlFqa2Q0ZjF3V2pCVm5BeUlqT3NrWkxJRkF1UDRGR01HRk9seTVKTDROWEx2RXk4ZktNSXZOWXBkUTdYWmFPY2h4V1VGc3JETW9ISXVRdThuTXVHMlpuRFBwZkNZQlpqZy1JbDNQMHJBV2ozQ1NZRjl5QkhtVWdQQnVtM3dpdzkteXptT01oSFFLdnBNRXNhSzNGS25HcDFBb3c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T14:02:27Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Confirmado por el Estatuto de los Trabajadores: las personas que enfermen durante las vacaciones de verano podrán recuperar los días - La Provincia",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPdHZnNVZtcGFucWswMEFmNWlSb2QwLTlDT3ZuckJtZ3pUT2EzUjNFbVQtck8weGlTYWVOb18wbF9EQk92QUZ0MkpJZk5BVzJVdko1NjNJM05KakYwUFpnWVBMVWdQRW9hSURLRDBJQS0yQ0o4NTNUdm9CcUEwVnNUR1pHcE1naGpmdFJBNWR2eExNRC1WUzBUdElQcGVRNmh3eWVZcFZkMHBtVDZSWWY4RUhMRWlKSDhYY1g3MVExZFBuRHJITkU0MHh0bEs2b0p0M1RLVU9n0gHbAUFVX3lxTFBXdnlvbmhTLVB5aGxPZ1VpXy0wM2xGN3RxbnBRa3ltV0VnSXc0Z3h4WEp3RTVwWC1Scm43WFNiQUx4MFRMa3VSNWN1Tlk3T3ZqREJhWUoyN2l0Y2Z5amgtU1pUeGZmQ1FORmplZmNrOHNMMGFfWkZvMHlhMGNueTY0bV9JM3VHY3pnd2xsOFROb2dsTEtEUHhfRWFTUjY2YWZ0ck50dFdBejVHb21ZZXVWV0IwdlBtWGpNME5uZW1zOVM2SllKMWduU0YwTC1GM3RPZ3ZHc1JzV3ctYw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T06:00:26Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Provincia"
  },
  {
    "titulo": "Oficial | Los trabajadores deben descansar mínimo un día a la semana o el empleador podría ser multado, según el artículo 37.1 del Estatuto de los Trabajadores - El Cronista",
    "url": "https://news.google.com/rss/articles/CBMiqgJBVV95cUxOWldyNGV1TG5hQjRid09SZXVUYXY0ekoxRkpMN1JYTGlqOW5TMy1kUWl2X1RaY0NiN3NwY1BVZTcxSWE1UEkyWWpEM3ppcjNUTXBWdE5tT244ckRrckRQWkFHVXVCb0ROZW9fSUN6QU5LVWJrOXdIdENjRE1mandSbmRxQWFFUHRwdmRhMG1ldHJqb18tV0VoV3oxYTVqNDNmc2t6LUNRUzM1YnJsbTFFZndhblhUbDFSWUlHcUh3WTh2aV9VOV9VM2tCb2czOE91anE1bmJPbmc3TlEzRjZFb21nbFJLVUU2WS1ORWhVNGFHZ3EzcGFKaEN1dlVkNzlkZTZNMnJ3WVFqZ3VibTlPRVotb3NRam54cTVnSDdDRWpocWRkTl9STUtR0gHEAkFVX3lxTFBYMDBOMEVoYTdlTm9fSkk3bjNjeXJQMGxHYVVnYkRfTFZvdVNUWW1zVmJHZUUzSWtTUU9JSkc0MnhSaEFWZFFRSGRUU3JyczYwY2FzRTdPRDdUWG5mNHJ2b2R1M2lpUzRGWHlhRkJ0enV4aTZVU2tjNEE4M2RNMV9SUWVyWm9MSnRjejhfbEV4OERnOHR1dGl4QjB2TUZQcXltbm5fQzBDYWFwOFZ2T296MXNNVVdEMklGYnlMQWZvSldURm1GTkVBc0dmWGNRLWh3dWw0RHk4WDdaQTZDMkxGSDF4cFFMc2dwT0tuY2hpMFFnOTBlLXJOb1dJVzhRWUUtU1B1cGlXcm94cGdreGVNMVVMNklsUHVhLVJDSzFEeUlUaTdtQjU4TTZHYVVqdlk4dVBFSTJ1Q3VnXzFwRG5pbjlZYQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T11:58:59Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "A horas de dejar el poder, Gobierno Petro expide decreto que afecta a repartidores de Rappi y contradice a la reforma laboral - Yahoo",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxOdXJDek5wY1ZfRHpuVlZNMjQ3M1M0WHlfT25OTjZBelRsbHB2NFhma0xaemFaRXlSVXlOcDZDTzQ2bTZYd2tZQ01vd1N1U05IQnB3MlBzZURaQW5EdlZDdVR6eG9nOTZJalY4WDRmSTc5WF9sU1dxTjBENXE2azNoSXk2UzZEOHM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T20:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Yahoo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Alianza In rechaza decreto de Petro sobre repartidores y pide al nuevo gobierno derogarlo - DPL News",
    "url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE5OaW5xcXJ4TVdpRlhBR09QZFppNGFwcEo1b1B6S3pUeXhoWXhfVGZjLXBucnJURDRmRzJ5WUhvVXVLWi1TVktkZmlUWk5Rb2pldV9xQ1BRUUVNRzYyb29oR0pWYllvS0RXLWpyT0Zmb0ZoT2Nx?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T17:41:48Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Alianza In",
    "ubicacion": "Petro"
  },
  {
    "titulo": "Ministerio de Trabajo podrá entrar a inspeccionar hogares con empleadas domésticas: así serán los controles - Yahoo",
    "url": "https://news.google.com/rss/articles/CBMimgFBVV95cUxOM0VaMnh1aS0xeE5rNlptYzJFSDJqSkY5X3Z6alB2MF83UzFQRjExTFN3M0laSlg3a2ZKZ05lWDIwNW1BV0hvSW5wMGVVRUlrNHlPRHh3MjRJRUw3QW1qSkVJcDNxT2U4bm9IOHhEX1lnZTM0V05Jd19qOTZub0hYNGtUdUxpQ3I3Z2REd2dKNHVXUUprem05MEhn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T18:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Reforma laboral: tras el acuerdo Gobierno-CGT, se destrabó la renegociación de unos 800 convenios colectivos de trabajo - Infobae",
    "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxOLVF6am1jRUpXbTVSUDVNRXZFS1g3NHJ2REMzTlA3bUxucXlybE56NFYwV2R1LV9ybm1FQm9fVmJjZGpTY1padDUxdVJOWWZZdnk0UVJyQ0RNN1ZMbzMtcWlYWEhGSThNcS1fcU9LS1h2QXZIQTFyYVRtQ2wxd0JYazQtNlZ2eGgwWmtJMkJmVnNwVjhQb1VsaFVvNWlrOVpGSmowY1pMT0w1dXpJNXJiRzNJVGxhNi1FalZZd1gzQTVKSkJXa3pCaUNmZTVwN0NKczZmLUhCVHFLV08tVVZCZ1VwRUozcHB5YTdETUVjYjhTVlJZ0gGPAkFVX3lxTFAwR21QZFd6MG43UjAxQVpSVWtSV3RDSjEySk51czh1MFNVZE5WdkczVzFtajE1YzdMS0IyR0NZOUtTWk1uSHZqWGxxeERaYmpCMHBjZm9ZTmxHTk9CMUh0TmxwSFI3REZOSFU2YWhodV9pTUIyZlhKNllBM1hVS0dFZ1gwTmFpUjJVdGZoQThoWWpHT1Zob0RBYnpvckt1TWJoR2xueXZhc21odUVrdldTXzJCc2hNLXJ0STBIZjZxSXRBd2NnblBVeERZNFF5MGN2bm5TNzM5MEJaVndpS2pJR2wtelRvakprUXZpZzd2M0swcE9PM3ZtYzNsemZHWkc5SWRrM1REdGlOVk85dDA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T08:11:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Frente sindical argentino denuncia reforma laboral - prensa-latina.cu",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPSjFQTW9SWTRXeFhrTHlpTkdFUVU2cldGZVVJQVg1QnJzM01YQmpVSUx3YzFXeHc0WlpabGEtZ1E5UU1iZnhCeDdVMVJXNC1WTUZXNjJ2Ym1qSzFPMnZCTjVwbGFTWG16UDNzN3EtZ0t5dDJSYU1EbElYSWgzemR4SllXdU15dlYycEpOek01NTNMYi0zelE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T13:13:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Argentina: SiPreBA denunciará al Gobierno nacional ante la CIDH por la reforma laboral - telesurtv.net",
    "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOeVNReWRrNXdZUm1WbFZKMlduNGpLMlZteXMxMmRmekJnRzZVaDhYck0wenc5dENEUTZJUDlvNnNkeDMwbDhVYjRLb3pkdEo5b0drSnM1Wnk0cGF1Q2pidlgzcXBHZmx3dVZNcGp3RDJMTnQ0cXdtcFczQ2NMbExNNTJRR0Z5dkx0OEludWFR?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T16:34:36Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "CIDH",
    "ubicacion": "Argentina"
  },
  {
    "titulo": "El ajuste en salud y la reforma laboral de Milei llegan a la CIDH: \"El proceso de reformas combina shock con represión\" - elDiarioAR.com",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxOWU84QXFzYlFIVDc1cmxiWlZzbWYxem9hRHg3alBQbE1LLUN5czF5TjBJU1pmS0VhdklOMnkzbHpxd1EzTXJSblJJOXM4bzk3QmFzbVBOaGZpQW82cHA1emlTdjJLRVhJUTFzM3B2YmFNOUx0X2hua2QtNm50dzBSbEVCdE11dHhjWWJObGY4Q195N1U2NFE1S2ljMFZlMm1XRWEtSVpSVUt4bTFfemlFVWNPV2Y4dGpaNzZSNnZFd3lNdkhldHpvd2x6cnF6c2ZXbWppNGp30gHbAUFVX3lxTE9NY0ExUEU3eEZSbi1JNG1XSmVDTlpEZzZYSWJzN3NwSWRzNGlpSElsS19HU2g3dUNKbi12YjlkbzFaWDNLZjFWNHNsTnB1c245bzBJN3VjeUVvc1RYbENSRzJPZHppUTl3Vk5nNXJhMnJGR0xpNjdkbjdvTWRJVlhiQk5DamdGZkdvNWt1WHBNRGlsLXNRcERNV0Rrbl9xR3pCQnpHai1TVnlIX1pWOWdZMFFQOFZfNzVGQWZnNU82WG9zamxRSlFXNFBQS0lpUlhYcDlQZHJORHJ3TQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T16:51:34Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "CIDH",
    "ubicacion": "Milei"
  },
  {
    "titulo": "Estos son los últimos cambios de la reforma laboral del gobierno Petro: Falta aumento clave en el salario - Valora Analitik",
    "url": "https://news.google.com/rss/articles/CBMi7AFBVV95cUxNWDl3M3BxVnJNYWJJMGhwdndFdkZXSG84YUhpUU8tWDNzNE9DYVh0Y3d4ejltdjlKdGlfbXNPZDhxRzg1OHFZRXprRGVNRU1IY01FaFBZV2VYaWVCcE9MY1ktQzVtMFRzMFF4TTR0MmJMMDFENWIzaWQyX0U0QmhQLVhOVkU0c1Nza1prZjQ2cUVRV1pneFc1QXRUelBJQXRMZGtvN19hV2F1NXRLM1pfcGl0OXdzV0RqV1pHZ3JxbFgyMWpCekY5V0pPWTFndi16dlBLZ0VxOWl2bTdLSDZiZEFtQlpfLTdBRkdVNNIB8gFBVV95cUxNMG9KblNEb3ptaDlGUkh1U0xCS09jRUZ4YXlHOFpkemkzYldZaVpRNzBxcGs3TkwybFpvTXEtdl8yQlFTei1vY2dwVDJUN2RmUEV2eGZjTmZzc2oxRXlNWWlJSkhPcm5GcHVpV1lXUDZIc0o0OEQ2QkpsMlpBNEdZZHZYUDB6NFFaYkljdnlTNWNNZGdHdkpWSURQSjllY1dnV1ZiTkR5Q1ZUaWtGUmx0N3RXS1YtMng2SXVxVXc3bXdiSWxubmtvN2Nta0t0WHdWanNMZjM5UlZVeUxJWUNNTC16NkFkMUFIYUlpTnZSUHVjQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T22:00:00Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Entró en vigor: “Los trabajadores tienen derecho a 2 días libres por fallecimiento de un familiar, 4 si hay traslado” - El Cronista",
    "url": "https://news.google.com/rss/articles/CBMi8gFBVV95cUxQdlVBN3VHVFBVMkktcHJBSk85RHB2WGJXQ3NHNkN2SEFfbWtIQklUUkNubDMwRy1ieTNSbF9CWFpDVGhrVzVnTTUyVF9Wa3FkWnNTbGQ3MTNzSGV5NXJPZm9lanRacjN1V3FEOU03VVNvbmtYTGJSdWFIeHhaRWF5TFpIcVJvMktZdHo2X3NKT202SkZJQXY2Y09TdmgzdXJTQUNubWVzbEZfWUpBOWhoaWxEekRDeEdxTThiVzh5YjFJQ3FIS25wZ1R2b2xXNzRrOFpxVkdrTTBXcjNyUkh0QS1GTmF0M0tMalV5S1NNLXVZZ9IBjAJBVV95cUxPYm1BX2hmNEMwUHNnSWItYmVXcHQ0MDdINEY2V1ZqUU83UURpSi1RYkhJTzZTaENXWkZZcjFxNjFYemt4Nmp1WFN1UG5YWTRNYjItNHJReW00MVVVM1d4aVU4NGtDRVQ4TUl5WmkxQzhRaUI0c0hmX2xpZmRNc29IQ2VxeFZIbmVjaDR0OXRiQzhQNmFsMGpHRlZ6b0dXRlQ5MHU1MEdCeWNfc3FzOUdQTnN2NWc4STZJUm5pRlJ0ZWVFeEdPN09Gcy1US2VHUEF2UjNILW9RVDVQUTc1VzluejJvOEJpaTBYVTNOQUV4VG9uQWNPUzB0MU9WaWRUQUtmX3RXaXdhNXBTMHRu?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T10:29:14Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "Desconocida",
    "ubicacion": "“"
  },
  {
    "titulo": "Reforma laboral, RIGI y Banco Central: las tres leyes que el FMI pide acelerar - Perfil",
    "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxPdnFiUGJwZU42RGt1U0hjdjhxOWExRjNUazViWkxLZG0tZHlFM09MRFJjZFlsM2I1bUhqUjVKNi0zR1dIUmFSX0x5YUM3LUhJaF9SeVN4Um1hVXdCY2pXZGtVeWRPSmtxZjVLM29mb2RIZi1abm9ZQUZ4cFVSZ29Sb09kVzVpdHB1NWxJMkV2TGwtblBFb0M0YkZHWlo4WkFXWGZTNzF4MzlTZVNGdDlLWEpsLWNjTWxKeThoNUp3OGlyZ9IBxwFBVV95cUxNazJ5M2pvYTUxa3VOa096dmZCMkF3M2psaTE4WmE2UjJpQlVXMkNXelZXMVZTMHNaSzNzV1JlS2hwNjlXcjJBNURKaEV2Y1pXZUxQc09FU3k4eEhaaXZNdG1KOGhuSTBFSHRiVTRfVjN5ekkxRlNpV0xhYUJITHhSVHprQ1QtdUtLSkN5WFVaLXd6Z1NZOU9wcXFTbGhLLUNUT0tRR0ZNTzdiVWI0TjhUemR6MnBTT3V1MmVQbmw3TjBxMTUwdG1B?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T22:50:09Z",
    "fuente": "Novedades Legales (España)",
    "categoria": "Legislación",
    "empresa": "RIGI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Novedades de la Dirección General de Recursos Humanos - Comunidad de Madrid |",
    "url": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxOTUwxaEJPMGNvbjkxZjhkQ0pxTzJ5ZzdSM21yUkdxaXlXcnlYdUxnMnpsN05jYWNHVW1tenJBLTRGVk5OU1NIcS1PRGNYbjQwX3FHM2dyclgtblVKaHpicHhhUVoySEUzYkZsWDJKVFlQQkIybV9JSmFlU2ZxSmlDeVJ1dlZ1MVp4TVhn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T09:59:41Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Comunidad de Madrid"
  },
  {
    "titulo": "La Diputación define las convocatorias para un técnico superior interino de Archivo y Biblioteca y para una bolsa de empleo para técnico medio de Turismo - Diputación de Segovia",
    "url": "https://news.google.com/rss/articles/CBMizwNBVV95cUxOMEVLSGZWenFRYjk2eHU0aEltUGx5Y1JnSHBKU1hTVkxSQkFzbmtvX2pORFlzcE9FaVB5Y1pOemhVZ3ZZS2c0OTZzUzE5WmFLdS1udmUwY2hzWFdLUjhVZjFZNVVIZFN6X0F6b3NlQW1SSWdXb3FFdFVqXzJwakUzNExNeWJ6eU1JREN1Rkh1LWZzU2t4cE81cEFadk5NazQzU29LRElmTHRyUVFZRkhLdTZYY19JZnJwQWZKMzZidzJXcWthTHdsbkd3SGxPakwwdWltbHdFelZmSlFoZHFrb2N0YURNenRZeEFLbWc2X3RrWE1ZTEl0RFpyTUU0Zm9jS3FNZ2hCSFN0TXRfWlgtTDlXYVlhR0x3TFF4aDJaTXZkT0kzOHBRSnhJVld0TWQ1RkxjQ3REdDMxc2I5ZG5GbjZwa1FqTGNPVVBzUk1SSXY0dzFrUS1Sd2RUSkxCcHAzTjNWSlhncjFhQVVEREp4OVVBZXNjZmZnUE5jTmVxNkkyVUNxYnBTWEtsYlJmWGdpT09nRUZmSk1FVUgxYlphYVVndC01bllQaGhnZVB2N1FTdDQyMHRkMEpzVksxWkFtZElySjdya3RnYVpsN1pN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T10:44:28Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Archivo",
    "ubicacion": "La Diputación"
  },
  {
    "titulo": "AZZ nombra a Rhonda Davenport directora de recursos humanos - Investing.com España",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOVmRTM1lkenBEZDAtZmdtZHBhMDFxZHNYSGJhLVdFOXZzU2lUTlZQdjQ1VGVtYkFQc0ZiT2kxZDJXWHBPbXJJakhucUZDc3JsSi1hUGhobmtUcTFET0E5RVJCYlVpRVRxRXJvTjJSTll1NTJqOW5NNG9GRmp6eFg2TzY3WWJpTFRoaFRZajVRZHNvcm1Xalp2cDdCWFJXOHB3RmpwVkRhcTdPd2lTcGxEV1drODhMZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T10:37:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Gloria Cuadrado, fichaje de Ahorramas para el departamento de Recursos Humanos - InfoRETAIL",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxQYy1zNjcxdmpNZ2dNOUs1ZUJ1R0VQOFhOM3FpV3pBcGdKSFBpeG9iV3dTcmxCZ1NEblFHT01BTi12ZGhBU3AwMnZGNVdoUndpTEw5TnZOZFphb1BEelJvLUpPb1JWT1hESUp2WkNYeHl5Q2Vlek51R0VmbjJPMGlZTnJxZENNNkdyUjBnS0dDaTlmQVZ6NnVZZF8xVDZmU2J5Rk95XzZaa1dNV0NEQ0VKaXJHb1FPVTNvY2lKNEluQUMzcWYyWXR4YmdwUlhzX2dvWDhrUEp6TzNjWnlWRGZ6UlVtOGpLZUsxelow?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T11:16:40Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Ahorramas"
  },
  {
    "titulo": "El CSIF pide una auditoría externa sobre Recursos Humanos de la Autoridad Portuaria de Las Palmas y revisar las competencias de la presidenta - elDiario.es",
    "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxPYXhZUWxpaU9CZDJFMHhXZDJvZTAyV21vTFJERVI4bEdqV2cxTk9GTHNmdHA1Z3NsUzRtaDRoTi01MnZnV3F1d2dkN0pjRVBGVlhPYmxhWl9mZDN3bktBZndKenNyTTB3eW5wTWZNamprdDdEX0FDeDQ3ZTV2emMzSGRxLV9SZFBVc3d2aEZqdjFrNFdOUnIzSDM3bjZTNjRDdUhwRXJVNGNOQV9iLS1mazJfSzdWcVhnU3ZmazBnYjZZZUt0RnNhY3NqVGxmcHRwM2lLTUVXNGdLcEdyekE4d0RLSjExVWF4QTNJb3hCUzBRVU1ZWGfSAfsBQVVfeXFMUENkSnhBNm1TRjZWUG9ObmxxMms1U09WSVhPNDdQTlYwNlZpYllKR1Zyd0h1TU1QRVZlTnA1ZThmNVBldVc5MmlqTnVWcEpUM1BaVFRDUU85Z0doamx0MDloUHoycXJEaDZnMGxpbEI5SXJHR0JuNTVyUF94Z0h6Ymc3QWdHU2lnWkJxOXluSDVDQjVjQVlGM3pmWlZYcEhaT2JZY0IxVlplTDg4SGd0R0IzS0xyMjRLbllvQU00YXY4WHEtRjlYZjBEcTdGWF9wMFJXTHZPNGNKTEY5dUsza0pOWjZfUDltdUcyRmVIY3NqS3dMWXNSU21SMlU?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T16:31:12Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Autoridad Portuaria de Las Palmas"
  },
  {
    "titulo": "Francisco, trabajador de Recursos Humanos: \"Si le caes mal a RR.HH te van a impedir muchas más cosas de las que crees. Incluso en situaciones de conflicto\" - Mundo Deportivo",
    "url": "https://news.google.com/rss/articles/CBMikAJBVV95cUxPX0hUWHJ2WklHUkd6dW1SRXlFTGQ5Y21wUzJYb1Y0SDVHcTlzZHFvQWtLbUlhUzBvNzdockVGal9zbzFwS0FLQ3dLbW9CbndoYzJqNVFBMUt6VHpHSXFtNVQtY2hwZ2JBLUpiY1JJS3NEMTdtLThMSEYxUENFZWFsdDM3VHVCYllON2xycTRjUUhwQ3d3MDRhMmhGeFlOUUgwUE1CTTdVVHZOOWg3Y010Q25WNTVqWVJOLUxjYkhKRFZ6SV9tTXJ1Q1dYX01CbFY5alFKRHRKNHVydjhLSU1uVXlVU1NpanQxbnotRXdobm1VWnhXalgyUnZPZEJmMzZsdlh6ekY4RmRpYWlaMGhKUdIBngJBVV95cUxPZmlqVmVWbE14UmpnWDZUd096T3JONzhNQmNjQ09yU2NMSUhmMHJseHVRZEQ5cWpvNnFnejFUb3FMQUtteHBUU2JZQ2U4bXpsZTFzaUlBNk82LXZMeWhZZDZYWm9LNHNGSVVlTm8ycjZKUE9wYUJDdE9WQ2gyX3IxSzU0cmVSbkJxSmZkM0g1bjZyYmt2d2QwVnMwbGMySUhta0Z4aUwwQS1hNFQzN2d6WGhMaHBoSWxXajF6ZXc1LTIwbGl4bi1UR3BxN3Fja0oxd3VlVG5IblczTjJnTGRZUDUteXFrd2tYRWFBNnZrTFZzdGVzenoteVZhYUdpTnpKVnJDYTk2T29SZENHcG9zbkQxQUVBYk5rX0tEYjdn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T16:43:28Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Mundo Deportivo",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Marta Suárez asume Auditoría y Control Interno en plena tensión con Recursos Humanos en el Puerto de Las Palmas - Atlántico Hoy",
    "url": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxQREdfaU1IdUUxcERieGNreFJTczRWV01XYlpMWmhWMVdXVzhsUWNlbEZINzRWWTBNaEp5NDlPaEFNd1hBRW96UTZlaFFOSGdxY01PMmRBVWhDN1RZVnEzWl9UZzgtVlRMazA1cnRYUUtGaTg0Q1ZoZ2RNWU1TamZhSUtPdUZBNGVUQ1RoOHUzUXZNcTJsT054YTY5TEdheGVrelZxelBOeVJrXzF5emNZeVVvVUxQVUJfcG5MNEhXRlpneHo2VExZT2Q0bm1pRnUyTFBDcnBMZnBCWHJDNHB3bVdycnYyeVV5QXc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T04:00:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Puerto de Las Palmas"
  },
  {
    "titulo": "HR Startup Competition | Tres categorías, tres ganadores y una misión: reinventar los Recursos Humanos - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMi9wFBVV95cUxOU3ozUld2XzVMclpzQlBlZWNTelY2bHBHa21YUTVNQWlrS3pGX2RQa2tJbi1qejN0c19hYW0wdnRvdkNaWENkZnJlQVozaVlSREY1WXFmYlNCSXN2NTZRUk5FdHR5eU5xbWtIS3NrNjBqVXJabmZCVkFneXZ5R1cyeUpnTFA0UVZjT0ktWlF5clN6SkdFbVZPUXBheEVYaHFXUXdtcXE3RHBNbjg4cDZkS2RFbmJQYmFUM2g5eWstWWhHcmduaXNPa01BdU1mRkJFYlJJMDBXNHlDaXBnb2hCaVVVUWlleDE3aFJTY3RJemJXeGNOd1Fj?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T22:21:55Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "HR Startup Competition",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "El Ayuntamiento presume de tres reformas \"fundamentales\" en Recursos Humanos tras aprobar el Reglamento de Teletrabajo - diariodemiguelturra.com",
    "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxQWGRsLS1tcG5UQnFPb0tQbF90Q3JlblJzTFgxRjJJVUNwT3UtaVZGeUJaSFJuU0M1SHphVFN4UElCbDUtX19yQ3lLY0hJVXhCOTRYNDlqbXhwbnVhUE5fN0JXZjZGY1luejBtRGctTmxodG4xQlc3SDV3NzJLNWlfMXZMb2NLZjBDM0c4TzZsUnBaeTNVRW5UeXhKbE5TVDk0QUFuRG5RZ3E3TUJRRlN4VmZrYnljbklreWh1bUw4NXNXLVBPRGxLUVZNUTJNaWM2VjdUMVVYWkw1TkFZVUVSNTN1OA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T12:00:57Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento"
  },
  {
    "titulo": "AZZ Inc. nombra a Rhonda Davenport directora de Recursos Humanos, con efecto a partir del 3 de agosto de 2026 - es.marketscreener.com",
    "url": "https://news.google.com/rss/articles/CBMi6gFBVV95cUxNQ0hNNTA2ZlVPeHdFcHVTZnFhLTh0NXZHMXhLa01SWU90cFZpMDB1X3BBYzRDRUVvY1EyTkZ2bTRXWFdEN1VjZlIwZXJXRWxzOVN4cmY3ZHFGTHgtdWxwU2U5SHRzUXd1b1p2X08yTFBXSDN4c3VPcDA1WnQxU2tkeU0zaG02M2tTX3cxem5CblBGTTRLUTNPdy1SX2V5SDJaUXN2LWtjMXNpSmUwVzR1UDlxYW1fS0ZMSVUwVkF6UDhtYkoxdTBVeEYwRDRpTTVobHd6empYNlJuSjJlUWNoWVpFNGZHdkplb2c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T16:22:33Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "AZZ Inc",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Recursos Humanos entra en el centro del negocio - capital.es",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNU3RTLUNNN3JOcWgyVTRBMFBmak9pVXNlWlZ2YTg4ZDBETi1zMkt5aXZVR2lPREtSRkh5RnNWdUxnRl81RDhqbkxxbHRpTFNTN1BGemREQnFVZlVibnh0VXFSbElOalZjTGxSMnJtZkF4OC1OSlJDTnFRVFNmNG42M3hKWHRBR0RyS01GcVpUV0FLN1c3?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T06:00:51Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Murcia impulsa un ciclo gratuito de prevención de riesgos laborales para empresas, asesorías y responsables de Recursos Humanos - Murcia Actualidad",
    "url": "https://news.google.com/rss/articles/CBMiiAJBVV95cUxNOWFIOFVza3hPb2pxNHB0MXM4cFNVWUNpM2t6U1pXVlZ6dFUwazFPUndnUjFHUEFMS2FoUmFqYjNYdDRWcTJySjdKNWxJeTlKRFFvUGNlMUtuT1B0V2RjZThkSUNTNmZ2TWFzcTF4U1pOZ3R6eFhqbUVxS3VmWUN0LTBjX0s3S3ZUOGhoUjhuWHpXZEdsQ1lxdGdZUVFTNVo3ZWtySEZQOXJNNjFuRlZ4eGl3NkkwaHQtcGhMd0l4VXFQeFhvdlRKUldVdmZHS2VIaGRHQm1EWGs3bnpseGpEUkI0N2hTRnkwMFdGNHhHTFVqOUtVRFVyQkJ3ZVAtaHp5YlRkT1dJcWg?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T08:01:47Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Murcia"
  },
  {
    "titulo": "Laia Calsina Blanquer supera el proceso selectivo del Ayuntamiento de Manacor y se hace con la plaza de técnico medio de recursos humanos y será nombrada personal funcionario de carrera - MANACOR NOTICIAS",
    "url": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE5XZi1sdlF6RGxmOFE1UDRCalZYUDl2NUtKVGFiYkFOZEJ2djNjdFJGd0pZSHNYWkNDLTlpUS1EaDFRa2N2SHd6bFh3V2dLamNZNmFDM1dHdkhHTmhEbGw3Ykp3?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T04:58:48Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Ayuntamiento de Manacor"
  },
  {
    "titulo": "Orbio AI cierra Serie A de 18M€: cómo la IA agéntica revoluciona recursos humanos - El Ecosistema Startup",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQaUhYWmR0Y2hsVnVsNE9oU0gyYmxmeVhwcURKLUJqNWdnWGdESXpPWVl3VGpubEZkT0I4czI5enhLMlo1VndfdnZXMWlIdjBYSGNZbS1MQ2E3RmFYMWlja1c2cVNkLU0yRGc5RnB4VTZxdHF5TjZ3Qy04OHIweXlVX2R5WE0xQ05wZ1pMbkNOVzNVS1RCejhLTXREaHJIcld0TzJCenFSZTRBNTJaLW1Oaw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T17:54:33Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Orbio AI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Telde actualiza su Relación de Puestos de Trabajo tras años de espera - Telde Actualidad",
    "url": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxNVThMaGFMVlVSa2MxSXRwbE9Oczd5NEMtcEVsS043VmRqTm1UQy03R2NqclVSLWw5TVFLekFweUx5bllac0lTODNzRmJLUEw5c2YzZ29XRURzbmJSSkFrc1cwVlhqM1NHRXpJVG5rOFp2aUlVZUFCRHk4b1BMVHdIc3hXVmFzOFZ4el9KUlBmU3p5UFNZWUJfOUhJM0pPOGFacTQwYi1RY3I?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T10:54:53Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Telde"
  },
  {
    "titulo": "David, técnico de Recursos Humanos de Aldaia, se planta con 25.000 euros en ‘Allá tú’ junto a su hermana - El Periódico de Aquí",
    "url": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxPMC1qREZyd3hsN1djdWNiZTlHbGRNUjV5a2xWSVJrdlA0T29uS3liUGswLVVqSTNiWGVFUWNfenUyel9XWWQ4ZlV5ZURFUVlvckEwd2RUemR0c2RBdUVQMmxqakpzNWJWb1V5Wm5jR0J0a2JTOUxxa0wxS2dlWTVkTk9YOWotY1JmTUxaSDlsUy1Ca05sYk1yRzN3VnpDV0VNektWWTd2dFcxdGpPWjQtbDZacHgtWlFvU3FYemxEV0dGUkphWHVfb0VsZ0c4UHROREQwaFAwYVFxaVNMUEtKTmtJNlZFcTlNX1N3NEF5amE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T09:01:20Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "‘Allá tú’"
  },
  {
    "titulo": "Señales de que estás sobreviviendo laboralmente y no construyendo una carrera - emprendedor.com",
    "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxQUGN0THJRa2ZGdmtteExqcWE5ekxENTNCbFhsMU1RcHBiYWIzT3F6ckhOcjljWTNpUndZdVE5MEhoYnpYSlp2czlvczg5cEVUc1MyYVc0SDNoelhoZWtvV08xV3gwOHRZQnU5QlVRQXpWSDlCVGVIQlo3NE80bHd2WnJ30gGHAUFVX3lxTFBCUE5QTEJQajBqaGZTcnBaRHpTZHVkWktUQ1VGZzlkMlpTQW8talBtaW9zV0FmZGhOQkc1YXZzaDZKaHhja3hhWUR5cWJ4TzQxNU9zZVc1TGFOSHhBYW04dGJGQ2tjSlk3MmxjbkxsZU5GaEtOQm5RYXVoQmRCVTItLXZBMURaUQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T19:05:58Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La brecha de habilidades llega al balance: el nuevo indicador financiero que miran los CFOs e inversores - Forbes Argentina",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxOa1p5VWN3NzN4MVhCT2ozU0xpT1dXTnVWb0RUQ3FOcWxraDJfVER0d080NE9rRFo0ODNraDdFZWExSXFGZC0tZm9aZ1BjNU1lb2g5blVWVXEyMHE1MVJTb0FCenBpbFg4UnNKZE1qMkU3RGM1bVlHYWtYNWtXNTh4NjFvM2RsVldRSUxNZFVfeVZ5a3JqUVNXR3BPeHBRMGxtR2ctdDh4ZEM1QndWRExaQ29mTG9QVDk0U0hQUm1maXVmMEcxNVFaZEczcGJkS2t20gHWAUFVX3lxTFAxdkRGWHlsVFoxOVZJa3pwUF9rTlJFVnRfS3FPQXVfRmItWmJ6VDZlQkRzcjZHR2NEX0tLRmtvNlZDXzc0MTJxQ25zUWZfTEhndWNreXVlQXVnVnJKdUpJRW9xTzg1QXlfZXJYOTBRSnI2NzhVU3N5OEU1MFZNcmM4c2N0bjJ1aUZNZlB6a2wzTFdyWkcwbmlfbjUyY1p2SnpIb0FLNXhEcEp2eHlEaHZhTHR0bnpHYXQtOU82dWx1ZV9yUnV3VnNFdmNMXzJOZGZBanZEbUE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T11:01:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Forbes Argentina"
  },
  {
    "titulo": "Promover la cooperación tripartita en el desarrollo de recursos humanos para la ciencia, la tecnología, la innovación y la transformación digital. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPUElpUFhldWZxMndOcWZ3MnNVdndXTWhYcVYzcE5yclBrVXVmRmc0R1lTcFJQMDNlTUttblQ1Z01KZkgyRUpHd2szcG1FYWFsMURJX1V2TV82NXZuS25QWmZBNFQ4U1VUU0dFeVUzTnAxZlB5eHRFX19MaEc2d3c4N3YxUDNQY09JNXpwVHhubFdXWHlveTZMUm5lWm9nUFhXS3JNRzJ6YXBaWDVOLWpaSTFzREdGY0tIeGNZc1p2eTFQWmxSOWhN?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T09:36:44Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "CACI nombra a Marcie Small como directora de Recursos Humanos - Investing.com España",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNdHVIMlpadklhU20tYWU0MzBGbG9XQlp0aXlTZVhkejdpWWJocVFtb3ZRMUxtYWIyYWRLQ3lDNWhTc1ZjVUlsOEpPUEVQQ0J5OTEyU1JhNXlqbk0xcDRJUkRTeTZnblVjVy1PSTRHYUlzM0NOMFNsTndlZEdHLUh6MnpRcUZ4MXFGZ2VtQ1M5OXU5LTF5c2tjQTd6YVdZMmV6R3pVbEV6b3cwUmhOT1lLam1xYTcxZ3oz?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T12:25:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "CACI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Desarrollar recursos humanos de alta calidad para la industria de defensa en la nueva era. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNZll6ekEwYzJIZzZPaVhab2V0dFE5b1dYaXlhVnhnMGhsdlcxYlFWb2JLT19ncVJJUFY5VlJ0ZnZNcGRHQzFwdEFhUTBTNks3TXFQWXNBLVpKTk04eDNDdlFlUFZxWFhfVF9ZZDRqVGVYTmh1amdlOGotX0ZfZklMeGptRDBSeDd2VUFxbVU1cENYcW9fMXhpbUNXRQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T16:08:38Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Opinión| Talento mixto en el sector empresarial - EntrepreNerd",
    "url": "https://news.google.com/rss/articles/CBMie0FVX3lxTE5FWk5Cbndfd0ZjVUNpdGZJRjJXTkkyUGlIUUhyQzhMZ2xrQUNLeURac3JEOGFVaXNKaFRTUGJyR2IzOGlFMFNjVjVBYVlRc2k0WDNxRHRiR3BPeGFVRDRmSEF1SDRnYUs4R0hIeU94YTZjVlB1dlhMSF91aw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T21:07:14Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Capacitar a los recursos humanos para dominar la era de la IA. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTE1Gd0Y2dXJGaUVpQ1dmMEVnUEphaVRnRUpzcVpJb0dEdGp3SGx0RTRUd0o0MnRlOVZwVml4Y2VPYWlya1RWc2RCMThOR1hPZGtYT2d1ck5KTDQ1cWlpQXZaNVJIOS0xa1IydEtBeElDOA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T01:04:27Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La formación en recursos humanos vinculada al empleo en la trayectoria de 20 años del Grupo ESUHAI. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxNUWVINmJGeTcyWTJwM0ZHU2U5M28zR0Z1UWk5UFVBZjJFQUtBQVBUamJ1RlZjWFF4U2Q5MXlVWkZ2QmxZN0VnYTltS3ZqczlnVVYtRG9LcVVnUFpFUUZCS2tPQlVKeUw2ZHB4NnRTZjg0N2dfRlpuREgybnU2cXlKdkNKMWtwUEUyMW5NdHVFejA1aVdaLVVadGozTXczOEs4QVE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T12:50:31Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Grupo ESUHAI",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La colaboración tripartita genera un impulso para el desarrollo de los recursos humanos en ciencia y tecnología. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxNc1UxNjFHd1pDTHh1VVpuNmVaWmN3cnZHZUh2ckFDMmNsODhNSjV4NWJoMXRTNlJxZFlWNTNtMm1xUFppdVQyai05dFR2ak1WZVFqZm1YOXN6bXRTQ2hSTlJBVkJZaDdwUXFwNkVjdW5VRjBQLWJwcVMxTXQxOEctQms1SEE0NGlaYUp3anVMc3lkai0wQTBJ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T07:36:38Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Generar impulso para el desarrollo de los recursos humanos a nivel nacional. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFA4YTFpWEhTdlBlWHA2eEplakw4QWF3SXV0TUlwNDU3WFBmMldYRE1YeHRyQjdndTgycTJfdE1uV05HSnFiUlQyQzlSd3NMdWJiV2ZWOWw3TFgwN0hidnpnRDVQOUtiRE1VSzFVQXdzSTNhRG1INWhzZTlTaWFVdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T04:13:34Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Desarrollar competencias en inteligencia artificial y preparar a los recursos humanos para la transformación digital. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMikgFBVV95cUxQZEFQTFhVSk1SVm9PSy1CeTd5bml0WDQ3bEszUllvX0U1UXhiZEdsOWhfdVFNQ0lKTjRWZHQ2MHl6cFlFRXFia3lsZlZYeXFOUTRsd0xodnB0Vlg3cmtmdUJtUV9nQnVtZWg4N2Z6QTVNRDUwUVFIanl0ZkJhM3RtWWNOMTFieWtCNnIxZDJkSVZmQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T07:00:00Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Los miembros del Parlamento proponen formación gratuita para el personal de recursos humanos del sector editorial. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMilwFBVV95cUxOZnBPMm9RYndRc01kSEhEYk1aeWIzY1hQZy1NT2RwN29uakNBRmxyM1VDYWhhc3Q0Zm40aGR5NW01Slc2aG9fZ3daeEkxWGJVMWpFVVZrM2xGQ2tKZmdIa1VPZmtCTncxeEhienV3SW00VGRQVTlJRFo0czAwYzdOZW95VDBEblJJWGtUNkxFU2V3empOM3k0?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T08:39:19Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Parlamento",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Complementar las políticas de desarrollo de recursos humanos en la industria del petróleo y el gas. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxNXzFzUTZoYXczSXdlcXY3Zm5sdWQwVk9TTG1uSWtkanhlaHJyQXJqWGdlR0l4aW5WNlpYcXZKcTJNVFYybmZyd1VHUVZCTWExaWlpT21PSHBDSmgyZjhrYVF5WWhleWU3VFotaV9abWlibTQxRVFYS1RXSkJxX3ZTamU5ODE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T16:14:22Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Fortalecer la cooperación para el desarrollo de recursos humanos de alta calidad en el sector de la salud. - Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNeElhTmQ0aE1YeHhQektDNUdNRWl5bVFyVjlwa2ZLOENBVW5uZUJQcGNlRHRQcTgwX0I1WFBuOFN5YnJFVGJvUDNQRmUxMlFxZ1FDNE5oRmdQYTJyZ0tHbGdYMm1oeTJHYmFfdUJ2Q0k0SnpteG1CYURIVVJzM3RJNkRuTHhNcDQ0NzVOWkh1MnRfYnot?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T01:28:49Z",
    "fuente": "Panorama Nacional RRHH",
    "categoria": "Mercado",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Randstad busca cubrir unas 2.300 vacantes para la campaña de vendimia en toda España - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxQWUNmSmdkS2FfVWF4b2NRM2VOMENDbFZrZmVaOWZLTkNnV2xUbG0teVZzOWVVTlE4ZllIWVpUdG9Tajliem1RY01GZWFUUTZKWXA0cy04SnNBb0k5TDlyZ3FpQTh5OGNfVndmbWxsUmtfam10M3NLNV9CY3RyQkFnVzh6UEVPM3g2U25BU2ttay1vQVl2NWdSdExSZXViYmVaNFIwa1FCUVZvYkFzV1lRQlhvT0YxWnE2cExtbWEtLXBzMEVYcEZLeEFNazNWWTg2alJBTEo5dVE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T23:32:45Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "El grupo Adecco lanza Reverse Matching, una herramienta de IA para recomendar empleos en función del currículum - El Diario Vasco",
    "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxNT0d1cjNhMmxPZU1ud2d2V0RtOUZmZFVvYlFoT3NUMnlEeUNDNlVpOGtiQXNMdndoWV8yTy1XNk9Scl84UGF6QV9ldDg1SmhybHFWaG03cllLcWxJQ2x5T25CRFZrRm55cHdVR09JRjktSjdua3V1eE51RTF3M3hmTVc3cnhtSms5Z0lWZFB5RW5waEFKcGxfMTFlMktPd1p4N0FXQlRtai1EMGs1QnpadDZMTDlQaU0zdWfSAb8BQVVfeXFMTUdfNUNHbWRkLXJKY28ySExhRGxXaW5jVVJDM080bnc1ckZxSWJEeUd2SFlHZ0pLSGhpT0c2MTV1NUNodUtieUNXc2dPWW56TWp0anJYNXlXaDNxekE3THhNYkRRVEhZNmtxWkxyNTdYVWllLW1yS29zUUpvbjZ6VEFsV2hjajZfQzlrbWZCdkRqUFR0RmJNN1E0bk41Mk5tbDM4c3ZETFVmU3lMMmFpS3ZZT2h1VGVJRldxV0wtbmM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T22:12:28Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "función del currículum"
  },
  {
    "titulo": "Adecco refuerza su negocio en Iberia con un crecimiento del 22% de los ingresos - El Conciso",
    "url": "https://news.google.com/rss/articles/CBMilAFBVV95cUxNMHlzRnZ0Q2lJVUppb0pTdmRhX1BrX2ZldGtNNkVfZHJMaGktVmhkVnRrdmExM0NHMUdLRF9Yb0tYUGdGVTFIVHlTMWRJbjVKUDJQUUVKZGwzeTZOcUZKaG91bkJaa2JtN2JGbWMtckVjLXNwcjlpRzdkcXNqWVZudjNFYTVsWHRzWGJQa1hkTk1iWXRJ0gGaAUFVX3lxTFBaM2ZKeU9hY1FwaTJHUjYwV2UyX1NwZjk5NjBfRktSMjNZYVBaZjVPY3lUSlRNZ3RUUnRRZy1jMk9acXZDZEstWmJmNWhScmNOVFc3M3F6cnN1c1Btd2lEVGVzcW5PQ2NHSVV3UHZVRGx1V3JMYmlYenBXODQ1dFkteXAxZHVNZk9yX3owcFFTTGpiRHVBUWlrSXc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T11:20:45Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Iberia"
  },
  {
    "titulo": "Randstad busca cerca de un centenar de trabajadores para la vendimia en La Rioja - La Rioja",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQQlM3ajBfTklndVd4ZktwU2otaC1CcUlnMmR4TG9GOWEtUllTdWRSbkN2Q0lTU1hXT3o1SExleU43S1ZzaEU5R2s1bkNVSHY1MlFsTFp3aTVmNFZwV0EyRTlob3JEZ1I4VkdaTWhleUlxSEU0RmlUY0NZSWFlU2FyZFo1S0RXd3hjS0ZxaTM1b3NjN3RfQ2VxNnZybTQ4a3RFVXFPc3lMNUZZX1JHSkQ3ZdIBtgFBVV95cUxQV1dESnE1cG9DVHdzTHZ6U3RrM1BsS0N0STZuQWxIOXlHQlF1YUtEZktqdE5VSExTZDdHWXp1NURURkZtS1NHNWFRUGk0ZnE0NEJRd281aFVxd0tRcjZUcHRlU2JtWl9EeHhWa2ZlWWxkUUl5c2hCa3VJQU5icmd2MlZvMFFUSld0UXNfcFhjSktwZFdaUl9hX2lUSFZsZTZWdThId3BCOWthenZSSVB0dkpKSlFIQQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T19:27:23Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "Día Mundial del Síndrome de Down: Descubre la campaña de Fundación Adecco - Bankinter",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxOajdFZVRvcUF3WVRqaW1iMUFId0tqMkJxZkZRZ1hLVTdJYTBoRVRHVVdBUTVOY1lLVXI3ZGlZTDU5Vi1kQmszcGFDeGUzc0E1SmVVejZYOU5IYkdmMDNZd3ZzN1NubXlfbzhLaFlWck55b2hiT3Qydk9HRGZXdVc0cw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T16:35:29Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Adecco Iberia se consolida como motor de The Adecco Group con un alza del 22% en sus ingresos - El Confidencial",
    "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNQUt2dndTazk1NUdTbnpKb1llYjZTRFlYdWpXMzdtQmpiZmhDWVNybFRSeGY2andxSkIxWE5sYnF4QS1fR2kySUtyeHo5NDBMRmk4dFJTeHlfWnAxUjFfUXhlc0JMOEo5NjZsZ3poZzRYUklyV29vMkZhTVlZVnVuUmNTck80b2VvOFV4SUFhcFJfT1ZHOTV0YWtIejJvLUQ5MG1PVEhmRQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T14:35:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "The Adecco Group",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Adecco profit disappoints despite better than expected sales - es.tradingview.com",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNSGIzVy1wWU04SUIzd2tnWmo0OVpmM1ZCcExjN1RuU2psZTZ0UlFZUU53VG9nM3ZZSjdTem9Gak54WHM0R3pFWU1IcW1xaXJvUURoRVZWSGVON2tRUmRObk9VUE4wQ2t6ME5QZUY5ajJJTzB5ejRJV3paOXVwZk9EUUFhdm1fX2hsdE13X2VvTlEyUi1KRmRnemRWcWRmSWtobTMzVjlyTHpCRTlOcDZkdVZhbUVYY1d3NklnUFhabk1nNTlSaTVTZA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T05:25:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Randstad busca más de 1.600 trabajadores para la campaña de la vendimia en Galicia - GC Diario",
    "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxNd05URk8xOHhGYkJ5MnllS3dUM0EyNnl1Y1hsZ3dfREI0UUpDRnU4Ym9DbUdRb3lDYnczMUNQVUpCLXBjSjByajlESktGelMtOTNad3BPM2FyNzhNbFJFVTVJZVF4M3VyLWROVHd6NGZkOGg2c0JqNUVKdldRMlM5dmNwc2NCeFFWZENUZ25XNFYybkFZb0wySlBLSmxYZzd2RkdESHZtaXA5VUNyYkU0NDZ6V2V2NkhoODkzVQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T09:32:32Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Randstad"
  },
  {
    "titulo": "Resultados de Adecco Group en el segundo trimestre de 2026 - PR Newswire",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPZmw0Mmc2UmpuYUN3c19vSnJId2FXNTJSTlpUMlBqR3E1bnBiZkdPTEpHblpKM0RYaTRYdlgwZkh5Y3BWZTRjNXh4YnNDWWxLanhjSENfNHBQb2NhQVJCWGRKSncxMzBQRFVVRkduY1VnUlBwYm9aMVRpNl9KN2dFMHJReWpicFRxb0pHVGZBbXMtejNBOGV3bjg3aVkxLWt6OEZ6ZjlTQ0I5N0xDanM1N0JzUGU?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:33:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "CCOO logra que Gullón compute la antigüedad trabajada en ETT - Cadena SER",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxOanRGQ1V2RmNzVDFvS0h4OFFCcmxsUEkzWEZockdKSTI5RGt1VW01OUVmZzF3b3A2bHVJQmJRRC1rZ0x5Qjc3eXQwdFFTWFRraVRTdjFGNWktdk9ZVnQyRVRhRGJob1BLN2t0VWJtUks3R1ZVRmJuTklsSm9OeTd0ZXVac0hVMUphdlVKTkF0T0g2bUtFbktaQzRYYnVHQzI1THhZWmFsSEVoTGplQ1RKVi1hZ2dIcVo5WEhqTV9RY03SAdQBQVVfeXFMTk0xN1BiOWppYzV2b25vODBiVmxMZ2ZtVUQzeVY1WHVqQ2NTZDB5aGZiMGh4N0NFMHpqZUhhWU5GR05KemRCc2RrRWtWY0ZNQ1FiRjBhc2wxRWNGaVFUSlREU19WUy1WdXdrMjFSRk96cHhNLU9nTXhucTc0X0FQLWVMZnhrdng3c05BRzNGbjM2LV94NVpkcmNMNVo5bExyc2hlM0FOVUx2cllTa1kyMV83ampWOHpYVjMtajR4dE5aNE1TWnBmb09HZExFdU5mZHVVcng?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T07:37:46Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "CCOO",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Reconocen la antigüedad a un trabajador de Gullón procedente de ETT - Tribuna de Palencia.",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPbGdJVkxiTVBjWVp4blFsNU5rZmlZSjQ1ZTJ0QTItM1BqYkowZ01WZElTWEpvNHFXTENITHBrS2pId2ZGZXN4RUtKZDQ2U3RJQXdvNVpzdlF4aGtBUkJaMmpxc0JoX2xRaHVTRkx2M2p0Ti1iMC1uOWpCMkZ1bTJFQ3FsRmpFMlRxWDdyZmZEa2FKU2R1V21aQW56aWkxeXFPdlB5Q2hKalc3d0RXcGZLSDRhaHFYZw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T15:55:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Tribuna de Palencia"
  },
  {
    "titulo": "¿Por qué cae hoy la acción de Adecco? - Investing.com España",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxNODI5cGlZWG1TWjQ3ZGJUNHQ0U1lxbHQyeW80ZWVidWhJR0trVk9nR01HQ0xKbk5iR043VjZKRHdZcVFpUExOb19WZUluSXJTakhkQmF3Smg0M3M0T2VvNUpQa2pNaTBjUl9mek9SclVQcm92T1lVY1lhbVlSNlpNSlFGN1lvZ2RzTFh3REZxRDYxbHdUZDBfQ19BYjA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:43:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Una falsa ETT deja sin cobrar a 15 temporeros durante la campaña de la cereza en Caspe - Aragón Digital",
    "url": "https://news.google.com/rss/articles/CBMizwFBVV95cUxNbTREV28tSm40R0RXdkRleUl1X3h1U3NPaFZwYWtKeElZcnVwU2RueDVLdFRhbWpXUFFOeHBRR1pCX05YX0FqYTROMmFyYXV6b0pvNTk4WXk1MkU3TUFYdDZZbXJmRmxSNGJkNkxmaFdqUjI4TU9sT0QtVFZVQlZaM0o0NGhwX3JtUzdicEg5cGRHUkQtLXJJUG9JWkgxUmxYWmh3cHpQMGZ6b0VNNExwNHk3Sk9VR3F2dHRWZXJkbmJIWXlCeHpCQlVnZ25lckHSAdQBQVVfeXFMTjBzcHdILTFnTTlJbVJLSWYxRUJDaDI5UGpRZGUxTFNHUDM0UG5ZTUdCek9GU3NyTTYtcHZTd0dMd3FIRVlJT19VSldfZGtvZmpSbW5lNzNxcHNBLUJyVjN5NEI4MnNjSWc3NzFTaHlRbU9DZk9TNUtnYk1GRXRpTlFRSU5rNUd5Qi03NS0xX2RMS0NCU3BmMmRya2tnVnlORGtrdDJFXzcwNzdZUHhrUkJua25RTURoQllSa1A1ZGwzTFMyUjNuQlQtemk2NFNvaTdvY2s?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T10:02:52Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "ETT",
    "ubicacion": "Caspe"
  },
  {
    "titulo": "Adecco Iberia crece un 22% en el segundo trimestre - RRHH Digital",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNNVIyYVlvdS1XUjBiNnhKY1ZMc01kazZPR1J2a0VqMld1Q2RjbVM5RFE5STVIWGVGWUhfYi15Yml4MTZZQVBpWmtDSmh3NnNxU1RHNGpTaURzQVUxQndxMnVUV2ZsazkwQ0U0QzVSNDFwbW51WHlYUjJIYVo1aXE5d3dxSGE0M1B6Z2RyYUgxaS1ISHk0Vk1iQVA1MGF3endJUE43M1VjWm5fdw?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-10T00:09:38Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Informe semestral 2026 del Grupo Adecco - PR Newswire",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQUUlUUnlCMzl4YlZOUjVWbWtZOFA1WlJ0SWU3a01Hb2xHQkNOSV9ab2dCT1AzVVFVWDlMT0xxaTdUQkNIZmdKUzNOU0dDVDFoNzVDRDAzWnJVbnBlR3R5WjJaTkVoX0JhdkZXLWVjMFg4TUdJY3luVk52bUg2Tm5ISHhLTXZjVWhPa2E3aVNOazFPOW9GNWUyNUV5MA?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:15:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Grupo Adecco",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Adecco prevé que el empleo siga creciendo en 2026, aunque a menor ritmo que en 2024 y 2025 - Huelva Red",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxOaUlNbHphcEprUmU5bmc4d3dzODFsd2lnWHhIMXpRWGFNOEdoT1hKR1Y2UWhiWHNUckpUZXZLXzItUWF0ZGxOOW1ESlNFT2pIRjFiMkQ3TEg0QmRJUTFKcWNlUzc1dWlVM0hNYTB4amJoaXlTc19HVzdFNnFmUzdmazVzeGlFbkVGWFRDMHJhV3hKS0cyQ0pVSnNJR2pLN01MeDR4Y0hEYkJwYkJoeFZrNktqM0pYNXRQNXdNblh3ZXQ?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T09:32:52Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Huelva"
  },
  {
    "titulo": "Adecco Iberia crece un 22% en el segundo trimestre y destaca en el sector - Córdoba Buenas Noticias",
    "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxQSnczUFFoQjBIa2dyQWtNeUo0R0pfUWlseFREMW9wT0YxLTlJbUVBNlhQd3V4S0hMbmF3RUE0dWJYTGVZWF9ZZ1ZEUXJ4aVltLTkyX1IzZHE4MFRVSDhfckh3VEpzOVNZRW80VzQ3blo1S1doSFVIblBBUFFNMEhnZ2RxYkxiS24tdTZ5dGl0U0tRY0tReGdvRDJCWkFiYWdCV00zaXV0YmFXMy1yNHZpWG42U0RWRDc3TzBQWkptX3Z1a0t6NXBOOHJ1dVNuYWozVmfSAdcBQVVfeXFMTkZ0R2h2M0JrVmxHNU9SeExiUDFwcVdlR0s4VXQtS0tHM1Nad2d0LTEwa3dCWWRQcjVpMmppdTR6M3Jra0NEenFLcDYtUXZEbUhPQlhEMnVZaVB5dWZnTzBoQnN3YVZTRk5qWUNnZ3ZIeWNScjJHckgyMzRjeEdzWkRhZ3pOWmtHMjdreGp2X1A2WFFtYWxEUHBNaGtzTGRTN0h4MVF5bzNqckdUcmlEdFlXQlR4SW5TQXQ3RzFHakRIVVo4dEZIc0dVYk0yaVlnaW1kYUgtTFE?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:14:22Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "La justicia da la razón a CCOO y Gullón \"deberá tener en cuenta la antigüedad generada en las ETT para el salario y la categoría profesional\" - Palencia en la Red",
    "url": "https://news.google.com/rss/articles/CBMigAJBVV95cUxQMEVIMEdBQjhQTzhXYnNBVVBXUmN5UlYwUEU2VW1pNG10YV9KTXVRQkdSSzlicE5aM2FxZ2Fja2NyRm55T2JNYzdodFVxazJnYmZlbXlnZnVLOVRfaXJEVWdhQklfQTN5MHkyYXlhTHRRNWIzVDh3b2tXSE9GVkxDd24tZ0NRT1c1bk0tUkJoUGFld0RiR0tNbldiZHZRRXp6a1hOZ1JVcFIxRUdqNWZJenZLVGZjdTl1cV9yTDlQZlVaNjRNc0QzYmhJVjVtME1jX2ZWVDBqRGNDRDNDV0E5dHJCMVJpYzJDakpvXzVwTjhqRV9HYXNNem4wc29DZjZo?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-03T15:24:27Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "CCOO",
    "ubicacion": "Palencia"
  },
  {
    "titulo": "El absentismo laboral se dispara: las actividades turísticas más afectadas por las bajas laborales - Hosteltur",
    "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPeTY4M1pWel93Wjkzam5aZGNReFNmNERMRGNtak5NYUhmNmFsMnNyOFRTTXNDRXZfTzdmVWRSdWV6VHNaRXduTHppOGtHTHlTRVFoWjYyaWxKMl9JTExScmZMU3ZHQ3FZYmlUMjhmS3NlWXYtZDkxendmSno1cVViWlgyUUZZZGxkMWFmY1hqandaeGk5SWNNMVh5OGU5TlhkMkNqcEVTX0tIUHdkWmowMDNPRi11NjJtQXpzSTVTNlJvT25QYlJRSnJJT3pTRDVP?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T11:11:31Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Sergio Rodríguez - ACB",
    "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxNM1ZDdVZiV2Yxb09SNHlfT1N5b2JtZWdqS2tJQXVuRVgtaHNldVhUM0g1M09qMUk0Z1MzUUx0Zzh3RmZuS2tySEZYeHNXWTU0Nk9XdzNpZUJneUNMbndfMGZ6Y21UMnlTX3lHTUtHMklzRE5fRmlLMGdQZTduelpVZWhUNXlkZ081ZWlvamJTdWlXNU9JVFFXREhWdTFqUk9RamliNEdkMTNpRm1VM0F6RlpudXhzamtxNm9zcHNmSEFQVEdWRjRxMUlQMkNublpDMDVQVDhBRTY?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-08T19:38:53Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Pancho Jasen - ACB",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQU2pUMFRUVEJyZTlSUzEyeXp2bUliMF9aM2FvMVBtSlM0NVlxZXVHWVZzN1lRQUdPSjllUHJFOGFuU3B5NWg4XzczTng4SmtaY1BuLXJjU296S29BT01oNzZHemxMNXJ1T2ZhdDBlUjRZMUNNTjNvajA3dll6dV9TRzFacU9QVzRzT3B2NnRaSjZyYjFDWmc?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T17:47:47Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Informe semestral 2026 del Grupo Adecco - Bolsamania",
    "url": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOLVAzYzRaX3Vvc2l4S2gyaTNfQjdlT0E2U2VKRUJVTUlMVldTV3FoaTdBNzlJVTQ1bzFnaFpyOXZleGdwZmlMNkdWYklnRnRiMUxoSXBpNjFGQ09wZ2N6ZHJ2bV9CTkt2SGpNQkt3RDByS2FfUFFaWDNGSG5tMEkwck16MFItNG9iblVXcERfeEJ0aV9wcGYwUmp1bmxlOXotcGljWVpncXDSAa4BQVVfeXFMTmlqRXFjNjVDZjJGbVlaOER2NExQcGF1YTczVmFGdHNfczF6blp4VzZPWTBIOUN0NFZZQnRNMzRJeHhRcFJyUDl4WlItN0FyeURwNU1IMmtUZXFfNlNYZkFFbF9JVEd0TmhGTXRIdFg1Yy10XzFSYXVCNnNVWnZKZGdvb3FwUC10RTdsUVA4ckZFTGU4SkFTejF2SGNkRXdVVzRPY3BpSTkwb2dPQnNn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:15:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Grupo Adecco",
    "ubicacion": "Bolsamania"
  },
  {
    "titulo": "Profesiones mejor valoradas por niños andaluces en la XX Encuesta Adecco - Córdoba Buenas Noticias",
    "url": "https://news.google.com/rss/articles/CBMipgJBVV95cUxNeElrZ3RKdFJQVGR4UWlqX1VsX2dodzhnVl9fSDZfZ3BiXzl4MDVYRWxRQWdydXMzZzZscXhUS29LSkZ3Q1N1M1ZEeUNTRmxPeWFYSmhUTFhmOWFXZUFaX3lRRGo5UGJOU19WbU1TdmFxVXVmRGpsUXp2ZVBJLUtDSl9MS1JydXVJVm9BSU9JVk5YUzlZWmRDWV9xWC11bU9FZWMtX0VxY1FwVWdBNFNKNUxmQko4VkJxZTFtQ2liSFdsOGpoaUtGelZhV2tWc3B3dE1XazNiRl9XZ0pnRk1wQ2V5eUE3Rm1zRW9LZk9GMllXTHp1TEtnMXQ3ekV5R1NHOVByUXU0RTBzZmFqdGtYNEtMU1dGZ1FvZlRKaC1ZZ0ZlNllBN2fSAasCQVVfeXFMTjRUZnVoOG05dTVONXlXYWJ4aU01TUNveG8zUFVQX3ZlMFgwWVRHS1FXOWtHejZPTU0xam5WeHNTajlkT3BBWmFfZ0MxMkZYcHRsaWh5V251OFVhTzgybEFBQ2RLNER1QnVhUDJaeUs2R2Nad0NwdDNnLWVnVFZ1Q3pFdUxhcDJiWHNBa0d1NG5yclNMdU51cmd5SE50VkR3bmd3Q1JGcG5oX2pxM1lLd0dpNFZEaVJTcFo5b0pLN0ttVHhIclNVeWtWNk1NRVJIV1dXTmU1WV9SMDJhUEhsUTFHbHYtRHA3UnlsbTRfQU94U3M4a1JNanhvQXl2eDJhbUtvUWVlYWpHeXc1b0tHYjhNbXJGd3BqRjBZTXBZcGNmbWZ2Skc3OTVnbWM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T08:22:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Partidos Juan Ignacio Jasen - ACB",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxPSnNpUTNqMEdXQ1NSb0drWFB5YUtNRl9rZVNvR2dsTHBhMlY4Z0JuSGhDVGthT0xzM2JhR2dNb1dUaTViSWo1a25OMDZjS1VpaElXczlUY0JQa19pbGVPZDlacHljYlkzSzVUVU5zSUlIRXdxemxJTlR0WWRmQzRPcnBDZlMyb1RLSldiWFpCcTRjRmJoVWJvbFRISEg5aUYyTkQ1YmVsUFFuMnN4eWdOX3ozRnVzNGM?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T22:17:27Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Una falsa ETT estafa a 15 temporeros malienses en Caspe y desaparece sin pagarles - moncloa.com",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE9ZTEdYelN0bDVhUmM0SkJ4bXhSLWZsMC1WQ3NzVTdDMF9xS3lvbWk5SEFMUF9WVXFDanVSZnF1RGJISjlhYlB6dHNEd2FxYzAyNV9QWWpBUWF6aTBGOHF4YUt5djlVdFozRmhrcXg1ZEhCUTI3a2c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-04T10:30:43Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Caspe"
  },
  {
    "titulo": "Juan Ignacio Jasen - ACB",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxOR0RSaXFacnpTYXdqRTgzLXJHdWhJSjkxY29oUTk1U1FFdFlVNm45anFiZFNya3RJb1RacmRTaGZjTXJ0MXNjZXJfb0FubGlkRlpGTnNMaVNTWjM0NjFURkJKdUt3UnZFSFViU3lIcnpUWXVIMFVNQ283d2hEMHR1OTc3ZFNoYWJLV285aUpDc0VSSy02RUxxQUhiQzllWEM4NURtWjlwRGFIN0k?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-09T21:46:37Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Estad. Avanzada Marlon Garnett | Jugador acb - ACB",
    "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxNdklRYnF2SllwYUF0czlTZDlDYUdRSkthWkwxajdkXzdzRmEtN05oUWJMSlJzTFRyVUR2aXZqSFI4NUxVaDdXVFd0TWtTeGdaeW80Q1lyLTQwbUdtYUM4bldXa0R3SWVxeTMzckRUUHV2S1NDVzZPclVFV0V4bHo5Uzc3Tkp6QjZVdXJkMjhZSG05elFkY1gzNHB4S2owdnFyaXpRdnY4dGZEN1BxRGJoWnpMd2tJWGVSUHhaMmNzR1NaMTJZUEVBcHpn?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-07T18:14:49Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Entrega de Premios Legado en la Gala de Manpower y Brain Co. - www.revistaeyn.com",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNdFZkMFR4MkF0YklWeFNUQ1BkQXZvRG1PTzFKSV80Y1BTZVBCQ1Vqd1dFb3JTdU11TTVsdzZGNk93bW5LVm4yVGV2bnBCdnByZDJPaW5qeGkyQl9teVgydTBQZzgzcGJadVpOYlc3aXotOXBaOV9NWmNDNnF5UENGazlBa2FsUnI3SGs0aVRjR2c1VVJBSFFNdTdua0pzMU9MY0xCclpIdm9ZVEVZdFA0?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-05T21:46:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  },
  {
    "titulo": "Informe semestral 2026 del Grupo Adecco - Bolsamania",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPMEFNUUVEZ050bkhfUUV0RklpWV9xSXN6cngwVk9DcEFEaGlxZkZxLURsWjlJS3JMajNNYjdIMUpZQ3JHcmdUaUpFRW5jcll5Ukk0a29hdmNiUzVDZjZ3ZmJ3N0JPaGhMSEdLanNlSjJ6UEd1QTdGT3R1WlJvWGF3QTc2TmVCanQ1eEdVY1J1MXlUSlBOUFBsRnhCUjVDVnNyU0RtQXdUeGZPVXhQbDVCd9IBrgFBVV95cUxOaWpFcWM2NUNmMkZtWVo4RHY0TFBwYXVhNzNWYUZ0c19zMXpuWnhXNk9ZMEg5Q3Q0VllCdE0zNEl4eFFwUnJQOXhaUi03QXJ5RHA1TUgya1RlcV82U1hmQUVsX0lUR3ROaEZNdEh0WDVjLXRfMVJhdUI2c1VadkpkZ29vcXBQLXRFN2xRUDhyRkVMZThKQVN6MXZIY2RFd1VXNE9jcGlJOTBvZ09Cc2c?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:15:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Grupo Adecco",
    "ubicacion": "Bolsamania"
  },
  {
    "titulo": "RAPPORT SEMESTRIEL 2026 DU GROUPE ADECCO - PR Newswire",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxPRzU4TWthNHotelltZE10YkFiU3VnSlpsX2xRcXlocmlJWThSNUFHcGtRNGFvYTRJcUkzdmdyN2tRQ1dFSExmQkMydTZEajUzOVoxeW80UFVEejR0Z0ZjMTY1RXZhQk1TbVRuQWhyaDBOOG9xS1Byd3JLVC1Bd2NvMW56Ny1GX3I3WTgybzVYb2lETFlCU08wT0taZ2k?oc=5",
    "resumen": "Configura la API Key de Gemini en Github Actions para desbloquear la IA.",
    "impacto": "Análisis IA no disponible o texto insuficiente.",
    "riesgos": "N/A",
    "fecha": "2026-08-06T07:22:00Z",
    "fuente": "Actualidad ETTs",
    "categoria": "ETTs",
    "empresa": "Desconocida",
    "ubicacion": "Nacional"
  }
];